"""Scoped supersession rows. Old parent bytes stay unchanged; each row names exact selectors, the scope,
the disposition, why it is unavoidable (or why it is only a clarification), and the checker ids that test it."""

D2 = "$.typescriptSemanticSubstrate.providerProtocol.wireSchema."
R2 = "$.wireSchema."


def row(id_, scope, targets, disposition, statement, wire_change, justification, checks):
    return {"id": id_, "scope": scope, "targets": targets, "disposition": disposition, "statement": statement,
            "wireChange": wire_change, "justification": justification, "referenceChecks": checks}


def t(pin, *selectors):
    return {"pin": pin, "selectors": list(selectors)}


ROWS = [
    row("SUCC-PER-KEY-SCOPE2", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("delivery2", D2 + "definitions.RequestedCoverageDomainV1.workerRule (clause: every key.subjectScopeCommitment equals subjectScope.subjectScopeCommitment)",
           D2 + "coverageDomain.keyConstruction.subjectScopeCommitment"),
         t("rust2", "$.planAndDomainProjection.coverageDomainAlgorithm[3] (member subjectScopeCommitment)",
           "$.commitments.subjectScope (as the value placed in keys)")],
        "superseded-value",
        "Each request key's subjectScopeCommitment is the sha256: text form of the key's own scope2 (PER-KEY-SCOPE2). Retained unchanged: TS SubjectScopeV1 (shape, recipe, subjectCount) and its place inside domainCommitment; rust2 subjects/SubjectV2, analysisDomain recipe; rust2 commitments.subjectScope stays a named recipe with no wire carrier. Per-stage SubjectScope and domain commitments remain; only the per-key member value changes.",
        "none (member, type and pattern unchanged; values change)",
        "native-evidence §4.1a, identity §3 and startup coverageFrames.entries require per-key values; keys in one stage differ in relation/rung/target, so a single per-stage value cannot satisfy them. Unavoidable.",
        ["scope2-ts2-admits", "scope2-rust3-admits", "scope2-per-stage-value-refused", "scope2-keys-differ"]),
    row("SUCC-FACT-REF-REFUSED", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("factPlane", "$.factRecordContractV1.anchorSchema.variants.fact-ref"),
         t("delivery2", D2 + "definitions.AnchorRefV1.variants.fact-ref")],
        "not-admitted-under-fact2",
        "kind=fact-ref is PROVIDER.PROTOCOL_VIOLATION at candidate admission. Vocabulary and AnchorRefV1 shape unchanged.",
        "none", "fact-identity-fact2 is mandatory in both token sets; identity-schemas.v3 #/$defs/fact/properties/anchors items are {path, blobDigest, startByte, endByte}; FACT-ID-V1 is never relabeled (native-evidence §9.1).",
        ["anchor-fact-ref-refused", "fact2-anchor-closed-shape"]),
    row("SUCC-ANCHOR-RULES", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("factPlane", "$.factRecordContractV1.sourceSpanSchema.rule", "$.factRecordContractV1.anchorSchema.ordering"),
         t("delivery2", D2 + "definitions.AnchorRefV1.ordering"),
         t("identityModel3", "line 1892 ANCHOR_RANGE (unchanged, not narrowed)")],
        "clarified-types-and-separated-rules",
        "Wire anchor rule: non-empty in-bounds interval (retained fact-plane rule) plus types of ANCHOR-WIRE-SPAN. Shared fact2 rule: 0 <= startByte <= endByte <= blob length and UTF-8 boundaries (identity-model.v3 ANCHOR_RANGE/ANCHOR_UTF8), unchanged. Anchor array order is per language: TS2 deterministic-CBOR bytes, Rust3 CVE1 bytes; they are different orders and must not be merged.",
        "none", "Types were unstated (TS2-G5/R3-G5); the empty-interval difference between the two owners is a scope difference, not a contradiction, once stated separately.",
        ["anchor-empty-interval-refused-on-wire", "fact2-anchor-range-permits-empty", "anchor-order-languages-differ"]),
    row("SUCC-TS2-MANIFEST-DIGEST", ["typescript-semantic major 2"],
        [t("delivery2", D2 + "commitments.domains.snapshotManifest (as applied to SnapshotManifestV1/SnapshotSealV1/SnapshotAcceptedV1.manifestSha256)")],
        "not-applied",
        "manifestSha256 is DigestHex = lowercase hex SHA-256(deterministic-CBOR(entries)), no domain and no sha256: prefix. The snapshotManifest domain has no TS2 carrier.",
        "none", "Field text says DigestHex; DigestHex cannot hold a sha256: value; rust2 commitments.snapshotManifest states the same raw recipe. Citation correction: the v1 checker (check-rust-provider-protocol.py line 1048) executes that recipe for rust-provider-protocol.v1; the v2 checker executes no manifest digest. Neither checker is an owner.",
        ["ts2-manifest-digest-raw", "ts2-manifest-domain-form-refused", "citation-v1-checker-is-v1"]),
    row("SUCC-DEPSRC-DIGEST", ["rust-semantic major 3"],
        [t("evidence", "#/$defs/DependencySourceManifestV3/properties/manifestSha256/x-opensip-digest",
           "#/$defs/DependencySourceSealV3/properties/manifestSha256/x-opensip-digest",
           "#/$defs/DependencySourceManifestV3/properties/entries/x-opensip-order",
           "#/$defs/DependencySourceManifestV3/properties/entries/items/properties/packageKey")],
        "superseded-recipe-registered-bytes-kept",
        "manifestSha256 = lowercase hex SHA-256(deterministic-CBOR(entries)) (non-self-referential; same recipe as rust2 commitments.snapshotManifest, whose 'same discipline as the snapshot' native-evidence §3.2 invokes). entries order package-then-path; packageKey = name SP version SP sourceId of one DependencySourceSetV1 package. The registered schema document is not edited (its raw digest is a registered payloadSchemaDigest, as the HelloV3 precedent in §0 states).",
        "none (types/patterns unchanged; order and value recipe stated)",
        "The annotated preimage 'exact transport manifest frame bytes as sent' contains manifestSha256 itself, so no value satisfies it. Unavoidable.",
        ["depsrc-digest-non-self-referential", "depsrc-self-referential-unsatisfiable", "depsrc-order-and-key", "depsrc-file-manifest-join", "depsrc-empty-set"]),
    row("SUCC-DEPSRC-RECORDS", ["rust-semantic major 3"],
        [t("nativeMd", "§9.2 rows DependencySourceChunk (line 2877) and DependencySourceAccepted (line 2879)")],
        "field-level-publication",
        "Rust3DependencySourceChunkV3 and Rust3DependencySourceAcceptedV3 (alias of Native2DependencySourceSealV3) are private names; no wire tag or record name is added.",
        "none", "The frame rows gave members without types.", ["carrier-member-lists"]),
    row("SUCC-PREPARED-V3", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.PreparedOutputManifestV2", R2 + "payloadSchemas.PreparedOutputChunkV2", R2 + "payloadSchemas.PreparedOutputSealV2",
           R2 + "payloadSchemas.PreparedOutputAcceptedV2", R2 + "definitions.PreparedOutputEntryV2", R2 + "definitions.PreparedOutputBlobV2",
           "$.commitments.preparedOutputBlob", "$.preparedOutputCustody.order", "$.preparedOutputCustody.manifestConstruction",
           "$.preparedOutputCustody.planCommitmentProof", "$.preparedOutputCustody.readAuthority", "$.requestProjection.preparedOutputs")],
        "superseded-value-members-kept",
        "Frame member names are unchanged. entries answer PreparedOutputSetV3.rows one-to-one (PREPARED-V3-ENTRY): planRow becomes the exact Plan-bound PreparedOutputRowV3, kind the inert row kind, blob bytes the exact inert bytes named by row.blob, contentByteLength/contentSha256 equal the blob values because the PreparedOutputBlobV2 wrapper is gone, logicalPath uses .opensip/prepared/v3/. commitments.preparedOutputManifest recipe retained over V3 entries. Read authority: generated-file rows mount read-only at .opensip/out/v1/<ownerKey>/<generated.logicalPath>; expansion and directive rows are looked up by site/owner (§3.6 PO-4). Entry limits: macro-expansion <= maxExpansionRows, generated-file <= maxGeneratedFileRows, build-script-directives <= maxPreparedOutputEntries; blobs <= maxPreparedOutputTotalBlobBytes; manifest <= maxFramePayloadBytes.",
        "none (member lists unchanged; value domains substituted)",
        "The V2 payloads join rust-v1 buildScriptOutputs/procMacroOutputs rows that native-evidence §0 line 130 supersedes, so no V2 value is constructible for a major-3 universe. Unavoidable.",
        ["prepared-v3-entries-from-set", "prepared-v3-generated-blob-equality", "prepared-v3-set-identity-join", "prepared-v3-v2-planrow-refused"]),
    row("SUCC-TRANSITION-PRECEDENCE", ["rust-semantic major 3"],
        [t("rust2", "$.orderingAndStateMachine.transitionAstV2.rules", "$.orderingAndStateMachine.eventRecord", "$.preparedOutputCustody.order"),
         t("p3", "$.rules[P3-25]", "$.initialState", "$.stateUpdates")],
        "precedence-and-guard-refinement",
        "TRANSITIONS.rust-semantic: P3 table governs matching; framePrecheck and T016/T020 payload guards retained as pre-match admission; P3-25 gains guard outputSeen=false with outputSeen reset at Analyze and set by FactBatch/CoverageV3; Cancel in START has no row (host never sends it).",
        "none", "native-evidence §0 line 118 supersedes only phaseValues and P3 claims to state existing behaviour exactly, so rust2 T019's guard (stageIndex 0, no output) is retained law that the P3 transcription dropped; T023's START entry is not host-observable because the host has sent nothing in START.",
        ["p3-unavailable-after-output-faults", "p3-unavailable-before-output-admits", "p3-cancel-in-start-no-row", "p3-overlay-differential", "ts2-order-unchanged"]),
    row("SUCC-COMMIT-MAP", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("nativeMd", "§0 line 126 and line 129 ('recipes and domains unchanged'); §9.7 Coverage frames commitments")],
        "field-to-domain-map-stated",
        "COMMITMENT_MAP rows are the exact field-to-domain map for both languages.", "none",
        "Field texts named no domain for wrapper/terminal coverage commitments (TS2-G12, R3-G12).",
        ["commit-map-complete", "commit-ts2-fact-batch-matches-wire-model", "commit-empty-stream"]),
    row("SUCC-ECHO-ENUMERATION", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("startup", "#/x-opensip-startup-law/identityMembers")],
        "enumeration-completed",
        "Transitive echoes also carry snapshot2/plan2 text: SnapshotFileChunk.snapshotId (both), AnchorRefV1 source-span snapshotId (both), PreparedOutputChunk/Seal.planId, and the snapshotId inside the rust2 SubjectV2.subjectId preimage.",
        "none", "Each is an exact echo of an enumerated member; value domains follow necessarily (R3-G16).", ["echo-rules-present"]),
    row("SUCC-RUST3-FAULT-CANCEL", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.ProviderFaultV2", R2 + "payloadSchemas.CancelV2", R2 + "payloadSchemas.CancelledV2")],
        "types-stated",
        "Types per Rust3ProviderFaultV2/CancelV2/CancelledV2 and RUST3-FAULT-CANCEL-TYPES; phase vocabulary is the 16 *PRE_COMPLETE phases.",
        "none", "Members had no types (R3-G14); choices follow TS2 CancelV1 nullability, rust2 IdentityText and P3 phase names.",
        ["rust3-cancel-types", "rust3-phase-vocabulary"]),
    row("SUCC-RUST3-OBSERVED", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.BudgetExhaustedV2 (observed)")],
        "value-stated", "observed = limit + 1, as TS2 BudgetExhaustedV1 states and rust2 deterministicBudget checked increments imply.",
        "none", "R3-G14 residue.", ["rust3-observed-limit-plus-one"]),
    row("SUCC-RUST3-SNAPSHOT-ENTRY", ["rust-semantic major 3"],
        [t("rust2", R2 + "definitions.SnapshotEntryV2.variants")],
        "types-stated", "contentSha256 DigestHex, executable bool, targetBytes non-empty byte string.",
        "none", "rust2 subjectsAlgorithm consumes contentSha256 as the manifest digest; requestProjection keeps symlink target BYTES in the manifest; schemaLanguage.bytes is the only byte type (R3-G15).",
        ["carrier-member-lists"]),
]

FALSE_GAPS = [
    {"gap": "R3-G13 StageResultV2 has no successor", "refutation": "native-evidence.md §9.7 (Coverage frames, Commitments) names StageResultV2.coverageCommitment among recipes unchanged over CoverageResultV3 values; the §0 line 129 row supersedes its value domain, not its members. Carrier Rust3StageResultV2 keeps the five members; no StageResultV3 is needed."},
    {"gap": "R3-G15 chunk/seal integer types only derivable", "refutation": "rust2 schemaLanguage.integer ('exact nonnegative CBOR major-type-0 integer') plus canonicalCbor.closedDataModel make every integer member uint64; limitPolicy.arithmetic states the checked uint64 law. Governed, not derived."},
    {"gap": "TS2-G3 stageId bound", "refutation": "dispatch-binding expectedStageId maxLength 255 is defined as StageRequestV1.stageId / StageRequestV2.planStage.stageId and §9.6 requires a dispatch binding for each requested stage."},
    {"gap": "TS2-G6 / R3-G6 payload selection without tag", "refutation": "Handshake law factBatch.negotiated and startup preAnalyzeUnavailable.phase select the payload from host state; the carrier input publishes the two selectors and adds no wire tag."},
    {"gap": "TS2-G9 wireSchemaCommitment for major 2", "refutation": "No TS2 Hello member carries a contract digest (handshake frameAndMajor); the historical commitment stays recomputable over unchanged bytes and is not a wire field."},
    {"gap": "R3-G18 common-control owner", "refutation": "Closed by root: docs/implementation/m1/control-source-route.v1.json pins control-completion.schema.v3 through the reviewed freeze chain. Out of scope for provider carriers."},
    {"gap": "R3-G17(c) T016/T020/framePrecheck missing from P3", "refutation": "P3 ownedByProse assigns payload validation to prose/schemas; the retained rust2 guards are payload admission applied before matching, with the same FAULT outcome."},
    {"gap": "Envelope/DependencySourceChunk/Accepted names (R3-G3)", "refutation": "The wire carries no record names; private type names are implementation choices, not version changes."},
]
