from pathlib import Path
import json,hashlib,shutil
B=Path('/tmp/opensip-design-corrections');L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews');N='claude-independent-design.v40';R=B/N;D=L/N;O=Path(__file__).parent;S=B/'candidate-subject.v40';H=lambda b:hashlib.sha256(b).hexdigest()
manifest=D/'final-public-artifact-manifest.json';m=json.loads(manifest.read_bytes());assert m['subjectManifestSha256']=='3be452843acb6f5f234dfc1826b627a234d81e5a45edd70715a03715d7467072'
for r in m['files']:
 b=(R/r['runtimePath']).read_bytes();assert H(b)==r['sha256'] and len(b)==r['bytes'],r['runtimePath']
 retained=D/r['retainedPath'] if 'retainedPath' in r else S/r['sameAsSubjectPath'];assert retained.read_bytes()==b,r['runtimePath']
j=json.loads((R/'review.json').read_bytes());assert j['verdict']=='CHANGES_REQUIRED' and not j['newMustIssues'] and [r['id'] for r in j['newShouldIssues']]==['S40-01'];assert j['childCompletion']['backgroundProcessesOutstanding']==0
rows=sum([j[k] for k in ['fDispositions','evaluationResidualDispositions','arDispositions','fwDispositions','inheritedResidualDispositions','scopedReviewOwnerDispositions']],[]);assert len(rows)==107
assessment={'standing':'Completed actual independent source40 CHANGES_REQUIRED substantively assessed. No current source41 assent, blind assent, grade, activation or readiness. Source41 contains an author correction still awaiting independent review; remaining capture assessment is active.', 'subjectManifestSha256':m['subjectManifestSha256'],'publicManifestSha256':H(manifest.read_bytes()),'allPublicArtifactBytesVerified':len(m['files']),'reviewJsonSha256':H((R/'review.json').read_bytes()),'reviewMarkdownSha256':H((R/'review.md').read_bytes()),'rootReadScope':'Complete substantive Markdown including all107 dispositions; selected JSON findings/observations/item assessments/TCB and probe evidence; both minted-view probe implementations read complete. JSON contains additional machine inventories not all read as prose. Eleven claimed fresh whole-file reads independently verified against public line output. Other probe executions are reviewer evidence, not new root reruns.', 'requiredFinding':{'id':'S40-01','assessment':'Agree source40 lacks the capability-relation attribution recipe and explicit shared/unmatched-view treatment. Source41 publishes that recipe and enforces same-universe scope law. Remaining explicit-return capture and multi-cell shared-view controls are under actual author assessment.','qualification':'Two different hostCapture observations are distinct semantic inputs. Acceptance of both alone does not establish nondeterminism or detectable malicious host omission. Concrete question is whether the builder faithfully captures the same explicit returned-view input. The published trusted-host boundary stays intact.','next':'Assess actual f561 capture proposal, integrate any minimal required correction into a NEW frozen successor, then obtain independent85 substantive final source review.'},'editorialAdvisory':{'id':'ADV40-01','assessment':'Retain immutable historical layer8 bytes. Clarify its superseded intermediate standing in current planning provenance at the next successor; current layer10 binds the current31 planning inputs. No old-byte relabel.'},'confirmedPredecessorFindings':['S39-01','S39-02','ADV39-01'],'107Dispositions':'All individually read in Markdown; final application must assign substantive grades. No blanket carried acceptance.','trustedBoundary':j['sharedAssumptionTCBSCOPE01'],'readAudit':{'path':'verification.json','sha256':H((O/'verification.json').read_bytes()),'completeReads':11},'retainedObligations':j['retained'],'sourceAcceptance':False,'implementationReady':False}
(O/'assessment.json').write_text(json.dumps(assessment,indent=2)+'\n');shutil.copytree(O,L/O.name);print(json.dumps({'artifactsVerified':len(m['files']),'manifestSha256':H(manifest.read_bytes()),'assessmentSha256':H((O/'assessment.json').read_bytes()),'sourceAccepted':False}))
