"""Prepared only: actual independent v17 review requires final frozen source and root assent."""
from pathlib import Path
import datetime,hashlib,json,subprocess
root=Path.cwd();dc=root/'docs/coop/design-corrections';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text())
mp=dc/'reviews/candidate-subject.v17.json';m=load(mp);digest=sha(mp)
a=load(dc/'reviews/codex-post-reset.v1/successor-source-assessment.v17.json');assert a['finalSourceAssent'] is True and a['independentAcceptance'] is False
handoff=root/a['actualCoauthorHandoff']['path'];assert sha(handoff)==a['actualCoauthorHandoff']['sha256'];receipt=load(handoff.with_name('response.json'));assert receipt['is_error'] is False
for rel in ['reviews/codex-post-reset.v1/technical-review.v17.md','post-reset-dispositions.v17.proposed.json','reviews/codex-post-reset.v1/blind-assessment.v6.json']:assert (dc/rel).is_file()
for row in m['files']:
 p=Path(m['snapshotRoot'])/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes']
out=Path('/tmp/opensip-design-corrections/post-reset-review.v17');out.mkdir(exist_ok=False)
prompt=f'''You are ACTUAL CLAUDE in a FRESH INDEPENDENT OpenSIP architecture/design/reference review. You authored none of these bytes and are not correction coauthor {receipt['session_id']}, blind15922f81-214f-4262-9201-227218b75e99, or prior independent543080e2-18a0-42f2-bfd7-29858aaed6bb. User requires actual Claude and Codex alignment before implementation. No agents, fixes, product implementation, commits, pushes or subject edits. Write ONLY {out}, including every disposable copy/probe/report. Python /tmp/opensip-architecture-review-env/bin/python -I -B. Never run report-writing checks in immutable snapshot/live repo.

Frozen subject {m['snapshotRoot']}; manifest {mp}; SHA256 {digest}. Verify ALL file hashes/lengths and undeclared inventory before and after review. Read all five product contracts/index, exact v16->v17 source delta, successor-source-assessment.v17.json, technical-review.v17.md, v17 dispositions/advisory account, actual coauthor handoff at {handoff.relative_to(root)} with retained source/probes/custody. Fully read actual post-reset-review.v16 JSON/MD and consumer-b.v6/output/blind-review JSON/MD plus root blind-assessment.v6.json and actual root probes. Earlier independent ACCEPT did not survive blind reconstruction. Every unresolved MUST OR SHOULD requires CHANGES_REQUIRED regardless of headline or check count.

Independently assess EACH CB6-MUST1/2, SHOULD1/2, ADV1/2/3 and EVERY additional finding in source assessment/coauthor handoff, preserving original severity and actual disposition:
- Repair per-requirement producer/consumer vocabulary preserves each native sufficiency cause and separately defines imported-evidence outcomes. Inspect actual schema/reference/prose joins, satisfaction/reason consistency and original full-evidence authority. Global D9/public termination vocab must not silently grow. Exercise actual native sufficiency to requirement to repair descriptor handling, including lossless formerly inexpressible failures and usable positives; distinguish trusted admitted model inputs from production measurement. No copied boolean alone proves authorization.
- Exact all-node TypeScript config kind derivation from admitted logical path, custom/nonentry configs, case and basename conventions. Verify normative recipe equals actual context admission and no semantic widening/case folding/prefix inference. Valid retained contexts must remain usable, wrong kind refuses.
- One owned closed command->operation map: every45command and24operation accounted including intentional operations without a command, specialized import/preparation and repair-apply versus generic MutationParams. Name/class/step joins, exact schema/prose/reference consistency, replay preimage law and authority separation. Reject invalid mappings without promoting dedicated repair apply to generic mutation or inventing implicit config write.
- Coverage partition law: general disjointness within full owning tuple, totality only as declared by coverageTotality registry; preserve file inventory/ownership joins and relation/rung/state/count/class rules at producer and retained-Run admission. Symbol-to-file attribution remains trusted where contract says so, not claimed independently reconstructed.
- Unit discovery versus JS synthesized mode recognition, actual declared confidence-method scope versus defensive low-confidence sufficiency fixtures, and selected D9 extension versus immutable historical artifact/future integration obligation. Independently assess actual chosen wording, not the prior reviewer's inferred reading.

Assess all actual additional changes and new issues; do not limit review to named findings. Retain previous corrections on capability/default/availability composition, Unicode15 lib name conversion assumption, body language/compiler dialect ownership, anchor cardinality, registered payload/digest annotations, typed canonical equality, imported observations/ScopeDocument binding, static/runtime evidence distinctions, cache admission, repair projection/replay/purge disclosure and output failure after committed Run. Schema-document byte changes may move identity inputs and must not be described as unchanged exact preimages.

Reproduce ALL SIX final-reference.v17/reference-checks.json commands in disposable FULL exact subject copy. Verify all transitive source pins BEFORE execution, exits and deterministic reports against frozen results, never repin to manufacture success. Native checker writes in-tree report, so run ONLY disposable copy. Preserve all failed attempts and complete-copy deltas; record each copy. Independently author meaningful positive and negative controls at the changed boundaries. Use full admitted positive Run graphs where changes affect closure; schema fragments do not prove full Runs. Avoid rerunning the full check-identity suite on every probe import. Reference counts are measured calls/distinct IDs and scoped cases/sweeps, not product qualification.

Evidence honesty: blind v6 constructed355 CAS objects but its four claimed complete Run graphs refuse missing retained schema bytes, and separate policy/waiver schema checks fail. Its83 negative-labelled controls include3positive/hash-distinction controls; some other assertions are narrative. Original report remains literal historical evidence, with root qualifications. Those helper limits do not erase valid normative gaps and do not count as design omissions where existing text is precise. Your own report must distinguish schema/helper/full closure/executed expectation/narrative and first actual refusal boundary. Keep every required count/result tied to actual code/output, no blanket coverage claim. A NEW independent blind reconstruction remains separately required after your acceptance.

One complete intended product implemented in stages. All16AR/all15FW,27inherited residuals,30evaluation subresiduals,fiveDR201..205 and32UNPERFORMED qualification gates remain in view. CARRIED-UNCHANGED and routing-only are not new grades/final application outcomes. D372 unapplied;condition5 NOT MET; no implementation authorization. All four selected macOS/Linux machine IDs and TS/JS/Rust/bounded grammar paths retain current scope; no invented provider/OS/compiler/crypto/storage qualification.

Deliver substantive review.md AND review.json: top-level verdict ACCEPT/CHANGES_REQUIRED/actualBLOCKED, subjectManifestSha256='{digest}', newMustIssues and newShouldIssues arrays empty ONLY when none unresolved, separate newAdvisories. priorFindingDispositions individually account all7CB6 plus actual additional source findings. Individually keyed arDispositions/fwDispositions/inheritedResidualDispositions/scopedReviewOwnerDispositions provide actual basis/scope/authority. When five owner rows remain routing-only, explicitly record appliedByThisReview=false and finalApplicationOutcomeGranted=false; the precise scope is that five owner routing assessments do not grant a final application outcome and are not a grade. Do not grant a grade by inference. Retain probe source/results/failed attempts and complete-copy custody. Finish a substantive verdict bound to exact frozen bytes; no blind/application/readiness/product acceptance inferred.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Bash','Write','--strict-mcp-config','--output-format','json']
p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=root,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(out/'process.json').write_text(json.dumps({'pid':p.pid,'manifestSha256':digest,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(p.pid,digest)
