"""Root fixes the remaining native-registry annotation; actual Claude reviews exact bytes."""
from pathlib import Path
import datetime,difflib,hashlib,json,shutil,subprocess
root=Path.cwd();base=Path('/tmp/opensip-design-corrections');old=base/'bv6-corrections-author.v5';out=base/'bv6-corrections-author.v6';sid='4b48ccdd-92fb-4f92-9db2-ac8942f796d6';ev=root/'docs/coop/design-corrections/reviews';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();h=json.loads((old/'handoff.json').read_text());assert not json.loads((old/'response.json').read_text())['is_error'];assert (ev/'bv6-corrections-author.v5/custody.json').exists();assert len(h['changesRequired'])==1
for r in h['changedSource']['files']:assert sha(old/'work'/r['path'])==r['v5Sha256']
a={'standing':'Fullv5handoffJSON/MD/receipt and onecommentdiff read; priorcommentcorrected, finalaggregateassentstillfalse for one nativeannotation. Rootagrees andcorrects it innewcopy.','sessionId':sid,'handoffReadInFull':True,'markdownReadInFull':True,'responseReadInFull':True,'sourceDeltaReadInFull':True,'finalSourceAssent':False,'handoffSha256':sha(old/'handoff.json'),'markdownSha256':sha(old/'handoff.md'),'responseSha256':sha(old/'response.json'),'finalSourceHashesVerified':17,'remainingFindings':h['changesRequired'],'reportQualifications':['V5 no suite run;1787count remainsv4measurement, ASTidentitynotnewmeasurement.','V5controlIdCount170 is extracted literalIDs only,notruntimecheckcount; coauthor priorv4staticcalls338includesdifferentextraction.','Root broadcase-insensitive scan independently confirms remaining presenceLaw falsecausalclause. NeighboringcheckID accuratelydescribesCURRENTschema; retainingit is not a newfinding.','Allpreviousv3/v4source/evidencequalifications remain in their unchangedrootassessments.'],'implementationAuthorized':False,'readinessChanged':False};p=ev/'codex-post-reset.v1/coauthor-assessment-bv6-v5.json';assert not p.exists();p.write_text(json.dumps(a,indent=2)+'\n')
assert not out.exists();out.mkdir();shutil.copytree(old/'work',out/'work');inp=out/'root-input';inp.mkdir();shutil.copyfile(p,inp/'root-assessment.json')
for n in ['handoff.json','handoff.md']:shutil.copyfile(old/n,inp/('prior-'+n))
rel='docs/coop/design-corrections/native/native-evidence.schemas.v2.json';p=out/'work'/rel;s=p.read_text();wrong='except for the cross-plane rows, which the schema cannot decide because `relation` is a canonical identifier rather than an enum; that limit is stated rather than papered over.';right='except for the cross-plane rows: this schema deliberately leaves the authoritative relation-registry lookup to admission. Its oneOf admits either outcome vocabulary on either relation; admission decides the plane from registry membership. JSON Schema can branch on const/enum under a broader string type, but this schema does not duplicate that registry as conditionals or fetch its rows. This is the selected division between schema validation and admission, not a limitation caused by the relation type.';assert s.count(wrong)==1;p.write_text(s.replace(wrong,right));before=json.loads(s);after=json.loads(p.read_text());selector=['x-opensip-deficiency-cause-registry','perRequirementConsumerBoundary','consumers',0,'presenceLaw'];left=before;rightobj=after
for k in selector[:-1]:left=left[k];rightobj=rightobj[k]
left[selector[-1]]=rightobj[selector[-1]];assert before==after
(inp/'annotation-correction.diff').write_text(''.join(difflib.unified_diff(s.splitlines(True),p.read_text().splitlines(True),fromfile='v5/'+rel,tofile='v6/'+rel)))
(inp/'proposal.json').write_text(json.dumps({'finding':'BV6-V5-CR-1','severity':'SHOULD','path':rel,'selector':selector,'beforeSha256':sha(old/'work'/rel),'afterSha256':sha(p),'diffSha256':sha(inp/'annotation-correction.diff'),'onlyOneJsonStringChanged':True,'scope':'One normativeannotationstring reconciled to3agreedcopies. No executable/control/field/enum/validation constraint change. Registered documentdigest changes normally; rootfinal6mustrecomputeaffectedfixtures.'},indent=2)+'\n')
mp=ev/'candidate-subject.v16.json';inv=[]
for r in json.loads(mp.read_text())['files']:
 p=out/'work'/r['path'];inv.append({'path':r['path'],'sha256':sha(p),'bytes':p.stat().st_size})
(inp/'source-inventory.json').write_text(json.dumps(inv,indent=2)+'\n');(inp/'custody.json').write_text(json.dumps({'files':[{'path':str(p.relative_to(inp)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(inp.rglob('*')) if p.is_file()]},indent=2)+'\n')
prompt=f'''Actual sameClaude: bounded finalcheck of BV6-V5-CR-1. RootFULLYread yourv5handoffJSON/MD/receipt andagree soleSHOULD. Exactoneannotationstringcorrected in {out/'work'}, no otherJSONvalue/executable/control/enum/constraintchange. Read {inp/'root-assessment.json'}, {inp/'proposal.json'}, {inp/'annotation-correction.diff'}, finalpresenceLaw andthe3alreadycorrectedowningcontexts. Rootcase-insensitive broadscanconfirms thefalsecausalclause; neighboringcurrent-schema checkID stays asyounoted becauseitistrueofthisschemaaswritten, notnewfinding.

Verifyactual6839inventory/17finalhashes andsubstantively assesswhether exactaggregatecanadvance. SourceREADONLY;writeONLYunder{out};nofrozen/live/history/previoussourcewrites,baretmp,implementation,commit/push/publication/subagents. No broadsuitemeasurementneededforanannotation; registerednative-schema documentdigestDOESchange androotcanonical6willrecomputeaffectedreferencefixturesafterrecords/pins. Do notclaimbyteidentityofschemaorfixtureidentities. Youmaydisagree; returnpreciserequiredchangesifany. Preserveallpriorfindingseverities/dispositionsandqualificationsbyexactpriorhandoffreference.

Write EXACT {out/'handoff.json'} and {out/'handoff.md'}. Include technicalAssent.value, changesRequired, changedSource.files path/frozen16Sha256/finalV5Sha256/v6Sha256/changedThisTurn derivedfromactualbytes+priorhandoff. Keep proseunder800wordsbesides17hashinventory; nohistoryessay or repeatedfullsuites. Need substantivecorrectness/contextassessment, notjusthashverification. Thisis COAUTHOR assent only; freshindependentfullClaude,NEWblind andfullapplicationreviewstillowed. Finishthisboundedreviewnow.'''
(out/'prompt.txt').write_text(prompt);args=['/Users/sb/.local/bin/claude','--resume',sid,'-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json'];proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=base/'bv6-corrections-author.v1/work',start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close();(out/'process.json').write_text(json.dumps({'pid':proc.pid,'sessionId':sid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'parentSubjectSha256':sha(mp),'priorHandoffSha256':sha(old/'handoff.json'),'sourceRoot':str(out/'work')},indent=2)+'\n');shutil.copyfile(old/'session-discovery.json',out/'session-discovery.json');print(json.dumps({'pid':proc.pid,'sessionId':sid,'out':str(out)}))
