"""Same actual Claude: reconcile final-v2 remaining joins, with fixed upfront feedback."""
from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
root=Path('/Users/sb/code/opensip-ai/opensip_arch');ev=root/'docs/coop/design-corrections/reviews';base=Path('/tmp/opensip-design-corrections')
old=base/'bv6-corrections-author.v2';out=base/'bv6-corrections-author.v3';sid='4b48ccdd-92fb-4f92-9db2-ac8942f796d6';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
receipt=json.loads((old/'response.json').read_text());assert receipt['is_error'] is False and receipt['session_id']==sid
retained=ev/'bv6-corrections-author.v2';assert (retained/'custody.json').exists()
for n in ['handoff.json','handoff.md']:assert sha(old/n)==sha(retained/n)
points=[
 {'id':'BV6-V3-RECEIPT','parent':'CX-BV6-04','severity':'SHOULD','finding':'The step-kind -> operation mapping is a substantive correction. But MutationReceiptV1 REQUIRES idempotencyKey, while import/native-preparation are explicitly excluded from generic replay and the new law only alludes to their own idempotency law without defining it. Publish the exact deterministic key/preimage and lookup/delivery meaning for these required receipts, bound to immutable admitted request/step/attempt inputs, or cite an exact existing owner. Preserve fresh explicit native execution, no auto-retry, custody/security/source joins. Also workflows section10 lists TWO receipt2 domains (workflow.mutation-receipt and workflow.verification-link), so exactly one receipt domain is false. Name the owning mutation receipt domain for these result branches. Reference not executing production emitter is a qualification limit, not a reason to omit required receipt fields.'},
 {'id':'BV6-V3-IMPORT-BINDING','parent':'CX-BV6-03','severity':'MUST','finding':'RepairPlanDescriptor.targets are finding FINGERPRINTS, whereas RuntimeSubject uses LogicalPath plus optional symbol and HistorySubject uses LogicalPath. Current imported_requirement_outcome directly reads maps keyed by those target strings, and prose calls the targets the same payload subjects. Publish the deterministic host projection/join via retained finding/fingerprint subject records, including ambiguity/unmatched handling and exact original evidence Run binding. A pure helper may consume an already-admitted projection, but the actual owning records and its caller/projection must be explicit; do not equate fingerprint strings with paths. RecipeRef has only contributionId/recipeId/recipeVersion/closureId and NO window-demand wire field. If a closure-owned deterministic recipe predicate owns a bounded observation demand, specify its binding/projection rather than claim a nonexistent field. Preserve symbol versus file granularity and bounded observation semantics without inventing universal non-use.'},
 {'id':'BV6-V3-IMPORT-CAUSE','parent':'CX-BV6-03','severity':'MUST','finding':'Final-v2 root controls prove admit_evidence_requirement ADMITs runtime-observation with history-range-insufficient and history-change with subject-not-observable, although the published perKindApplicability excludes both. The producer checks per-kind applicability; consumer checks only the broad imported plane. Reconcile actual producer/consumer admission with the owning per-kind law, retaining lawful runtime and history outcomes and typed presence/error routing. These are helper boundary controls, not claimed host exploits.'},
 {'id':'BV6-V3-IMPORT-SEMANTICS','parent':'CX-BV6-03','severity':'MUST','finding':'Final-v2 law says partial-acceptable requires at least one supported target, but producer still vetoes any unobservable runtime target and any uncovered history target before its ANY test. Root partial fixtures have one supported and one such other target and refuse. Choose and state all actual conditions coherently; preserve valid partial cases and required safety. required=True default is fine, but explicit None/0 currently becomes optional success, while text says unknown declarations are required. Either enforce the precise typed input boundary/derivation or make its actual admitted precondition explicit and remove the contradictory unknown claim; do not invent a full-product exploit from out-of-domain helper arguments. The existing completeness enum did not already publish this imported ALL/ANY target interpretation: identify it as the selected clarification. Optional repair projection must be explicitly related to owning recipe/rule declaration, not silently equated with policy predicate truth.'},
 {'id':'BV6-V3-PRECISION','parent':'CX-BV6-07/CX-BV6-08','severity':'SHOULD','finding':'A broad string relation type does NOT make schema conditionals on const/enum impossible. It is fine to deliberately leave authoritative registry lookup to owning admission, but remove the false because-relation-is-not-enum rationale. Preserve D9 ENUM, not assert whole changed definition bytes unchanged. Handoff FULL RETAINED-RUN claim for repair_preview cases is false: those are synthetic workflow helpers; reserve close_run claim for actual retained closure controls, distinct from ledger/evaluator execution. Four command renames comprise3generic+1dedicated preparation, not4generic rows. V2 wrote external /tmp/hb.log,/tmp/hd.py,/tmp/delta-table.md (and possibly cx_handoff_fix.txt only if actually written); do not repeat all-writes-inside-output claim. Public tools and exact external final files retained with limits. V2 public note was read once at22:51UTC; later root additions were not substantively covered, including feedback arriving during/after handoff. Do not claim every final note point was agreed. Original handoff stays verbatim.'}
]
a={'standing':'Final-v2 proposal partly corrected; remaining joins require follow-up. No integration or successor acceptance.','sessionId':sid,'handoffReadInFull':True,'finalSourceAssent':False,'handoffSha256':sha(old/'handoff.json'),'markdownSha256':sha(old/'handoff.md'),'finalSourceHashesVerified':17,'sourceDeltaReadInFull':False,'sourceReadingScope':'Core changed registry/model/schema laws and drafts read; full17-file v2 delta assessment continues independently. Known final-source counterexamples suffice to reject assent; no blanket review coverage claimed.','confirmedCorrections':['Root final-source overlap3cases: disjoint and different-relation admit; overlap refuses precise guard.','Root no-Coverage2cases: disjoint admits, overlap refuses.','Root five requirement shape cases now agree with owning schema.'],'rootPoints':points,'finalSourceProbes':'bv6-final-v2-root-probes.v1','qualification':'Reference controls only. Prior8rootpoint/originalblind severities preserved. The following are remaining aspects of those points, not independent acceptance.'}
ap=ev/'codex-post-reset.v1/coauthor-assessment-bv6-v2.json';assert not ap.exists();ap.write_text(json.dumps(a,indent=2)+'\n')
assert not out.exists();out.mkdir();shutil.copytree(old/'work',out/'work');inp=out/'root-input';inp.mkdir()
shutil.copyfile(ap,inp/'root-assessment.json')
for n in ['handoff.json','handoff.md']:shutil.copyfile(old/n,inp/('prior-'+n))
shutil.copyfile(old/'CODEX-PUBLIC-NOTE.md',inp/'final-v2-public-note.md')
shutil.copytree(ev/'codex-post-reset.v1/bv6-final-v2-root-probes.v1',inp/'final-v2-root-probes')
mp=ev/'candidate-subject.v16.json';assert sha(mp)=='ca5f36d421fb38d264f49fc6b2e1eeffee5bbe8182a7fe25bd50787244042ee9';shutil.copyfile(mp,inp/mp.name)
inventory=[]
for x in json.loads(mp.read_text())['files']:
 p=old/'work'/x['path'];q=out/'work'/x['path'];assert sha(p)==sha(q);inventory.append({'path':x['path'],'sha256':sha(q),'bytes':q.stat().st_size})
(inp/'final-v2-source-inventory.json').write_text(json.dumps(inventory,indent=2)+'\n')
(inp/'custody.json').write_text(json.dumps({'standing':'Fixed upfront final-v2 feedback for actual coauthor, not independent evidence.','files':[{'path':str(p.relative_to(inp)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(inp.rglob('*')) if p.is_file()]},indent=2)+'\n')
prompt=f'''Continue as ACTUAL CLAUDE COAUTHOR in same session. Codex read FULL final v2 handoff JSON/MD and receipt, verified17exact source hashes, and executed final-source root controls. Root does NOT assent yet. V2 and all its evidence are retained verbatim. All source remains unintegrated; no successor freeze/readiness or product implementation.

ONLY editable scope now {out}; work {out/'work'} is complete exact copy of FINAL v2, verified against6839-file inventory. This replaces earlier write locations. NO writes in v1/v2/live/frozen/history, NO product implementation/commit/push/publication/subagents. EVERY script/log/temp must be under {out}; no /tmp/hb.log or other immediate /tmp output. Read {inp/'root-assessment.json'} and all final-v2 root probe source/results fully BEFORE edits. The five remaining items are narrow, concrete final-source joins, mostly later public-note additions you had not seen at your22:51read. This feedback is fixed upfront. Preserve earlier real corrections and original severities; do not re-open unrelated design.

Fix all five items substantively in coherent normative/schema/reference bytes and meaningful controls. In particular required import/preparation receipt key derivation and retained fingerprint-to-imported-subject binding cannot be replaced by claiming no production emitter or a trusted boolean. Pure reference already-admitted assumptions are permitted when exact owning boundary/projection is defined. Preserve supported runtime/history, partial cases, symbol/file distinctions, original native safety and recipe authority, all23generic operation tokens and dedicated repair apply. No D9 widening. Treat new laws as selected design clarifications, not historical facts you did not find.

Do NOT run whole suites after each edit. Focus changed-boundary controls and run affected suites once after coherent final source. Root does canonical final six AFTER source and records/pins. Do not change RELEASED work generated reports/pins/readiness/reviews. Any repins/full checks in separately inventoried disposable copy ONLY under {out}; preserve failures without repeatedly overwriting reports. No prose-substring or self-mirroring tests. Write assessment then final handoff.md/json with exact aggregate delta vs frozen16 AND turn delta vs finalv2, all five follow-up plus original8root/originalblind/own-new dispositions, precise controls/limitations and technicalAssent only to exact released source. Correct v2 scope claims in NEW handoff; originals stay unchanged. Read any {out/'CODEX-PUBLIC-NOTE.md'} immediately before the final handoff if present. Finish the bounded corrections now. Root concurrently continues source/evidence review; final full exact-byte root review and fresh independent Claude, NEW blind and application review remain owed.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','--resume',sid,'-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Edit,Write,Bash','--allowedTools','Read','Grep','Glob','Edit','Write','Bash','--strict-mcp-config','--output-format','json']
proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=base/'bv6-corrections-author.v1/work',start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':proc.pid,'sessionId':sid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'parentSubjectSha256':sha(mp),'priorHandoffSha256':sha(old/'handoff.json'),'sourceRoot':str(out/'work'),'workingDirectory':str(base/'bv6-corrections-author.v1/work')},indent=2)+'\n');shutil.copyfile(old/'session-discovery.json',out/'session-discovery.json')
print(json.dumps({'pid':proc.pid,'sessionId':sid,'out':str(out),'standing':'Actual coauthor v3 active; no final source assent.'}))
