"""Root fixes actual coauthor's sole remaining comment; same Claude reviews exact successor."""
from pathlib import Path
import ast,datetime,difflib,hashlib,json,shutil,subprocess
root=Path.cwd();base=Path('/tmp/opensip-design-corrections');old=base/'bv6-corrections-author.v4';out=base/'bv6-corrections-author.v5';sid='4b48ccdd-92fb-4f92-9db2-ac8942f796d6';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ev=root/'docs/coop/design-corrections/reviews';h=json.loads((old/'out/handoff.json').read_text())
assert not json.loads((old/'response.json').read_text())['is_error'];assert (ev/'bv6-corrections-author.v4/custody.json').exists();assert h['technicalAssent']['value'] is False and len(h['changesRequired'])==1
for r in h['changedSource']['files']:assert sha(old/'work'/r['path'])==r['v4Sha256']
a={'standing':'Actualv4fullhandoff/sourcepatch/evidence assessed; all5rootpatchitems agreed, one remaining SHOULD comment correction required. No final source assent.','sessionId':sid,'handoffReadInFull':True,'markdownReadInFull':True,'responseReadInFull':True,'sourceDeltaReadInFull':True,'handoffSha256':sha(old/'out/handoff.json'),'markdownSha256':sha(old/'out/handoff.md'),'responseSha256':sha(old/'response.json'),'finalSourceAssent':False,'finalSourceHashesVerified':17,'remainingFindings':h['changesRequired'],'reportQualifications':h['rootQualificationsAccepted']+['V4 phrase no report/pin mutation applies to released work. It executed check_workflows directly in two disposable copies and wrote external reports underout; no canonical6reproduction claimed.','Focused probe claim one-row/two-target coarsening is disclosed is established in normative text, not a new per-outcome variant-discriminator field; actual behavioral check establishes shared matching only.','Bounded coauthor review and AST comparison are separate from required fresh independentfullreview.'],'reviewedControls':['Full AST/checker comparisons, two1788/1787PASSreports withsourcehashes read.','Full verify_published_claims.py and sixclaimresultsread. Specific ambiguityreason checked; no harmless exception counted.','Leftover scan finds inheritedcomment error; historicalone-receipt narration is not currentfalseclaim.'],'sourceChangeAuthorized':'Root addressessolecommentinnewcopy; no behavioral testchange.','implementationAuthorized':False,'readinessChanged':False}
p=ev/'codex-post-reset.v1/coauthor-assessment-bv6-v4.json';assert not p.exists();p.write_text(json.dumps(a,indent=2)+'\n')
assert not out.exists();out.mkdir();shutil.copytree(old/'work',out/'work');inp=out/'root-input';inp.mkdir();shutil.copyfile(p,inp/'root-assessment.json')
for n in ['handoff.json','handoff.md']:shutil.copyfile(old/'out'/n,inp/('prior-'+n))
rel='docs/coop/design-corrections/workflows/check_workflows.v1.py';p=out/'work'/rel;s=p.read_text()
wrong='''# The two CROSS-PLANE rows are held separately and deliberately, because the SCHEMA CANNOT DECIDE
# THEM. `relation` is a CanonicalIdentifier, not an enum, so no keyword in this document can look up
# which registry that relation belongs to; the oneOf therefore admits either vocabulary on either
# relation. The plane is decided at ADMISSION from registry membership - the same place the
# imported-evidence evidenceDeclarationRule already separates the two planes - and these rows record
# exactly where the schema stops rather than asserting an agreement that does not exist.
'''
right='''# The two CROSS-PLANE rows are held separately because this schema deliberately leaves the
# authoritative relation-registry lookup to admission. Its oneOf permits either outcome vocabulary
# on either relation; the admission boundary decides the plane from registry membership. JSON Schema
# can branch on const/enum even when a property's base type is a broader string, but this schema does
# not duplicate that registry as conditionals or fetch its rows. These controls record the selected
# division between schema validation and admission, not a limitation caused by the relation type.
'''
assert s.count(wrong)==1;p.write_text(s.replace(wrong,right));assert ast.dump(ast.parse(s))==ast.dump(ast.parse(p.read_text()))
diff=''.join(difflib.unified_diff(s.splitlines(True),p.read_text().splitlines(True),fromfile='v4/'+rel,tofile='v5/'+rel));(inp/'comment-correction.diff').write_text(diff)
(inp/'proposal.json').write_text(json.dumps({'finding':'BV6-V4-CR-1','severity':'SHOULD','path':rel,'beforeSha256':sha(old/'work'/rel),'afterSha256':sha(p),'diffSha256':sha(inp/'comment-correction.diff'),'fullAstIdentical':True,'scope':'Exactly onecommentblock corrected; no executable/control/schema/law behaviorchanged.'},indent=2)+'\n')
mp=ev/'candidate-subject.v16.json';inv=[]
for r in json.loads(mp.read_text())['files']:
 p=out/'work'/r['path'];inv.append({'path':r['path'],'sha256':sha(p),'bytes':p.stat().st_size})
(inp/'source-inventory.json').write_text(json.dumps(inv,indent=2)+'\n')
(inp/'custody.json').write_text(json.dumps({'files':[{'path':str(p.relative_to(inp)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(inp.rglob('*')) if p.is_file()]},indent=2)+'\n')
prompt=f'''Actual same Claude, bounded final check of your sole remaining SHOULD BV6-V4-CR-1. You substantively agreed all5rootpatchitems and returned one leftover checkercomment. Codex FULLY read your v4handoffJSON/MD/receipt, all5diffs and owningcontexts, focusedprobesource/results and workflowreports, agreedyourfinding, and correctedexactlythatcomment in {out/'work'}.

Read {inp/'root-assessment.json'}, {inp/'proposal.json'}, {inp/'comment-correction.diff'} and finalcomment plus corrected owning repair.schema EvidenceRequirement.deficiency and workflows section6. FullASTINCLUDINGdocstrings is identical before/afterthiscommentedit; rootverified. Verify actual17finalhashes/6839inventory, no guessedhashes. Work source READ-ONLY; write review artifacts ONLYunder{out}, neverpreviouscopies/live/frozen/history/baretmp. No sourceedit/productimplementation/commit/push/publication/subagent.

Give substantive disposition of BV6-V4-CR-1 and exact aggregate17sourceassent ifwarranted, keeping your prior5itemagreement and previousfindingseverities/qualifications by exactpriorhandoffreference. Do NOT repeat a long historicalessay or run whole suites for a comment-only change; ASTcomparison plus actual wording/context review is appropriate, and rootcanonical6afterintegration/pinsstillowed. Existing1787workflowcount is historicalfromv4and not newlymeasuredhere unlessactuallyrun. This is coauthorassent, not independentacceptance/readiness. Final output files MUST be EXACTLY {out/'handoff.json'} and {out/'handoff.md'} (no extra out/subdirectory). JSON needs technicalAssent.value, changesRequired (emptyonlyifnone), changedSource.files with path,frozen16Sha256,finalV4Sha256,v5Sha256,changedThisTurn. Read all17hashes fromactualfiles, basesfrompriorhandoff. Keep prose concise (under1000words besideshashinventory), substantive and literal. Finish this one-comment review now; fresh independentfullClaude review, NEWblind and fullapplicationreview remain required.'''
(out/'prompt.txt').write_text(prompt);args=['/Users/sb/.local/bin/claude','--resume',sid,'-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json'];proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=base/'bv6-corrections-author.v1/work',start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close();(out/'process.json').write_text(json.dumps({'pid':proc.pid,'sessionId':sid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'parentSubjectSha256':sha(mp),'priorHandoffSha256':sha(old/'out/handoff.json'),'sourceRoot':str(out/'work')},indent=2)+'\n');shutil.copyfile(old/'session-discovery.json',out/'session-discovery.json');print(json.dumps({'pid':proc.pid,'sessionId':sid,'out':str(out)}))
