"""Record root substantive judgment after full completed actual independent21 review."""
from pathlib import Path
import json,hashlib,datetime,collections,subprocess
root=Path('/Users/sb/code/opensip-ai/opensip_arch');dc=root/'docs/coop/design-corrections';ev=dc/'reviews';own=ev/'codex-post-reset.v1';review=ev/'post-reset-review.v21';load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ref=lambda p:{'path':str(p.relative_to(root)),'sha256':sha(p)}
mp=ev/'candidate-subject.v21.json';assert sha(mp)=='360c2758c0409ebc307966c7a385c385c2d7f580b4623dd760b7ba0e26bf18c1'
rp=review/'review.json';r=load(rp);receipt=load(review/'response.json');custody=load(review/'custody.json')
assert sha(rp)=='f0a2824989ac1741e0f63b57209fbbfd541c715052330085fd5d7a32bd45e3fa'
assert sha(review/'review.md')=='85f12ea3c20e923aaceacd8c1b252e3bb56d224ca8b70c3acc390091405407af'
assert receipt['session_id']=='5256f644-14e4-41cb-93d5-fb19adf5a21b' and not receipt['is_error'] and receipt['subtype']=='success'
assert r['verdict']=='ACCEPT' and r['newMustIssues']==r['newShouldIssues']==[] and r['subjectManifestSha256']==sha(mp)
assert custody['firstPromptMatched'] and custody['frozenFilesVerified']==12212
canonical=load(review/'results/canonical/canonical-execution.json')
assert canonical['allSixExecuted'] and canonical['allExitAgree'] and canonical['allSourceHashesAgree'] and not canonical['orchestrationTimeout']
assert len(canonical['commands'])==6 and all(x['exitCode']==0 for x in canonical['commands'])
copies=custody['copies'];clean=next(x for x in copies if x['copy']=='copy');mut=next(x for x in copies if x['copy']=='mutation/tree')
assert clean['unchanged']==12212 and not clean['missing'] and not clean['deltas']
assert mut['unchanged']==12211 and not mut['missing'] and len(mut['deltas'])==1 and mut['deltas'][0]['path']=='docs/coop/design-corrections/workflows/workflows_model.v1.py'
counts=load(own/'identity-check-counts.v21.json');assert (counts['passingCalls'],counts['distinctIds'],counts['duplicateExtraInstances'])==(1596,1584,12)
mutreport=load(review/'results/identity-report.MUTATED.json');assert mutreport['passed']==1594 and mutreport['failed']==2
assert len(r['arDispositions'])==16 and len(r['fwDispositions'])==15 and len(r['inheritedResidualDispositions'])==27
assert set(r['scopedReviewOwnerDispositions'])=={'DR-'+str(i) for i in range(201,206)}
assert all(x['appliedByThisReview'] is False and x['finalApplicationOutcomeGranted'] is False for x in r['scopedReviewOwnerDispositions'].values())
environment=subprocess.run(['/tmp/opensip-architecture-review-env/bin/python','-I','-B','-c',"import sys,unicodedata,importlib.metadata,json;print(json.dumps({'python':sys.version,'executable':sys.executable,'unicodeData':unicodedata.unidata_version,'jsonschema':importlib.metadata.version('jsonschema'),'referencing':importlib.metadata.version('referencing')}))"],capture_output=True,text=True,check=True)
environment=json.loads(environment.stdout);assert environment==load(own/'final-reference.v21/environment.json')
qualifications=[
 'Full read covers complete final JSON with all ID maps, complete Markdown and receipt, source changes, substantive retained probes/results and relevant public tool provenance. No private thinking; not every unchanged historical file was manually reread.',
 'Independent21 did read the complete fivecontracts/index first: root compared each actual returned source line against frozen source,7729lines,6files. This is verified input-reading coverage; substantive judgment is in the completed Markdown section7, not inferred from line counts.',
 'Allsixcanonicalcommands were actually executed in an exact unrepinned copy and exit0. Root retention independently rescanned that surviving copy:12212unchanged,0deltas. The native command has no explicit --report, so its canonical record has null reportPath/hash; actual implicit native report is covered by the exact full-copy rescan. No timeout path was freshly executed by independent21; root synthetic and coauthor evidence remain separately pinned.',
 'The real workflow binder was called on seven scenarios, then a pure guard-transposition mutation changed exactly the noncandidate/multiple-row outcome. This is direct helper evidence, not a complete invocation or retained Run. Its script constructs plausible scope documents/specs but does not first run full schema/closure admission; admitted-positive-data wording is broader than that script demonstrates. Canonical checker separately schema-admits the third document.',
 'The mutated full identity checker executed1594passing/2failing, with exacttwoexpected control IDs. Mutated report is outside the sourcecopy; root retention verified mutationtree differs only in the intended workflow source, with before/afterbytes retained. The seven-scenario script records values rather than asserting expected outcomes; root read the actual values and broad checker contains discriminating assertions.',
 'CB-GAP-1 zero parameters legal is foundation/pre-Plan law. The direct scope-binding function refuses zero with BASELINE.SCOPE_NOT_A_SELECTED_PARAMETER when binding is requested. The review phrase zero rows legal at the helper does not describe that workflow function.',
 'Law structure/targeted scripts are source/JSON inspections, not actual independent registered-schema admission. Their initial wrong registry/annotation selectors and _SENTINEL search yielded0/empty, followed by public corrected reads of real selectors/_NO_REFUSAL. Do not promote those initial heuristic outputs into negative design findings or complete execution. Independent21 labels schema registration retention-first as read, not a hostile-store test; canonical actual closure checks and prior root/coauthor controls supply separate evidence.',
 'V20-ROOT-3 adopt_baseline and its two failure envelopes executed through the canonical identity checker. The independently authored adversarial.py separately constructs a Refusal(detail=None) and validates its termination; it does not itself call adopt_baseline or reach the duplicate-entry branch. Reachability is source inspection plus canonical suite, not a separately authored duplicate-baseline runtime probe.',
 'The AST comparison normalizes docstrings and compares selected code-object fields. Actual raw code objects, docstrings, trace line positions and introspection are not identical. The inspected workflow diff is documentation-only for modeled runtime behavior; the launcher/checker change executable behavior.',
 'The review calls three paths executables as a file category; only launcher and checker have executable logic changes. Workflow is documentation-only. Source21has0productcontract/schema changes; source20laws remain cumulative reviewed design.',
 'The environment wording is incorrect: independent21 used the SAME /tmp/opensip-architecture-review-env as root, not a distinct undocumented environment. Root remeasured exactPython3.12.13/UCD15.0.0/jsonschema4.25.1/referencing0.37.0 equality to final-root record. The prior final coauthor used jsonschema4.26.0 in its own environment; do not conflate sessions.',
 'V21-CL-ADV-1 search covers Python under design-corrections excluding reviews, not the entire frozen corpus or all human/external readers. Frozen review/orchestration scripts do read per-script reports. Their completion/exit and manifest gates matter; no-consumer-in-reviewed-corpus is an overclaim. Old child bytes remain a published advisory; aggregate timedOut/nullattribution/failed prevents acceptance for the timed-out run, and current canonical checks all completed.',
 'Fresh-report directories are an available caller option through --report-dir. Root retains the explicit attribution contract and historical child evidence rather than deleting old reports during this design correction. Any future consumer must bind child reports to a successfully completed aggregate or isolate per-run output; bare child passed counts are insufficient. This is an accounted advisory, not a silently waived required issue.',
 'AR16/FW15/inherited27 rows are literal carry-forward/routing only with generic bases, not individually adjudicated new grades. Markdown claim eachsetdisposedbyID is too broad: evaluation30 and gates32 have counts/flags, not30+32individual JSON dispositions. Complete final application review must assess allactualrows and gates substantively, including exactselectors; current source acceptance closes none of them.',
 'The five scoped owner rows say ROUTED-ONLY with bothauthorityflagsfalse. Preserve that literal vocabulary in the future application and adapt its scope-account guard explicitly; never convert this to an independent readiness grade. Source-independent acceptance does not grant application outcomes.',
 'CB-ADV-4 remains live: selectedcurrentD9composition is complete while owningartifact successor integration/qualification remains owed. Futureapplication must carry mandatoryobligation on DR007/DR011R08 and advisoryaccount; condition1MET/activation/finalappreview cannot discharge it.',
 'Broad whole-design descriptions are design judgments, not measured host/compiler/confinement behavior or exhaustive proof. Example counts and byte-identical reports are finite reference evidence; new blind semantic reconstruction and future qualification remain necessary.',
 'Preserve all rejected20 and earlierblind8 findings, prior scope/probe overclaims and actual failed attempts. Acceptance is only for frozen21bytes and does not retroactively accept historical versions or claim no future defect can exist.'
]
advice=[{'id':'V21-CL-ADV-1','originalSeverity':'advisory','reviewEvidence':{**ref(rp),'selector':'/newAdvisories/0'},'disposition':'Keep published aggregate-attribution contract and preserved stale child artifacts. Only a completed successful aggregate or isolated per-run report directory can support current child counts; actual source21canonicalrun completes. Root qualifies search scope: review/orchestration consumers exist and must gate on completion. Future full application review checks these gates. No required source defect left unresolved.','standing':'Accounted nonblocking advisory, not product qualification or permission to consume stale standalone reports.'}]
basis=[
 'Complete independent actual-Claude judgment on frozen21 with0MUST0SHOULD; exactmanifest12212files,all31protectedhistoryfiles and allfourledgers verified before/after. Root retention independently reverified frozen source and surviving canonical/mutation copies.',
 'Allfivecontracts/index actually supplied in full before findings, plus substantive whole-design judgment across discovery/native/evidence/identity/baseline/invocation/authorization and cumulative13source20corrections. Scope differs from incomplete20reading and remains explicitly design-level.',
 'Real seven-scenario binder counterexample and mutated fullchecker establish NEW-SHOULD-1 correction; root finaltimeoutreproduction and canonical six-successes establish reference failure-report path and preserved valid controls within stated limits.',
 'No unresolved root MUST/SHOULD on these exact design bytes. One advisory explicitly carried with narrower search/consumer scope. Eighty-one prior accounts retain originalseverity/history and currentindependentadvisory becomes82nd.',
 'Governance acceptance deliberately separate: freshNEWblind9, complete independentlyreviewedapplication/readinessreconciliation and unperformedplatformgates remain required; no implementationauthorized.'
]
record={'standing':'Root technical assent to actual independently accepted frozen21; not a second independent review, blind acceptance or readiness grade.','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actualReviewSession':receipt['session_id'],'actualClaudeModel':list(receipt['modelUsage']),'reviewSha256':sha(rp),'reviewMarkdownSha256':sha(review/'review.md'),'subjectManifestSha256':sha(mp),'fullRead':True,'rootDesignAssent':True,'unresolvedRootMustIssues':[],'unresolvedRootShouldIssues':[],'basis':basis,'qualifications':qualifications,'newAdvisoryApplicationAccount':advice,'actualReviewCustody':ref(review/'custody.json'),'contractReadCoverage':ref(own/'independent21-contract-read-coverage.v1.json'),'rootFinalSourceAssessment':ref(own/'successor-source-assessment.v21.json'),'actualEnvironment':environment,'requiredNextActs':['NEWblind9completeindependentsemanticreconstruction','Rootfullblindassessment','Completeindependentlyreviewedapplication/readinessreconciliation'],'implementationAuthorized':False,'readinessChanged':False,'productQualification':False}
p=own/'review-assessment.v21.json';assert not p.exists();p.write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'rootDesignAssent':True,'actualReviewSession':receipt['session_id'],'qualifications':len(qualifications),'sha256':sha(p)}))
