from pathlib import Path
import json,hashlib,importlib.util,shutil
root=Path.cwd();mp=root/'docs/coop/design-corrections/reviews/candidate-subject.v14.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(mp)=='45b1e128ca51d114895f3c406cc92575e6efe95051bf319023dc1f3180c2f92c';m=json.loads(mp.read_text());b=Path(m['snapshotRoot']);dc=b/'docs/coop/design-corrections';out=Path('/tmp/opensip-design-corrections/v14-post-freeze-publication.v1');out.mkdir(exist_ok=False)
s=importlib.util.spec_from_file_location('native_postfreeze',dc/'native/native_evidence_model.v2.py');N=importlib.util.module_from_spec(s);s.loader.exec_module(N)
rows=[]
for count in [93,94]:
 units=[{'rootPath':f'apps/u{i:03}','languageMode':'ts-tsconfig','languageFamily':'tsjs'} for i in range(count)]
 try:
  result=N.default_capability_selection(units,[]);rows.append({'units':count,'outcome':'ADMIT','requests':len(result['analysisSpec']['requestedCapabilities']),'notices':len(result['undeclaredCapabilities'])})
 except Exception as e:
  raw=str(e);r={'units':count,'outcome':'REFUSE','exception':type(e).__name__,'errorPrefix':raw[:160],'errorScalars':len(raw),'errorSha256':hashlib.sha256(raw.encode()).hexdigest(),'requestedRows':count*len(N.required_default_capabilities('ts-tsconfig'))}
  try:r['publicTermination']=N.public_termination_for(raw,'host-generated-internal-layer')
  except Exception as f:r['nativeRouteComposition']={'outcome':'REFUSE','exception':type(f).__name__,'error':str(f)[:250]}
  rows.append(r)
p=b/'docs/v2/contracts/product-v1/admission-and-qualification.md';text=p.read_text();fragment='`DomainDetail` carrying the existing `native.capability-unavailable`, through\n`DoctorResult.defects[]` or `StepTermination.domainDetail`.';assert fragment in text
report={'standing':'Root read-only findings on frozenv14; candidate unchanged; independent review active. Not an independent reviewer verdict.','subjectManifestSha256':sha(mp),'confirmedCurrentProseContradiction':{'id':'CX-V14-ADMISSION-AVAILABILITY-MIRROR','path':str(p.relative_to(b)),'sourceSha256':sha(p),'selector':'section1.1, paragraph beginning The registry states availability','literal':fragment,'conflictingSelectedSources':['native-evidence.md section1.4','workflows-and-surfaces.md section8','workflows/schemas/common.schema.json CapabilityAvailabilityV1 and command-envelope.availability'],'requiredCorrection':'Replace old doctor/singular-termination route with the actual original-invocation per-step typed availability collection, preserving native1.4/10 owning laws and no new behavior. Also align the opening registry supplies exact capabilities wording with matrix-derived scope; availability-only semantics already selected.'},'defaultCardinalityProbe':{'standing':'Investigation, not yet assigned severity. Generic schema refusal alone may be an existing admitted-size limit, but the public pre-Plan handling needs an owning route; root has not shown that the real host emits the native helper error or invents a host fault. No real host executed.','cases':rows,'openQuestion':'94ordinaryTSunits are below workspaceRoots1024 but default11capabilities yields1034requestedCapabilities above1024. Identify selected pre-Plan refusal/limit/carrier rather than silently truncate, misclassify host bug or claim arbitrary-scale support. Native public helper alone cannot map generic schema error. Verify owning generic host law before treating as a missing design contract.'},'implementationAuthorized':False}
(out/'report.json').write_text(json.dumps(report,indent=2)+'\n');shutil.copy2(__file__,out/'probe.py');q=out/'admission-and-qualification.md';shutil.copy2(p,q);print(json.dumps(report,indent=2))
