from pathlib import Path
import json,hashlib,datetime,copy,shutil
root=Path('/Users/sb/code/opensip-ai/opensip_arch');b=Path('/tmp/opensip-design-corrections');dc=root/'docs/coop/design-corrections';ev=dc/'reviews';own=ev/'codex-post-reset.v1';proposal=b/'v19-combined-proposal.v1';src=proposal/'work';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text())
def put(p,d):
 assert not p.exists(),str(p);p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,indent=2)+'\n')
def ref(p,selector=None):
 d={'path':str(p.relative_to(root)),'sha256':sha(p)}
 if selector is not None:d['selector']=selector
 return d
mp=ev/'candidate-subject.v18.json';assert sha(mp)=='cd6e828c22c6bc0ecf07ab8fe1f4bd5d1a5a8726708e0deffac99960bdc25a44';m=load(mp);frozen=Path(m['snapshotRoot']);old={x['path']:x for x in m['files']}
for row in m['files']:
 assert sha(frozen/row['path'])==row['sha256']
 if row['path']!='docs/coop/design-corrections/reviews/NEXT-REVIEW.md':assert sha(root/row['path'])==row['sha256'],('live drift',row['path'])
main=ev/'v19-native-coauthor.v1';mh=load(main/'handoff.json');assert mh['technicalAssent']['value']
subject=ev/'v19-subject-coauthor.v1';sh=load(subject/'handoff.json');assert sh['technicalAssent']['value'];assert not load(subject/'response.json')['is_error'];assert load(own/'coauthor-assessment.v19-consistency.v1.json')['rebasedSourceAssent'];assert load(own/'coauthor-assessment.v19-repair.v1.json')['finalSourceAssent']
paths={x['path'] for x in mh['changedFiles']}|{'docs/v2/contracts/product-v1/workflows-and-surfaces.md','docs/coop/design-corrections/workflows/workflows_model.v1.py','docs/coop/design-corrections/workflows/check_workflows.v1.py','docs/coop/design-corrections/check-integration.py'};assert len(paths)==11
for name in ['v19-protocol-preservation.final.v1','v19-plan-shapes.final.v1','v19-subject-final.v1']:
 q=b/'codex-post-reset.v1'/name;d=load(q/'result.json');assert d.get('allEqual',d.get('failed')==0);shutil.copytree(q,own/name)
for name in ['root-comment-corrections.json','root-subject-integration.json','standing.json']:shutil.copyfile(proposal/name,own/('v19-combined-'+name))
# Exact source proposals/diffs and before images, without duplicating unchanged whole subject.
before_dir=own/'source-before-v19';before_dir.mkdir(exist_ok=False);after_dir=own/'source-proposal-v19';after_dir.mkdir(exist_ok=False);delta=[]
for rel in sorted(paths):
 p=root/rel;q=src/rel;assert q.is_file();bd=old.get(rel,{}).get('sha256');assert (sha(p) if p.exists() else None)==bd
 if p.exists():t=before_dir/rel;t.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,t)
 t=after_dir/rel;t.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(q,t);p.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(q,p);delta.append({'path':rel,'beforeSha256':bd,'afterSha256':sha(p),'sourceProposal':str(t.relative_to(root))})
qual=['Main native coauthor originally delivered seven files. Actual consistency coauthor rebased against those exact final bytes, combining agreed precise prose/initialState additions. Root corrected four documentation-only residues with executable AST equality.','Root chose the literal-presence workflow subject conditional explicitly accepted as an alternative in actual coauthor handoff V19S-ROOT-3. BoundedText admits empty strings; unlike truthiness, presence preserves them and passes malformed supplied values to schema validation.','Coauthor says only None/empty differ; actually False,0,[],{} differ too. Its universal malformed-nonstring rejection claim does not hold for falsey values under truthiness. Final presence variant preserves all supplied shapes; root verified empty admitted and six malformed shapes refused by schema.','Coauthor backward-case adapter incorrectly read dependencyGate instead of case.gate, so it did not reconstruct all32 original records. Root reran exact original gate/dependency/retry mappings: all32 outcomes equal (24returned,8expected exceptional). Equality is structured, not byte serialization proof.','The lost subject does not make fields wholly indistinguishable: per-field remedies differ. Exact promised count/limit subject loss is independently sufficient justification. Root compacted overbroad new comments.','Only one projection site was changed; no claim every other field or detail constructor is universally lossless.','Actual coauthor59checks plus16durable helper checks are reference evidence over synthetic trusted observations. Root adds12durable actual-invocation composition checks and32original-case comparisons; no earlier fullRun or producthost execution.','Truthiness sibling Refusal.termination remains unchanged. Final terminate deliberately preserves an explicit empty subject, so parity is asserted for nonempty/absent only.','Source coauthors are not independent reviewers. No whole-candidate acceptance or readiness grade inferred from their substantive source agreement.']
put(own/'coauthor-assessment.v19-subject.v1.json',{'standing':'Root fully read actual handoffJSON/MD/receipt, all3probe sources, both durable blocks and measured outputs. Source variant choice and scope qualifications explicit.','fullRead':True,'finalSourceAssent':True,'independentAcceptance':False,'actualSessionId':'4b48ccdd-92fb-4f92-9db2-ac8942f796d6','handoff':ref(subject/'handoff.json'),'selectedVariant':'literal key presence, expressly permitted by coauthor','source':ref(root/'docs/coop/design-corrections/workflows/workflows_model.v1.py'),'qualifications':qual,'actualRootControls':ref(own/'v19-subject-final.v1/result.json'),'implementationAuthorized':False,'readinessChanged':False})
findings=[
 {'id':'CB7-MUST-1','severity':'MUST','finding':'Unknown TypeScript source-variant clone scope could claim complete without a fact.','correction':'Derive closed-suffix capability from owning universe at producer and retained Run boundaries; unknown/language-tier-unsupported/capability-missing for unsupported scope, preserving supported empty-body and Rust ownership cases.'},
 {'id':'CB7-SHOULD-2','severity':'SHOULD','finding':'Reachable Plan arrays128/128/256 lacked typed prospective refusal.','correction':'Account actual arrays before Plan minting and at context producer; PROJECT.SCOPE_LIMIT/REQUEST.UNSATISFIABLE/exit2 with exact subject and field remedy. Retained malformed Plan keeps schema route.'},
 {'id':'CX-V19-PRECEDENCE-PUBLICATION','severity':'SHOULD','finding':'Proposed grammar-first refusal wording contradicted earlier producer admission.','correction':'Align native contract and scopeCapabilityLaw metadata to producer first, then ownership/grammar/suffix prerequisites; honest disclosed unsupported scope admitted.'},
 {'id':'CX-V19-CONTEXT-AND-PLAN-ORDER','severity':'SHOULD','finding':'Remedy implied incomplete context identity was sufficient and Plan-array order was overstated across earlier producer phases.','correction':'Full identity equality, explicit fewer-root remedy, locally scoped assembledPlan order and accurate typed-vs-generic error explanation.'},
 {'id':'CX-V19-PROTOCOL-INITIALIZATION-PUBLICATION','severity':'SHOULD','finding':'Published transition rows omitted initialization and update-order details needed for independent reconstruction.','correction':'Publish exact nine-field initialState and ordered application law; consume initialState, preserve main disjoint matchLaw and34rows. No speculative security-bypass claim.'},
 {'id':'CX-V19-REPAIR-PROJECTION-MAPPING','severity':'SHOULD','finding':'Published REPAIR.EVIDENCE_RUN_UNAVAILABLE mapping did not explain existing per-requirement reuse.','correction':'Make mandatory per-requirement emission and exact cause/remedy explicit; distinguish retention and per-requirement remedy fields. Original blind code==cause finding remains withdrawn.'},
 {'id':'CX-V19-WORKFLOW-SUBJECT-PROJECTION','severity':'SHOULD','finding':'Workflow rejected-observation projection dropped actual bounded refusal subject.','correction':'Copy explicitly supplied subject; schema owns malformed values; durable unit/cross-unit/full-invocation controls preserve exact subject, earlier results, and refused-step absence of result/derivation.'}]
for f in findings:f['status']='CORRECTED-PENDING-SUCCESSOR-INDEPENDENT-REVIEW'
coauthors=[ref(ev/name/'handoff.json') for name in ['v19-native-coauthor.v1','v19-repair-coauthor-clarification.v1','v19-consistency-coauthor.v1','v19-subject-coauthor.v1']]
review=ev/'post-reset-review.v18/review.json';blind=ev/'consumer-b.v7-clarification.v1/output/blind-review.json';rr=load(review);assert rr['verdict']=='ACCEPT' and not rr['newMustIssues'] and not rr['newShouldIssues'];assert load(own/'design-assent.v18.json')['assent']
assessment={'standing':'Root and actual Claude substantive source agreement with explicit variant and documentation-only root differences. Source correction, not independent acceptance.','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finalSourceAssent':True,'independentAcceptance':False,'actualCoauthorHandoffs':coauthors,'actualCoauthorSessions':['4b48ccdd-92fb-4f92-9db2-ac8942f796d6','f8404b42-38fc-491c-973b-3c176e38278d'],'rootCoauthorAssessments':[ref(own/n) for n in ['coauthor-assessment.v19-native.v1.json','coauthor-assessment.v19-repair.v1.json','coauthor-assessment.v19-consistency.v1.json','coauthor-assessment.v19-subject.v1.json']],'priorIndependentReview':ref(review),'priorRootAssessment':ref(own/'review-assessment.v18.json'),'predecessorManifest':ref(mp),'latestBlindClarification':ref(blind),'sourceDelta':delta,'findingDispositions':findings,'withdrawnFinding':{'id':'CB7-SHOULD-1','status':'WITHDRAWN-BY-ORIGINAL-REVIEWER','evidence':ref(ev/'consumer-b.v7-clarification.v1/output/clarification.json'),'rootAssessment':ref(own/'blind-assessment.v7-clarification.v1.json')},'normativeInputAdditions':[ref(dc/'native/protocol3-transitions.v1.json')],'referenceEvidence':[ref(own/n/'result.json') for n in ['v19-protocol-preservation.final.v1','v19-plan-shapes.final.v1','v19-subject-final.v1']],'rootIntegrationQualifications':qual,'requiredNextActs':['Seal four ledgers includingnewnormativetable; six canonical commands; finalafterrecordingpinseal.','Freeze exact19 and obtain fresh independent source acceptance with0unresolvedMUST/SHOULD.','NEW blind8 on acceptednormativebytes; full separatelyindependentlyreviewedapplication/readinessreconciliation.'],'implementationAuthorized':False,'readinessChanged':False,'productQualification':False};put(own/'successor-source-assessment.v19.json',assessment)
items=copy.deepcopy(load(own/'design-assent.v18.json')['advisoryApplicationAccount']);assert len(items)==61
for item in items:item['carriedRecordScope']={'asOfSourceSubject':ref(mp),'standing':'Preserved earlier source-reference bindings are historical at their originating record, not silently rebased to19. Current19source changes bound by successor-source-assessment.v19.json; no fresh application grade.'}
ba=load(blind)['advisories'];notes=load(own/'blind-assessment.v7-clarification.v1.json')['advisoryAccounts']
for i,x in enumerate(ba):
 disposition=notes[x['id']]
 if x['id']=='CB7-ADV-4':disposition='Published34-row protocol3 artifact now includes initial state/update order and is consumed by reference. All11628bounded before/aftercomparisons agree; NEWblindmust independently reconstruct. No hostqualification.'
 items.append({'id':x['id'],'originalSeverity':x.get('severity','advisory'),'reviewEvidence':ref(blind,'/advisories/'+str(i)),'disposition':disposition,'standing':'Accounted for successor; no independent/application acceptance inferred.'})
assert len(items)==len({x['id'] for x in items})==66
put(own/'advisory-application-account.v19.proposed.json',{'standing':'66 individually accounted advisories, original severities/history preserved; finalsource19 review and complete application remain pending.','items':items,'sourceAssessment':ref(own/'successor-source-assessment.v19.json')})
put(dc/'post-reset-dispositions.v19.proposed.json',{'standing':'PROPOSED completed source corrections; canonical checks/freshindependent19/NEWblind/fullapplication pending.','predecessorManifestSha256':sha(mp),'actualPredecessorReview':ref(review),'predecessorVerdict':'ACCEPT','predecessorRootAssent':True,'latestBlindClarification':ref(blind),'items':findings,'withdrawnFinding':assessment['withdrawnFinding'],'actualCoauthorHandoffs':coauthors,'finalSourceAssessment':ref(own/'successor-source-assessment.v19.json'),'advisoryAccount':'reviews/codex-post-reset.v1/advisory-application-account.v19.proposed.json','implementationAuthorized':False,'readinessChanged':False,'productQualification':False})
p=dc/'correction-crosswalk.proposed.json';shutil.copyfile(p,own/'crosswalk-before-v19.json');cw=load(p)
for row in cw['items']:
 prev=copy.deepcopy(row.get('latestCompletedReview'));hist=row.setdefault('historicalReviews',[])
 if prev and prev not in hist:hist.append(prev)
 assert row['id'] in rr['arDispositions'];row['latestCompletedReview']={**ref(review,'/arDispositions/'+row['id']),'subjectManifestSha256':sha(mp),'overallVerdict':'ACCEPT','unresolvedMustIds':[],'unresolvedShouldIds':[],'standing':'Actual independent18 source review with originalcarrying/routingscope preserved. Laterblind7requires19correction; this historicalreview doesnotaccept19, NEWblind, fullapplicationorreadiness.'}
p.write_text(json.dumps(cw,indent=2)+'\n');p=dc/'README.md';oldread=p.read_bytes();(own/'corrections-readme-before-v19.md').write_bytes(oldread);p.write_text('''# Architecture corrections — v19 awaiting independent review

**Not ready for implementation.** Codex and actual Claude corrected unsupported clone-scope claims, prospective Plan limits and the preservation of exact refusal details through workflows. The published provider protocol now includes its transition table and initialization law, and the repair contract makes the existing evidence-requirement mapping explicit. The [technical assessment](reviews/codex-post-reset.v1/technical-review.v19.md) records exact source, checks and limitations.

These corrections belong to one complete design. Fresh independent acceptance, a NEW blind consumer and complete independently reviewed application/readiness reconciliation remain required. Historical v18 acceptance applies only to its frozen bytes. No product implementation, commit or push is authorized. [Resume guide](reviews/NEXT-REVIEW.md).

## Earlier progress — historical

'''+oldread.decode());print(json.dumps({'sourceFilesIntegrated':len(delta),'advisories':len(items),'sourceAssent':True,'independentAcceptance':False}))
