from pathlib import Path
import json,hashlib,subprocess,datetime,shutil
base=Path('/tmp/opensip-design-corrections'); out=base/'v19-consistency-coauthor.v1';out.mkdir(exist_ok=False)
main=base/'v19-native-coauthor.v1/work'; files=['docs/coop/design-corrections/native/native_evidence_model.v2.py','docs/coop/design-corrections/native/protocol3-transitions.v1.json','docs/coop/design-corrections/foundation/identity-model.py','docs/coop/design-corrections/foundation/identity-schemas.v2.json','docs/coop/design-corrections/integration-fixtures.py','docs/v2/contracts/product-v1/native-evidence.md']
manifest=[]
for rel in files:
 p=out/'before'/rel;p.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(main/rel,p);manifest.append({'path':rel,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(out/'before.json').write_text(json.dumps(manifest,indent=2)+'\n')
prompt=f'''Continue your actual-Claude SOURCE coauthor role, not independent acceptance or blind. No subagents. Only write {out}; main active copy remains read-only and do not edit it. Read copied current files in before/ and your prior agreed outputs under {base}/v19-prose-final-coauthor.v1 and v19-protocol-initial-coauthor.v1. Complete a bounded combined consistency pass, deliver proposed versions of ONLY the native contract, identity schema metadata, native model and protocol table under proposed/<original relative path>, plus handoff.json/MD with exact hashes, each disposition, and any disagreement. Keep all unrelated bytes unchanged. Use available pinned Python {base.parent}/opensip-architecture-review-env/bin/python -I -B if needed. No product implementation, no pins/reports/readiness edits, no six-suite reruns.

Apply your already agreed precedence-final.md and scope-remedy-before/after.py snippets, and protocol initialState+initializationAndUpdateOrder and initial-state-before/after.py snippets, after validating copied relevant control flow still matches. Main coauthor independently revised its matchLaw to state pairwise disjointness; PRESERVE that corrected main matchLaw rather than overwriting with the earlier proposed one. All34rows must remain byte/value identical.

Additional root concrete inconsistencies now visible in latest main draft; critically assess and correct narrowly:
1 identity-schemas x-opensip-digest-domains.scopeCapabilityLaw.guardOrder still says grammar/ownership FIRST and keep refusal names without accounting for earlier producer admission WITH owning dialect. Align it with your agreed precise native paragraph: producer admission may refuse falsecomplete suffix before closure prerequisites; within prerequisites ownership then grammar then suffix backstop. Honest disclosedunknown is admitted. The refusals property also claims distinct retained names; qualify that producer can refuse earlier, don't claim every name reachable in every scenario.
2 native protocol3_run docstring still says permuting currenttable demonstrates order load-bearing, contradicted by main's corrected disjointness controls/table. State optional rules is a reference control input and disjoint rows preserve current outcomes; normative declaredfirstmatch still governs.
3 native admit_plan_selection_cardinality docstring says same compiler/stdlib/options collapse contexts, omitting configGraphPaths and other identity fields. Replace with exact full-context-identity equality requirement, as prior remedy pass already agreed. Also its new generic schema exception claim 'names no field/count/limit' is false (actual schema errors may namefield); say it lacks required typed scope/termination projection, not nonexistent diagnostic details. Same new changed S14 native paragraph uses this falseclaim; correct current paragraph AND adjacent pre-Plan paragraph's same old unsupported claim so normative prose consistent. Do not change schema routing semantics.
4 S14 and helper docstring claim one fixed Plan-array order for an entire request, yet plan_native_context_digests now raises nativeContextDigests before assembled Plan fields exist. Clarify PHASES, preserving existingcode: producer computes/admission-validates/deduplicates contexts and can refuse there; if it succeeds, assembled prospectivePlan checker uses semanticClosures/nativeContextDigests/importIds order among fields PRESENT at that boundary. No globalordering claim acrossearlierproducer refusals. This is publicationclarity, no executable order change. Reject if evidence contradicts root.
5 Native protocol section should now explicitly mention published initial state and ordered state updates as part of completeartifact; no claim of newsecurity enforcement. Root disproved your earlier speculative initial-identityNegotiated=true bypass: phase gatingrequiresHelloAck whichoverwritesflag. Root retained exactprobe under live reviews/codex-post-reset.v1/protocol-initial-claim.v1; do notrepeatbypassclaim. The initialization publication is sound for complete independent reconstruction.

The original main author is independently finishing its source handoff. Your final proposals will be rebased only against verified matching beforebytes/relevantcontrolflow. Record this boundary, actual substantive assent to combinedchanges, and no independentcandidateacceptance. Be concise and finish this bounded prose/initial-state consistency work. No unrelated new features or review loops.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','--resume','f8404b42-38fc-491c-973b-3c176e38278d','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json']
p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=out,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':p.pid,'sessionId':'f8404b42-38fc-491c-973b-3c176e38278d','startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(p.pid)
