"""Prepared launcher, not executed until exact combined v19 source assent and frozen bytes exist."""
from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/Users/sb/code/opensip-ai/opensip_arch');dc=root/'docs/coop/design-corrections';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text());mp=dc/'reviews/candidate-subject.v19.json';m=load(mp);digest=sha(mp);a=load(dc/'reviews/codex-post-reset.v1/successor-source-assessment.v19.json');assert a['finalSourceAssent'] is True and a['independentAcceptance'] is False
for row in m['files']:
 p=Path(m['snapshotRoot'])/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes']
assert (dc/'reviews/codex-post-reset.v1/technical-review.v19.md').is_file();out=Path('/tmp/opensip-design-corrections/post-reset-review.v19');out.mkdir(exist_ok=False)
prompt=f'''You are ACTUAL CLAUDE in a completely FRESH INDEPENDENT OpenSIP architecture/design/schema/reference review. User explicitly requires substantive Claude and Codex agreement before implementation. You are not the source coauthors4b48ccdd-92fb-4f92-9db2-ac8942f796d6 or f8404b42-38fc-491c-973b-3c176e38278d, nor prior independent87a6bcea-c26a-47fe-8ded-2941b3e4e2ce or blind e6448709-ca71-43a1-97ce-b45b939367d9. No agents. Sources/history are READ ONLY; write probes, exact disposable copies and reports ONLY {out}. No product implementation, commits, pushes, publication or readiness activation. Use /tmp/opensip-architecture-review-env/bin/python -I -B. Never execute report-writing tools in the frozen or live tree.

FROZEN SUBJECT: {mp}, SHA256 {digest}; snapshot {m['snapshotRoot']}; {len(m['files'])} files. Verify every declared hash/length and inventory before and after; verify all four source-pin ledgers including new runtime table inputs. Reproduce the six canonical commands from reviews/codex-post-reset.v1/final-reference.v19/reference-checks.json in a disposable FULL exact copy WITHOUT repinning. Retain command/exits/stdout/stderr/report hashes and actual source-copy deltas. Unchanged bytes reconstruct from frozen parent; preserve changed probe/model/corpus bytes and failed attempts, rather than storing repeated unchanged full copies as review evidence. Counts are calls/cases, not qualification.

Read the five complete product contracts/index, owning schemas/registries and cross-unit reference joins. Inspect exact final sourceDelta in successor-source-assessment.v19.json, technical-review.v19.md, post-reset-dispositions.v19.proposed.json and advisory-application-account.v19.proposed.json. Independently inspect changed executable/schema/contract bytes and relevant surrounding control flow. Read actual two source coauthor handoffs/receipts and root assessments referenced there, treating assertions as evidence to assess rather than an oracle.

CONTEXT: independent18 ACCEPT was real, but original fresh blind7 found a TS unknown-suffix clone-scope gap and reachable prospective Plan128/128/256 limits without bounded typed refusal. Its additive clarification corrected its own missing finding-order and grammar-tree checks; root then verified all9 exact corrected exports against accepted18 reference. This preserves MUST1. S2's contexts are actual records, but its claimed retained config graphs are overbroad (unused local graph list, not full native/Run closure). Original CB7-SHOULD1 cause==code premise was retracted in full. A separate root/code-owner repair projection clarification now explicitly maps required entries to existing RUN_UNAVAILABLE and distinguishes retention vs per-requirement remedies, broadening published meaning to match unchanged model behavior. It must not be represented as original blind acceptance or revival of11newcodes. Read blind-assessment.v7-clarification.v1.json and actual blind7 clarification to assess these distinctions. Five advisories include published provider transition law, D9 enum11to12, default cap narrowing, platform scope and pinned UCD limits.

REQUIRED SUBSTANTIVE REVIEW: (1) TS closed-suffix clone scope classification at producer and retained-Run admission, unknown/language-tier-unsupported/capability-missing using owning registry. Empty and mixed scopes, unsupported zero-fact claims, supported TS/JS variants including declaration suffixes, inventory unaffected; preserve Rust ownership and syntax selected-grammar semantics, noting actual first refusal and any intentional precedence changes. Check optional context parameters cannot bypass final authority; no hardcoded vocabulary duplication. (2) Prospective Plan nativeContextDigests128, semanticClosures128, importIds256 must reach actual invocation refusal PROJECT.SCOPE_LIMIT / REQUEST.UNSATISFIABLE / exit2 with bounded field:count>limit/remedy, no refused-step Plan/Run, earlier committed outcomes preserved. Actual array-only cardinality, within-bound positives, mixed wrong types/oversized arrays and multi-field precedence; retained oversized Plan is corruption/schema admission, not prospective rejection. Confirm actual invocation wiring, not an orphan helper. (3) Provider protocol3 normative table must be directly consumable from the public kit, with34ordered rows, phase/wildcard/guard/action interpretation, drift checked or consumed by reference model; no silently altered transition behavior. (4) Exact workflow S6 code/remedy projection paragraph and unchanged model behavior; per-requirement cause fields are required only on that entry, not retention remedy; authoritative applicability/exact authorization binding preserved; schema-only permissiveness is not normative optionality.

Author your own discriminating controls for these changed laws and inspect preserved complete design: zero-config capabilities/discovery/config, native ownership/clone progression, static/runtime/test/history/import evidence authority, deterministic typed identity/closure, changed-code/baseline semantics, invocation/repair/replay/error surfaces, authorization and current availability. Reuse retained evidence for unchanged areas after verifying exact source identity and honest scope; do not rerun old broad probe suites absent a concrete concern. New required findings need a concrete counterexample and owning selector, with actual first failing boundary. Do not report literal/schema observations as executed security, host/compiler enforcement or fully admitted Runs. Do not force ACCEPT.

Assess every v19 disposition and carried advisory source binding. Prior reviews remain historical, not automatic acceptance of changed bytes. Review the governance groups on their actual scope:16AR15FW27inherited30evaluation5scopedowners32unperformed gates. Carry-forward/routing alone is not a fresh substantive readiness grade. Five DR201..205 rows must set appliedByThisReview=false and finalApplicationOutcomeGranted=false if only routing assessed. All32 qualification flags stay false, D372 unapplied, condition5 NOT MET. A NEW blind and complete separately independently reviewed application still follow any source acceptance; never claim their agreement now.

Deliver substantive review.json and review.md, top-level subjectManifestSha256='{digest}', verdict ACCEPT/CHANGES_REQUIRED/actualBLOCKED; newMustIssues/newShouldIssues empty only if none unresolved, separate newAdvisories. priorFindingDispositions must individually include CB7-MUST-1, CB7-SHOULD-2, withdrawn CB7-SHOULD-1 (as withdrawn), CX-V19-REPAIR-PROJECTION-MAPPING and all CB7-ADV1..5, plus any additional v19 source findings. ID-keyed arDispositions, fwDispositions, inheritedResidualDispositions and scopedReviewOwnerDispositions with actual basis/scope. Keep Markdown roughly3000words and JSON concise, with shared exact source references instead of duplicating prior reports or raw output. Retain probes/results separately. Finish with your substantive independent judgment on these exact bytes, not coauthor deference or readiness acceptance.'''
(out/'prompt.txt').write_text(prompt);args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json'];p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=root,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(out/'process.json').write_text(json.dumps({'pid':p.pid,'manifestSha256':digest,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(json.dumps({'pid':p.pid,'manifestSha256':digest}))
