from pathlib import Path
import json,hashlib,subprocess,datetime,shutil
base=Path('/tmp/opensip-design-corrections');out=base/'v19-subject-coauthor.v1';out.mkdir(exist_ok=False);root=base/'candidate-subject.v18';rel='docs/coop/design-corrections/workflows/workflows_model.v1.py';shutil.copyfile(root/rel,out/'workflow.before.py')
prompt=f'''Continue actual Claude SOURCE coauthor role, not independentacceptance. Your main handoff is completed and immutable. Onlywrite {out}. No subagents, no product implementation, commits/pins/governance. Root has fully read your source delta and is integrating with separate actualcoauthor's precise prose/initialstate additions. One concrete cross-unit reference issue found by root while meeting original requirement to exercise ACTUAL invocation boundary:

Read root exactprobe {base}/codex-post-reset.v1/probe-v19-invocation-subject.v2.py and result {base}/codex-post-reset.v1/v19-invocation-subject.v2/result.json. It obtains actual N.admit_plan_selection_cardinality refusal for each128/128/256Planfield, N.scope_refusal_termination exactsubject, supplies those typedfields to W.run_invocation rejected observation. Existing workflows_model terminate.dd copies code/remedy but DROPS obs.subject. All3 subjectPreserved=false, while earliercommittedresultpreserved=true/refusedstepnoresultorderivation=true. InputrecordandIDs synthetictrustedfixture; this doesNOTclaim earlierfullRunclosure orproducthost. v1probe failed on incorrectlyassumed Wreturnshape; v2corrects actualtupleunpacking and succeeds; preservebothscopehonestly.

Read frozen18 workflowmodel {root/rel} and owning native S14 + workflowcontract/Common DomainDetail law. Is rootidentifiedloss a real mismatch with the exactsubject the published scope refusal promises? If so propose narrow referencefix preserving optional subject WHEN provided, e.g. dd helper aftercreatingDomainDetail conditionalif 'subject' in obs copiesexactvalue, leaving no-subjectoutputsidentical. No schema/code/contractchange expected, no universal schema-admissionclaim for malformedtrustedobservations. If you disagree explainconcretely.

Deliver workflow.proposed.py exactbefore/afterhash and handoff.json/MD substantiveassent/disagreement, ownboundedprobe andoutput. Execute actual rootcomposition against proposedW with N from your completed work (readonly). Test all3 Planfields, previousrequestedCapabilities bound and workspaceRoots too if cheap, absent subject backwardequality, exactsubject retained perstep andaggregatetermination, exit2/error/detail/remedy, noresult/derivationforrefusedstep, earlierresultpreserved. Validate actual returnedInvocation/StepTerminationagainst publishedschemas using available pinnedPython /tmp/opensip-architecture-review-env/bin/python -I -B, label syntheticadapters. Add a small proposed durablecheck block for workflowchecker or standalone referencecontrol (root willintegrate); do not rerun sixsuites/pins. No unrelated changes. Complete bounded correction now; fresh independentcandidateandNEWblindwillassesscombinedfrozenbyteslater.'''
(out/'prompt.txt').write_text(prompt);args=['/Users/sb/.local/bin/claude','--resume','4b48ccdd-92fb-4f92-9db2-ac8942f796d6','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json'];p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=out,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(out/'process.json').write_text(json.dumps({'pid':p.pid,'sessionId':'4b48ccdd-92fb-4f92-9db2-ac8942f796d6','startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(p.pid)
