from pathlib import Path
import json,hashlib,shutil
root=Path('/Users/sb/code/opensip-ai/opensip_arch');dc=root/'docs/coop/design-corrections';own=dc/'reviews/codex-post-reset.v1';b=Path('/tmp/opensip-design-corrections');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text());ref=lambda p:{'path':str(p.relative_to(root)),'sha256':sha(p)}
a=load(own/'successor-source-assessment.v19.json');assert a['finalSourceAssent'] and not a['independentAcceptance'];commands=load(b/'final-reference-v19-complete/reference-checks.json');assert commands['passed'] and len(commands['commands'])==6 and all(x['exitCode']==0 for x in commands['commands']);dest=own/'final-reference.v19';assert not dest.exists();shutil.copytree(b/'final-reference-v19-complete',dest)
summary=load(dc/'validation-summary.v1.json');assert summary['claudeFinalReview']=='PENDING-FROZEN-V19' and summary['native']['qualifiedCells']==0;rows=[]
for row in a['sourceDelta']:
 p=root/row['path'];assert sha(p)==row['afterSha256'];rows.append({'path':row['path'],'beforeSha256':row['beforeSha256'],'finalSha256':sha(p)})
for rel in ['correction-crosswalk.proposed.json','foundation/source-pins.v1.json','security/source-pins.v1.json','native/source-pins.v2.json','workflows/source-pins.v1.json','validation-summary.v1.json']:
 p=dc/rel;rows.append({'path':str(p.relative_to(root)),'finalSha256':sha(p),'rootOwnedRecording':True})
p=own/'final-source-account.v19.json';assert not p.exists();p.write_text(json.dumps({'standing':'Exact mutually assessed source corrections with explicit root variant/documentation differences and executed six reference commands. Freshindependent19/NEWblind/fullapplication pending.','files':rows,'sourceAssessment':ref(own/'successor-source-assessment.v19.json'),'priorIndependentRootAssessment':ref(own/'review-assessment.v18.json'),'actualFinalCommands':ref(dest/'reference-checks.json')},indent=2)+'\n')
body='''# Codex v19 correction assessment

Codex and actual Claude addressed the two remaining blind findings and the adjacent publication and workflow projection gaps. These are changes to the complete intended design, schemas and reference models, not product implementation. [The source assessment](successor-source-assessment.v19.json) binds all eleven source files, actual coauthor handoffs, root assessments and exact limitations. Source agreement does not grant independent acceptance or implementation readiness.

The corrected blind7 clarification retains its TS unknown-suffix clone-scope MUST and prospective Plan-limit SHOULD. Root checked all nine corrected exported graphs against accepted18 before correcting the source. The original repair code-equals-cause premise was substantively withdrawn by the original reviewer; a separate root/coauthor mapping clarification now explains the existing mandatory per-requirement projection. Original opinions, probe failures and retractions remain preserved.

Unsupported body-dialect clone scopes now disclose unknown/language-tier-unsupported/capability-missing from the owning universe registry, even with zero facts. This law is selected by dialect form, not a TypeScript special case. Supported TS and declaration suffixes, Rust ownership and syntax selected-grammar controls remain meaningful. Producer admission with the owning dialect precedes the closure prerequisites; the revised native prose and schema metadata state that order. An optional producer context argument is not a bypass of final retained-Run authority. Mixed/empty helper controls are not each independently admitted full Runs, and the future opaque-subject branch has no current relation-registry caller.

Prospective Plan semanticClosures/nativeContextDigests/importIds limits remain128/128/256. Oversized actual arrays refuse before Plan minting with REQUEST.UNSATISFIABLE / PROJECT.SCOPE_LIMIT / exit2 and field-specific remedies. Context production can refuse earlier; declaration ordering applies among fields at the assembled-Plan boundary. Root verified24 composed full-schema controls covering malformed fields, missing fields, oversized malformed arrays and the two phases. Retained corruption keeps schema admission. Synthetic admission rows and a minted Plan with256synthetic imports do not prove129native contexts or256imports close a Run.

The provider protocol is now directly published as a34-row normative JSON table with the exact initial state and ordered update law. The model consumes it. All34rows and the corrected disjoint-match law remain intact. Root compared11628pure transition executions across38selected event alternatives, stage counts1and2 and122/162observable states with no mismatch. This is finite reference exploration, not arbitrary-input completeness, wire-schema or host/compiler/OS qualification. Claude withdrew a speculative initial-flag security bypass after root disproved it; publication completeness is the valid reason for the initialization addition.

The repair contract explicitly maps each unsatisfied evidence requirement to the existing REPAIR.EVIDENCE_RUN_UNAVAILABLE code, while its remedy and typed deficiency preserve the exact cause. Retention and per-requirement remedies have different fields. The source meaning is broadened to describe existing model routes, without adding codes or changing repair authority. Root reproduced the actual coauthor's16synthetic direct-preview controls under the pinned Python3.12 environment.

Root's actual invocation composition found that workflow terminate dropped the exact refusal subject. Actual Claude reproduced this over all3Planfields and2inherited bounded fields, proposed the two-line correction and explicitly permitted literal key presence. Root selected presence because BoundedText admits an empty string and malformed supplied values should reach schema validation. This is explicitly different from the coauthor's first truthiness proposal; no fabricated byte identity or unconditional producer parity is claimed. Root corrected the coauthor's32case adapter to use original case.gate values: all32outcomes agree (24returned,8exceptional). Seven explicit subject shapes distinguish schema-valid empty text from malformed supplied values. Durable controls include12actual full-invocation checks retaining the exact per-step and aggregate subject, preserving the earlier synthetic result and omitting a refused-step result/derivation.

All model evidence uses synthetic trusted inputs; no product host or earlier complete Run is inferred from invocation fixture outcomes. Coauthor static name-resolution scans are supporting heuristics; actual canonical checker execution below is the stronger integration evidence. Root-owned comment/docstring cleanup removes inaccurate schema diagnostic and context-identity wording, with executable AST equality for the documentation-only native changes. Necessary-versus-sufficient context-identity reasoning is explicitly qualified.

The prospective application account preserves66individual advisories:61from accepted18 and5from blind7. Original source-reference bindings are historical at their originating record, not silently relabeled current. The source assessment binds current19changes. These are records for the forthcoming application review, not fresh readiness grades.

Measured reference results, not exhaustive coverage or qualification:

'''
body+='```json\n'+json.dumps({k:summary[k] for k in ['foundation','security','native','workflows','integration']},indent=2)+'\n```\n\n'
body+='All31protected historical files remain unchanged. All four pin ledgers include the new normative protocol table. Final live and copied pin verification after recording is mandatory. Remaining acts: fresh independent acceptance of frozen19 with zero unresolved MUST/SHOULD, a NEW blind consumer using the accepted normative table and contracts, and complete separately independently reviewed application/readiness reconciliation. All32product qualification gates remain unperformed; D372 and condition5 remain unapplied/not met. No implementation, commit or push is authorized.\n'
p=own/'technical-review.v19.md';assert not p.exists();p.write_text(body)
td=own/'v19-tools';td.mkdir(exist_ok=False)
for n in ['assemble-v19-proposal.v1.py','finish-v19-subject-proposal.v1.py','integrate-record-v19.py','refresh-pins-v19.py','run-final-v19.py','record-v19.py','record-technical-v19.py','freeze-next.py','launch-review-v19.py','launch-consumer-b-v8.py','probe-v19-protocol-preservation.v1.py','probe-v19-plan-shapes.v1.py','probe-v19-subject-final.v1.py','probe-v19-invocation-subject.v1.py','probe-v19-invocation-subject.v2.py','retain-v19-native.v1.py','retain-v19-bounded.v1.py','launch-v19-consistency-coauthor.v1.py','launch-v19-subject-coauthor.v1.py']:
 shutil.copyfile(b/'codex-post-reset.v1'/n,td/n)
for n in ['retry-frozen-custody.v19.v2.json']:
 shutil.copyfile(b/'codex-post-reset.v1'/n,own/n)
# Preserve original root counterexample and failed attempt scope without changing historical files.
for n in ['v19-invocation-subject.v2']:
 shutil.copytree(b/'codex-post-reset.v1'/n,own/n)
print('Retained exact final19 source/reference evidence and technical assessment; fresh review pending.')
