"""Scoped supersession rows (candidate 03). Old parent bytes stay unchanged; each row names exact selectors, scope,
disposition, wire effect, justification and the checker ids that test it."""

D2 = "$.typescriptSemanticSubstrate.providerProtocol.wireSchema."
R2 = "$.wireSchema."


def row(id_, scope, targets, disposition, statement, wire_change, justification, checks):
    return {"id": id_, "scope": scope, "targets": targets, "disposition": disposition, "statement": statement,
            "wireChange": wire_change, "justification": justification, "referenceChecks": checks}


def t(pin, *selectors):
    return {"pin": pin, "selectors": list(selectors)}


ROWS = [
    row("SUCC-PER-KEY-SCOPE2", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("delivery2", D2 + "definitions.RequestedCoverageDomainV1.workerRule (clause: every key.subjectScopeCommitment equals subjectScope.subjectScopeCommitment)",
           D2 + "coverageDomain.keyConstruction.subjectScopeCommitment"),
         t("rust2", "$.planAndDomainProjection.coverageDomainAlgorithm[3] (member subjectScopeCommitment)",
           "$.commitments.subjectScope (as the value placed in keys)")],
        "superseded-value",
        "Each request key's subjectScopeCommitment is the sha256: text form of the key's own scope2 (PER-KEY-SCOPE2). Retained unchanged: TS SubjectScopeV1 (shape, recipe, subjectCount) and its place inside domainCommitment; rust2 subjects/SubjectV2 and the analysis-domain recipe; rust2 commitments.subjectScope stays a named recipe with no wire carrier.",
        "none (member, type and pattern unchanged; values change)",
        "native-evidence §4.1a, identity §3 and startup coverageFrames.entries require per-key values; keys in one stage differ in relation/rung/target, so a single per-stage value cannot satisfy them.",
        ["scope2-ts2-admits", "scope2-rust3-admits", "scope2-per-stage-value-refused", "scope2-keys-differ", "vectors:PER-KEY-SCOPE2", "scope2-descriptor-members-match-owner"]),
    row("SUCC-FACT-REF-REFUSED", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("factPlane", "$.factRecordContractV1.anchorSchema.variants.fact-ref"),
         t("delivery2", D2 + "definitions.AnchorRefV1.variants.fact-ref")],
        "not-admitted-under-fact2",
        "kind=fact-ref is PROVIDER.PROTOCOL_VIOLATION at candidate admission. Vocabulary and AnchorRefV1 shape unchanged.",
        "none", "fact-identity-fact2 is mandatory in both token sets; identity-schemas.v3 #/$defs/fact/properties/anchors items are {path, blobDigest, startByte, endByte}; FACT-ID-V1 is never relabeled (native-evidence §9.1).",
        ["anchor-fact-ref-refused", "fact2-anchor-closed-shape", "vectors:ANCHOR-FACT-REF-REFUSED"]),
    row("SUCC-ANCHOR-RULES", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("factPlane", "$.factRecordContractV1.sourceSpanSchema.rule", "$.factRecordContractV1.anchorSchema.ordering"),
         t("delivery2", D2 + "definitions.AnchorRefV1.ordering", D2 + "definitions.AnchorRefV1.join ('field-for-field')"),
         t("identityModel3", "line 1892 ANCHOR_RANGE (unchanged, not narrowed)"),
         t("factBatch3", "#/properties/candidates/items/properties/anchors/maxItems (JSON-vector bound 4096)")],
        "clarified-types-and-separated-rules",
        "Wire anchor rule: non-empty in-bounds interval plus ANCHOR-WIRE-SPAN types. Shared fact2 rule: 0 <= startByte <= endByte <= blob length and UTF-8 boundaries, unchanged. Anchor order per language: TS2 deterministic-CBOR bytes (the more specific TS transport ordering wins over its 'field-for-field' fact-plane claim), Rust3 CVE1 bytes. The orders differ through map-key order, not through string encoding. Wire count 1..100000 from identity-schemas.v3; 4096 is the fact-batch.3 JSON-vector bound.",
        "none", "Types were unstated (TS2-G5/R3-G5); the empty-interval difference between the two owners is a scope difference once stated separately.",
        ["anchor-empty-interval-refused-on-wire", "fact2-anchor-range-permits-empty", "anchor-order-languages-differ", "anchor-order-path-only-same", "vectors:ANCHOR-WIRE-SPAN"]),
    row("SUCC-TS2-MANIFEST-DIGEST", ["typescript-semantic major 2"],
        [t("delivery2", D2 + "commitments.domains.snapshotManifest (as applied to SnapshotManifestV1/SnapshotSealV1/SnapshotAcceptedV1.manifestSha256)")],
        "not-applied",
        "manifestSha256 is DigestHex = lowercase hex SHA-256(deterministic-CBOR(entries)), no domain and no sha256: prefix.",
        "none", "Field text says DigestHex; DigestHex cannot hold a sha256: value; rust2 commitments.snapshotManifest states the same raw recipe. Citation correction (inventory gap R3-G19): check-rust-provider-protocol.py is the v1 checker (line 27, recipe at line 1048); the v2 checker computes no manifest digest. Neither is an owner.",
        ["ts2-manifest-digest-raw", "ts2-manifest-domain-form-refused", "citation-v1-checker-is-v1", "gap-r3-g19-is-citation-defect", "vectors:TS2-MANIFEST-DIGEST"]),
    row("SUCC-DEPSRC-DIGEST", ["rust-semantic major 3"],
        [t("evidence", "#/$defs/DependencySourceManifestV3/properties/manifestSha256/x-opensip-digest",
           "#/$defs/DependencySourceSealV3/properties/manifestSha256/x-opensip-digest",
           "#/$defs/DependencySourceManifestV3/properties/entries/x-opensip-order")],
        "superseded-recipe-and-order-registered-bytes-kept",
        "manifestSha256 = lowercase hex SHA-256(deterministic-CBOR(entries)) (non-self-referential; rust2 commitments.snapshotManifest recipe, invoked by native-evidence §3.2 'same discipline as the snapshot'). entries order: UTF-8 byte tuple (name, version, sourceId, path) of the exactly joined package row, which equals DependencySourceSetV1.packages x-opensip-order {by:[name,version,sourceId]} then DependencyFileManifestV1 path order, as native_evidence_model.v2 dependency_source_set_admit sorts. The registered schema document is not edited.",
        "none (types/patterns unchanged; order and value recipe stated)",
        "The annotated preimage 'exact transport manifest frame bytes as sent' contains manifestSha256 itself. packageKey byte order is not the tuple order when a name holds a byte <= 0x20 (reviewer counterexample), so the tuple is normative.",
        ["depsrc-digest-non-self-referential", "depsrc-self-referential-unsatisfiable", "depsrc-file-manifest-join", "depsrc-empty-set", "vectors:DEPSRC-CUSTODY"]),
    row("SUCC-DEPSRC-SET-KEY", ["rust-semantic major 3"],
        [t("evidence", "#/$defs/DependencyPackageSourceV1/properties/name", "#/$defs/DependencyPackageSourceV1/properties/version",
           "#/$defs/DependencySourceManifestV3/properties/entries/items/properties/packageKey"),
         t("nativeModel", "dependency_source_set_admit (wrapped by the successor selector; function source sha256 in public-route-successor.v1.json)"),
         t("nativeMd", "§3.1 DependencySourceSetV1 (lines 1648-1703)")],
        "scoped-admission-constraint",
        "packageKey = name SP version SP sourceId, an exact echo join to one package row (PACKAGE-KEY-JOIN). The dependency-source set admission successor selector, run on an owner-admitted set before PlanId, refuses a package whose name or version contains a scalar <= U+0020 or whose constructed key exceeds 4096 scalars (the registered packageKey maxLength). The refusal is the SUCC-PUBLIC-ROUTES key native.dependency-source-not-wire-representable. sourceId keeps its owner domain: it may be empty (min key 4 scalars) and may contain spaces; a key is parsed only by the first two SP. DEL and C1 controls in name/version are deliberately admitted. Carrier minScalars is 4.",
        "none (no member/type change; a scoped refusal for an otherwise unrepresentable set)",
        "Owner row bounds (256 + 256 + 4096 + 2 = 4610) exceed the registered key bound 4096, and bytes <= 0x20 in name/version make keys ambiguous and break order. Cargo names and versions never contain such bytes, so no real lockfile is refused.",
        ["vectors:PACKAGE-KEY-JOIN", "vectors:DEPSRC-SET-KEY-CONSTRAINTS", "package-key-bounds-derived-from-owner", "route-join"]),
    row("SUCC-DEPSRC-REPRESENTABILITY", ["rust-semantic major 3"],
        [t("evidence", "#/$defs/DependencyFileManifestV1/items/properties/path", "#/$defs/DependencyPackageSourceV1/properties/name",
           "#/$defs/DependencyPackageSourceV1/properties/version", "#/$defs/DependencyPackageSourceV1/properties/sourceId"),
         t("nativeModel", "dependency_source_set_admit and file_manifest_identity (no segment or NFC check)")],
        "scoped-admission-constraint",
        "The same successor selector refuses an owner-admitted set with a non-NFC name, version or sourceId, or a file path that is non-NFC, longer than 4096 scalars or fails canonical-path-segments (empty, '.', '..', U+0000, backslash or a drive-prefix first segment). Nothing is normalized, truncated or renamed. The refusal is native.dependency-source-not-wire-representable (request-rejected 2 REQUEST.PRECONDITION_FAILED, derived). Owner refusals keep precedence.",
        "none (no member/type change)",
        "The owner admits and mints file-manifest identities for C:x, c:/lib.rs, a:b/c, Z:, a//b, a/ and non-NFC strings (executed: owner-admits-unrepresentable-dependency-inputs), while the Rust3 wire refuses non-NFC text at decode and canonical-path-segments refuses those paths: without this rule a reachable input would become a host that cannot encode or a worker protocol fault.",
        ["vectors:DEPSRC-WIRE-REPRESENTABILITY", "owner-admits-unrepresentable-dependency-inputs", "route-join"]),
    row("SUCC-REQUEST-ACCOUNTING", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("rust2", "$.framing.lengthScope", "$.framing.allocationRule", "$.limitPolicy.aggregateAccounting"),
         t("handshake", "#/$defs/ProtocolLimitsV3/properties (maxFramePayloadBytes, maxRequestPayloadBytesTotal, maxRequestFrames)", "#/$defs/TypeScriptProtocolLimitsV1/properties/maxFramePayloadBytes"),
         t("nativeMd", "§9.1 step 1 'Plan time (no spawn)' (line 2848)")],
        "scoped-pre-spawn-planner",
        "Before spawn the host plans the exact host-to-worker frame sequence and measures every frame as its deterministic-CBOR envelope payload; the 40-byte prefix is excluded from every limit (rust2 lengthScope 'payload bytes only' and aggregateAccounting). A planned frame over maxFramePayloadBytes (both majors; includes the one-frame SnapshotManifest, DependencySourceManifest and PreparedOutputManifest) or, for major 3, a request over maxRequestPayloadBytesTotal or maxRequestFrames refuses as native.provider-request-exceeds-wire-limit. Chunks are greedy: each chunk carries the maximum chunk bytes except the last; zero-length entries have no chunk. One maximal Cancel is reserved. maxRequestFrames is not reachable by inputs the other admissions accept (check computes the bound) but is still enforced.",
        "none (planning law; no member/type change)",
        "Owner limits make over-frame manifests (>~578k minimal dependency entries; 256 prepared rows with 1024x256 configurations) and over-total requests (8 GiB snapshot + 8 GiB dependency + 1 GiB prepared > 9 GiB) reachable; a host that cannot send them would otherwise misclassify reachable input as a protocol or host fault.",
        ["vectors:REQUEST-WIRE-ACCOUNTING", "request-accounting-law-matches-owner", "request-accounting-closed-form-matches-owner-encoder", "request-frames-bound-unreachable", "route-join"]),
    row("SUCC-PUBLIC-ROUTES", ["rust-semantic major 3", "typescript-semantic major 2"],
        [t("evidence", "#/x-opensip-public-route-registry/keys (three added keys)", "#/x-opensip-public-route-registry/keys/*/possibleOrigins (value admitted-plan-input added)"),
         t("publicDetailRegistry", "$.records (two added members)"),
         t("workflowCommon", "#/$defs/DomainDetailCode/enum (two added members)"),
         t("nativeModel", "PUBLIC_ROUTE_REMEDIES (two added remedies)"),
         t("nativeMd", "§10 route table row at line 3525 (request-precondition family extended)")],
        "scoped-public-route-successor",
        "public-route-successor.v1.json publishes three internal keys (domainDetail absent; class request-rejected; errorCode REQUEST.PRECONDITION_FAILED; exit 2 derived), two envelope-only DomainDetailCode members with remedies, owner selectors with function source digests and pre-spawn timing anchors, and route-table rows. check.py applies exactly these published rows in memory to the pinned owner model and derives termination, envelope errors and exit with public_termination_for, failure_envelope_errors and CLASS_TO_EXIT, validating against the real StepTermination and DomainDetail schemas.",
        "none (public failure vocabulary: +3 internal keys, +2 envelope detail members, +1 origin value)",
        "Review-02 RF-1: candidate-02 refusal details joined no closed public owner. The internal-key form follows the release-declaration route law; the two envelope members are needed because failure_envelope_errors requires a registered remedy and no existing remedy is a true next step.",
        ["route-join", "route-join-owner-family", "route-timing-anchored", "route-selectors-owner-source", "route-remedy-not-reused", "route-origin-closed"]),
    row("SUCC-DEPSRC-RECORDS", ["rust-semantic major 3"],
        [t("nativeMd", "§9.2 rows DependencySourceChunk (line 2877) and DependencySourceAccepted (line 2879)")],
        "field-level-publication",
        "Rust3DependencySourceChunkV3 and Rust3DependencySourceAcceptedV3 (alias of Native2DependencySourceSealV3) are private names; no wire tag or record name is added.",
        "none", "The frame rows gave members without types.", ["carrier-member-lists"]),
    row("SUCC-CANONICAL-PATH", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("rust2", R2 + "definitions.CanonicalPath.rule"),
         t("evidence", "#/$defs/CanonicalPath/pattern (supplementary; used by DependencySourceManifestV3 entries)"),
         t("identitySchemas3", "#/$defs/LogicalPath (declarative segment grammar)")],
        "normative-lexical-admission",
        "Rust3 path members (params.members and params.externMembers of CANONICAL-PATH-ADMISSION, computed from the carrier graph) admit by lexicalRules[canonical-path-segments]; TS2 project paths admit by lexicalRules[logical-path-segments]. Rules are structured data executed by the reference; their text is rendered from the structure. Newline is not forbidden by either owner. Patterns are supplementary and evaluated in the declared ECMA-262 u dialect; every reachable pattern site is published in patternSites and the lowering subset in loweringRequired.",
        "none",
        "The registered Native2 CanonicalPath pattern admits 'a\\n/../b', 'a\\n//b', 'x\\n/..', 'a\\n/.', 'a//b', 'a/', 'C:x'. Under ECMA-262 it also admits 'a/..\\n', 'a/.\\n', '..\\n' (Python re refuses them); canonical-path-segments admits those three too, so reference and dialect now agree. The Rust regex crate has no lookaround.",
        ["vectors:CANONICAL-PATH-ADMISSION", "vectors:TS2-LOGICAL-PATH-ADMISSION", "native2-canonical-path-pattern-weaker", "path-members-match-carrier-graph", "lexical-rule-text-rendered"]),
    row("SUCC-PATTERN-DIALECT", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("evidence", "every reachable `pattern` (JSON Schema 2020-12 ECMA-262 dialect)"), t("handshake", "every reachable `pattern`"),
         t("startup", "every reachable `pattern`"), t("occupancy", "every reachable `pattern`")],
        "executable-dialect-and-closed-lowering-list",
        "patternDialect is structured (engine ECMA-262 RegExp, flags u, evaluation, line terminators, dot/dollar/whitespace semantics, pinned reference engine). patternSites is the closed list of every pattern site reachable from the carriers (wire scalars, inline members and extern roots followed through $ref), with negation and construct inventory; loweringRequired is its closed subset needing hand lowering for the Rust regex crate. The reference checker evaluates every carrier and extern pattern through a finite ECMA translation that is differential-checked against the pinned engine.",
        "none",
        "Review-02 RF-3: the list was prose and scalar-only, and the checker evaluated patterns with Python re, which disagrees with ECMA-262 on a/..\\n, a/.\\n, ..\\n (and on \\r, U+2028, U+2029 for dot).",
        ["pattern-sites-closed", "pattern-lowering-closed", "pattern-dialect-structured", "ecma-differential", "ecma-review-probe-replayed", "ecma-newline-counterexamples"]),
    row("SUCC-PREPARED-V3", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.PreparedOutputManifestV2", R2 + "payloadSchemas.PreparedOutputChunkV2", R2 + "payloadSchemas.PreparedOutputSealV2",
           R2 + "payloadSchemas.PreparedOutputAcceptedV2", R2 + "definitions.PreparedOutputEntryV2", R2 + "definitions.PreparedOutputBlobV2",
           "$.commitments.preparedOutputBlob", "$.preparedOutputCustody.order", "$.preparedOutputCustody.manifestConstruction",
           "$.preparedOutputCustody.planCommitmentProof", "$.preparedOutputCustody.readAuthority", "$.requestProjection.preparedOutputs"),
         t("nativeModel", "prepared_output_set_admit (wrapped by the successor selector; function source sha256 in public-route-successor.v1.json)")],
        "superseded-value-members-kept",
        "Frame member names are unchanged. entries answer PreparedOutputSetV3.rows one-to-one (PREPARED-V3-ENTRY). maxPreparedOutputEntries = 256 is retained as the TOTAL entry bound (outputOrdinal 0..255); maxExpansionRows/maxGeneratedFileRows stay preparation-set limits. The prepared set admission successor selector, run when the owner outcome is admitted (before Plan construction), refuses more than 256 inert rows or blob bytes over maxPreparedOutputTotalBlobBytes as native.prepared-output-exceeds-wire-limit; an encoded manifest over the frame limit is refused by REQUEST-WIRE-ACCOUNTING. Read authority: generated-file rows mount read-only at .opensip/out/v1/<ownerKey>/<generated.logicalPath>; expansion and directive rows are looked up by site/owner (§3.6 PO-4).",
        "none (member lists unchanged; value domains substituted)",
        "The V2 payloads join rust-v1 rows that native-evidence §0 line 130 supersedes. The owner admits 257 inert rows and over-limit blob bytes (executed: owner-admits-over-limit-prepared-sets), so the refusal is a request precondition, not a host invariant.",
        ["prepared-v3-entries-from-set", "prepared-v3-generated-blob-equality", "prepared-v3-set-identity-join", "prepared-v3-v2-planrow-refused", "vectors:PREPARED-V3-WIRE-LIMIT", "owner-admits-over-limit-prepared-sets", "limit-literals", "route-join"]),
    row("SUCC-TRANSITION-PRECEDENCE", ["rust-semantic major 3"],
        [t("rust2", "$.orderingAndStateMachine.transitionAstV2.rules", "$.orderingAndStateMachine.eventRecord", "$.preparedOutputCustody.order"),
         t("p3", "$.rules[P3-25].guard", "$.initialState", "$.stateUpdates")],
        "precedence-and-guard-successor",
        "p3-guard-successor.v1.json (generated from TRANSITIONS.rust-semantic): P3 plus guard P3-25 outputSeen=false, outputSeen reset at Analyze and set by FactBatch/CoverageV3; framePrecheck and T016/T020 payload guards retained as pre-match admission; host never sends Cancel in START.",
        "none", "native-evidence §0 line 118 supersedes only phaseValues and P3 claims to state existing behaviour exactly, so rust2 T019's guard is retained law the P3 transcription dropped (equivalence: Coverage always sets outputSeen). START is host-controlled.",
        ["p3-unavailable-after-output-faults", "p3-unavailable-before-output-admits", "p3-cancel-in-start-no-row", "p3-overlay-differential", "ts2-order-unchanged", "vectors:P3-OVERLAY", "p3-guard-successor-file"]),
    row("SUCC-COMMIT-MAP", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("nativeMd", "§0 line 126 and line 129 ('recipes and domains unchanged'); §9.7 Coverage frames commitments")],
        "field-to-domain-map-stated",
        "COMMITMENT_MAP rows are the exact field-to-domain map for both languages, with value classes derived from owner recipe text.", "none",
        "Field texts named no domain for wrapper/terminal coverage commitments (TS2-G12, R3-G12).",
        ["commit-map-complete", "commit-map-value-classes-match-owner", "commit-ts2-fact-batch-matches-wire-model", "commit-empty-stream", "vectors:COMMIT-MAP"]),
    row("SUCC-ECHO-ENUMERATION", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("startup", "#/x-opensip-startup-law/identityMembers")],
        "enumeration-completed",
        "Transitive echoes also carry snapshot2/plan2 text: SnapshotFileChunk.snapshotId (both), AnchorRefV1 source-span snapshotId (both), PreparedOutputChunk/Seal.planId, and the snapshotId inside the rust2 SubjectV2.subjectId preimage.",
        "none", "Each is an exact echo of an enumerated member (R3-G16).", ["echo-rules-present"]),
    row("SUCC-RUST3-FAULT-CANCEL", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.ProviderFaultV2", R2 + "payloadSchemas.CancelV2", R2 + "payloadSchemas.CancelledV2")],
        "types-and-observation-semantics-stated",
        "Cancel/Cancelled per RUST3-CANCEL-TYPES (Cancelled.observedPhase = host send phase). ProviderFault per RUST3-PROVIDER-FAULT: worker-observed phase and null-or-echo triple, admitted against the host possible-phase set since the last admitted worker frame; the worker reads Hello before writing any frame. A refused ProviderFault payload turns P3-28 provider-fault into FAULT with the identical owner D9 outcome (operational-failed 4 PROVIDER.PROTOCOL_VIOLATION, no facts, no Coverage, no Run).",
        "none", "Members had no types (R3-G14). A host-receipt phase is unsatisfiable when OpenUniverse, SnapshotManifest or Analyze is in flight (reviewer traces through protocol3_run).",
        ["rust3-cancel-types", "rust3-phase-vocabulary", "vectors:RUST3-PROVIDER-FAULT", "p3-race-traces-admitted-by-owner-table", "provider-fault-refusal-same-d9"]),
    row("SUCC-RUST3-OBSERVED", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.BudgetExhaustedV2 (observed)")],
        "value-stated", "observed = limit + 1, as TS2 BudgetExhaustedV1 states and rust2 deterministicBudget checked increments imply.",
        "none", "R3-G14 residue.", ["rust3-observed-limit-plus-one", "vectors:RUST3-BUDGET-EXHAUSTED"]),
    row("SUCC-RUST3-SNAPSHOT-ENTRY", ["rust-semantic major 3"],
        [t("rust2", R2 + "definitions.SnapshotEntryV2.variants")],
        "types-stated", "contentSha256 DigestHex, executable bool, targetBytes non-empty byte string.",
        "none", "rust2 subjectsAlgorithm consumes contentSha256 as the manifest digest; requestProjection keeps symlink target BYTES in the manifest; schemaLanguage.bytes is the only byte type (R3-G15).",
        ["carrier-member-lists"]),
]

FALSE_GAPS = [
    {"gap": "R3-G13 StageResultV2 has no successor", "refutation": "native-evidence.md §9.7 names StageResultV2.coverageCommitment among recipes unchanged over CoverageResultV3 values; the §0 line 129 row supersedes its value domain, not its members."},
    {"gap": "R3-G15 chunk/seal integer types only derivable", "refutation": "rust2 schemaLanguage.integer plus canonicalCbor.closedDataModel make every integer member uint64; limitPolicy.arithmetic states the checked uint64 law."},
    {"gap": "TS2-G3 stageId bound", "refutation": "dispatch-binding expectedStageId maxLength 255 is defined as StageRequestV1.stageId / StageRequestV2.planStage.stageId and §9.6 requires a dispatch binding for each requested stage."},
    {"gap": "TS2-G6 / R3-G6 payload selection without tag", "refutation": "Handshake law factBatch.negotiated and startup preAnalyzeUnavailable.phase select the payload from host state; the carrier input publishes the two selectors and adds no wire tag."},
    {"gap": "TS2-G9 wireSchemaCommitment for major 2", "refutation": "No TS2 Hello member carries a contract digest (handshake frameAndMajor); the historical commitment stays recomputable over unchanged bytes and is not a wire field."},
    {"gap": "R3-G18 common-control owner", "refutation": "Closed by root: docs/implementation/m1/control-source-route.v1.json pins control-completion.schema.v3 through the reviewed freeze chain. Out of scope for provider carriers."},
    {"gap": "R3-G17(c) T016/T020/framePrecheck missing from P3", "refutation": "P3 ownedByProse assigns payload validation to prose/schemas; the retained rust2 guards are payload admission applied before matching, with the same FAULT outcome."},
    {"gap": "Envelope/DependencySourceChunk/Accepted names (R3-G3)", "refutation": "The wire carries no record names; private type names are implementation choices, not version changes."},
]

REVIEW_RESOLUTIONS = [
    {"id": "RF-1", "review": "review-02", "resolution": "Every new refusal is a route REFERENCE (params.route.routeKey) to public-route-successor.v1.json: three internal keys with domainDetail absent under the existing public-route law, errorCode REQUEST.PRECONDITION_FAILED, two envelope-only DomainDetailCode members with remedies, one new origin value, owner selectors (function source digests), timing anchors and route-table rows. check.py applies the published rows in memory to the pinned model and derives class, errorCode, exit, envelope detail and carrier with public_termination_for, failure_envelope_errors and CLASS_TO_EXIT; it validates against the real StepTermination and DomainDetail schemas (the registry file is now pinned); it requires the owner request-precondition family and executes the selectors wrapping dependency_source_set_admit and prepared_output_set_admit.",
     "checks": ["route-join", "route-join-owner-family", "route-timing-anchored", "route-selectors-owner-source", "route-remedy-not-reused", "route-origin-closed", "route-rule-references", "vectors:DEPSRC-WIRE-REPRESENTABILITY", "vectors:PREPARED-V3-WIRE-LIMIT"]},
    {"id": "RF-2", "review": "review-02", "resolution": "DEPSRC-SET-KEY-CONSTRAINTS and DEPSRC-WIRE-REPRESENTABILITY run in the dependency-source set admission successor (owner-admitted sets only): non-NFC name/version/sourceId/path, <= U+0020 in name/version, key > 4096, path > 4096 scalars or failing canonical-path-segments refuse; nothing normalized. REQUEST-WIRE-ACCOUNTING plans exact deterministic-CBOR envelope payload bytes (40-byte prefix excluded per rust2 framing/aggregateAccounting), refuses any planned frame over maxFramePayloadBytes and, for major 3, totals over maxRequestPayloadBytesTotal/maxRequestFrames; boundary vectors at exactly 67108864 frame bytes, 9663676416 request bytes and a frame-count limit, without materializing chunk bytes (ByteLen accounting validated against the owner encoder).",
     "checks": ["vectors:DEPSRC-WIRE-REPRESENTABILITY", "vectors:DEPSRC-SET-KEY-CONSTRAINTS", "vectors:REQUEST-WIRE-ACCOUNTING", "owner-admits-unrepresentable-dependency-inputs", "owner-admits-over-limit-prepared-sets", "request-accounting-law-matches-owner", "request-accounting-closed-form-matches-owner-encoder", "request-frames-bound-unreachable", "route-join"]},
    {"id": "RF-3", "review": "review-02", "resolution": "patternDialect is structured; patternSites (13 wire + 41 extern sites) and loweringRequired are closed lists with location, pattern, negation and constructs, asserted equal to the closure recomputed from the pinned schemas; carriers and extern JSON Schema validation evaluate patterns through the ECMA-262 translation, differential-checked against pinned Node 24.16.0 over every site and a line-terminator corpus, and the review-02 engine output is replayed.",
     "checks": ["pattern-sites-closed", "pattern-lowering-closed", "pattern-dialect-structured", "ecma-differential", "ecma-review-probe-replayed", "ecma-newline-counterexamples", "ecma-engine-pinned"]},
    {"id": "A-1", "review": "review-02", "resolution": "Exact snapshot pins retained (36 files: +public-detail-registry.v1.json); no clean-git claim.", "checks": ["architecture-pins-verified-before-import", "architecture-pins-unchanged-after-run"]},
    {"id": "A-2", "review": "review-02", "resolution": "tools/filelist.py is the static execution closure; selftest and isolation read it; subject-files.json is an output only. The open-audit closure is stated as covering open events only, not a general confinement proof.", "checks": ["closure-execution-inputs-listed", "isolation"]},
    {"id": "A-3", "review": "review-02", "resolution": "lexicalRules are structured and executed by wirecodec.lexical; their text is rendered and compared; CANONICAL-PATH-ADMISSION and TS2-LOGICAL-PATH-ADMISSION carry member lists recomputed from the carrier graph, and the extern hook applies externMembers from the rule.", "checks": ["lexical-rule-text-rendered", "path-members-match-carrier-graph", "wire-depsrc-manifest-native-pattern-bypass-refused"]},
    {"id": "A-4", "review": "review-02", "resolution": "DEL and C1 controls in name/version are stated as deliberately admitted in lexicalRules.package-key; vector admits DEL through the owner-admitted path.", "checks": ["vectors:DEPSRC-SET-KEY-CONSTRAINTS", "lexical-rule-text-rendered"]},
    {"id": "A-5", "review": "review-02", "resolution": "RUST3-PROVIDER-FAULT states the P3-28 to FAULT conversion; check executes stage_authority for both terminal kinds.", "checks": ["provider-fault-refusal-same-d9"]},
    {"id": "A-6", "review": "review-02", "resolution": "PREPARED-V3-WIRE-LIMIT is placed in a successor selector wrapping the owner prepared_output_set_admit (source digest pinned), timing anchored at nativeMd line 1855.", "checks": ["route-selectors-owner-source", "vectors:PREPARED-V3-WIRE-LIMIT"]},
    {"id": "A-7", "review": "review-02", "resolution": "Confirmed: R3-G19 is the proposal's checker citation defect, resolved by SUCC-TS2-MANIFEST-DIGEST's citation correction; R3-G18 (common-control owner) stays falseGaps[R3-G18] via the pinned control-source route.", "checks": ["gap-r3-g19-is-citation-defect", "gap-r3-g18-is-control-owner", "field-coverage-gaps-resolved"]},
]
