from pathlib import Path
import json,hashlib,datetime,subprocess
root=Path.cwd();base=Path('/tmp/opensip-design-corrections');inp=base/'v18-checker-proposal.v1';out=base/'v18-checker-coauthor.v1';out.mkdir(exist_ok=False);sid='4b48ccdd-92fb-4f92-9db2-ac8942f796d6';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert json.loads((inp/'exception-handler-results.json').read_text())['mismatches']['proposal']==[]
prompt=f'''Resume as the actual Claude SOURCE COAUTHOR for a bounded reference-checker correction. Your prior final17sourceassent remains historical. Root discovered a real reference-harness false-pass AFTER original independent17ACCEPT. The independent reviewer is separately correcting its report and assessing this on unchanged frozen17; do not read its private reasoning or interfere. Root has not assented to17 and treats this checker weakness as required before promotion. No original source/review bytes may be edited.

Read {inp/'proposal.json'}, checker.diff, checker.before.py, probe-exception-handlers.py and exception-handler-results.json. The actual frozen base is {base/'candidate-subject.v17'}, manifest in repo reviews/candidate-subject.v17.json SHA8cfe6d20a7d49b819f7c2eb2578afcaa5037048ed290ff1867fdcd6789cf3a9c. Root proposal ONLY changes ten exception-handler comparisons in docs/coop/design-corrections/workflows/check_workflows.v1.py; every .get(refusal/recoverRefusal)==detail needs explicit key membership so unexpecteddetailNone cannot falsely match absentexpectation. Preserves explicitnull, namedrefusal, errorcode/remedychecks. Root actual100handler-bodyexecutions reproduce10oldfalsepasses, 0proposal mismatches; those are syntheticexceptionhandler tests, NOT full model/Run/host admission. Existing independent reviewer direct37repair_previewcalls found all25expected-success previews complete; no actual current silentlymaskedpositive at preview. Some negative cases expect refusal later in apply/verify and properly completepreview. Existing canonical1787PASS is not therefore shown false.

Substantively inspect alltenhandlercontexts and whether the proposed guard correctly fixes the issue without disallowing deliberate null-detail expectations. Verify exact sourcehash and AST delta. Independently reproduce discriminating handler controls or choose a better bounded failure injection; use normative and actual checker meaning, not root expectedoutput blindly. Inspect for missed equivalent cases within THIS checker. You may reject or propose precise additional changes if the ten-line fix is inadequate; do not expand into unrelated broadrewrite. Make an isolated complete workingcopy of frozen17 inside {out} if needed to run the canonical workflow checker with the proposed file. Refresh ONLY necessary local sourcepins for your disposablecopy; don't claim changed pins/new reports are source identical. No requirement to rerun sixunits here: root will run canonical six after final record and pin updates. Preserve allfailedattempts/probeoutputs and exactly distinguish current positive control execution from synthetic exceptions.

Read-only inputs: all live/frozen/earlierproposal/review/history. Write ONLY {out}; no product implementation/commits/push/publication/agents. Can copy and correct proposal further in your output if a required flaw exists, with exactbeforeafterdiffs. FinalhandoffJSON/MD MUST be substantive and concise (about1200words plusstructuredhashes), including technicalAssent.value, changesRequired, suggestedSeverity, exact finalchecker path/hash vsfrozen17, individuallyassessedtenhandlers, executableevidence withlimits, and any actualsourcecorrectionyoumade. Clarify reference-checker assurance vs product contract: no product semantic/schema/model change proposed. Two earlierindependentnonblockingadvisories concerning importedperKindApplicability.rule metadata and historicalsourcepointer are separatelyaccounted in application; don't silently edit those acceptedcontractbytes here. Coauthorassent is NOT independentacceptance. Newfrozen18freshindependentreview, NEWblindconsumer andfullapplicationremainrequired. Please complete this bounded source review now.'''
(out/'prompt.txt').write_text(prompt);args=['/Users/sb/.local/bin/claude','-p','--resume',sid,'--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json'];p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=root,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(out/'process.json').write_text(json.dumps({'pid':p.pid,'sessionId':sid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'proposalSha256':sha(inp/'proposal.json'),'sourceParentManifestSha256':'8cfe6d20a7d49b819f7c2eb2578afcaa5037048ed290ff1867fdcd6789cf3a9c'},indent=2)+'\n');print(json.dumps({'pid':p.pid,'out':str(out),'sessionId':sid}))
