"""Launch a fresh actual independent Claude review only after final18is frozen."""
from pathlib import Path
import datetime,hashlib,json,subprocess
root=Path.cwd();dc=root/'docs/coop/design-corrections';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text());mp=dc/'reviews/candidate-subject.v18.json';m=load(mp);digest=sha(mp);a=load(dc/'reviews/codex-post-reset.v1/successor-source-assessment.v18.json');assert a['finalSourceAssent'] and a['independentAcceptance'] is False
co=root/a['actualCoauthorHandoff']['path'];assert sha(co)==a['actualCoauthorHandoff']['sha256'] and load(co.with_name('response.json'))['is_error'] is False
for row in m['files']:
 p=Path(m['snapshotRoot'])/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes']
assert (dc/'reviews/codex-post-reset.v1/technical-review.v18.md').is_file();out=Path('/tmp/opensip-design-corrections/post-reset-review.v18');out.mkdir(exist_ok=False)
prompt=f'''You are ACTUAL CLAUDE in a completely FRESH INDEPENDENT OpenSIP architecture/design/reference review. User requires substantive actual Claude + Codex alignment before implementation. You authored none of the source, and are not coauthor4b48ccdd-92fb-4f92-9db2-ac8942f796d6, original17independent e1b616a9-1419-46ed-8bfa-d768246973fc, or blind15922f81-214f-4262-9201-227218b75e99. No agents. Read-only source/reviews/history; no fixes/productimplementation/commits/pushes/publication. Write your probes/reports/disposablecopies ONLY {out}. Interpreter /tmp/opensip-architecture-review-env/bin/python -I -B. Never execute report-writing tools in live repo or frozen snapshot.

Exact frozen18manifest {mp} SHA256 {digest}; snapshot {m['snapshotRoot']}. Verify ALLdeclaredhashes/lengths and actualinventory before/after, including actual1308transitivepins. Reproduce ALLsix canonical commands from reviews/codex-post-reset.v1/final-reference.v18/reference-checks.json in a DISPOSABLE FULL exact copy, no repinning to manufacture success. Capture commands/exits/stdout/stderr and compare generatedreports to frozenbytes. Preserve every failedattempt and record copy inventory/deltas. Referencecounts arecalls/cases, not productqualification.

Read the five complete product contracts/index and governing schema/registry/reference joins. Read exact sourceDelta and root/coauthor assessments in successor-source-assessment.v18.json, technical-review.v18.md, post-reset-dispositions.v18.proposed.json, advisory-application-account.v18.proposed.json, actualcoauthorhandoff at {co.relative_to(root)} and its actualprobes/results/custody. Read corrected17reviewJSON/MD at reviews/post-reset-review.v17-clarification.v1, clarificationJSON/MD, and root review-assessment.v17.json (original17reports remain historical). The17review accepted source with3advisories; root explicitly withheldpromotion for the checkerfalsepass and actualsourcecoauthor independently agreed a SHOULDcorrection. Keep that disagreement in the record, never pretend independent17regraded itsadvisory. The prior16ACCEPT did notsurvive blind6; allblind6andearliercorrections remaininview with root blind-assessment.v6.json and the actual17corrected dispositions. No newblindhasaccepted17or18yet.

The proposed18executable delta is ONLY ten membership guards in workflows/check_workflows.v1.py. Models, schemas, contracts and caseexpectations are unchanged from17. A defaulting expected-refusal .get could equal actualnull and pass an unexpectedexception. Guard each key before comparing; deliberately expectednull remainslegal. Independently inspect ALLtencontexts including importoptionalerrorCode, reversedsource-mappingcomparison, recoverRefusal, repairpreview/apply/verify, invocation/test/render/review. Verify no equivalentmissed withinchecker. Author your own discriminating controls: actual falsepass through oldchecker and failure through newchecker, plus unchangedcorpus pass and explicitnull/namednegativepreservation. Root100syntheticactualhandler-bodycontrols and coauthorONEcorpusinjection are supporting evidence, not your oracle. Scopeenforcementclaims correctly: sourcepinwrappernotrunbycoauthor's directchecker; its1219-filepartialcopiesintentionallyomit6452reviewfiles;46handlerlinehits showreachabilitynotallnulledgecases. FirstcoauthorASTheuristiccontainsan alwaysTrue term and latercompareinventoryisnotfullASTproof; root exact wholeASTrollback/equality separatelyproves onlytennewguards. Independentlyverifydelta ratherthan trustingthoseclaims. Coauthorreport's universal eachhandlerhasposttrymissingrefusalguard isoverbroad; useactualcontexts. V18-OBS-1 nullfailurediagnostic nonblocking and accounted asoptionalreferenceconvenience, no publiccontractchange.

Review the complete current design for any new or preserved gap, not only this fix. The unchanged17corrections cover zero-config discovery and installedcapabilityavailability, typedconfig/TSlogicalnodekinds, language-specific nativeevidence and provider/body/dialect ownership, cloneprogression/confidence, import/runtime/history/testevidence authority, per-requirementnative9/imported7causes with loselessproducer/consumer vocabulary, coveragepartitionwithinfullowningtuple and conditionalfiletotality, stableidentity/typedcanonicalclosure, baselinechanged-codeaudit, command/operation/genericvsrepair replay, immutableRunandcurrentavailability, publicfailurecomposition, authorization and outputfailureaftercommittedRun. Verify preserve those laws on18, with exactsource/authority/evidencelimits, and inspect any concerning joins independently. Do not infer preservation solely from an ACCEPT headline or counts. For any new requiredgap, provide concretecounterexample and owningselector; don't manufacture producthostmeasurements before implementation.

Review every18disposition and all3new17advisories individually. V17ADV1: consumers enumerate registeredimportedrelations thenlookup perKindApplicability by validatedkey; embedded rule is metadata; optionalrelocationnot silentlydone. V17ADV2: new18prospectiveaccount labels V14ADV2.sourceCorrection as historicalasof16 andbindscurrent53380...; frozen17originaluntouched. V17ADV3: originaladvisoryseveritypreserved, rootCX-V17-REFUSAL-EXPECTATION requiredcorrection isnowimplemented. 58carriedindividualadvisories nohistoryloss. Inspect referencepin/pathrouting, exactprecedence and current-source bindings; distinguishreviewfiledigestfrom subjectmanifestdigest and historicalasofrefs. Earlier17CL3 mixeddenominators:177of240relation/causecrossproductcontrols+14presence/carryability=191; fullwould254withtheextra14. Partialhelper inputs are not admittednative/fullRuns; 7p06controlsactuallyfullclosure, otherauthorization/config/keyclaimsstatic/helperasqualified. No need to repeat17fullprobe suite absent a new concern; assess exactunchangedsource plus honestretainedpriorproof and your targetedverification. Don't repeat the previous reportingoverstatements.

Governance scope remains one complete intended product implementedinstages, 16AR15FW27inheritedresiduals30evaluation5scopedowners32UNPERFORMEDqualificationgates. FourselectedmacOS/LinuxmachineIDs andTS/JS/Rust/boundedgrammarpaths retained. Individually assess these groups on exactscope; carriedor routing-only isnotnewgrade. FiveDR201..205ownerrows must literallyset appliedByThisReview=false and finalApplicationOutcomeGranted=false whenonlyroutingassessed. All32demonstrated/qualified/implementationHarnessAuthored flagsfalse. D372unapplied,condition5NOTMET,noimplementation/readiness/productqualification. Freshblind andfullindependentapplicationstillrequiredafter yoursourceACCEPT.

Deliver substantive review.json AND review.md, bound top-levelsubjectManifestSha256='{digest}', verdict ACCEPT/CHANGES_REQUIRED/actualBLOCKED. newMustIssues andnewShouldIssues arrays emptyONLYifnoneunresolved; anyrequiredfindingmeans CHANGES_REQUIREDregardlessheadline; separate newAdvisories. priorFindingDispositions mustincludeCX-V17-REFUSAL-EXPECTATION, V17ADV1/2/3andV18OBS1plusmeaningfulpreservationof26resolved17findings viaexactpriorreference. ID-keyed arDispositions, fwDispositions, inheritedResidualDispositions, scopedReviewOwnerDispositions mustgiveeachidactualbasis/scope/authority; no checklist-gradeinflation. Keep review.md roughly3000words andJSONconciseper-rowbasis with sharedexactreferences; avoidrepeatingwholepriorreports or dumpingrawresultsintoreview. Retainfullprobes/rawoutputsseparately with exactcustody. Distinguishmeasuredschema/helper/fullclosure/caseinjection/sourceinspection/hostqualificationandfirstactualrefusalboundary. Finishsubstantiveindependentverdictnow, neverclaimblind/application/readinessagreement.'''
(out/'prompt.txt').write_text(prompt);args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Bash','Write','--strict-mcp-config','--output-format','json'];p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=root,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(out/'process.json').write_text(json.dumps({'pid':p.pid,'manifestSha256':digest,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(json.dumps({'pid':p.pid,'manifestSha256':digest}))
