from pathlib import Path
import json,hashlib,datetime
root=Path.cwd();ev=root/'docs/coop/design-corrections/reviews/codex-post-reset.v1';author=ev.parent/'bv4-corrections-author.v4';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());h=read(author/'handoff.json');f=read(author/'root-review-3.json');r=read(author/'review-ready-3.json');response=read(author/'response.json')
assert sha(author/'handoff.json')=='5785dc694e72e783aa299b419f6c49e32276011e0087fc68ff69ad0fcf7af8cf' and sha(author/'handoff.md')=='c56c8aeea45d541c27f61e05a0be78cb0e79f5b547eb855a2e720c7f1bab3306'
assert f['technicalAssent'] is True and not f['requiredFollowup'] and f['checkpointSha256']==sha(author/'review-ready-3.json')=='73dc744b57ba1945a4bdde6eb894528a345088a5c93911626d32e4df9b19514c'
assert response['is_error'] is False and response['session_id']=='77758b10-d7ba-4868-9d42-ae0b13e84cb6' and not response['permission_denials']
assert h['delta']['againstFrozenV14']['changedFiles']==r['delta']['againstFrozenV14']['changedFiles']
for row in h['delta']['againstFrozenV14']['changedFiles']:assert sha(author/'work'/row['path'])==row['afterSha256'] and sha(author/'before-images'/row['path'])==row['beforeSha256']
scans=read(author/'source-copy-accounts.json');assert len(scans)==8
released={x['path']:x['sha256'] for x in scans['work']['changedFiles']};suite=scans['disposable/suite-final-v4d/work'];extra={x['path']:x['sha256'] for x in suite['changedFiles']};diff=sorted(k for k in released.keys()|extra.keys() if released.get(k)!=extra.get(k));assert diff==sorted('docs/coop/design-corrections/'+x for x in ['foundation/source-pins.v1.json','native/source-pins.v2.json','workflows/source-pins.v1.json'])
def ref(p):return {'path':str(p.relative_to(root)),'sha256':sha(p)}
probe=ev/'bv4-v4-checkpoint3/preflight/report.json';pr=read(probe);assert pr['allHold'] and len(pr['cases'])==17 and pr['checkpointSha256']==f['checkpointSha256']
account={'standing':'Root full final handoff/source read and measured evidence reconciliation. Source assent only; actual independent review, NEW blind and full application remain required.','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'handoffSha256':sha(author/'handoff.json'),'handoffMdSha256':sha(author/'handoff.md'),'handoffJsonBytes':(author/'handoff.json').stat().st_size,'handoffMdBytes':(author/'handoff.md').stat().st_size,'readBothInFull':True,'allRequiredResolved':True,'latestCheckpointFile':'review-ready-3.json','latestFeedbackFile':'root-review-3.json','latestCheckpointSha256':f['checkpointSha256'],'sourceFiles':5,'beforeImagesVerified':5,'substantiveAssessment':f['substantiveAssessment'],'finalSourceProbes':[ref(probe),ref(ev/'bv4-v4-checkpoint3/preflight/probe.py')],'actualCoauthor':{'sessionId':response['session_id'],'model':'claude-opus-5','turns':response['num_turns'],'publicToolBlocks':read(author/'custody.json')['toolBlocks']['count'],'fullSourceCopyAccounts':8,'retainedFiles':len(read(author/'custody.json')['files'])},'additiveEvidenceClarifications':[
{'claim':'finalChecksOnFinalBytes.releasedVsSuiteDifferences lists regenerated native report as a fourth difference','measured':'There are THREE byte differences, exactly the temporary pin manifests. The native report was regenerated but is byte-identical a8b510f88fa08a25a92b6f0616a42adfa5c62a6c0aa5b0c69cee34478a16dcf7 in released/frozen/final-suite copies. Generation is not a byte difference.','actualDifferences':diff},
{'claim':'Handoff says no Run was closed/no full Run executed','scopeClarification':'This applies to the narrow new pre-Plan and mirror probes. The development checker suite executes inherited synthetic complete Run admission/closure controls. No real host/compiler/product execution is claimed. Do not erase inherited executed reference evidence by applying the probe limitation to the entire suite.'},
{'claim':'No previously admitted input is now refused','scopeClarification':'Measured valid default/explicit controls stay admitted. Vocabulary is now checked at complete pre-Plan admission, so a schema-shaped but semantically invalid capability spec may refuse earlier than raw schema validation, as the handoff itself acknowledges. Retained Run capability admission was already present. No blanket equivalence of raw schema validation and semantic admission is inferred.'},
{'claim':'Checkpoint3 metadata and p4 comment history','scopeClarification':'All three exact checkpoint3 revisions/replays recovered and SHA-verified; pre-amendment p4 SHA matches checkpoint2. Exact recovered evidence, public operations and initial stale-hash feedback refusal are retained under bv4-v4-checkpoint3. This is an additive reconciliation, not rewritten historical source.'}
], 'limits':['Root17case probe uses synthetic complete request specs and schema-admitted failure envelopes, not a host, CLI, renderer or actual invocation execution.','Raw retained-schema control and source ordering demonstrate the retained admission distinction; these new probes do not claim a new full-Run overflow test. Inherited full-Run reference suite controls keep their actual scope.','Temporary development pins and passing-call counts are not independent acceptance, real platform qualification or the final repository seal.','The final independent v14 review is still running and no result or agreement is assumed. No product implementation, commit, push or readiness change.']}
p=ev/'bv4-v4-final-handoff-read.json';assert not p.exists();p.write_text(json.dumps(account,indent=2)+'\n');print(json.dumps({'handoffRead':True,'actualSourceDifferences':diff,'allRequiredResolved':True},indent=2))
