from pathlib import Path
import json,hashlib
root=Path.cwd();out=Path('/tmp/opensip-design-corrections/application-draft.v3');files=out/'files';proposal=json.loads((out/'documentation-proposal.json').read_text());edits={r['path']:r for r in proposal['edits']}
def get(rel):
 p=files/rel;return p.read_text() if p.exists() else (root/rel).read_text()
def put(rel,s):
 p=files/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s);edits[rel]={'path':rel,'beforeSha256':hashlib.sha256((root/rel).read_bytes()).hexdigest(),'proposedSha256':hashlib.sha256(p.read_bytes()).hexdigest()}
rel='docs/START-HERE.md';s=get(rel);needle='The result is the architecture in ordinary prose.';s=s.replace(needle,'For the topic walkthrough, read [host authority](v2/architecture/01-semantic-model-and-host-authority.md), [components](v2/architecture/02-distribution-and-components.md), [security](v2/architecture/03-configuration-and-security.md), [operations](v2/architecture/04-lifecycle-delivery-and-operations.md), and [evidence workflows](v2/architecture/13-evidence-workflows-and-product-contracts.md), using each chapter’s current-applicability note.\n\n'+needle);put(rel,s)
rel='docs/v2/architecture/08-decision-and-readiness-register.md';s=get(rel);s=s.replace('02-distribution-and-components.md#product-boundary','02-distribution-and-components.md#current-v1-product-boundary-and-required-successors')
s=s.replace('MET at design level: all32 DR-G01–32 mappings','MET at design level through the [applied gate map](../../coop/design-corrections/qualification-gates.applied.v1.json): all32 DR-G01–32 mappings')
s=s.replace('MET by reviewed prospective dispositions for all DR-001–011, all sixteen DR-011 residuals and all thirty evaluation subresiduals.','MET by the [applied inherited dispositions](../../coop/design-corrections/inherited-residuals.applied.v1.json) for all DR-001–011 and all sixteen DR-011 residuals, plus [thirty applied evaluation dispositions](../../coop/design-corrections/evaluation-residual-dispositions.applied.v1.json).')
s=s.replace('under DR-201–205. Authors do not independently accept their own bytes.','under the [new scoped DR-201–205 review records](../../coop/design-corrections/review-owner-dispositions.v1.json). Exact review hashes and subject bindings are in those records and the application record; the [D-372 activation](../../coop/design-corrections/application-activation.v1.json) binds the independent final application verdict. Authors do not independently accept their own bytes.')
lines=s.splitlines()
for i,line in enumerate(lines):
 for n in range(201,206):
  if line.startswith('| DR-'+str(n)+' |'):
   c=line.split('|');c[6]=' **Current intended product — ACCEPTED under D-372**, by the exact [scoped review-owner record](../../coop/design-corrections/review-owner-dispositions.v1.json) for DR-'+str(n)+'. This is a new subject-specific design review. **Historical scope and evidence follow:** '+c[6].strip()+' ';lines[i]='|'.join(c)
s='\n'.join(lines)+'\n'
needle='| Gate ID | Claim | Platform matrix / harness |'
pos=s.index(needle);s=s[:pos]+'''**Current full-product gate application — D-372:** The [applied32-gate map](../../coop/design-corrections/qualification-gates.applied.v1.json) supplies current contracts, named owners, harness populations and mandatory acceptance requirements for these same IDs. The detailed rows below preserve historical claims/harness names; their preview scopes and prior blocking causes are historical, not the current full-product gate account. G06/G11’s inherited design blockers have accepted prospective dispositions; G10 uses TS protocol major2/Rust major3; G17 is explicitly reactivated for the four advertised SARIF commands. Every selected product gate remains unqualified and requires its actual implementation/release evidence. No old measurement is extended to new cells.

''' + s[pos:]
s=s.replace('| Gate ID | Claim | Platform matrix / harness | Required retained evidence | Owner | Assurance stage now | Threshold / waiver | Status |','| Gate ID | Historical claim | Historical platform matrix / harness | Required retained evidence | Owner | Historical assurance stage | Threshold / waiver | Historical status |')
needle='### Historical preview position — measured snapshot, 2026-09-05\n';s=s.replace(needle,needle+'\nFor current full-product readiness, use [Unified product design readiness](#unified-product-design-readiness) above. The dated counts below belong only to the preserved D-369 preview and are not recomputed as full-product grades.\n');put(rel,s)
rel='README.md';s=get(rel);needle='\n# opensip\n';assert needle in s;s=s.replace(needle,'''\n**Current complete product design — D-372:** Read the [product contracts](docs/v2/contracts/product-v1/README.md), [current readiness](docs/v2/architecture/08-decision-and-readiness-register.md#unified-product-design-readiness), and [exact application record](docs/coop/design-corrections/application.v1.json). Implementation is not authorized; supported-platform qualification remains required.\n\nThe preview handoff below is retained as D-369 history. It is not a competing current design or the current implementation handoff.\n\n# opensip\n''');put(rel,s)
rel='docs/v2/architecture/07-review-record.md';s=get(rel);pos=s.index('\n\n');s=s[:pos]+'''\n\n> **Current applicability — D-372:** The [new scoped DR-201–205 reviews](../../coop/design-corrections/review-owner-dispositions.v1.json) and [application record](../../coop/design-corrections/application.v1.json) supply the complete intended-product review account. The findings and scope below are historical; their old labels do not override [current readiness](08-decision-and-readiness-register.md#unified-product-design-readiness).''' + s[pos:];put(rel,s)
rel='docs/catalog/README.md';s=get(rel);s=s.replace('the [complete inventory](../operations/document-inventory.v1.json) for exact paths, hashes, and reference counts.','the [recorded inventory](../operations/document-inventory.v1.json) for scoped paths, hashes, and reference samples. Its declared cutoff excludes the later final application review and activation receipt, which are linked and hash-bound through [D-372’s application](../coop/design-corrections/application.v1.json). Inventories describe the current reading paths; they do not authenticate historical acceptance.');put(rel,s)
# The catalog itself will be generated from the corrected classification in the final package.
proposal['edits']=list(edits.values());(out/'documentation-proposal.json').write_text(json.dumps(proposal,indent=2)+'\n');print(len(edits),'future-effect draft documents; repository unchanged')
