[package]
name = "opensip-asset-assembly-consumer-trial"
version = "0.1.0"
edition = "2024"
publish = false
[workspace]
[dependencies]
opensip-report-asset-trial = { path = "../verifier" }
opensip-platform-asset-trial = { path = "../verifier/platform" }

[dev-dependencies]
opensip-identity = { path = "../verifier/identity" }
