from pathlib import Path
import json,hashlib
r=Path.cwd();dc=r/'docs/coop/design-corrections';rp=dc/'reviews/post-reset-review.v11/review.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
review=json.loads(rp.read_text());resp=json.loads(rp.with_name('response.json').read_text());assert resp['is_error'] is False
assert review.get('verdict',review.get('overallVerdict'))=='CHANGES_REQUIRED'
assert [x['id'] for x in review['newMustIssues']]==['v11-M1'] and [x['id'] for x in review['newShouldIssues']]==['v11-S1']
assert [x['id'] for x in review['newAdvisories']]==['v11-A1','v11-A2','v11-A3']
ref={'path':str(rp.relative_to(r)),'sha256':sha(rp),'sessionId':resp['session_id'],'verdict':'CHANGES_REQUIRED','newMustIds':['v11-M1'],'newShouldIds':['v11-S1']}
intent={'v11-M1':'Update the pinned crosswalk before refreshing source pins and executing all six commands. Both final recording scripts verify every pinned input before/after their writes; a final all-ledger check and both live/copy freezer checks refuse stale inputs. Preserve frozen-v11 reports as evidence of an earlier working state, with explicit root error account.','v11-S1':'Set the successor summary claudePriorReview to completed v11 and claudeFinalReview to PENDING-FROZEN-V12, with an explicit version consistency assertion before freeze. Preserve the old inaccurate frozen-v11 field as historical.'}
items=[]
for key in ['newMustIssues','newShouldIssues']:
 for i,f in enumerate(review[key]):items.append({'id':f['id'],'severity':f['severity'],'status':'ROOT-CORRECTION-PENDING-FINAL-VERIFICATION','owner':'Codex recording/integration','finding':f['title'],'reviewEvidence':dict(ref,selector='/'+key+'/'+str(i)),'intendedCorrection':intent[f['id']],'limitation':f.get('boundedScope',f.get('notClaimed'))})
adv={'v11-A1':'Corrected proactively at its actual ADVISORY severity by released actual-Claude coauthor v10: all annotation comparison stages use existing C.equal_typed through one helper. Root final 35-case five-location recheck must preserve positive controls and measure pre/post discrimination. No current-payload/Run attack or normative feature is claimed.','v11-A2':'Preserve historical duplicate IDs and literal results. Report passing calls separately from distinct IDs: v11 has673calls/663unique IDs, v10 has661/651, with the same10extra instances and agreeing outcomes. The v12 final report must measure its own call/unique counts; no passing count is claimed as exhaustive coverage and no original ID is silently renamed.','v11-A3':'Add one exact, mutually assessed sentence to the existing normative annotation paragraph: Local-reference traversal must terminate on cycles. This states the current chain-guard robustness requirement without adding an algorithm or changing an admission verdict. Actual Claude wording assessment and root before/after custody must be retained before final freeze.'}
a=json.loads((dc/'reviews/codex-post-reset.v1/advisory-application-account.v11.proposed.json').read_text());assert len(a['items'])==28
for i,x in enumerate(review['newAdvisories']):a['items'].append({'id':x['id'],'reviewEvidence':dict(ref,selector='/newAdvisories/'+str(i)),'disposition':adv[x['id']]})
a['standing']='31 carried actual v5-v11 advisories, with explicit v12 corrections and limits. No v12 independent acceptance or assent.';assert len(a['items'])==31
ap=dc/'reviews/codex-post-reset.v1/advisory-application-account.v12.proposed.json';assert not ap.exists();ap.write_text(json.dumps(a,indent=2)+'\n')
d={'standing':'PROPOSED v12 correction, pending final integration/rechecks and fresh independent review','predecessorManifestSha256':'a03b7fe987ee886101a6d5b85bf4b0760f59b06a5a9e9c5f627accb9a7263bdf','actualPredecessorReview':ref,'priorCorrections':{'path':'docs/coop/design-corrections/post-reset-dispositions.v11.proposed.json','sha256':sha(dc/'post-reset-dispositions.v11.proposed.json'),'standing':'v11 independently resolves v10-S1 and its three advisories; surrounding final-recording failures still require successor correction.'},'items':items,'advisoryCorrections':[{'id':x['id'],'status':'PROPOSED-PENDING-FINAL-VERIFICATION','intent':adv[x['id']]} for x in review['newAdvisories']],'advisoryAccount':{'path':str(ap.relative_to(dc)),'standing':'31 explicit carried advisories, preserving original severity.'},'actualCoauthorHandoff':{'path':'docs/coop/design-corrections/reviews/digest-corrections-author.v10/handoff.json','sha256':sha(dc/'reviews/digest-corrections-author.v10/handoff.json'),'sessionId':'5dec928a-6357-4726-9ea8-49a3079fb726','role':'Actual coauthor, not independent acceptance'},'implementationAuthorized':False,'readinessChanged':False,'productQualification':False,'remaining':['released two-file correction and mutually assessed cycle sentence applied with before-images','all pinned record edits before fixture/pins/sixcommands; final after-recording pin seal','fresh independent successor review at zero unresolved MUST/SHOULD','actual Codex assent and NEW fresh blind consumer','complete independently reviewed application/readiness reconciliation']}
p=dc/'post-reset-dispositions.v12.proposed.json';assert not p.exists();p.write_text(json.dumps(d,indent=2)+'\n')
print('Prepared actual v11-M1/S1 and31-advisory account; original severity preserved. No acceptance.')
