from pathlib import Path
import json,hashlib,shutil,difflib
B=Path('/tmp/opensip-design-corrections');L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews');A=B/'claude-attribution-capture-assessment.v1';S=B/'candidate-subject.v41';T=B/'source41-capture-successor.v1/source';O=Path(__file__).parent;H=lambda b:hashlib.sha256(b).hexdigest()
assert json.loads((A/'process-completion.json').read_bytes())['exitCode']==0
m=json.loads((A/'delta-manifest.json').read_bytes());assert H((A/'correction.patch').read_bytes())==m['patchSha256']=='92aa515f52b439792fb63930e4237a5ee5352d57f053213868c2a3be4ba9017e';assert len(m['changedFiles'])==4
for r in m['changedFiles']:
 old=(T/r['path']).read_bytes();new=(A/'work/patched-tree'/r['path']).read_bytes();assert old==(S/r['path']).read_bytes() and H(old)==r['baseSha256'];assert H(new)==r['afterSha256'] and len(new)==r['afterBytes'];q=O/'before'/r['path'];q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(old);(T/r['path']).write_bytes(new)
rel='docs/coop/design-corrections/foundation/evaluator_graph_fixture.v3.py';p=T/rel;old=p.read_bytes();phrase=b'            # Without the split these views bind to no cell outcome and the host capture drops\n            # them from selectedRefs, which is EVALUATION_VIEW_ROOTS rather than a real Run.\n';assert old.count(phrase)==1;new=old.replace(phrase,b'            # Other explicitly returned views remain captured but do not discharge these cells.\n');q=O/'before'/rel;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(old);p.write_bytes(new);(O/'fixture-comment.diff').write_text(''.join(difflib.unified_diff(old.decode().splitlines(True),new.decode().splitlines(True),fromfile=rel,tofile=rel)))
r={'standing':'Root substantive author-proposal assessment and exact isolated integration. No final source/consumer/application assent, implementation or readiness. Required reference checks and actual independent review pending.','sourceParentManifestSha256':'eb7a4c48d86c844914ffc0ef70743752655a411e453bbaa066cfaee572312236','authorReviewSha256':H((A/'review.json').read_bytes()),'authorPatchSha256':m['patchSha256'],'files':m['changedFiles'],'rootCommentCorrection':{'path':rel,'beforeSha256':H(old),'afterSha256':H(new),'scope':'Remove obsolete assertion that the builder drops unmatched views; no code behavior change.'},'assessment':'Agree builder capture must retain all explicitly declared returned views; stage-produced selection must equal complete receipt union. Shared-view attribution and relation-column membership preserve existing model semantics. Exact new checker controls distinguish old capture defects; no malicious-host omission detection or independent reconstruction claimed.','refsOnlyDecision':'Keep both documented explicit inputs: viewIds/viewId and evaluationInputRefs. A refs-only view now remains captured and an evidence record omitting it fails EVALUATION_VIEW_ROOTS. Silently dropping that declared input would be inconsistent with the published builder interface.','clarificationOfAuthorWording':'P1 versus P1y is one admitted and one refused encoding, not two Run-admissible encodings. Owner selects relation-column membership; no nondeterminism claim from different observations.','preservedLimits':'File-fixture symbol baseline defects uncorrected; multistage/multiproducer capture not independently exercised by the author. Full integrated checks cover remaining helper consumers, no product qualification.'};(O/'integration.json').write_text(json.dumps(r,indent=2)+'\n');shutil.copytree(O,L/O.name);print(json.dumps({'integratedAuthorFiles':4,'commentOnlyFiles':1,'integrationSha256':H((O/'integration.json').read_bytes())}))
