"""Recover exact overwritten metadata by inverse additive operations, validating every historical SHA."""
from pathlib import Path
import json,hashlib,copy
b=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v4');out=Path('/tmp/opensip-design-corrections/bv4-v4-checkpoint3-metadata-history.v1');out.mkdir(exist_ok=False);sha=lambda raw:hashlib.sha256(raw).hexdigest();encode=lambda d:(json.dumps(d,indent=2)+'\n').encode();current=json.loads((b/'review-ready-3.json').read_text());initial=copy.deepcopy(current);del initial['followupDispositions'][0]['rootProbeRunVerbatimOnTheseBytes'];raw=encode(initial);assert sha(raw)=='295b56d807d5b539432d461b7f4f62bc401440f3e7b2b871b4c8e543f1e2b13e';(out/'review-ready-3.initial.json').write_bytes(raw)
pr=json.loads(Path('/tmp/opensip-design-corrections/bv4-v4-checkpoint3-preflight.v1/report.json').read_text());assert pr['checkpointSha256']==sha(raw);prraw=encode(pr);(out/'root-preflight-replay.initial.json').write_bytes(prraw)
second=copy.deepcopy(current);row=second['followupDispositions'][0]['rootProbeRunVerbatimOnTheseBytes'];del row['reportHashNotRecordedHere'];replacement={}
for k,v in row.items():
 replacement[k]=v
 if k=='out':replacement['reportSha256']=sha(prraw)
second['followupDispositions'][0]['rootProbeRunVerbatimOnTheseBytes']=replacement;raw2=encode(second);assert sha(raw2)=='abf46e4ffd4666b1bd6d97161eb1222af661133f36924952009dc4079abf776c';(out/'review-ready-3.intermediate.json').write_bytes(raw2)
pr2=copy.deepcopy(pr);pr2['checkpointSha256']=sha(raw2);(out/'root-preflight-replay.intermediate.json').write_bytes(encode(pr2))
curraw=(b/'review-ready-3.json').read_bytes();assert sha(curraw)=='73dc744b57ba1945a4bdde6eb894528a345088a5c93911626d32e4df9b19514c';(out/'review-ready-3.final.json').write_bytes(curraw)
curpr=(b/'logs/root-preflight-replay-checkpoint3.v1/report.json').read_bytes();expected=copy.deepcopy(pr);expected['checkpointSha256']=sha(curraw);assert curpr==encode(expected);(out/'root-preflight-replay.final.json').write_bytes(curpr)
(out/'account.json').write_text(json.dumps({'standing':'Recovered exact historical checkpoint metadata and probe records after coauthor overwrote checkpoint3 twice and regenerated its local replay report. No source changed. Each prior checkpoint reconstruction matches its publicly logged SHA; initial replay bytes equal the independently retained root replay, and final replay agrees with the same deterministic report differing only in checkpointSha256. This is recovery from measured byte operations, not invented review agreement.','cause':'An added probe-report hash referenced a report that itself contained checkpointSha256; coauthor removed the circular binding. The first root assessment correctly refused a stale checkpoint hash.','files':[{'path':p.name,'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in sorted(out.glob('*.json'))],'noSourceChange':initial['delta']==second['delta']==current['delta'],'rootInitialAssentScript':'review-bv4-v4-checkpoint3.py stopped at its exact checkpoint SHA assertion; no feedback or assent delivered.'},indent=2)+'\n');print(json.dumps({'recovered':str(out),'sourceDeltaUnchanged':True},indent=2))
