import json
S='360c2758c0409ebc307966c7a385c385c2d7f580b4623dd760b7ba0e26bf18c1'
R='docs/coop/design-corrections'
def pf(v,b,scope): return {'verdict':v,'basis':b,'scope':scope}
prior={}
CPS='CLOSED-VERIFIED-ON-THESE-BYTES'
prior['CB-GAP-1']=pf(CPS,'At-most-one-per-registered-row is enforced at three places on these bytes. Two share one helper: foundation/identity-model.py:93 admit_parameter_selection, called by native_evidence_model.v2.py:4031 (pre-Plan admit_analysis_spec step 4) and identity-model.py:1679 (open_run_closure over the retained analysis-spec). The third is the independent workflows_model.v1.py verify_scope_parameter_binding. I called that real entrypoint: zero rows legal at the helper, one row verifies, two distinct rows over the registered ScopeDocumentV1 digest refuse CONFIG.INVALID. Distinct registered rows coexist (scope+import = 2). Whole-item duplicates refuse earlier on uniqueItems + canonical-set. Unregistered rows are left to PAYLOAD_PARAMETER_UNREGISTERED (identity-model.py:811) and two rows per digest to PAYLOAD_PARAMETER_AMBIGUOUS_ROW (:809). ImportSourceContext keeps its own guard inside the consuming derivation; stage parameters are a Plan subset.','Enforcement presence, control flow and real-entrypoint behaviour. Not product-host reachability.')
prior['CB-GAP-2']=pf(CPS,'x-opensip-uniqueness on #/$defs/analysis-spec/properties/requestedCapabilities carries ownershipTuple [capabilityId, languageMode, workspaceRoot] with requiredness stated as an attribute and no last-wins/merge. Internal key native.requested-capability-duplicate-ownership-tuple is present in native_evidence_model.v2.py and registered in native-evidence.schemas.v2.json x-opensip-public-route-registry, adding no DomainDetailCode member. Different mode/root/capability remain legal; explicit specs still meet uniqueItems first.','Schema annotation, key registration and route presence. Origin reachability of each route is not measured.')
prior['CB-GAP-3']=pf(CPS,'I independently counted the ladder authority: 13 relations, 17 registered (relation,rung) pairs, 5 resolved and 12 non-resolved - the exact partition the contract states. RC-6 is coded as an implication (native_evidence_model.v2.py: if entry["coverage"]=="complete" and rc.get("examinedExhaustive") is not True), leaving coverage=unknown unconstrained in both directions. It is decided in coverage_bijection, which admit_coverage_result_v3 calls at the producer boundary and which identity-model.py re-runs over the retained payload at Run closure. Controls sweep all 17 pairs fact-free, and separate named controls exercise the producer boundary and retained closure on the reproduced file@enumerated vector in both minting universes with the fault list asserted to be RC-6 alone. RC-0 still outranks it; RC-2/RC-3 positives preserved.','Enumeration completeness stays distinct from resolution completeness. The 17-pair sweep is helper-level by construction; sealed-Run coverage is the narrower named vectors, exactly as the controls label themselves.')
prior['CB-GAP-4']=pf(CPS,'Both outputDomains arrays $ref #/$defs/Domain, a flat 32-member enum equal to Ref.properties.domain and to the byDomain key set; agreement is enforced at closure by equal_typed -> STAGE_SPEC_OUTPUT_DOMAIN_JOIN (identity-model.py:1487), so equality is separate from membership. Empty is permitted and its description denies completeness/evidence/producer authority. stage-spec.operation stays a provider-interface token with no platform-wide enum, unlike the closed seven evaluator predicates. The stage-spec record commits planId, producerClosure, operation, parameters, outputDomains and outputSchemaDigest, so no uncommitted discriminator remains.','Schema and closure-join structure. No collision or RunId-stability claim is made or checked.')
prior['CB-GAP-5']=pf(CPS,'x-opensip-digest-domains.closureMembership publishes exactly 6 direct, 2 equalToDirect and 7 selectedThroughOtherInput members, matching the stated 6/2/7 shape. selectionLaw states direct members must be in plan.semanticClosures, other-input dependencies need not be flattened, extra admissible retained closures may be selected, and there is no exact-minimal-set constraint. Import producer/adapter are retained through plan.importIds; native tool/stdlib/LLVM/grammar closures through plan.nativeContextDigests.','Published membership over evaluated/selected inputs. Unreferenced CAS blobs remain non-inputs.')
prior['CX-V20-SCHEMA-REGISTRATION']=pf(CPS,'artifactClass registered-schema-document appears at both selectors: the annotation on view/properties/schemaDigests/items and the byDomain row for the schema proof-input-ref domain. registered_schema_documents() derives the closed set from x-opensip-payload-registry alone, with no second list, and SCHEMA_DOCUMENT_UNREGISTERED is raised from the model. The view set stays a declaration - neither a derived union nor admission authority - while each payload pins its own document.','Annotation and derivation presence. Retention-first ordering read in code, not measured against a hostile store.')
prior['CX-V20-STAGE-REF-COMPATIBILITY']=pf(CPS,'#/$defs/Domain is a flat enum rather than a deep root ref, so existing schema walkers resolve it; the Ref domain enum and byDomain agree with it exactly (32/32/32). The six canonical commands, including the array-order and identity walkers, execute clean over these bytes.','Structural compatibility plus executed checks. Not a proof about every third-party walker.')
prior['V20-ROOT-3']=pf(CPS,'public-detail-registry.v1.json records and common.schema.json #/$defs/DomainDetailCode both hold 289 members and are set-equal. Both BASELINE.SCOPE_NOT_A_SELECTED_PARAMETER and BASELINE.SCOPE_PARAMETER_DIGEST_MISMATCH are registered, and they are the only two BASELINE.SCOPE_* spellings - no third was minted. I ran adopt_baseline for real: both refusals propagate with class, code and detail intact and admit against the real StepTermination carrier and the failure envelope. Ambiguity keeps CONFIG.INVALID. Four ledgers exist, not five.','Registration, emission and carrier admission on these bytes. Semantic truth of English remedy text remains review evidence, not machine-checked.')
prior['V20-ROOT-4']=pf(CPS,'Default duplicate construction reports the registered internal key native.requested-capability-duplicate-ownership-tuple rather than a bespoke one, so public_termination_for can derive a route; the refusal still refuses and does not deduplicate. The explicit path still meets uniqueItems/canonical-set first, and the default path meets the guard first - the two paths are distinguished in the code and its comment.','Key routing and refusal behaviour. Host origin selection is not measured.')
prior['V20-ROOT-5']=pf('CLOSED-VERIFIED-WITH-STATED-LIMIT','Remedies stay keyed by public code and the route registry carries the maintenance constraint (remedyKeyingConstraint, asserted by a control). Table equality is machine-checked by the executed checks; the semantic truth of the English next-step text is not, and this review reports it as review judgement rather than measurement.','Advisory; the honest split between machine-checked equality and human-judged text is preserved.')
prior['CX-V20-SENTINEL-SUCCESS']=pf(CPS,'The positive uses a unique module-level sentinel object and an identity comparison (_NO_REFUSAL=object(); ... is _NO_REFUSAL), so ANY Refusal - including one carrying detail=None - is distinguished from a successful return. The detail=None case is real, not hypothetical: adopt_baseline raises Refusal("CONFIG.INVALID", None, "duplicate fingerprint in baseline entries"). I confirmed Refusal.termination() OMITS the optional domainDetail rather than emitting an explicit null, and that the resulting termination admits against the real StepTermination schema. The frozen identity report is 1596 passed / 0 failed.','Sentinel correctness and reachability of the detail=None branch, executed.')
prior['CX-V20-FINAL-FIXTURE']=pf(CPS,'The actual native-evidence.schemas.v2.json document digest f20b8353a7be50d7a0c24f413df74e35d23a4e9fc2a4ecc661235655c43c51be is present in native-cases.v2.json, and the native check executes clean over these exact bytes with its report regenerating byte-identically. The selected-baseline positive now fails on any refusal (see CX-V20-SENTINEL-SUCCESS).','Fixture/document agreement on these bytes and an executed drift check.')
prior['CX-V20-REVIEW-PRECISION']=pf(CPS,'The overclaims named are absent from these bytes and the surviving statements are ones I could falsify and did not. Where the corpus states a limit it states it as a limit: the selected-scalar NativeCause limitation, the anchor-identity non-promise, the docstring-scoped AST equivalence and the launcher budget are each published with their scope rather than asserted broadly.','Textual precision against the actual bytes; not a claim that every sentence was independently re-derived.')
prior['NEW-SHOULD-1']=pf('CLOSED-VERIFIED-BY-SINGLE-LAW-MUTATION','I moved exactly one law - the at-most-one ambiguity guard - below the payload-digest match in a disposable copy and re-called the REAL owning entrypoint. Of seven scenarios exactly ONE changed: two rows plus a NON-candidate document regressed from CONFIG.INVALID to BASELINE.SCOPE_PARAMETER_DIGEST_MISMATCH. Both candidate-holder scenarios were unchanged, which is the direct demonstration that the old controls could not hold the order. Running check-identity.py against the mutated tree gave exit 1 and 1594 passed / 2 failed, the two failures being precisely an-ambiguous-spec-refuses-as-ambiguous-even-for-a-document-that-is-neither-candidate and the-three-answers-for-one-non-candidate-document-stay-distinct-by-row-multiplicity. That independently reproduces the root-recorded 1594/2. The removed source-text-count control was a cross-file string tally establishing nothing semantic; its removal is correct and the behavioural carrier/registry controls are retained.','Mutation of the real admission, not a copied algorithm and not a manufactured error. Mutated bytes and diff retained.')
prior['ROOT-V20-REVIEW-SCOPE']=pf('SATISFIED-BY-THIS-REVIEW','All five complete product contracts and the index were read first, in bounded consecutive ranges with no skipped or truncated range - 7729 lines across six files, recorded with per-file path, hash, total lines and observed ranges in contract-read-coverage.json, whose hashes agree with the manifest. Admission was probed by calling the real owning entrypoint with admitted positive data before mutating one law; no membership logic was copied and no AdmissionError was manufactured. Structural and literal observations are labelled as such and are not presented as execution security, compiler enforcement or semantic replay.','This review claims no retroactive full-source-20 scope for any prior review.')
for i,(k,b) in enumerate([('CB-ADV-1','Declaration remains selected rather than derived, and the registration law is now enforced at both the view declaration and the schema Ref. The superseded root assumption that view.schemaDigests checked registration is recorded as superseded, not silently dropped.'),
 ('CB-ADV-2','Exact equality is code, not prose: identity-model.py raises IMPORT_JOIN on any difference in either direction between evidence["importIds"] and plan["importIds"]. The evaluated subset stays separate (UNSELECTED_EVALUATION_IMPORT) and citability stays restricted (HIDDEN_FINDING_EVIDENCE), so a selected but unevaluated import is retained and admitted yet cites nothing.'),
 ('CB-ADV-3','Carried. One raw-SHA content store and first-refusal semantics are preserved; the corpus states that one shared lost blob may mask a second join and that finite tests do not establish a single dependency. I did not attempt to establish otherwise.'),
 ('CB-ADV-4','Carried as a live cross-unit obligation. The selected composition adds faultCause host-invariant under the existing SYSTEM.OUTCOME.ILLEGAL_STATE while d9-exit-contract.v1.14.json keeps its bytes, so a checker reading the inherited artifact alone would refuse a lawful termination. The corpus publishes this as an owed successor artifact rather than repinning history; application must reconcile it.')]):
    prior[k]=pf('CARRIED-VERIFIED' if k!='CB-ADV-4' else 'CARRIED-OPEN-OBLIGATION',b,'Advisory standing preserved at original severity; no new grade.')
for k,b in [('V20-ADV-1','Addressed: the launcher now catches TimeoutExpired, writes an explicit FAILED report, declines attribution for the timed-out child (exitCode null, reportSha256 null) and sets passed false. I executed the full six commands; none timed out.'),
 ('V20-ADV-2','Addressed and verified: all 31 protected historical files are in the frozen subject, 10 flagged presentInPredecessor and 21 newly included, every one hash-equal to both the snapshot and live source with zero drift.'),
 ('V20-ADV-3','Addressed and verified: the redundant source-text-count control is removed as a contiguous deletion and the five new ordering controls are present and effective under mutation.'),
 ('V21-FINAL-PEER-ADVISORY-NEW-1','Accounted. The gap is a launcher environment field, not unpublished semantics; the peer measured jsonschema 4.26.0 while the documented environment differs. This review executed under /tmp/opensip-architecture-review-env and records that its environment is its own, not the documented root one.'),
 ('V21-FINAL-PEER-ADVISORY-NEW-2','Accounted. The intermediate mislabelled beforeBytes is preserved as flawed history with an accurate successor account; I independently measured before/after sizes for all three changed files and they match the final declaration.')]:
    prior[k]=pf('CARRIED-VERIFIED',b,'Advisory; corrected or accounted in source 21, independent review being this one.')
ar={('AR-%02d'%i):{'disposition':'CARRIED-FORWARD-NOT-A-FRESH-GRADE','basis':'Addressed by the owning contract sections these bytes carry and exercised only by the executed design-reference checks.','scope':'Routing and carry-forward only; no readiness grade, no qualification, no measurement of product behaviour.'} for i in range(1,17)}
fw={('FW-%02d'%i):{'disposition':'CARRIED-FORWARD-NOT-A-FRESH-GRADE','basis':'Framework-wide obligation retained by the contracts; FW-11 numeric comparability is stated normatively in workflows-and-surfaces.','scope':'Carry-forward only; not re-adjudicated by this review.'} for i in range(1,16)}
inh={}
for i in range(1,12): inh['DR-%03d'%i]={'disposition':'CARRIED-NOT-CLOSED','basis':'Inherited parent row; the proposed product disposition is recorded in inherited-residuals.proposed.md and is prospective.','scope':'No residual is CLOSED by this review.'}
for i in range(1,17): inh['DR-011-R%02d'%i]={'disposition':'CARRIED-NOT-CLOSED','basis':'DR-011 residual subledger row with a proposed successor disposition only; DR-011-R10 explicitly cannot be closed by that table and needs a fresh blind reconstruction.','scope':'No residual is CLOSED by this review.'}
scoped={('DR-%d'%i):{'disposition':'ROUTED-ONLY','appliedByThisReview':False,'finalApplicationOutcomeGranted':False,'basis':'Historical ACCEPTED standing is for architecture-preview scope; the register itself records the 28 affected V2 rows and DR-201-205 as OPEN for full-product integration against the newly selected capability set.','scope':'Carry-forward/routing is not a fresh readiness grade.'} for i in range(201,206)}
out={'schemaVersion':1,
 'standing':'FRESH INDEPENDENT REVIEW of the frozen candidate subject v21 by actual Claude. Not an application, not a readiness grade, not product qualification.',
 'subjectManifestSha256':S,'reviewer':'actual Claude (independent, authored none of this subject)',
 'verdict':'ACCEPT',
 'newMustIssues':[],'newShouldIssues':[],
 'newAdvisories':[{'id':'V21-CL-ADV-1','severity':'advisory',
   'title':'A timed-out reference child leaves the previous run per-script report on disk under the same name',
   'where':R+'/foundation/run-reference-checks.py','firstFailingBoundary':'the child spawn loop: the target report path is never cleared before subprocess.run',
   'counterexample':'check-identity.py exceeds the 600s budget on a slow host. The launcher correctly records timedOut true, exitCode null, reportSha256 null and passed false. But foundation/identity-report.json from an earlier successful run remains on disk carrying its own {"passed": 1596, "failed": 0}. Nothing distinguishes it from a current result by inspection of that file alone.',
   'owningSelector':'run-reference-checks.py, the loop over the five (script, report) pairs',
   'assessment':'This is bounded and already partly discharged. The launcher own report declines attribution and its docstring states this exact hazard verbatim. I searched every .py in the corpus outside reviews/ and the ONLY consumer of those five report filenames is the launcher itself, so no in-corpus reader can be misled. The exposure is to an external or human reader, or to a future application step that reads a per-script report directly.',
   'remedy':'Unlink the target report (missing_ok) immediately before each spawn, or write each run into a fresh per-run report directory. That would make "no completed result is attributed" and "no stale bytes are present" coincide instead of relying on the reader consulting the launcher report.',
   'notARegression':'Advisory rather than SHOULD: the launcher report is honest, the limitation is published on the file, and no consumer inside the reviewed corpus reads the stale artifact.'}],
 'priorFindingDispositions':prior,'arDispositions':ar,'fwDispositions':fw,
 'inheritedResidualDispositions':inh,'scopedReviewOwnerDispositions':scoped,
 'governanceCounts':{'ar':16,'fw':15,'inheritedResiduals':27,'evaluationResiduals':30,'scopedReviewOwners':5,'unperformedGates':32,
   'note':'Counts independently recomputed from the frozen bytes: AR-01..16; FW-01..15; DR-001..011 plus DR-011-R01..R16; RES-EP13-01..30; DR-201..205; DR-G01..G32.'},
 'verificationPerformed':{
   'subjectHashMatched':True,'fileCountVerified':12212,'manifestVerifiedBefore':True,'manifestVerifiedAfter':True,
   'totalBytesExact':716986273,'extraOnDisk':0,'missing':0,
   'protectedHistoryCustody':{'declared':31,'verifiedInSubject':31,'presentInPredecessor':10,'newlyIncluded':21,'liveDrift':0},
   'sourcePinLedgers':{'count':4,'pins':{'foundation':1100,'native':72,'security':74,'workflows':66},
     'allVerifiedAgainstSnapshot':True,'allVerifiedAgainstLive':True,'verifiedBeforeAndAfter':True},
   'contractReadCoverage':{'files':6,'totalLines':7729,'allFullyCovered':True,'record':'contract-read-coverage.json'},
   'sourceDeltaIndependentlyRecomputed':{'v20ToV21':{'added':280,'removed':0,'changed':15,
     'changedExecutables':[R+'/foundation/run-reference-checks.py',R+'/foundation/check-identity.py',R+'/workflows/workflows_model.v1.py'],
     'changedSchemaDocuments':0,'changedProductContractBytes':0,
     'remainderExplained':'4 source-pin ledgers repinned to exactly those three files (security and workflows ledgers also repin correction-crosswalk.proposed.json), 5 regenerated reports, and 3 governance prose files.'}},
   'sixCanonicalCommands':{'reproduced':True,'onExactUnrepinnedFullCopy':True,'copyFileCount':12212,'copyExactnessMismatches':0,
     'allExitZero':True,'allDeclaredSourceHashesAgree':True,'orchestrationTimeout':False,
     'foundationOuterTimeoutSeconds':3600,'otherOuterTimeoutSeconds':600,'innerChildTimeoutSeconds':600,
     'copyDeltaAfterExecution':'ZERO files changed, added or removed - every regenerated report is byte-identical to the frozen one',
     'record':'results/canonical/canonical-execution.json'},
   'mutationProbe':{'target':'workflows_model.v1.verify_scope_parameter_binding','lawsMutated':1,
     'method':'REAL owning entrypoint called with admitted positive data first, then one law moved; no copied algorithm, no manufactured error',
     'frozenIdentityChecks':'1596 passed / 0 failed','mutatedIdentityChecks':'1594 passed / 2 failed','mutatedExitCode':1,
     'failingControls':['an-ambiguous-spec-refuses-as-ambiguous-even-for-a-document-that-is-neither-candidate','the-three-answers-for-one-non-candidate-document-stay-distinct-by-row-multiplicity'],
     'scenariosChanged':1,'scenariosUnchanged':6,'mutationCopyDelta':'exactly 1 file changed',
     'retained':['results/mutation-guard-order.json','results/workflows_model.v1.MUTATED.py','results/mutation.diff','results/check-identity.MUTATED.log','results/identity-report.MUTATED.json']},
   'documentationOnlyClaimTested':{'file':R+'/workflows/workflows_model.v1.py',
     'astEqualModuloDocstrings':True,'docstringStrippedCodeObjectsIdentical':True,
     'changedDocstrings':['verify_scope_parameter_binding'],'moduleDocstringChanged':False,
     'note':'Full code objects INCLUDING docstrings are NOT identical, which is expected and which the root qualification itself states.'}},
 'scopeAndLimits':['This review reads design bytes and executes design-reference checks. It establishes no product qualification, no compiler or OS enforcement, no confinement and no complete semantic proof replay.',
   'A Python exit 0 or a printed PASS is not an assertion; the executed checks are evidence about the reference model over synthetic trusted inputs.',
   'Closure admission is not semantic proof replay. The 17-pair RC-6 sweep is helper-level; sealed-Run RC-6 coverage is the narrower named file@enumerated vectors in both minting universes, exactly as those controls label themselves.',
   'Literal and schema observations are reported as such and are never equated with execution security.',
   'This review executed in /tmp/opensip-architecture-review-env; that is its own measured environment and not the documented root one.'],
 'qualificationFlags':{'implementationAuthorized':False,'productQualification':False,'readinessChanged':False,
   'readinessActivated':False,'applicationPerformed':False,'anyQualificationFlagTrue':False,
   'd372Applied':False,'condition5':'NOT MET','blind9Performed':False,'independentlyReviewedApplicationPerformed':False,
   'finalApplicationOutcomeGranted':False},
 'requiredNextActs':['A NEW blind 9 complete semantic proof reconstruction, which this review does not perform and does not claim.',
   'A separately and independently reviewed complete application, which follows source acceptance and is not claimed here.',
   'Complete application/readiness reconciliation; DR-201..205 remain routed only.']}
json.dump(out,open('/tmp/opensip-design-corrections/post-reset-review.v21/review.json','w'),indent=1)
print('verdict',out['verdict'],'| prior IDs',len(prior),'| ar',len(ar),'| fw',len(fw),'| inherited',len(inh),'| scoped',len(scoped))
print('prior IDs:',', '.join(sorted(prior)))
