from pathlib import Path
import json,hashlib,shutil,datetime
b=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v4');snap=Path('/tmp/opensip-design-corrections/candidate-subject.v14');out=Path('/tmp/opensip-design-corrections/bv4-v4-checkpoint2');out.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();r=json.loads((b/'review-ready-2.json').read_text())
for row in r['delta']['againstFrozenV14']['changedFiles']:
 p=row['path'];assert sha(snap/p)==row['beforeSha256'] and sha(b/'work'/p)==row['afterSha256'];q=out/'source'/p;q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(b/'work'/p,q)
probe=Path('/tmp/opensip-design-corrections/bv4-v4-checkpoint2-preflight.v1');pr=json.loads((probe/'report.json').read_text());assert pr['checkpointSha256']==sha(b/'review-ready-2.json') and len(pr['cases'])==17;bad=[x for x in pr['cases'] if not x['holds']];assert len(bad)==5
f={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checkpointSha256':sha(b/'review-ready-2.json'),'technicalAssent':False,'verdict':'CHANGES_REQUIRED','standing':'Actual root technical review of exact checkpoint2, not independent acceptance, application or readiness.',
'agreed':['Both remaining carrier mirrors now name/limit the selected original-invocation route correctly.','Four-fields/two-record-families, exact headroom, per-refused-step attribution and actual report accounting are corrected.','The complete pre-Plan helper and closed vocabulary check are appropriate. Default93 and complete explicit1024/empty/small controls admit; default94 and explicit1025 produce ScopeRefusal with schema-admitted complete failure envelopes. Raw retained-schema overflow still rejects as ValidationError.'],
'rootProbe':{'root':str(probe),'reportSha256':sha(probe/'report.json'),'probeSha256':sha(probe/'probe.py'),'cases':17,'hold':12,'fail':5,'limits':pr['standing']},
'requiredFollowup':[
 {'id':'CX-V4-PREFLIGHT-MALFORMED-ARRAY','finding':'admit_analysis_spec unconditionally indexes requestedCapabilities and applies len before shape validation. This violates its new wrong-types/schema promise and misclassifies a string as1025capabilities.','actualFailures':bad,'requested':'Condition the cardinality precheck on the presence of an actual JSON array in an object. All other shapes must proceed to the existing complete schema validation, not KeyError/TypeError or ScopeRefusal; do not coerce values. Keep valid actual arrays over the bound on the typed refusal path before generic maxItems validation. State this conditional order in the owning paragraph/docstring. Retain meaningful malformed/missing-field controls plus fitting/overflow positives. The supplied root probe is readable and reproducible; keep its original failed result.'},
 {'id':'CX-V4-RETAINED-PATH-CLAIM','finding':'The new narrative goes beyond the available evidence: it says the previous guard would have been reached on an oversized retained payload and reclassified it. Current admit_run validates the retained analysis-spec schema before reaching the native vocabulary helper, as root previously showed. The raw-schema probe confirms that overflow is rejected there.','requested':'Correct current model/checker comments and additive handoff account to distinguish architectural separation of pre-Plan selection from retained validation from an actually reachable prior corruption reclassification. Do not assert that the latter occurred or would occur on the current path. Keeping cardinality out of the shared vocabulary helper is a sound separation; no behavioral change to retained Run closure or new full-Run fixture is required for this correction.'}
],
'next':'Correct these two bounded points, then STOP at new review-ready-3.json for root-review-3.json. Preserve checkpoint2, source/probe failures and all earlier custody. No unrelated new feature or public code is requested.'}
shutil.copy2(b/'review-ready-2.json',out/'review-ready-2.json');shutil.copytree(probe,out/'preflight');(out/'root-review-2.json').write_text(json.dumps(f,indent=2)+'\n');shutil.copy2(out/'root-review-2.json',b/'root-review-2.json');d=Path.cwd()/'docs/coop/design-corrections/reviews/codex-post-reset.v1/bv4-v4-checkpoint2';shutil.copytree(out,d);shutil.copy2(__file__,d/'review.py');print(json.dumps({'feedbackSha256':sha(b/'root-review-2.json'),'checkpointSha256':f['checkpointSha256'],'requiredFollowup':2},indent=2))
