"""Prepared only. Launch fresh actual Claude after combined source assent, final checks and freeze20."""
from pathlib import Path
import json,hashlib,subprocess,datetime
root=Path('/Users/sb/code/opensip-ai/opensip_arch');dc=root/'docs/coop/design-corrections';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text())
mp=dc/'reviews/candidate-subject.v20.json';m=load(mp);digest=sha(mp);a=load(dc/'reviews/codex-post-reset.v1/successor-source-assessment.v20.json')
assert a['finalSourceAssent'] is True and a['independentAcceptance'] is False
for row in m['files']:
 p=Path(m['snapshotRoot'])/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes']
assert (dc/'reviews/codex-post-reset.v1/technical-review.v20.md').is_file()
out=Path('/tmp/opensip-design-corrections/post-reset-review.v20');out.mkdir(exist_ok=False)
prompt=f'''You are ACTUAL CLAUDE in a FRESH INDEPENDENT OpenSIP architecture/design/schema/reference review. User explicitly requires substantive Claude and Codex agreement before implementation. You authored none of this subject. No subagents, implementation, commits, pushes, publication or readiness activation. Sources/history are read only. Write probes, exact disposable copies and reports ONLY {out}. Use /tmp/opensip-architecture-review-env/bin/python -I -B. Never execute report-writing checkers in frozen/live source.

FROZEN SUBJECT: {mp}, SHA256 {digest}; snapshot {m['snapshotRoot']}; {len(m['files'])} files. Verify every declared hash/length and inventory before and after, and allfour source-pin ledgers. Reproduce allsix canonical commands from reviews/codex-post-reset.v1/final-reference.v20/reference-checks.json in a disposable FULL exact copy WITHOUT repinning. Retain commands/exits/logs/report hashes and actual copy deltas. Preserve changed probe/model/corpus bytes and failed attempts. Unchanged bytes reconstruct from frozen subject; do not retain repeated full unchanged copies in final output. Counts are finite calls/cases, not qualification.

Read the five complete product contracts and index, owning schemas/registries and cross-unit reference joins. Inspect exact final sourceDelta in successor-source-assessment.v20.json, technical-review.v20.md, post-reset-dispositions.v20.proposed.json and advisory-application-account.v20.proposed.json. Independently inspect ALL changed executable/schema/contract bytes and relevant control flow. Read actual source coauthor/peer handoffs and root assessments referenced there as claims to judge, not authority.

CONTEXT: actual independent19 ACCEPT was real, but NEW blind8 found CB-GAP1..5 (2MUST3SHOULD) and four advisories. Root rejected blind8 and qualified its claimed evidence: all699rawidentities valid, only14/16finalgraphs admit closure; jsconfig and Rust imported-inert reconstruction errors already had normative answers. Six literal false/pass absence atoms have no required unresolved-edge evidence. Closure admission is NOT semantic proof replay, and a Python exit0 or printed PASS is not an assertion. Original findings/reconstruction/custody and root blind-assessment.v8.json remain historical. No acceptance of blind8 is claimed. Root's initial assumption that view.schemaDigests checked registration was subsequently disproved and explicitly superseded by the actual advisory assessment/root record.

REQUIRED CHANGED-LAW REVIEW:
1. At most ONE selected parameter per registered row, especially ScopeDocumentV1, at prospective analysis-spec admission, retained Run, and direct workflow scope binding. Zero stays legal for ordinary analysis; requested binding keeps its existing missing/mismatch refusal. One of each distinct registered row remains legal. ImportSourceContext zero/one/multiple and more-specific import derivation refusal preserved. Stage parameters are Plan subset, not a hidden second selection. Exact whole-item duplicates/schema/cardinality precedence remain distinct. Assess actual public routes and trusted boundary limits rather than assuming a helper completes an invocation.
2. Unique requested-capability ownership tuple(capabilityId,languageMode,workspaceRoot), requiredness is attribute. False/true conflict refuses both prospective and retained. Different modes/roots/capabilities legal. Valid default selections remain usable, no truncation/dedupe. Default duplicate-construction now emits the existing tuple INTERNAL key with tuple subject; explicit spec still reaches uniqueItems first for identical rows. Origin-dependent config/external/host routes use existing public details for this condition; actual default origin is host-generated, mapper testing at other origins is not default reachability. Complete failure envelope/remedies required. Tests must really contain competing faults where precedence is claimed.
3. RC6 coverage=complete implies examinedExhaustive=true across all17registered relation/rung pairs and fact-free scopes, at producer and retained closure. Unknown+true and unknown+false remain legal where other laws permit; enumeration completeness is distinct from resolution completeness. RC3 unresolved edges, Rust missing/ambiguous ownership, capability deficits, stageTerminal independence, RC0/RC2 precedence preserved. The12non-resolved helper cells are not automatically12complete sealed-Run tests. Modified older injected-complete vectors must retain their original deeper refusal target by making the hostile coverage claim internally coherent, not weaken it.
4. Both stage outputDomains sets admit only registered Domain vocabulary; flat $defs/Domain compatible with existing schema walkers; Domain/Ref/byDomain agreement guarded. Equality remains separate. Emptyset declares nooutput, grants no completeness/evidence/producer authority. Provider-owned operation token interface explicit; no platform-wide stage enum, host aliases or uncommitted discriminator. Hash recipe commits COMPLETE records, no overbroad collision or RunId-stability claims.
5. closureMembership publishes existing6direct2equal7other-input laws over evaluated/selected inputs, not every unreferenced CASblob or exactminimalset. Required direct members remain selected; import/native dependency closures retained through their own selected inputs. Deliberate extra retained selections legal and identity-affecting.
6. Registered-schema-document artifact class at BOTH view.schemaDigests and schema Ref enforces closed registry document membership, annotation-driven with retention first. Empty/subset/registeredextra sets remain declarations, never derived unions or admission authority. Eachpayload independently pins its actual schema. Arbitrary retained bytes refuse, missing bytes retain unavailable. Native coverageView is a bounded fragment with refreshed native document digest, not falsely claimed sealedRun. Other raw-artifact fields keep their own declared laws.
8. Register the TWO EXISTING baseline-scope public details (BASELINE.SCOPE_NOT_A_SELECTED_PARAMETER and BASELINE.SCOPE_PARAMETER_DIGEST_MISMATCH) in common schema and closed registry. Actual binder/adopt_baseline Refusal.termination and failure-envelope controls, ambiguity CONFIG.INVALID unchanged. Model projection uses caller-admitted inputs and is not a product invocation; Selected positive uses actual-Claude-authored unique sentinel, distinguishing ANY Refusal (including detail=None) from a successful return; root’s earlier is-None version is preserved and superseded. Public code count289, current four ledgers (not five), preserved emitted names but expanded admissible enum. Assess shared-code remedy constraint honestly: table equality is machine-checked, semantic truth of English next steps is review evidence.
9. Native fixture declaration matches FINAL native document and durable registered-schema guard detects drift. Combined peer OBS1 domain subsets and OBS2 compatibility duplication remain explicit advisories; no current subset-vocabulary defect is claimed.
7. Existing exact semantic-evidence.importIds==Plan.importIds publication, separately evaluated subset and finding citability; selection requires retention/admission even unused. No implicit imported facts or hidden evidence authority.

Author discriminating controls and inspect preserved complete design: zero-config capabilities/discovery/config; native ownership/clone progression; static/runtime/test/history/import evidence; deterministic typed identities/closure; changed-code/baseline; invocation/repair/replay/errors; authorization/availability. Reuse unchanged evidence only with verified source identity and honest scope. New required findings need a concrete counterexample, owning selector and first failing boundary. Do not equate literal/schema observations with execution security, compiler enforcement or complete semantic replay. Do not force ACCEPT.

Assess each20disposition and allfour CB-ADV1..4 with actual scope. Prior reviews remain historical. Governance16AR15FW27inherited30evaluation5scopedowners32unperformedgates: carry-forward/routing alone is not a fresh readiness grade. DR201..205 appliedByThisReview=false and finalApplicationOutcomeGranted=false when only routed. Allqualificationflags false, D372unapplied, condition5NOTMET. A NEW blind9 and separately independently reviewed complete application follow source acceptance; never claim them now.

Deliver review.json/md with top-level subjectManifestSha256='{digest}', verdict ACCEPT/CHANGES_REQUIRED/actualBLOCKED; newMustIssues/newShouldIssues empty only if none unresolved, separate newAdvisories. ID-keyed priorFindingDispositions cover CB-GAP1..5, CB-ADV1..4 and new root/peer corrections. ID-keyed arDispositions/fwDispositions/inheritedResidualDispositions/scopedReviewOwnerDispositions with actual basis/scope. About3000words Markdown and concise JSON using exact shared source refs, not duplicated prior reports. Retain probes/results separately. Give your substantive independent judgment on these exact bytes, not coauthor deference or readiness acceptance.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json']
p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=root,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':p.pid,'manifestSha256':digest,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(json.dumps({'pid':p.pid,'manifestSha256':digest}))
