"""Prepared only; requires root's completed substantive final-peer assessment before execution."""
from pathlib import Path
import json,hashlib,datetime
R=Path('/Users/sb/code/opensip-ai/opensip_arch');E=R/'docs/coop/design-corrections/reviews';O=E/'codex-post-reset.v1';B=Path('/tmp/opensip-design-corrections');F=B/'v20-final-source.v2';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text());ref=lambda p:{'path':str(p.relative_to(R)),'sha256':sha(p)}
last=load(O/'coauthor-assessment.v20-final-delta-peer.v1.json');assert last['fullRead'] and last['boundedFinalDeltaAssent'] and last['requiredChanges']==[]
m=load(F/'proposal.json');assert last['subjectManifestSha256']==sha(F/'proposal.json')=='7843e3cc7ba8a21ba12d9ca17c816ce8b680e4fa5b208f055d34f6ce7e66f96e'
for row in m['files']:
 assert sha(F/'work'/row['path'])==row['afterSha256'];assert sha(R/row['path'])==row['beforeSha256'];assert sha(E/'v20-final-source.v2/work'/row['path'])==row['afterSha256']
checks=load(F/'root-identity.v1.json');assert checks['passed']==1592 and checks['failed']==0 and all(r['passed'] for r in checks['checks'])
names=['main','stage.initial','advisories','stage-proposal','composition-peer','route','final-delta-peer']
rootrefs=[];qual=[]
for n in names:
 p=O/('coauthor-assessment.v20-'+n+'.v1.json');d=load(p);assert d['fullRead'];rootrefs.append(ref(p));qual.extend([{'source':ref(p),'qualification':q} for q in d.get('qualifications',[])])
handoffs=[E/'v20-coauthor.v1/output/handoff.json',E/'v20-stage-membership-assessment.v1/assessment.json',E/'v20-advisory-assessment.v1/assessment.json',E/'v20-stage-proposal-review.v1/assessment.json',E/'v20-combined-peer.v1/assessment.json',E/'v20-route-coauthor.v1/handoff.json',E/'v20-final-delta-peer.v1/assessment.json']
# Actual reports may use named output layouts: fail rather than infer a missing path.
assert all(p.exists() for p in handoffs),[str(p) for p in handoffs if not p.exists()]
sessions=[]
for p in handoffs:
 receipt=load(p.parents[1]/'response.json') if p.parent.name=='output' else load(p.parent/'response.json');assert receipt['is_error'] is False and receipt.get('subagent_stats',{}).get('spawned',0)==0;sessions.append(receipt['session_id'])
a={'standing':'Actual root/Claude technical assent to complete final source20 composition. Separate independent source review, NEWblind and fullapplication still required.','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fullRead':True,'finalCombinedSourceAssent':True,'independentAcceptance':False,'subjectManifestSha256':sha(F/'proposal.json'),'subjectManifest':ref(E/'v20-final-source.v2/proposal.json'),'actualCoauthorSessions':sessions,'actualCoauthorHandoffs':[ref(p) for p in handoffs],'rootCoauthorAssessments':rootrefs,'sourceDelta':m['files'],'reference':ref(E/'v20-final-source.v2/root-identity.v1.json'),'qualifications':qual,'basis':['Root read main10delta, all stage/advisory proposals, exact preliminary6rootdiffs, route9delta and final4rootdiffs with substantive actualClaude assessments and independent targeted root reproducers. Each final source path is traceably composed from these exact stages; earlier broader claims are qualified explicitly.','Required current parameter-selection, capability-ownership, RC6, schema-registration, stage-vocabulary and public-route defects corrected in source. No semantic exception introduced to bless rejected blind reconstruction.','Root1592identitychecks pass, but final source pins and six reports still owed. All observations are design/reference evidence over synthetic trusted inputs; no product or semantic proof replay qualification inferred.','The new public enum has289members: two preserved emissions newly admitted. Route fault identity now reaches the existing host-invariant carrier. Four actual ledgers, not five; shared-code English remedy truth is review evidence, distinct from table-equality checks.','Fresh independent20 and NEWblind9 remain independent tasks. All prior histories and working-tree beforeimages remain preserved. Condition5 remains NOT MET; no implementation authorization.'],'implementationAuthorized':False,'readinessChanged':False,'productQualification':False}
p=O/'coauthor-assessment.v20-combined.v1.json';assert not p.exists();p.write_text(json.dumps(a,indent=2)+'\n');print('Recorded actual final source composition assent; integration is next.')
