"""Record final executed reference evidence after all source20 corrections, never infer acceptance."""
from pathlib import Path
import json,hashlib,shutil
root=Path('/Users/sb/code/opensip-ai/opensip_arch');dc=root/'docs/coop/design-corrections';own=dc/'reviews/codex-post-reset.v1';tmp=Path('/tmp/opensip-design-corrections');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text());ref=lambda p:{'path':str(p.relative_to(root)),'sha256':sha(p)}
a=load(own/'successor-source-assessment.v20.json');assert a['finalSourceAssent'] and not a['independentAcceptance'];executed=tmp/'final-reference-v20-complete';commands=load(executed/'reference-checks.json');assert commands['passed'] and len(commands['commands'])==6 and all(v['exitCode']==0 for v in commands['commands']);dest=own/'final-reference.v20';assert not dest.exists();shutil.copytree(executed,dest)
summary=load(dc/'validation-summary.v1.json');assert summary['claudeFinalReview']=='PENDING-FROZEN-V20' and summary['native']['qualifiedCells']==0
rows=[]
for row in a['sourceDelta']:
 p=root/row['path'];assert sha(p)==row['afterSha256'];rows.append({'path':row['path'],'beforeSha256':row['beforeSha256'],'finalSha256':sha(p)})
for rel in ['correction-crosswalk.proposed.json','foundation/source-pins.v1.json','security/source-pins.v1.json','native/source-pins.v2.json','workflows/source-pins.v1.json','validation-summary.v1.json']:
 p=dc/rel;rows.append({'path':str(p.relative_to(root)),'finalSha256':sha(p),'rootOwnedRecording':True})
p=own/'final-source-account.v20.json';assert not p.exists();p.write_text(json.dumps({'standing':'Exact mutually assessed source20 corrections and executed six source-pinned commands. Fresh independent20, NEWblind9 and complete application pending.','files':rows,'sourceAssessment':ref(own/'successor-source-assessment.v20.json'),'actualFinalCommands':ref(dest/'reference-checks.json')},indent=2)+'\n')
body='''# Codex source20 correction assessment

Actual Claude and Codex corrected the required blind8 design/reference gaps and additional public-schema defects discovered while doing so. This is one complete intended design, with implementation staged later. Exact source changes, actual coauthor/peer evidence and root qualifications are bound in [the source assessment](successor-source-assessment.v20.json). These records grant no independent acceptance, blind acceptance, application approval or implementation readiness.

Historical independent19 ACCEPT remains valid for its own frozen subject. The NEW blind8 returned CHANGES_REQUIRED. Root rejected that reconstruction: all699 raw identities/preimages checked, but only14/16 final graphs admitted closure; jsconfig and imported-inert Rust graphs violate existing native joins. Six literal false/pass absence atoms lack required unresolved-edge evidence. Closure admission is not full semantic proof replay. The original report, code, failed attempts and qualified root assessment remain preserved. Source20 does not change contracts to bless reconstruction mistakes. NEW blind9 must compute and compare complete proof results and exercise tampered-logical-result refusal rather than count hashes or printed PASS lines as semantic verification.

The corrected parameter selection law permits at most one selected parameter per registered row. Zero remains legal for ordinary analysis; comparison/baseline consumers requiring a scope binding retain explicit missing and mismatch outcomes. The same foundation helper is called at prospective admission and retained closure, with a direct workflow binding guard before digest comparison. The ImportSourceContext sibling keeps its more-specific derivation refusal. Whole-item duplicates and cardinality/schema precedence remain distinct. Pre-Plan helpers do not claim full blob or retained-Run admission.

Requested capabilities have a unique capability/mode/root ownership tuple; requiredness is an attribute. Opposing requiredness values now refuse at prospective and retained boundaries. Different roots, modes and capabilities remain valid. Existing origin-dependent public codes carry the new internal fault with appropriate remedies. RC6 makes complete coverage imply exhaustive examination, preserving unknown with either examination state and preserving the distinction between enumeration and resolution completeness. The17pair helper matrix is not17complete Run tests. Rebuilt file@enumerated examples in TypeScript and syntax demonstrate the precise retained-closure refusal; resolved-reference examples can report RC2 alongside RC6. Earlier hostile complete-coverage controls now make the claim internally coherent so their original deeper guard remains reached.

Both stage output-domain sets use the registered vocabulary through flat Domain references compatible with the reference walkers. Root's original deep reference was rejected after Claude found it crashed valid records; root reproduced the failure and correction in the actual closure validator. Durable checks require Domain, Ref.domain and byDomain registry agreement. Empty output sets confer no evidence authority, and the selected provider owns operation tokens. Complete stage and cache records determine identity; the corrected prose does not omit Plan/outputDomains or other cache inputs from its collision reasoning. The closure-membership publication describes existing direct, equal and other-input selections over evaluated inputs, preserving extra retained selections without turning unrelated CAS bytes into evaluation inputs.

Registered-schema-document annotations now enforce membership at both view.schemaDigests and schema Refs. Retention is checked first; registered declarations may be empty, incomplete relative to payload-schema unions, or include unused registered documents. They grant no payload admission authority. Each payload retains its own independently admitted schema. Root's earlier assumption that registration was already enforced was disproved and is explicitly superseded, with original evidence preserved. The bounded native view fixture now names the actual final native document; it remains a fragment, not a sealed Run. The existing exact evidence/Plan importIds equality is published separately from evaluated-subset and finding-citation authority.

The main coauthor also discovered public baseline-scope details absent from the closed carrier vocabulary. They are required correction work, not silently deferred because they predate blind8. The final source assessment below records the actual route correction, default-selection route assessment and code-keyed-remedy maintenance disposition after substantive review. No speculative redesign or unreviewed source variant is accepted by this account.

Final finding dispositions:

'''
for row in a['findingDispositions']:body+='- '+row['id']+': '+row['correction']+'\n'
body+='\nMeasured reference results (calls/cases, not exhaustive coverage or qualification):\n\n```json\n'+json.dumps({k:summary[k] for k in ['foundation','security','native','workflows','integration']},indent=2)+'\n```\n\n'
body+='All four owning ledgers are verified after recording and again in the frozen copy. All31protected historical files remain unchanged. Root/Claude bounded probes use synthetic trusted observations; no product host/compiler/parser/OS or platform is qualified. Full-source and review provenance, failed fixture attempts, locally repinned coauthor report limits and exact source variants remain explicit in the source assessment.\n\nStill required: fresh independent20 with zero unresolved MUST/SHOULD, NEW blind9 with complete semantic replay, and separately independently reviewed complete application/readiness reconciliation. All32product qualification gates remain unperformed; D372 is unapplied and condition5 remains NOT MET. No product implementation, commit or push is authorized.\n'
p=own/'technical-review.v20.md';assert not p.exists();p.write_text(body)
print('Recorded exact final20 source/reference evidence; independent review remains pending.')
