from pathlib import Path
import json,hashlib
r=Path.cwd();out=Path('/tmp/opensip-design-corrections/application-draft.v3');files=out/'files';p=out/'documentation-proposal.json';d=json.loads(p.read_text())
rows={v['path']:v for v in d['edits']}
def stage(rel,text):
 dest=files/rel;dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(text);rows[rel]={'path':rel,'beforeSha256':hashlib.sha256((r/rel).read_bytes()).hexdigest(),'proposedSha256':hashlib.sha256(dest.read_bytes()).hexdigest()}
rel='docs/v2/architecture/00-status-and-authority.md';s=(r/rel).read_text();pos=s.index('\n\n');s=s[:pos]+'''\n\n> **Current intended-product authority — D-372:** The [applied product contract index](../contracts/product-v1/README.md) and [exact application record](../../coop/design-corrections/application.v1.json) supply the reviewed prospective successors for this scope. [The source map](../../coop/design-corrections/current-source-map.proposed.md) names their relationship to the historical V1/preview accounts below. Exact resolution and preservation of historical evidence still apply; the newer filename alone grants no authority. Conditions 1–4 are met at design level in [file 08](08-decision-and-readiness-register.md#unified-product-design-readiness); condition 5 remains NOT MET.''' + s[pos:];stage(rel,s)
rel='docs/v2/architecture/README.md';s=(r/rel).read_text();s=s.replace('> **Status:** Preview design complete under D-369; wider V2 directions below retain their stated scope.','> **Status:** Complete intended-product design accepted under D-372; D-369 is a historical preview milestone.').replace('> **Authority:** Exact V1 sources under [`docs/coop`](../../coop/) remain authoritative.','> **Authority:** [Applied product contracts](../contracts/product-v1/README.md), exact [D-372 application](../../coop/design-corrections/application.v1.json), and compatible inherited laws through the [source map](../../coop/design-corrections/current-source-map.proposed.md).').replace('> **Blueprint readiness:** Conditions 1–4 met for the preserved preview; condition 5 (implementation authorization) remains the next act. See the central register.','> **Blueprint readiness:** Conditions 1–4 met at intended-product design level; condition 5 is NOT MET. No implementation or product qualification is claimed. See the central register.');s=s.replace('For the implementable preview, begin with the [accepted reference architecture](../../coop/completion/reference-architecture.v2.md) and its [exact application manifest](../../coop/completion/architecture-application.v1.json). It supplies the applied scoped successors to reservations in the historical topic text.','Begin with the [product scope](10-mvp-and-future-scope.md) and [consolidated product contract index](../contracts/product-v1/README.md). The D-369 preview architecture and application remain historical scoped evidence. Read the older topic chapters through the D-372 source map.');s=s.replace('## Wider authoritative architecture (future scope)','## Authoritative architecture (current product design)').replace('and the still-missing V1 integration.','and the accepted product identity/evidence/custody integration. Actual implementation conformance remains required.');stage(rel,s)
rel='docs/v2/architecture/13-evidence-workflows-and-product-contracts.md';s=(r/rel).read_text();pos=s.index('\n\n');s=s[:pos]+'''\n\n**Current scope — D-371/D-372:** The Fallow constraints below are incorporated into the [accepted complete product contracts](../contracts/product-v1/README.md). Their “future” and preview-scope labels preserve the original D-370 act, not a competing current design or a reason to omit a selected capability. [The applied FW-01–15 map](../../coop/design-corrections/current-source-map.proposed.md#fallow-constraint-applicability-in-the-full-product) names the concrete common and language-native contracts. Implementation and qualification are separate.''' + s[pos:];stage(rel,s)
for name in ['01-semantic-model-and-host-authority.md','02-distribution-and-components.md','03-configuration-and-security.md','04-lifecycle-delivery-and-operations.md','05-v1-to-v2-relationship.md','09-v1-to-v2-claim-matrix.md']:
 rel='docs/v2/architecture/'+name;s=(r/rel).read_text();pos=s.index('\n\n');s=s[:pos]+'''\n\n> **Current applicability — D-372:** Read this inherited chapter through the [applied source map](../../coop/design-corrections/current-source-map.proposed.md) and [current product contracts](../contracts/product-v1/README.md). The exact [application record](../../coop/design-corrections/application.v1.json) names the owning successors; historical preview/V1 labels and frozen evidence below retain their original scope. [File 08](08-decision-and-readiness-register.md#unified-product-design-readiness) owns current readiness.''' + s[pos:];stage(rel,s)
d['edits']=list(rows.values());p.write_text(json.dumps(d,indent=2)+'\n');print(len(rows),'staged current documents; none applied')
