/**
 * Dashboard HTML generator — orchestrates all modules into a single self-contained HTML file.
 *
 * Composes CSS, shared JS, and tab-specific JS into one HTML string with all data inlined.
 * Each tool tab (Fitness, Simulation) has subtabs: Sessions, Catalog, Recipes.
 */

import { formatScore } from '@opensip-cli/format';

// Bundled, type-checked client modules (L4 migration). Generated by
// scripts/bundle-client.mjs from src/client/*.ts; inlined before the legacy
// string emitters so its exposed globals (e.g. `el`, `renderOverview`,
// `renderFitnessTab`) resolve for them and for the render block below. The
// subtab-bar / overview / sessions / checks / recipes / tool-tabs renderers now
// live in that bundle (src/client/*.ts).
import { boundChangeImpactRuns, projectChangeImpactRuns } from './change-impact/project.js';
import { DASHBOARD_CLIENT_BUNDLE } from './client-bundle.generated.js';
import { dashboardCss } from './css.js';
import { renderDeclaredInputs } from './declared-inputs-html.js';
import {
  codePathsVendor,
  graphArtifacts,
  projectBrowserSessions,
  projectOverviewRuns,
} from './generator-artifacts.js';
import { REPORT_CUP_FAVICON_DATA_URI, REPORT_CUP_HEADER_HTML } from './report-cup-icon.js';
import { normalizeReportViewSelection } from './report-selection.js';
import { serializeJsonForScriptContext } from './script-context-json.js';
import { FIRST_PARTY_TOOL_TABS } from './tool-tabs-registrations.js';

import type { DashboardRun } from './generator-artifacts.js';
import type { ReportSelectionEvidence, ReportViewSelection } from './report-selection.js';
import type { StoredSession, GraphCatalog, DeclaredInputs } from '@opensip-cli/contracts';

export type { DashboardRun } from './generator-artifacts.js';

/**
 * Inputs to the dashboard HTML generator.
 *
 * `sessions` is required; everything else has a sensible default
 * (empty array / null) so a Tool that does not produce a catalog or
 * recipes can call `generateDashboardHtml({ sessions })` and get a
 * working dashboard.
 *
 * Future tool-shaped data — alarm history, dependency graphs, simulation
 * traces — will land as new optional fields on this interface rather
 * than as new positional parameters. That keeps the call site
 * order-independent and the public API source-stable.
 */
export interface DashboardInput {
  sessions: StoredSession[];
  runs?: readonly DashboardRun[];
  /** Initial report navigation. Absence retains the current Overview default. */
  selection?: ReportViewSelection;
  /**
   * Host metadata for an exact `report --run` selection (counts/caps).
   * Reserved merge key — tools must never contribute this.
   */
  selectionEvidence?: ReportSelectionEvidence;
  declaredInputs?: DeclaredInputs;
  // Tool-owned catalog data, consumed structurally by the dashboard's
  // renderers (audit 2026-05-29, L1). Typed `unknown[]` because the entry
  // shapes (fitness's CheckCatalogEntry / RecipeCatalogEntry) are tool
  // domain vocabulary owned by the producing tool, not contracts. The
  // dashboard inlines them as JSON and its JS reads fields structurally.
  checkCatalog?: readonly unknown[];
  recipeCatalog?: readonly unknown[];
  graphCatalog?: GraphCatalog | null;
  // Graph-owned catalog data (Plan B). DISTINCT keys from fitness's
  // `checkCatalog`/`recipeCatalog` because the CLI merges every tool's
  // contribution via Object.assign — same key would clobber fitness. The
  // dashboard reads them structurally (entry shapes are graph domain
  // vocabulary owned by @opensip-cli/graph, not contracts).
  graphRuleCatalog?: readonly unknown[];
  graphRecipeCatalog?: readonly unknown[];
  // Simulation-owned catalog data (L6). DISTINCT keys (sim prefix) for the same
  // Object.assign-merge reason; the dashboard's Simulation tab reads them
  // structurally (entry shapes are sim domain vocabulary owned by the sim tool).
  simScenarioCatalog?: readonly unknown[];
  simRecipeCatalog?: readonly unknown[];
  // Yagni-owned catalog data. DISTINCT keys for the Object.assign merge reason.
  yagniSummary?: unknown;
  yagniCatalog?: readonly unknown[];
  editorProtocol?: string | null;
  /**
   * Absolute filesystem path the report is being generated from. Threaded to
   * the client as `PROJECT_ROOT` (see `client/globals.ts`) so `editor-link`
   * can turn a catalog/risk-relative path into an absolute `vscode://file/`
   * URL — that scheme cannot resolve a repo-relative path on its own.
   * Omitted/null ⇒ the client hides "Open in editor" links instead of
   * emitting ones the editor can't resolve.
   */
  projectRoot?: string | null;
  /**
   * Byte budget for the inlined graph catalog (see `code-paths/bound-catalog.ts`).
   *
   * Omitted ⇒ {@link MAX_GRAPH_CATALOG_BYTES}, which keeps the report a size you
   * can attach to a PR or email. A caller that is producing a report to explore
   * LOCALLY rather than to send someone (`opensip report --max-catalog-mb 64`)
   * raises it — that intent is per-invocation, which is why it is an argument
   * here and a flag there, not a project-wide setting.
   */
  maxGraphCatalogBytes?: number;
}

// Host-owned catch-all tab for sessions whose `tool` is NOT claimed by any
// first-party tab (external-adapter scans — gitleaks / osv-scanner / trivy).
// External tool sessions render here; named dashboard tabs are first-party-only
// today. This id / label / icon is the single source of truth: the generator
// emits the tab, panel, and render-call, and injects `externalTabId` as a page
// global so the bundled overview row-click handler (client/overview.ts) routes
// unclaimed-tool rows here and the catch-all renderer (client/tool-tabs.ts →
// renderExternalTab) resolves the panel id.
const EXTERNAL_TAB_ID = 'external';
const EXTERNAL_TAB_LABEL = 'External Tools';
// Shield icon (lucide) — external adapters are typically secret/vuln scanners.
const EXTERNAL_TAB_ICON = String.raw`<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>`;
const CHANGE_IMPACT_ICON = String.raw`<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v18h18"/><path d="m7 15 4-4 3 3 5-6"/></svg>`;

// Coerce a session.score into a finite number safe for HTML interpolation
// in the <title> tag. Returns 0 for non-finite values so the rendered
// title remains well-formed even if a legacy or corrupted session row
// somehow carries a non-numeric score.
function coerceScoreForTitle(score: unknown): number {
  const n = Number(score);
  return Number.isFinite(n) ? n : 0;
}

/**
 * Serialize an optional value into either a `<script type="application/json">`
 * blob (kind `'json'`) or a JS `const X = …;` literal (kind `'literal'`).
 *
 * Both call sites used to inline the same escape-then-stringify dance;
 * folding them into one helper means the script-context escape is
 * applied uniformly and the null-vs-supplied branching is in one place.
 *
 * - `'json'`: emits `<script type="application/json" id="<id>">…</script>`
 *   when `value` is not null/undefined; emits the empty string otherwise.
 * - `'literal'`: emits `const <id> = …;` always — `null` is rendered as
 *   the JS literal `null`, anything else as `JSON.stringify(value)`.
 */
function serializeOptionalBlob(id: string, value: unknown, kind: 'json' | 'literal'): string {
  switch (kind) {
    case 'json': {
      if (value === null || value === undefined) return '';
      const escaped = serializeJsonForScriptContext(value);
      return `<script type="application/json" id="${id}">${escaped}</script>`;
    }
    case 'literal': {
      // Apply the same script-context escape as the 'json' arm — without it,
      // a value containing the literal sequence `</script>` would close the
      // surrounding inline <script> block (JSON.stringify does not escape `<`).
      const rendered =
        value === null || value === undefined ? 'null' : serializeJsonForScriptContext(value);
      return `const ${id} = ${rendered};`;
    }
  }
}

/** Renders a self-contained HTML dashboard string from sessions and catalog inputs. */
export function generateDashboardHtml(input: DashboardInput): string {
  const {
    sessions,
    runs = [],
    checkCatalog = [],
    recipeCatalog = [],
    graphCatalog = null,
    graphRuleCatalog = [],
    graphRecipeCatalog = [],
    simScenarioCatalog = [],
    simRecipeCatalog = [],
    maxGraphCatalogBytes,
    yagniSummary = null,
    yagniCatalog = [],
    editorProtocol = null,
    projectRoot = null,
    selection,
    declaredInputs,
  } = input;

  const latest = sessions[0];
  // Coerce score to a finite number before interpolating into the <title>
  // tag — `latest.score` is typed `number` but originates from a SQLite
  // column and a corrupt or legacy row could carry an arbitrary value.
  // Number(NaN-ish) on a string still yields NaN; we substitute 0 to keep
  // the page title well-formed in the pathological case.
  const latestScoreLabel = latest ? formatScore(coerceScoreForTitle(latest.score)) : '';
  const safeDataJson = serializeJsonForScriptContext(projectBrowserSessions(sessions));
  const safeRunsJson = serializeJsonForScriptContext(projectOverviewRuns(runs));
  const safeCatalogJson = serializeJsonForScriptContext(checkCatalog);
  const safeRecipeJson = serializeJsonForScriptContext(recipeCatalog);
  const safeGraphRuleCatalogJson = serializeJsonForScriptContext(graphRuleCatalog);
  const safeGraphRecipeCatalogJson = serializeJsonForScriptContext(graphRecipeCatalog);
  const safeSimScenarioCatalogJson = serializeJsonForScriptContext(simScenarioCatalog);
  const safeSimRecipeCatalogJson = serializeJsonForScriptContext(simRecipeCatalog);
  const safeYagniSummaryJson = serializeJsonForScriptContext(yagniSummary);
  const safeYagniCatalogJson = serializeJsonForScriptContext(yagniCatalog);
  // The catalog contract is a STORAGE shape; the browser reads a much smaller
  // one. Inlining it whole produced a 293 MB report on this repo. Project it to
  // the client's contract and bound what remains — truncation is surfaced to
  // the page (see `graphCatalogOmittedFunctions`), never silent.
  const graph = graphArtifacts(graphCatalog, maxGraphCatalogBytes);
  const boundedCatalog = graph.boundedCatalog;
  const graphCatalogBlock = serializeOptionalBlob('graph-catalog', boundedCatalog.catalog, 'json');
  // The Visualization view (view-graph.ts) consumes a slim, pre-projected
  // view-model rather than the raw catalog: projection aggregates the
  // function call graph up to PACKAGE nodes + package→package edges (with
  // coupling weights + cross-package SCCs) here at generation time and embeds
  // it as its own JSON blob, sized for the renderer rather than for storage.
  // See code-paths/graph-view-model.ts.
  const graphViewModelBlock = serializeOptionalBlob(
    'graph-view-model',
    graph.graphViewModel,
    'json',
  );
  const vendor = codePathsVendor();
  const graphVisualizationDegradations = [
    ...graph.degradations,
    ...(vendor.degradation === undefined ? [] : [vendor.degradation]),
  ];
  const graphVisualizationDegradationsBlock = serializeOptionalBlob(
    'graph-visualization-degradations',
    graphVisualizationDegradations.length === 0 ? null : graphVisualizationDegradations,
    'json',
  );
  const editorProtocolJs = serializeOptionalBlob('EDITOR_PROTOCOL', editorProtocol, 'literal');
  const projectRootJs = serializeOptionalBlob('PROJECT_ROOT', projectRoot, 'literal');
  const reportSelectionJs = serializeOptionalBlob(
    'REPORT_SELECTION',
    normalizeReportViewSelection(selection),
    'literal',
  );
  const normalizedSelection = normalizeReportViewSelection(selection);
  const projectedImpactRuns = projectChangeImpactRuns(runs, sessions, graph.catalog);
  const boundedImpact = boundChangeImpactRuns(projectedImpactRuns, normalizedSelection?.runId);
  const safeChangeImpactJson = serializeJsonForScriptContext(boundedImpact.runs);

  // Overview is a cross-tool aggregate kept fixed at position 0. The HTML tab
  // buttons, panel containers, renderXxxTab() invocation list, and overview maps
  // all derive from the same explicit first-party descriptor list.
  const toolTabs = FIRST_PARTY_TOOL_TABS;
  // Bucket every session whose tool is NOT claimed by a first-party tab into the
  // host-owned catch-all "External Tools" tab. Emitted ONLY when such sessions
  // exist so a fit-only repo never shows an empty External Tools tab.
  const claimedTools = new Set<string>(toolTabs.map((t) => t.tool));
  const hasExternalSessions = sessions.some((s) => !claimedTools.has(s.tool));
  const toolTabButtons = [
    ...toolTabs.map(
      (t) =>
        `  <button type="button" id="tab-${t.id}" class="tab" role="tab" aria-selected="false" aria-controls="panel-${t.id}" tabindex="-1" data-tab="${t.id}">${t.icon} ${t.label}</button>`,
    ),
    ...(hasExternalSessions
      ? [
          `  <button type="button" id="tab-${EXTERNAL_TAB_ID}" class="tab" role="tab" aria-selected="false" aria-controls="panel-${EXTERNAL_TAB_ID}" tabindex="-1" data-tab="${EXTERNAL_TAB_ID}">${EXTERNAL_TAB_ICON} ${EXTERNAL_TAB_LABEL}</button>`,
        ]
      : []),
  ].join('\n');
  const toolTabPanels = [
    ...toolTabs.map(
      (t) =>
        `<div id="panel-${t.id}" class="tab-panel" role="tabpanel" aria-labelledby="tab-${t.id}" hidden></div>`,
    ),
    ...(hasExternalSessions
      ? [
          `<div id="panel-${EXTERNAL_TAB_ID}" class="tab-panel" role="tabpanel" aria-labelledby="tab-${EXTERNAL_TAB_ID}" hidden></div>`,
        ]
      : []),
  ].join('\n');
  const toolTabRenderCalls = [
    ...toolTabs.map(
      (t) =>
        `renderDashboardPanel(${serializeJsonForScriptContext('panel-' + t.id)}, ${serializeJsonForScriptContext(t.label)}, () => ${t.renderFunctionName}());`,
    ),
    ...(hasExternalSessions
      ? [
          `renderDashboardPanel(${serializeJsonForScriptContext('panel-' + EXTERNAL_TAB_ID)}, ${serializeJsonForScriptContext(EXTERNAL_TAB_LABEL)}, () => renderExternalTab());`,
        ]
      : []),
  ].join('\n');
  // Overview's `tool → badge style` and `tool → tab id` maps, derived from the
  // same descriptors and injected as page globals so the bundled overview renderer
  // (src/client/overview.ts) reads them as ambient data — the descriptor
  // derivation stays type-checked Node code rather than a string template (F1/F8).
  const toolBadgeStylesJson = serializeJsonForScriptContext(
    Object.fromEntries(toolTabs.map((t) => [t.tool, t.badgeStyle])),
  );
  const tabMapJson = serializeJsonForScriptContext(
    Object.fromEntries(toolTabs.map((t) => [t.tool, t.id])),
  );
  const externalTabIdJson = serializeJsonForScriptContext(EXTERNAL_TAB_ID);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OpenSIP CLI${latest ? ` — Pass Rate: ${latestScoreLabel}` : ''}</title>
<link rel="icon" type="image/svg+xml" href="${REPORT_CUP_FAVICON_DATA_URI}">
<style>
${dashboardCss()}
</style>
</head>
<body>

<div class="report-ambient" aria-hidden="true">
  <div class="orb orb-1"></div>
  <div class="orb orb-2"></div>
  <div class="orb orb-3"></div>
</div>

<div class="header">
  <span class="header-icon">${REPORT_CUP_HEADER_HTML}</span>
  <div class="header-title"><h1><span class="brand-open">Open</span>SIP Report</h1></div>
  ${renderDeclaredInputs(declaredInputs)}
</div>

<div id="report-degradation-banner" class="report-degradation-banner" role="status" aria-live="polite" hidden></div>

<div class="tab-bar" id="tab-bar" role="tablist" aria-label="Report views">
  <button type="button" id="tab-overview" class="tab active" role="tab" aria-selected="true" aria-controls="panel-overview" tabindex="0" data-tab="overview"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/></svg> Overview</button>
  <button type="button" id="tab-change-impact" class="tab" role="tab" aria-selected="false" aria-controls="panel-change-impact" tabindex="-1" data-tab="change-impact">${CHANGE_IMPACT_ICON} Change Impact</button>
${toolTabButtons}
</div>

<div id="panel-overview" class="tab-panel active" role="tabpanel" aria-labelledby="tab-overview"></div>
<div id="panel-change-impact" class="tab-panel" role="tabpanel" aria-labelledby="tab-change-impact" hidden></div>
${toolTabPanels}

<div class="footer">Generated by <strong>OpenSIP CLI</strong> &mdash; <a href="https://opensip.ai">opensip.ai</a></div>

${graphCatalogBlock}
${graphViewModelBlock}
${graphVisualizationDegradationsBlock}
<script>
// This host-owned guard is deliberately defined before any vendored or client
// code. It reports fixed, non-sensitive degradation text even when client
// module initialization fails before an individual panel can render.
const dashboardDegradedAreas = new Set();
function showDashboardDegradation(label) {
  dashboardDegradedAreas.add(label);
  const banner = document.getElementById('report-degradation-banner');
  if (!banner) return;
  banner.textContent = 'Some report content could not render. Unavailable areas: ' +
    Array.from(dashboardDegradedAreas).join(', ') + '. The remaining report content is still available.';
  banner.hidden = false;
}
function renderDashboardPanel(panelId, label, render) {
  try {
    render();
  } catch {
    showDashboardDegradation(label);
    const panel = document.getElementById(panelId);
    if (!panel) return;
    const notice = document.createElement('div');
    notice.className = 'empty';
    notice.textContent = label + ' could not render. The rest of the report remains available.';
    panel.replaceChildren(notice);
  }
}
globalThis.addEventListener('error', () => showDashboardDegradation('A report component'));
globalThis.addEventListener('unhandledrejection', () =>
  showDashboardDegradation('A report component'),
);
</script>
<script>
const sessions = ${safeDataJson};
const runs = ${safeRunsJson};
const changeImpactRuns = ${safeChangeImpactJson};
const changeImpactOmittedRuns = ${String(boundedImpact.omittedRuns)};
const graphCatalogTotalFunctions = ${String(boundedCatalog.totalFunctions)};
const graphCatalogOmittedFunctions = ${String(boundedCatalog.omittedFunctions)};
const checkCatalog = ${safeCatalogJson};
const recipeCatalog = ${safeRecipeJson};
const graphRuleCatalog = ${safeGraphRuleCatalogJson};
const graphRecipeCatalog = ${safeGraphRecipeCatalogJson};
const simScenarioCatalog = ${safeSimScenarioCatalogJson};
const simRecipeCatalog = ${safeSimRecipeCatalogJson};
const yagniSummary = ${safeYagniSummaryJson};
const yagniCatalog = ${safeYagniCatalogJson};
${editorProtocolJs}
${projectRootJs}
${reportSelectionJs}
const fitSessions = sessions.filter(s => s.tool === 'fit');
const simSessions = sessions.filter(s => s.tool === 'sim');
const yagniSessions = sessions.filter(s => s.tool === 'yagni');
// Descriptor-derived Overview maps (tool → badge style / tab id), consumed as
// page globals by the bundled overview renderer (src/client/overview.ts).
const toolBadgeStyles = ${toolBadgeStylesJson};
const tabMap = ${tabMapJson};
// Host-owned catch-all: sessions whose tool is not claimed by a registered tab
// (external-adapter scans). Rendered in the "External Tools" tab; the overview
// row-click handler routes unclaimed-tool rows to externalTabId.
const externalSessions = sessions.filter(s => !(s.tool in tabMap));
const externalTabId = ${externalTabIdJson};

// The vendored Cytoscape renderer (defines the cytoscape / cytoscapeDagre
// browser globals the Visualization view consumes). Inlined BEFORE the bundle so
// those globals are present; it is a third-party UMD blob, not our client JS.
${vendor.javascript}
${DASHBOARD_CLIENT_BUNDLE}

// =======================================================
// RENDER TABS
// =======================================================
renderDashboardPanel('panel-overview', 'Overview', () => renderOverview());
${toolTabRenderCalls}
renderDashboardPanel('panel-change-impact', 'Change Impact', () => renderChangeImpact());
</script>
</body>
</html>`;
}
