"""Generate reviewed Unicode15 default lowercase data offline; no ambient UCD.

This is a developer generator, never a build script or runtime network lookup.
Input bytes are pinned by sources.json, and unknown default contexts refuse.
"""
from pathlib import Path
import argparse
import hashlib
import json

def scalar(n):
    return 0 <= n <= 0x10ffff and not 0xd800 <= n <= 0xdfff

def generate(data):
    manifest = json.loads((data/'sources.json').read_bytes())
    assert manifest['unicodeVersion'] == '15.0.0'
    expected = {'UnicodeData.txt', 'SpecialCasing.txt', 'DerivedCoreProperties.txt'}
    assert {r['file'] for r in manifest['files']} == expected and len(manifest['files']) == 3
    for row in manifest['files']:
        raw = (data/row['file']).read_bytes()
        assert len(raw) == row['bytes'] and hashlib.sha256(raw).hexdigest() == row['sha256']
    lower = {}
    for line in (data/'UnicodeData.txt').read_text().splitlines():
        fields = line.split(';'); assert len(fields) == 15
        if fields[13]:
            lower[int(fields[0],16)] = (int(fields[13],16),)
    default_contexts = []
    for line in (data/'SpecialCasing.txt').read_text().splitlines():
        line = line.split('#',1)[0].strip()
        if not line: continue
        fields = [s.strip() for s in line.split(';')]
        code = int(fields[0],16); image = tuple(int(s,16) for s in fields[1].split())
        conditions = fields[4].split()
        if not conditions: lower[code] = image
        elif not any(c in ('tr','az','lt') for c in conditions):
            default_contexts.append((code, image, conditions))
    assert default_contexts == [(0x03a3, (0x03c2,), ['Final_Sigma'])]
    properties = {'Cased':[], 'Case_Ignorable':[]}
    for line in (data/'DerivedCoreProperties.txt').read_text().splitlines():
        line = line.split('#',1)[0].strip()
        if not line: continue
        fields = [x.strip() for x in line.split(';')]
        if fields[1] not in properties: continue
        endpoints = [int(s,16) for s in fields[0].split('..')]
        lo, hi = endpoints[0], endpoints[-1]
        assert scalar(lo) and scalar(hi) and lo <= hi
        properties[fields[1]].append((lo,hi))
    # Coalesce adjacent ranges, retaining exact property membership.
    for name, ranges in properties.items():
        merged=[]
        for lo,hi in sorted(ranges):
            assert not merged or lo > merged[-1][1]
            if merged and lo == merged[-1][1]+1: merged[-1]=(merged[-1][0],hi)
            else: merged.append((lo,hi))
        properties[name]=merged
    out=['// Generated by tools/generate_unicode_case.py from pinned Unicode15 data.',
         '// Unicode data copyright Unicode, Inc.; source notices and license retained in tools/unicode/.',
         'pub(super) const VERSION: (u8, u8, u8) = (15, 0, 0);',
         '#[rustfmt::skip]', 'pub(super) const LOWER: &[(u32, &str)] = &[']
    for code, image in sorted(lower.items()):
        assert scalar(code) and image and all(map(scalar,image))
        if image == (code,): continue
        string=''.join('\\u{'+format(n,'x')+'}' for n in image)
        out.append(f'    (0x{code:x}, "{string}"),')
    out.append('];')
    for name, rows in properties.items():
        out += ['#[rustfmt::skip]', f'pub(super) const {name.upper()}: &[(u32,u32)] = &[']
        out += [f'    (0x{lo:x},0x{hi:x}),' for lo,hi in rows]
        out.append('];')
    return '\n'.join(out)+'\n'

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--data',type=Path,required=True)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args(); result=generate(args.data)
    if args.check:
        if args.output.read_text() != result: raise SystemExit('Unicode case table differs from pinned generator output')
    else: args.output.write_text(result)
