from pathlib import Path
import hashlib,json,shutil
B=Path('/tmp/opensip-design-corrections');L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews');O=B/'claude-independent-design.v36';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not O.exists()
for name in ['claude-independent-design.v35','claude-dependency-totality-assessment.v1','claude-dependency-totality-author.v1']:
 d=B/name;assert json.loads((d/'process-completion.json').read_bytes())['exitCode']==0 and json.loads((d/'result.json').read_bytes()).get('is_error') is not True
mf=L/'candidate-subject.v36.json';m=json.loads(mf.read_bytes());c=json.loads((B/'root-final36-custody.v1/verification.json').read_bytes());assert c['manifestSha256']==h(mf) and c['archiveEveryMemberVerified']
base=B/'claude-independent-design.v35/review.json';assert h(base)=='d7dc035c532968df80334809815f1257a49b83fd47f880e3a89630df9669cd52'
focused=B/'claude-dependency-totality-assessment.v1/review.json';assert focused.is_file()
pkg=B/'claude-author-package-successor.v13';vr=B/'author-package-final36-verification.v1/verification.json';assert vr.is_file()
O.mkdir();(O/'root-delta35-to36.json').write_text(json.dumps({'standing':'Measured inventory only, independently verify','files':c['delta']},indent=2)+'\n')
prompt=f"""Continue actual independent design-review origin ce3dec3b-0620-44ec-86e6-129b0e25cb1b AFTER your completed bounded dependency-totality assessment. Whole source36 design/reference review on final frozen bytes. No source/live/prior-evidence edits; write ONLY this new runtime. No consumer inputs or rootblind reports, other agents, product work, activation, commit/push. Your own exploratory remedy in the focused assessment is disclosed; identify any overlap with candidate authorship precisely, never claim fresh blind or application-review standing.

Frozen subject: {mf}, SHA {h(mf)}, archive SHA {h(L/'candidate-source.v36.tar.gz')}, snapshot {m['snapshotRoot']}, {m['fileCount']} files/{m['totalBytes']} bytes. Parent35 SHA {m['parentManifestSha256']}. Independently verify manifest/archive/everyfile/noextra/no-parent-omission and derive entire delta. Root inventory is not acceptance evidence by itself.

Baseline COMPLETE35 ACCEPT: {base}, SHA {h(base)}, plus your completed focused totality assessment {focused}, SHA {h(focused)}. Preserve all107 original individually reasoned rows and actual reading history, including nine legacy-reading corrections and all source34 qualifications. Current owner changed/unchanged arrays must derive from actual35/36 manifests. Inherit unchanged owner reads only by exact hash equality, while reassessing cross-owner consequences of every substantive change. No gratuitous rerun of unchanged probes, no historical execution relabelling. All107 row maps remain:14F,30evaluationResidualDispositions,16arDispositions,15fwDispositions,27inheritedResidualDispositions,5scopedReviewOwnerDispositions. Source35's91inherited/11package/5cross-owner population is historical; derive actual36 reading/consequence standing.

Assess the combined successor: completed dependency-scope author1 removed A13 mapped fallback; completed dependency-totality author1 corrected the partial dependency census with a precise published law; root afterward aligned historySubjectOrder to the duplicate-preserving payload sequence and stated existing runtime polarity quantifiers in atom prose. Inspect FINAL bytes, not just author reports or your own exploratory patch. Explicitly close A13 and every focused totality finding or retain a concrete blocker. Verify totality, lawful grouping/disjoint scopes, partial actual evidence and all original cause/citation channels, mapped/commitment pairing, same/different-kind and whole-source/empty boundaries, known-match/count dominance and deterministic ordering. Distinguish synthetic atom API, native producer/carrier, closed enumeration, retained Run and product reachability; do not claim an unexecuted stronger boundary. Root's generic prose changes need substantive source-owner review, not merely pin verification. Explicitly assess author two-view sufficiency retaining partial evidence versus your focused prototype A/B that drops it; check both causes and citations. Root separately reproduced that regrouping partial-carrier entries can add a per-view cause carrier while keeping unknown, and qualified the overbroad global cause-set invariant without changing algorithm or test assertions. Assess this qualification. Root explicitly chose existing bounded empty/different-kind behavior: no guessed file-to-symbol correspondence or promised population completeness, with Coverage/attestation empty-route differences stated. Determine whether those precise limits are coherent with all upstream owners, or retain a concrete blocker.

Nonblind author evidence: claude-dependency-scope-author.v1 and claude-dependency-totality-author.v1 completed public reports/probes, preserved exact source deltas, root-source36-prose-completion.v1, root-final36 reference/custody/planning records. Source author823 is not an independent acceptor. No consumer output or root blind diagnosis may be read. Review source-only root totality probes if useful; their expected values do not replace your independent reasoning.

Actual reference: root-final36-reference.v1 and codex-post-reset.v1/final-reference.v36 bound execution; six groups and16children, counts as measured. Independently run meaningful affected controls and justified regressions, respecting source immutability; verify source pins. Planning layer4 may be retained only if all29 inputs unchanged;198paths20packages320mappings54unexecutedrecovery cases, no fabricated new layer/population.

Current author package: {pkg}, manifest SHA {h(pkg/'artifact-manifest.json')}. Root actual verification {vr}, SHA {h(vr)}. Verify all13 exact Run/control outcomes through BOTH open_run_closure and close_run and7queries on actual36. Construction retains mixed33TS/30normalized-Rust provenance if exactexports unchanged; independently verify that claim. Do not assume binding proves replay. Preserve A9 repair/reference-only, A10 partial-helper/operator/binding limits,30PENDING author grades and TCB-SCOPE-01 over13 rows. No blind or productqualification conclusion follows these synthetic examples.

Final complete review.md/json required, with verifiedManifest/current subject SHA/verdict/newMustIssues/newShouldIssues/advisories, precise corrected/historical standing and actual measured evidence. All107 rows have appliedByThisReview=false and finalApplicationOutcomeGranted=false; current disposition and reading fields explicit. Preserve28condition2 obligations,32productgates0performed/condition5NOTMET,54recovery0executed,D9DR007/DR011R08,all30residualproposalsPENDING until separate finalapplication review. No application, architecture-readiness, activation or implementation authorization granted here. Finish substantive whole-design successor review unless actually externally blocked. Interpreter /tmp/opensip-architecture-review-env/bin/python -I -B.
"""
(O/'prompt.md').write_text(prompt)
t=(B/'claude-independent-design.v35/launch.py').read_text();start=t.index('cmd=');end=t.index('\nstart=time.time()',start)
cmd=['/Users/sb/.local/bin/claude','--safe-mode','--strict-mcp-config','--model','opus','--resume','ce3dec3b-0620-44ec-86e6-129b0e25cb1b','--permission-mode','dontAsk','--tools','Read,Glob,Grep,Bash,Write,Edit','--allowedTools','Read','Glob','Grep','Write','Edit','Bash(python3 *)','Bash(/tmp/opensip-architecture-review-env/bin/python *)']
for d in [Path(m['snapshotRoot']),B/'claude-independent-design.v35',B/'claude-dependency-totality-assessment.v1',B/'claude-dependency-scope-author.v1',B/'claude-dependency-totality-author.v1',pkg,B/'author-package-final36-verification.v1',B/'root-final36-reference.v1',B/'root-final36-planning-checks.v1',L,Path('/tmp/opensip-architecture-review-env')]:cmd+=['--add-dir',str(d)]
cmd+=['--output-format','stream-json','--verbose','-p'];(O/'launch.py').write_text(t[:start]+'cmd='+repr(cmd)+t[end:]);(O/'dispatch.json').write_text(json.dumps({'standing':'Prepared only; actual process/init and substantive final review still required.','sessionId':'ce3dec3b-0620-44ec-86e6-129b0e25cb1b','manifestSha256':h(mf),'promptSha256':h(O/'prompt.md'),'baselineReviewSha256':h(base),'focusedAssessmentSha256':h(focused),'packageManifestSha256':h(pkg/'artifact-manifest.json'),'actualPackageVerificationSha256':h(vr)},indent=2)+'\n');shutil.copytree(O,L/(O.name+'-dispatch'));print('Prepared independent36',h(O/'prompt.md'))
