from pathlib import Path
import json,hashlib,shutil,difflib
B=Path('/tmp/opensip-design-corrections');root=B/'dependency-totality-successor.v1/source';out=B/'root-source36-prose-completion.v1';L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews')
assert json.loads((B/'claude-dependency-totality-author.v1/process-completion.json').read_bytes())['exitCode']==0
assert (B/'root-dependency-totality-author-only-delta.v1/delta.json').exists() and not out.exists()
F=root/'docs/coop/design-corrections/foundation';edits=[]
p=F/'evaluator-projection-registry.v1.json';raw=p.read_bytes();d=json.loads(raw);assert (json.dumps(d,indent=2,ensure_ascii=False)+'\n').encode()==raw
assert d['historySubjectOrder']=={'order':'strict unique path UTF-8','uniqueKey':'path'}
d['historySubjectOrder']={'order':'existing sequence (producer order)','duplicatePaths':'allowed; retain every matching row at its original ordinal. No merge or pick rule is conferred; repair targetSubjectProjection keeps its own ambiguity refusal.'}
assert d['importQuantifiers']['polaritySetR']['observabilityFilter']=='may select disclosure of unobservable/unmapped rows; MUST NOT put them in R; MUST NOT make exists true'
d['importQuantifiers']['polaritySetR']['observabilityFilter']='restricts matching polarity. Unobservable/unmapped rows never enter R or make exists true; otherwise relevant such rows remain disclosed as uncertain independently of the observability filter.'
edits.append((p,raw,(json.dumps(d,indent=2,ensure_ascii=False)+'\n').encode()))
p=F/'atom-evaluation-contract.v1.md';raw=p.read_bytes();assert hashlib.sha256(raw).hexdigest()=='2d399ec91b14f22ccb7459d01ead6f54806747b24a9867cc8862fe84afa5b8c0';t=raw.decode()
OPS = [('pairs nothing, whether or not any exact scope exists, and that dependency then occupies no position.', 'contributes no pairing, whether or not any exact scope exists. A dependency occupies no position only when no selected Coverage remains.'), ('Consequences, stated so none is inferred: regrouping owed subjects into lawful disjoint partitions\ncannot change the value or the cause set; outgoing is unchanged, because a present position for the', 'Consequences, stated so none is inferred: missing dependency subjects block completeness whether\nthey share a primary partition with covered subjects or occupy separate lawful disjoint partitions.\nRegrouping preserves the truth of this totality check; it does **not** promise identical proof records,\ncited primary Coverage ids or per-view cause carriers. Each view retains the carrier selected by the\nfold law below, so splitting a view can disclose an additional carrier without changing the unknown\nanswer. Outgoing is unchanged, because a present position for the'), ('**Runtime:** wrapper complete + payload window', '**Runtime polarity:** an unfiltered `exists` tests whether a consumable mapped runtime observation exists, so either `observed-hit` or `observable-unhit` can satisfy it. An `observability` filter restricts the matching polarity set before applying the quantifier; unobservable and unmapped rows never enter that set. Otherwise relevant unobservable/unmapped rows remain disclosed as uncertain independently of that filter. This is the projection registry `importQuantifiers` law; an unhit observation is not an execution hit.\n\n**Runtime:** wrapper complete + payload window'), ('**Deterministic dependency view, and the `coverage-unknown` carrier.**', '**Empty and different-kind dependency boundaries (current profile decision).** An empty owed set\nmakes the subject-totality check vacuous; ordinary dependency presence and native sufficiency still\napply. No complete dependency entry is synthesized for an empty primary scope. In the Coverage route,\nsame-kind containment selects no dependency for an empty source-subject set, so a required dependency\nremains absent and the answer conservative. A whole-source attestation retains whole-source selection\nand may satisfy sufficiency with an admitted explicit empty dependency partition. These evidence forms\ndo not imply identical empty-program completeness. For a different source kind, dependency selection\nremains the collective whole-source *(S, T)* search and fold over actual partitions, with no per-primary-\nsubject containment or totality guarantee. This profile does not infer a file-to-symbol map from paths\nor invent an expected dependency population. A stronger population guarantee requires an explicit\nnormative correspondence in a successor profile; it is not an unspecified implementation choice here.\n\n**Deterministic dependency view, and the `coverage-unknown` carrier.**')]
for before,after in OPS:assert t.count(before)==1;t=t.replace(before,after)
edits.append((p,raw,t.encode()))
p=F/'check-atoms.v1.py';raw=p.read_bytes();assert hashlib.sha256(raw).hexdigest()=='ebb9da8cf07336104441f7ef4b12d0d6f5250ea87542489367cf255d171cae2d'
before='Splitting incoming primary {f, g} into disjoint partitions cannot change the answer or its causes.';after='Splitting these complete-entry missing/full-cover fixtures preserves their value and causes. Per-view carriers need not agree for arbitrary partial entries.'
t=raw.decode();assert t.count(before)==1;edits.append((p,raw,t.replace(before,after).encode()))
out.mkdir();rows=[]
for p,b,c in edits:
 rel=p.relative_to(root)
 for kind,by in [('before',b),('after',c)]:
  q=out/kind/rel;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(by)
 q=out/'diffs'/(rel.as_posix()+'.diff');q.parent.mkdir(parents=True,exist_ok=True);q.write_text(''.join(difflib.unified_diff(b.decode().splitlines(True),c.decode().splitlines(True))))
 rows.append({'path':rel.as_posix(),'beforeSha256':hashlib.sha256(b).hexdigest(),'afterSha256':hashlib.sha256(c).hexdigest()})
for p,b,c in edits:assert p.read_bytes()==b
for p,b,c in edits:p.write_bytes(c)
(out/'assessment.json').write_text(json.dumps({'standing':'Root post-author prose/registry/docstring corrections on unfrozen isolated successor. No evaluator algorithm, schema validation keyword or checker assertion changed. Final independent review pending.','changes':rows,'rationale':['Align history sequence metadata while preserving repair ambiguity refusal.','State existing runtime polarity and unconditional relevant uncertainty disclosure precisely.','A non-exact mapping contributes nothing; another valid selected dependency may remain.','Root actual partial-carrier regrouping counterexample disproves a global cause-set invariant. Keep the totality truth and per-view carrier laws; qualify prose/docstring without changing assertions.','Resolve empty-source/different-kind questions explicitly by retaining bounded current behavior with no inferred correspondence or stronger population guarantee.'],'rootDesignAssent':False,'rootBlindAssent':False},indent=2)+'\n');shutil.copytree(out,L/out.name);print('Applied3file root prose/metadata/docstring corrections; no algorithm or assertion changed')
