from pathlib import Path
import datetime,hashlib,json,shutil
root=Path.cwd();reviews=root/'docs/coop/design-corrections/reviews';ev=reviews/'codex-post-reset.v1';author=reviews/'bv4-corrections-author.v2';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text())
h=read(author/'handoff.json');response=read(author/'response.json');assert response['is_error'] is False and response['session_id']=='77758b10-d7ba-4868-9d42-ae0b13e84cb6'
assert response['modelUsage'].keys()=={'claude-opus-5'}
for row in h['delta']['aggregateVsFrozenV13']['changedFiles']:assert sha(author/'work'/row['path'])==row['afterSha256']
for row in read(ev/'bv4-author-v2-source-diffs/index.json'):
 assert row['source'] in h['delta']['thisTurnVsV1']['changedFiles']
checks=read(ev/'bv4-final-source-recheck.v2/summary.json');pub=read(ev/'bv4-public-recheck.v2/report.json')
assert checks['coauthorHandoffSha256']==sha(author/'handoff.json')
assert len(pub['publicTargets'])==16 and sum(r['literalTargetSchemaAdmission']=='REFUSE' for r in pub['publicTargets'])==14
assert all(r['exitCode']==0 for r in checks['commands'])
accounts=read(author/'source-copy-accounts.json');a=accounts['work'];b=accounts['final-suite/work']
def changes(x):return {r['path']:r['sha256'] for r in x['changedFiles']+x['addedFiles']}
x,y=changes(a),changes(b);suite_diff=sorted(p for p in x.keys()|y.keys() if x.get(p)!=y.get(p))
assert suite_diff==['docs/coop/design-corrections/foundation/source-pins.v1.json','docs/coop/design-corrections/native/native-evidence-report.v2.json','docs/coop/design-corrections/native/source-pins.v2.json'],suite_diff
def ref(p):return {'path':str(p.relative_to(root)),'sha256':sha(p)}
d={'standing':'Codex substantive assessment of actual-Claude coauthor v2. Main technical corrections supported; final-source assent withheld for two remaining public-output joins. Not independent acceptance, blind acceptance, implementation or qualification.',
'recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actualCoauthor':{'sessionId':response['session_id'],'model':'claude-opus-5','response':ref(author/'response.json'),'handoff':ref(author/'handoff.json'),'custody':ref(author/'custody.json'),'substantiveRole':'COAUTHOR follow-up; not independent reviewer'},
'readAccount':'Read complete handoff Markdown and all JSON components, every ten this-turn semantic/source changes (nine full unified diffs plus complete semantic JSON diff for native cases), including the actual public route registry and its checker. All13 aggregate hashes match retained source; final suite differs only at its2development pins and generated native report.',
'finalSourceAssent':False,'independentAcceptance':False,'readinessChanged':False,'implementationAuthorized':False,'productQualification':False,
'supportedCorrections':[
 {'id':'CX-BV4-TOTALITY','assessment':'Supported on final released source. Root full-Run recheck now refuses the same cross-universe counterexample with COVERAGE_INVENTORY_TOTALITY_OMITS_PATH, and both original and own-fact-per-universe controls admit. Registry-driven five-coordinate match includes redundant owning snapshot deliberately.'},
 {'id':'CX-BV4-DERIVATION','assessment':'Supported on final released source. Root references declaration refuses native.coverage-cause-relation-not-in-scope; types control admits. Actual final checker calls sufficiency_v2 for declared-only versus any. D5/D6 are the same closure Run, not independent policy evaluations; inherited RC3/existential controls remain in the passing suite.'},
 {'id':'CX-BV4-DEFAULT','assessment':'The matrix-fixed request scope, explicit override distinction, release availability separation and non-Coverage-shaped selection account are supported. Root full/staged release selection keeps the identical11-row TS request. Public disclosure and contradictory residual blanket-pair wording remain below.'},
 {'id':'CX-BV4-PRECISION','assessment':'Supported: shared anchor max100000 is retained; selected scalar cause and set carrier are distinguished; native10 has properly headed tables. This does not prove exhaustive observation of every missing runtime input.'},
 {'id':'CX-BV4-CONTROLS','assessment':'Supported: read actual raw-byte probe and full final retained checker controls. Empty/binary/extensionless inventory positive controls and digest/length/path/code-UTF8 negatives pass. Location uses fingerprint.subjectKey.logicalPath and payload.path. Structural proof/repair field checks are not a renderer or repair-tool execution.'},
 {'id':'CX-BV4-NOTE-CONSUMPTION','assessment':'V1 correction is additive and original bytes preserved. V2 genuinely read the initial full inputs and first four-point current note at13:13:00.405 with a complete public tool result. The two later appended carrier/classification follow-through sections have no observed Read before handoff; the13:23 shasum is not receipt. Treat that feedback as pending, not claimed mutual agreement.'}],
'requiredFollowup':[
 {'id':'CX-BV4-DEFAULT-PUBLIC-CARRIER','parent':'CX-BV4-DEFAULT','finding':'selection-account-only names a Python helper return, not a published retained/public output carrier. CommandEnvelope/AnalysisResult are closed and no projection is named for candidate-only absence. Root schema control admits a valid AnalysisResult and refuses literal undeclaredCapabilities insertion. This is the missing carrier mapping, not a demand to insert that exact property at that exact location.','correction':'Name and implement the actual bounded host diagnostic/selection-disclosure/public carrier using existing schemas where adequate, or a narrowly scoped necessary successor schema/projection. Preserve advisory candidate authority, no fake relation/fact/Coverage, no Control or repair authority, deterministic order and honest incompleteness. Correct ALL copies of the blanket provider-unavailable pair still present in admission1.1 and native10/unsupportedTypedIsNotOnThisTable so the owning language-tier precedence and candidate-only distinction apply consistently.','evidence':ref(ev/'bv4-public-recheck.v2/report.json')},
 {'id':'CX-BV4-PUBLIC-ROUTE-COMPLETE','parent':'CX-BV4-PUBLIC-ROUTE','finding':'New table still classifies a host invariant fault as request-rejected/REQUEST.PRECONDITION_FAILED, contrary to inherited D9 host-fault versus precondition event law. Its alleged exact publicDetail aliases include prose placeholders:14of16 branch targets refuse the actual closed DomainDetail schema and none of the14 internal keys is in internalAliases. The checker explicitly permits strings beginning request detail/operational record, so its PASS does not establish a usable public normalization. recordsEditOwnedByRoot falsely says every target is already a member and materialization is mechanical.','correction':'Finish actual origin/phase-aware public termination/detail projection. Distinguish external invalid config, externally supplied/retained invalid spec when origin is known, host-generated invalid internal layer and authenticated input failure; do not infer origin in a pure row helper. Derive class/code/cause through existing D9 law and explain any vocabulary limitation instead of choosing an unrelated code. Optional DomainDetail may remain absent where the existing event law permits, with the real operational diagnostic carrier explicitly named; prose is not an enum value. Shared public-detail-registry is normative source, not a mere readiness record. Necessary schema/registry/normalizer edits belong in the correction and substantive review, not an asserted later mechanical alias edit. Validate real schema-admitted public outputs and actor-dependent behavior, not only text membership.','evidence':ref(ev/'bv4-public-recheck.v2/report.json'),'inheritedLaw':'docs/coop/artifacts/d9-exit-contract.v1.14.json#/nonAnalysisDerivation/rules; domainCondition distinguishes host-fault/precondition-failed; codeMaps.faultCauseToErrorCode. Preserve historical D9 bytes.'}],
'rootRechecks':ref(ev/'bv4-final-source-recheck.v2/summary.json'),'publicationRecheck':ref(ev/'bv4-public-recheck.v2/report.json'),'developmentSuiteLimits':{'actualFinalIdentityPassingCalls':1203,'nativeCases':347,'matrixCells':66,'suiteVsReleasedDifferences':suite_diff,'otherFinalPassingCalls':{'foundation':231,'productQuality':24,'configuration':28,'arrayOrders':65,'workflow':1598},'notFinalPinnedSixCommandEvidence':True,'intermediateSuiteHistory':'An earlier1188/347 suite ran in final-suite, then that disposable directory was rebuilt for1203/347. The earlier results survive in public tool history, not as a separate preserved full copy. Named checks execute the whole checker and filter; they are not bounded selected-test execution.'},
'originalReviewCountsPreserved':{'blindBv4Must':2,'blindBv4Should':2,'blindBv4Advisory':4,'historicalAdvisoriesToAccount':43},
'next':'Actual Claude focused follow-up on these two publication joins, then final-source assessment, integrated fixtures/records BEFOREpins, six checks/freeze, fresh independent review, NEW blind consumer and independently reviewed full application/readiness reconciliation.'}
p=ev/'coauthor-assessment-bv4-v2.json';assert not p.exists();p.write_text(json.dumps(d,indent=2)+'\n')
for name in ['retain-bv4-corrections-author-v2.py','recheck-bv4-final-v2.py','retain-bv4-root-v2.py','probe-bv4-public-v2.py','assess-bv4-author-v2.py']:
 q=ev/name;assert not q.exists();shutil.copyfile(Path(__file__).parent/name,q)
print(json.dumps({'finalSourceAssent':False,'remainingRequiredJoins':[r['id'] for r in d['requiredFollowup']],'sourceChangedFiles':13,'thisTurnChangedFiles':10},indent=2))
