from pathlib import Path
import datetime,hashlib,json,shutil
root=Path.cwd();ev=root/'docs/coop/design-corrections/reviews/codex-post-reset.v1'
author=root/'docs/coop/design-corrections/reviews/bv4-corrections-author.v1'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
handoff=json.loads((author/'handoff.json').read_text());custody=json.loads((author/'custody.json').read_text())
assert custody['sessionId']=='77758b10-d7ba-4868-9d42-ae0b13e84cb6'
for row in custody['files']:assert sha(author/row['path'])==row['sha256']
captured=Path('/tmp/opensip-design-corrections/bv4-totality-recheck.v1/work')
for row in handoff['diffAgainstFrozenV13']['changedFiles']:
 assert sha(captured/row['path'])==row['afterSha256']==sha(author/'work'/row['path']),row['path']
out=ev/'coauthor-assessment-bv4-v1.json';assert not out.exists()
issues=[
 {'id':'CX-BV4-TOTALITY','required':True,'finding':'New complete-file totality counts another universe in the same view.','evidence':'bv4-totality-recheck.v1/attempt3/report.json','requiredCorrection':'Match owning snapshot/relation/rung/sourceUniverse/targetUniverse; retain two-universe own-fact positive and missing-own-fact negative. Earlier two diagnostic setup failures remain recorded.'},
 {'id':'CX-BV4-DERIVATION','required':True,'finding':'Declared derivation-policy-unmet is accepted on references, although native4.7/sufficiency_v2 scopes that policy to types.','evidence':'bv4-derivation-recheck.v1/report.json','requiredCorrection':'Add the owning relation condition to the registry and actual producer/Run check. Move the existing compiler-inferred positive from references to types; preserve policy=any and RC-3/positive-use boundaries.'},
 {'id':'CX-BV4-DEFAULT','required':True,'finding':'New release registry subset language can silently narrow the D371 full default; the content/membership distinction is not sufficient to specify required default requests and absence disclosure.','evidence':'Released native capabilityIdLaw.releaseDeclarationRegistry membershipAuthority and default helper; admission1.1/native1.4.','requiredCorrection':'State and exercise the exact full-default capability/mode obligation, installed/development subset and qualification boundary, explicit override and unavailable/absent disclosure. No new preview exception.'},
 {'id':'CX-BV4-PUBLIC-ROUTE','required':True,'finding':'New requested/release capability internal refusals lack an explicit owning public D9/detail route and phase distinction.','evidence':'Released native helpers, foundation close_run and native10.','requiredCorrection':'Map new guards to existing public code/detail/event boundaries, distinguishing invalid request from invalid authenticated release declaration. Preserve UNSUPPORTED-TYPED request disclosure and existing enums.'},
 {'id':'CX-BV4-PRECISION','required':True,'finding':'No-upper-bound prose contradicts fact.anchors.maxItems100000; scalar-loses-nothing language overclaims simultaneous input-closure cause retention; section10 event table loses its header after the new six-column table.','evidence':'Released relation registry, identity/native prose, native cause registry and native10.','requiredCorrection':'State no additional relation-specific bound; distinguish the full unresolved-class set from the selected scalar missing-input cause without inventing new formats; restore the separate properly headed event table.'},
 {'id':'CX-BV4-CONTROLS','required':True,'finding':'Requested empty/non-UTF8 inventory and downstream location controls are not accounted by the handoff.','evidence':'CODEX-PUBLIC-NOTE.md and current check-identity diff.','requiredCorrection':'Verify zero-anchor inventory admits valid empty/binary raw bytes and still rejects wrong digest/length/path. Explain/test the existing finding/repair/proof location route, keeping scope proportional.'},
 {'id':'CX-BV4-NOTE-CONSUMPTION','required':True,'finding':'Handoff claims reading the note before handoff; the only actual public full Read is11:09:04.258, and12:30:05 only hashes it. Later substantive feedback is absent from released source.','evidence':'Retained public tool calls and handoff.inputsReadInFull.','requiredCorrection':'Preserve v1 unchanged; read the entire supplied final note now, assess every numbered item before editing, and clarify the earlier consumption claim additively. Hashing is not substantive reading.'}
]
report={'standing':'Actual root substantive review of all13 released source diffs, full handoff JSON/Markdown and actual development probes. Corrections remain required; no source integrated.','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sessionId':custody['sessionId'],'handoffJsonSha256':sha(author/'handoff.json'),'handoffMarkdownSha256':sha(author/'handoff.md'),'finalSourceAssent':False,'independentAcceptance':False,'readinessChanged':False,'sourceReadAccount':'All13 interim diffs were read against frozenv13; every captured byte matches final released afterSha256. Full handoff read plus exact final Markdown insertion and executedCommands exactRelationToTheReleasedBytes addition read from public mutation.','substantiveChoices':{'inventoryZeroAnchors':'Agree with explicit zero-anchor inventory class plus nonempty source-text and one-anchor body classes, preserving distinct legitimate semantic descriptors. Final totality and limits need the listed fixes.','namedCauseCarriers':'Agree with existing structured carriers, unchanged enums and one-way declared-deficiency support, preserving requirement-relative sufficiency. Final relation/default/precision joins remain open.','capabilityVocabulary':'Agree with explicit matrix IDs distinct from fact relation/rung, registered mode applicability and Plan admission. Full-default and public-route obligations remain open.','cloneLanguageAndAdvisories':'S1 body-selector correction and all four advisory directions are substantively supported; retain old severity and stage evidence. No independent acceptance inferred.'},'requiredFollowup':issues,'probeLimits':{'totality':'Attempt3 is the actual counterexample; attempts1/2 are harness failure/proper unrelated refusal.','derivation':'Two full retained-entry controls, not evaluator policy verdicts.','unsupportedRequest':'Author p5 limitation is honestly recorded. Root compiler-free references/syntax-only Run ADMITs with unknown/language-tier-unsupported/capability-missing; three additional relation controls do not establish request/output bijection.','developmentSuites':'1133 identity passing calls and other reported totals are development evidence with temporary pin changes. Not final frozen-source acceptance or distinct-case/qualification counts. Native checker source changed despite a broad handoff phrase every other script unchanged; the complete13-file delta governs.'},'historicalFindingAccounting':'Preserve actual Bv4 2MUST/2SHOULD/4ADVISORY. These same-scope root findings do not rewrite original severities/counts.43 historical advisories remain to account in successor records.'}
out.write_text(json.dumps(report,indent=2)+'\n');shutil.copyfile(__file__,ev/Path(__file__).name)
print(json.dumps({'assessment':str(out),'requiredFollowup':len(issues),'finalSourceAssent':False},indent=2))
