"""Launch actual Claude coauthor against a captured interim blind finding set.
No accepted source, active blind inputs/output, or current readiness is edited.
"""
from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
root=Path.cwd();dc=root/'docs/coop/design-corrections';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
mp=dc/'reviews/candidate-subject.v13.json';expected='8e6670f74d6e0bbed50b6c4914b3c7b29f627221f1591f4add5567f652f4c023'
assert sha(mp)==expected;m=json.loads(mp.read_text());snapshot=Path(m['snapshotRoot'])
assert all(sha(snapshot/r['path'])==r['sha256'] for r in m['files'])
out=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v1');out.mkdir(exist_ok=False)
work=out/'work';shutil.copytree(snapshot,work)
inputs=out/'blind-interim-input';inputs.mkdir();blind=Path('/tmp/opensip-design-corrections/consumer-b.v4/output');rows=[]
sources=[p for sub in ['src','vectors'] for p in (blind/sub).rglob('*') if p.is_file() and '__pycache__' not in p.parts]
for p in sorted(sources):
 rel=p.relative_to(blind);before=sha(p);q=inputs/rel;q.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,q)
 assert sha(q)==before==sha(p),'Active blind file moved during capture; preserve this attempt and do not launch'
 rows.append({'path':str(rel),'sha256':before,'bytes':q.stat().st_size})
assert all(sha(blind/r['path'])==r['sha256'] for r in rows),'Captured set moved; do not launch'
gaps=json.loads((inputs/'vectors/v6-gaps.json').read_text());assert [g['id'] for g in gaps]==['CB4-MUST-1','CB4-MUST-2','CB4-SHOULD-1','CB4-SHOULD-2','CB4-ADV-1','CB4-ADV-2','CB4-ADV-3','CB4-ADV-4']
(out/'input-custody.json').write_text(json.dumps({'standing':'Captured INTERIM independently written blind reconstruction and gap vectors. Final blind verdict/severities pending; no final acceptance or disposition inferred.','baseManifestSha256':expected,'blindSessionId':'878e4b39-2d21-46b2-87bd-64f8d4db015f','capturedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':rows},indent=2)+'\n')
prompt=f'''You are actual Claude in a NEW COAUTHOR correction session. User explicitly requires substantive Claude+Codex alignment and correction of architecture/design gaps before implementation. This is authorized DESIGN/SCHEMA/REFERENCE work only, NOT product implementation, commit, push, publication or agent spawning. You are not an independent reviewer or blind consumer and cannot grant their acceptance.

Base exact accepted frozen v13 SHA {expected}, {len(m['files'])} files, copied to {work}. Work ONLY in that disposable source copy and outputs under {out}. Root {root}, all frozen snapshots and historical reviews remain untouched. Actual independent v13 ACCEPT exists but a NEW actual blind consumer is finding further inconsistencies. It is still concluding. Your captured inputs {inputs} and input-custody.json preserve its INTERIM own code/vector outputs. Read the complete vectors/v6-gaps.json and source, not just this prompt. DO NOT access or message the active blind session/directory, and do not modify the captured inputs. Root will supply its final exact review through CODEX-PUBLIC-NOTE.md and a separate retained input directory. Preserve actual final severities and any reconstruction limitations.

Concrete scope: CB4-MUST-1 inventory/symbol anchor law and syntax-universe inventory representability; CB4-MUST-2 closed native cause/disclosure carriers; CB4-SHOULD-1 clones languageIdSource wording; CB4-SHOULD-2 requestedCapabilities capabilityId authority; and all four associated advisories individually. Root independently confirms the section10 Cause(nativeCause) values are not expressible in the closed enum, clones languageIdSource contradicts the actual body selector, and requestedCapabilities accepts arbitrary Text while the release registry is only a trusted helper argument with no published normative vocabulary/selector. Root has NOT accepted the blind's proposed remedies as necessarily sufficient; assess them substantively and correct the entire owning law and its admission joins.

M1: the blind had to choose unanchored inventory facts for unsupported .py paths because the per-anchor selected-grammar guard otherwise refuses them despite unconditional inventory availability. Read its exact two-descriptor counterexample. Decide and publish the semantic anchor law for each relation or well-defined relation class, including canonical cardinality/source extent where needed, inventory-versus-code ownership, and which legitimate location differences are genuinely different semantic inputs. Avoid fabricating a universal cross-provider identity guarantee for distinct legitimate semantic descriptors; but do not leave representability dependent on an undocumented zero-anchor trick. A promised inventory capability must represent every inventoried path including unsupported/extensionless/data paths, and a complete empty result must not hide omitted inventoried facts. Keep snapshot path/hash/length joins, own-scope attribution and code-fact nonempty anchors/selected grammar capability enforcement. Exempting inventory from code grammar ownership may be right, but alone may leave ambiguous anchor semantics; assess both concerns. Preserve file/package/vcs inventory without compiler units, and genuine code/data distinction. Probe full retained Run admission, not just a helper. Include anchored/unanchored alternatives, mismatched own path/bytes/extent, unknown suffix, no bundled code grammar, mixed scope and supported code controls. Do not make all syntax code facts admissible merely because one anchor is supported.

M2: section10 explicitly labels its column nativeCause, but unresolved-edge classes, exports-open/unknown and compiler-inferred are not NativeCause members. A scalar also cannot carry multiple simultaneous unresolved classes. Choose a coherent closed law: either expand the actual typed cause representation with deterministic multi-cause/precedence handling, or explicitly name the existing typed carriers and specify lawful null/nativeCause values and exact derived joins. Do not merely hide required disclosure behind null or relabel every missing cause as generic capability-missing. Cover resolution partial/not-attempted/incomplete and unresolved classes, external-consumer state, declared-only type derivation, ownership and input-closure, unsupported/provider, budget and any same-class deficiency. Distinguish evidence retained in Coverage from outward common parity projection; every mandated disclosure must have an unambiguous retained/public route. Derive the owed state from committed evidence and enforce it at producer and retained Run admission; a schema-valid unrelated deficiency or cause must not substitute. Keep existing D9/public enums unless a necessary explicit same-contract correction truly demands otherwise, and explain it. Include positive/negative/fullRun controls for all affected branches, multiple causes/precedence, false complete/null/wrong deficiency/wrong carrier, and preservation of the v13 ownership law.

S1: relation registry clones.bodyIdentityJoin.languageIdSource must name the SAME actual body anchor/variant/dialect selector as identity section3 and the domain registry languageVersionBinding. Provider domain language is not body language. Correct owning metadata/prose consistently; TS-hosted JS and compiler-free syntax Runs must yield javascript/typescript/rust as appropriate, never syntax. Recheck native/reference consumers and cross-language clone identity rules.

S2: publish the exact requestedCapabilities.capabilityId vocabulary authority, spelling and selector, and relation to matrix capability IDs, relation@rung, release declarations, applicable language modes and zero-config default selection. The current default helper accepts trusted rows {{capabilityId,languageModes}} and current fixtures use relation@rung, whereas matrix IDs include inventory,syntax,clones-fact,clones-near,clones-cross-tsjs. Do not silently equate distinct concepts. Decide the smallest complete public contract; release-specific implementation content may remain an authenticated input but its schema, membership authority, canonical spelling and binding to Plan must be explicit normative inputs. Close admission and retained Run joins, not merely the default helper's preview-* check. Ensure all advertised modes, native contexts and full default selected product obligations stay representable. Probe unknown/alias IDs, wrong mode/row, duplicate/order, explicit/default agreement and semantic ID changes. Any new normative registry needed by implementers must be declared with exact path/selector and included in the next blind kit by root.

Advisories: ADV1 correct stale native prose60 versus actual66 (prefer a maintained/derived count rather than adding a new stale counter). Root also owns a stale60 in validation-summary.v1.json and will correct the successor recording before freeze. ADV2 reconcile all prose lists of native context/universe domains with the complete machine registry incl syntax. ADV3 explicitly document the repository-effect-to-permission-token mapping, preserving actual v9 values and stated host enforcement limits; do not imply the host-state write token grants repository filesystem authority. ADV4 keep the currently unambiguous parameter document-key law unless a substantive missing requirement calls for a semantic change; explicitly account the forbidden future duplicate-selector limitation rather than inventing unrequested flexibility.

Bounded source ownership: product contracts identity-and-evidence.md, native-evidence.md, workflows-and-surfaces.md, admission-and-qualification.md (and security-and-lifecycle.md ONLY for an actual necessary effect mapping clarification); source/schema/corpus files under foundation, native and workflows actually required by these corrections. No product implementation. DO NOT change source-pin manifests, existing generated reports, validation/provenance summaries, review/crosswalk/readiness/application records, historical artifacts, security reference models or historical reviews. Root owns recording and integration. Preserve exact before-images for every changed source. Existing pins intentionally become stale in this development copy; for whole-suite experiments use another disposable copy with an explicit measured temporary repin and retained logs, never present it as accepted pin evidence. New independent development probes belong under {out}/probes unless deliberately integrated as current reference regressions. No silent changes outside your scope.

Read CODEX-PUBLIC-NOTE.md fully if present before major edit batches and handoff. Diagnose on original v13 FIRST with retained exact counterexamples, then fix the smallest coherent set. Preserve semantic field annotation traversal/conflict/equality/order laws, closed relation-specific rungs, ScopeDocument parameter schema selection, full policy evidenceUse declarations, actual source/path/byte joins, clone body/version/dialect selected ownership, grammar selected-row suffix and own-scope laws. Do not conflate enum membership with evidence truth or synthetic probes with native enforcement. Reproduce legitimate controls to distinguish a working rule from universal refusal. Retain failed development attempts honestly. Python /tmp/opensip-architecture-review-env/bin/python -I -B has jsonschema.

Deliver handoff.md/json with substantive diagnosis and selected rules/tradeoffs, each exact final finding disposition (or pending-final limits), every changedFiles path/beforeSha256/afterSha256, sourceRoot={work}, exact executed commands/results/source versions, all added/deleted files and a complete diff account against frozen v13, no changed pins/generated reports in released source. Codex must read/assess your source and discriminating tests before integration; do not claim alignment merely from this request. Root then owns final reference fixture integration, recording edits BEFORE final pins, six commands, pin seal and freeze, fresh independent review, NEW blind reconstruction and complete application review. No readiness promotion or product qualification here. Complete this bounded correction pass thoroughly.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Edit,Bash','--allowedTools','Read','Grep','Glob','Write','Edit','Bash','--strict-mcp-config','--output-format','json']
proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=work,start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':proc.pid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sourceRoot':str(work),'baseManifestSha256':expected,'command':args},indent=2)+'\n')
print(json.dumps({'pid':proc.pid,'sourceRoot':str(work),'capturedInterimFiles':len(rows),'baseManifestSha256':expected}))
