"""Actual original blind reviewer, additive clarification on unchanged v18 normative bytes.
Original independent evidence remains immutable. No author model is provided.
"""
from pathlib import Path
import json,hashlib,subprocess,datetime,shutil
repo=Path('/Users/sb/code/opensip-ai/opensip_arch');base=Path('/tmp/opensip-design-corrections');prior=base/'consumer-b.v7';out=base/'consumer-b.v7-clarification.v1/output';kit=prior/'subject'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
r=json.loads((prior/'output/response.json').read_text());assert r['is_error'] is False and r['session_id']=='e6448709-ca71-43a1-97ce-b45b939367d9'
retained=repo/'docs/coop/design-corrections/reviews/consumer-b.v7';assert json.loads((retained/'custody.json').read_text())['sessionId']==r['session_id']
for name in ('blind-review.json','blind-review.md','response.json'):assert sha(prior/'output'/name)==sha(retained/'output'/name)
out.mkdir(parents=True,exist_ok=False);shutil.copytree(prior/'output/work',out/'work',ignore=shutil.ignore_patterns('__pycache__'))
prompt=f'''Resume your own completed BLIND consumer7 session for an additive clarification on the SAME unchanged v18 normative kit. Original review JSON SHA256 {sha(prior/'output/blind-review.json')} and Markdown SHA256 {sha(prior/'output/blind-review.md')} are retained verbatim with all82files/306publictoolblocks. Your actual completed154turn receipt is retained. Root has fully read both reports, all original helper modules and the relevant subsequent additions, and audited the exact final exported bytes. No implementation/readiness acceptance is granted.

Read design ONLY from {kit}, as before. You may read your own original {prior/'output'} and work ONLY in {out}; I copied your eleven helper modules into its work directory. Preserve original output and kit completely. No original repository, author models/cases, prior review directories, other /tmp directories, or agents. You are still clarifying your independent reconstruction, NOT authoring design corrections. No design/schema/contract edit here. Your new work is clearly post-review clarification after root feedback, not a new fresh blind. Keep all new failed attempts, before-images and reports rather than overwriting failures. Do not merely agree with root; execute the discriminating checks and state actual conclusions.

1. Your eight-graph/1974-check claim does NOT establish every owning schema/order/closure law. Root rehashed every exported blob and recomputed every object identity: all are correct. However the final ORIGINAL RUN-TS, RUN-RS-A/A2 and RUN-SYN-DATA finding.evidenceRefs are not strictly ordered by C(item), violating identity schema #/$defs/finding/properties/evidenceRefs/x-opensip-order and identity S3. Your Closure appears not to invoke schema/order admission on those finding records. RUN-SYN-CODE and DATA grammar bundle manifest and definition bytes are absent from their declared grammar closure tree, violating native S1.2's explicit 'every grammar definition, the bundle manifest and the normalizer specification present in the retained tree.' Merely retaining a blob elsewhere in CAS does not satisfy membership. Your own validator misses this. Root's separate reference check refuses five originals; Rust-B and both incomplete Rust disclosure graphs admit. In ROOT-ONLY diagnostic copies, sorting those evidenceRefs and retaining the actual grammar bundle/definition bytes in the declared tree is sufficient for the four representative TS/Rust/syntax graphs to admit. These are existing precise normative answers, not new design gaps, and my copies are not supplied as an oracle or accepted as your work.

Please correct your OWN validator/builders in the NEW directory using the kit, preserving originals. Explicitly validate all exported records against their owning schema plus order annotations, and every declared grammar member against the selected closure. Add bounded discriminating negatives for these two omissions, rebuild/export all8, reload from scratch, and revise complete-admission claims to measured scope. Export the MUST-1 probe itself as a complete graph too, after removing unrelated helper errors, so its claimed closure is independently inspectable. No need to recreate full host enforcement or chase unrelated implementation algorithm freedom.

2. Reassess CB7-SHOULD-1. Your helper imposes an extra equation: exact cause == unmetPreconditions[].code. The quoted workflow S6 says exact cause is carried into the unmet precondition so different causes are different REMEDIES; it never says the code must equal the deficiency token. DomainDetail also has remedy/subject string fields. The existing kit registers REPAIR.EVIDENCE_RUN_UNAVAILABLE; assess its applicability, and whether exact plane/relation/deficiency in distinct remedies satisfies the existing law with no new code. A chosen mapping must retain evidenceRequirements[].deficiency and keep applicable false/authority unchanged. Demonstrate two different causes in schema-admitted complete repair descriptors, including an imported cause; distinguish an expressible record from a fully authorized repair. If a remaining normative mapping ambiguity truly requires source clarification, identify that narrower issue honestly, preserving your original finding and any retraction/correction. Do not retain 'cannot express' merely because a cause is not a code member.

3. CB7-MUST-1 and SHOULD-2 appear substantive to root, subject to your corrected examples and exact scope. Reassess without pressure to accept. For Plan overflow distinguish a constructive bound/reachability argument plus schema fragments from 129 actually assembled contexts/complete Plan. Your own schema error prefixes the field name (nativeContextDigests/importIds), so 'names no field' is overbroad; it lacks a bounded typed count/limit/remedy. Keep semanticClosures bound128, not256. A final source fix will require a newly frozen candidate and another fresh independent/NEW blind; this clarification cannot accept future changes.

4. Correct reporting scope without inflating the exercise. vec_public.failure_envelopes are literal composed envelopes validated by schemas, not actual raised/caught internal failures. vec_authz authorization/effect examples check shape/table equality; several semantic refusals and repair-plan edit boundaries are literal assertions, not an executed security admission/authorization engine. Comparison cases are schema-valid descriptors/conceptual classifications, not a closed baseline/Run comparison engine; the two ScopeDocument Plans are real constructed Plans but not two full compared Runs. minResolutionPredicates is ladder-index helpers, not full sufficiency over every Coverage/evidence boundary. Selfcheck relation digest traversal explicitly covers7top-level occurrences, not arbitrary schema inheritance. The 29 negatives include changes to several fields/records and recomputation; 'single-field mutation' is not generally accurate. The displayed nativeHPreimages payloadBytes are truncated heads for four of six records; full bytes do exist in exports. ADV1 counts compare ten inherited fault-map entries versus twelve successor enum values INCLUDING none; actual enum comparison is11->12. State these limits in corrected JSON/MD and retain actual evidence instead of changing original claims silently.

Deliver clarification.json/clarification.md addressing1..4, then FULL corrected blind-review.json/blind-review.md with exact original references and effective verdict/newMustIssues/newShouldIssues/advisories (original IDs, explicit dispositions for any retraction). Retain your corrected code, all8exports plus MUSTprobe, raw vector-results/verify-report, and exact before/after changes. Reverify all45kitfiles at finish. Your original CHANGES_REQUIRED remains immutable historical evidence. No product qualification or implementation authorization. Keep the pass focused on these existing obligations.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--resume',r['session_id'],'--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Bash','Write','--strict-mcp-config','--output-format','json']
proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=kit,start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':proc.pid,'sessionId':r['session_id'],'parentSubjectSha256':'cd6e828c22c6bc0ecf07ab8fe1f4bd5d1a5a8726708e0deffac99960bdc25a44','originalReviewSha256':sha(prior/'output/blind-review.json'),'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(proc.pid)
