"""Record root assessment of completed blind Bv4 and supply exact final evidence to coauthor."""
from pathlib import Path
import hashlib,json,shutil,datetime
root=Path.cwd();dc=root/'docs/coop/design-corrections';reviews=dc/'reviews';b=reviews/'consumer-b.v4';out=reviews/'codex-post-reset.v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
expected='a49eaa503ff0ceaf2bdcdc017b51937bd1322e0ca7f2bda505bda0537342cec1';assert sha(b/'output/blind-review.json')==expected
assert sha(b/'output/blind-review.md')=='0245bfe77afc489144df2b200e660eb9f23b5bb4fd69a7fa581537e1015b834b'
review=json.loads((b/'output/blind-review.json').read_text());response=json.loads((b/'output/response.json').read_text());custody=json.loads((b/'custody.json').read_text())
assert response['is_error'] is False and response['session_id']=='878e4b39-2d21-46b2-87bd-64f8d4db015f'
assert review['verdict']=='CHANGES_REQUIRED' and len(review['newMustIssues'])==2 and len(review['newShouldIssues'])==2 and len(review['nonBlockingAdvisories'])==4
for row in custody['files']:assert sha(b/row['path'])==row['sha256'] and (b/row['path']).stat().st_size==row['bytes']
assert sha(b/custody['toolBlocks']['path'])==custody['toolBlocks']['sha256']
probe=Path('/tmp/opensip-design-corrections/bv4-original-recheck.v1');target=out/probe.name;assert not target.exists();shutil.copytree(probe,target)
def ref(p):return {'path':str(p.relative_to(root)),'sha256':sha(p)}
record={'standing':'Actual Codex substantive assessment of completed actual-Claude blind Bv4. Required design corrections remain. No successor assent, application, readiness promotion or product qualification.','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'review':ref(b/'output/blind-review.json'),'reviewMarkdown':ref(b/'output/blind-review.md'),'custody':ref(b/'custody.json'),'sessionId':response['session_id'],'parentSubjectSha256':review['inputVerification']['parentSubjectSha256'],'verdict':'CHANGES_REQUIRED','fullReviewRead':{'jsonBytes':21779,'markdownBytes':44081,'scope':'Full structured review and complete Markdown read in bounded sections; exact final hashes match.'},'findings':[
 {'id':'CB4-MUST-1','severity':'MUST','disposition':'CORRECTION-REQUIRED','assessment':'The normative every-anchor selected-grammar wording contradicts unconditional inventory capability. The anchor policy is under-specified. Preserve the blind literal reconstruction as evidence of that ambiguity. Its anchored unsupported-file REFUSE is NOT an observed defect of the current author reference: root fullRun controls on frozen v13 ADMIT anchored file facts for .py, extensionless, Markdown and Rust paths; helper inventory exemption applies at both fact and scope call sites. Correct the contract and explicit relation/class anchor law; do not claim the current model falsely reported an inventoried file absent. Distinct legitimate semantic location descriptors need not be identical; the promise and admissibility must be explicit.'},
 {'id':'CB4-MUST-2','severity':'MUST','disposition':'CORRECTION-REQUIRED','assessment':'Section10 explicitly labels the closed nativeCause field with unresolved-edge, export and derivation values it cannot carry. Existing structured evidence may supply the correct carriers, but their required projection and lawful null/cause pairing must be unambiguous and enforced. A vocabulary-only or blanket-null change is insufficient if mandated disclosure remains absent. Assess multi-cause/precedence and full producer/Run joins.'},
 {'id':'CB4-SHOULD-1','severity':'SHOULD','disposition':'CORRECTION-REQUIRED','assessment':'The normative relation registry languageIdSource points to provider/domain language while the owning body selector correctly derives JavaScript/TypeScript/Rust. Correct the metadata to the same selected anchor/variant law; syntax is not a body language.'},
 {'id':'CB4-SHOULD-2','severity':'SHOULD','disposition':'CORRECTION-REQUIRED','assessment':'The capabilityId field is free Text; current default helper receives trusted release rows and only rejects preview-* while Run closure checks language modes. No exact normative capability vocabulary/selector joins matrix IDs, requested relation/rung spelling and authenticated release declarations. This is a contract authority gap, not proof that a missing kit file is absent from the repository. Publish and enforce the exact authority and retain all advertised modes.'}],
 'advisoryAccount':[
 {'id':'CB4-ADV-1','severity':'ADVISORY','disposition':'Correct stale native prose matrix count in successor; root separately corrects the frozen summary60 versus actual66 recording error before successor freeze. Original accepted v13 evidence remains immutable.'},
 {'id':'CB4-ADV-2','severity':'ADVISORY','disposition':'Reconcile prose domain lists with the complete admitted context/universe registry including syntax. Registry semantics already distinguish all three.'},
 {'id':'CB4-ADV-3','severity':'ADVISORY','disposition':'Publish explicit effect-name/permission-token correspondence with exact scope and current v9 values. Host-state write permission is not itself repository-write authority; retain OS/host enforcement qualification limits.'},
 {'id':'CB4-ADV-4','severity':'ADVISORY','disposition':'Retain the currently unambiguous document-digest parameter key and explicit refusal of an additional row sharing that key. No requirement justifies expanding to a document/selector pair now. Future incompatible extension requires an explicit versioned design correction.'}],
 'originalSourceDiagnostics':[ref(target/'report.json'),ref(target/'helper-rung-correction.json')],
 'diagnosticLimits':'Root-selected cases use existing author reference/fixtures and a broad synthetic snapshot, not independent blind input or product measurements. Original helper package@enumerated/vcs-change@enumerated were invalid-rung controls. Two failed correction attempts confused rungs metadata with the actual ladder; both failed before output. Corrected registry-ladder controls confirm all three inventory capabilities are exempt. Literal reports/attempt account retained.',
 'vectorAccount':{'positive':56,'negative':57,'negativeRefused':57,'verification':11,'verificationHolds':9,'advisoryVectors':2,'gapRecords':8,'meaning':'126 vectors plus8 gap records, NOT126passing tests. The two failed law claims are actual cause/count findings. Complete positive graph claims are constructibility under the blind documented anchor/capability spelling choices, not unconditional conformance.'},
 'limits':review['limitations'],'coauthorWork':{'path':'/tmp/opensip-design-corrections/bv4-corrections-author.v1','sessionId':'77758b10-d7ba-4868-9d42-ae0b13e84cb6','basis':'Captured22interim source/vector files; now supplied exact completed retained review. Separate actual coauthor, no independent acceptance.'},'implementationAuthorized':False,'readinessChanged':False}
p=out/'blind-assessment.v4.json';assert not p.exists();p.write_text(json.dumps(record,indent=2)+'\n')
author=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v1');final=author/'final-blind-input';assert not final.exists();shutil.copytree(b,final)
shutil.copyfile(p,author/'codex-blind-assessment.v4.json');shutil.copytree(target,author/'codex-original-recheck.v1')
note=author/'CODEX-PUBLIC-NOTE.md';assert not note.exists();note.write_text(f'''# Completed Bv4 and Codex assessment — read in full\n\nActual blind session finished successfully. Final review is `final-blind-input/output/blind-review.json`, SHA `{expected}`; Markdown SHA `0245bfe77afc489144df2b200e660eb9f23b5bb4fd69a7fa581537e1015b834b`. Custody retains45exact normative files,77outputs/input files and246public tool blocks. Final verdict CHANGES_REQUIRED,2MUST2SHOULD4ADVISORY, exactly the captured eight finding IDs. Read the full review and `codex-blind-assessment.v4.json`. Actual totals126vectors plus8gaps;9/11law claims hold, not126passing tests.\n\nImportant root distinction for M1: original frozen v13 author reference ALREADY admits whole-file-anchored file facts for `tool/main.py`, `LICENSE`, `README.md`, `src/plain.rs` at full Run closure (see `codex-original-recheck.v1/report.json`). Its inventory exemption precedes selected grammar checks and therefore applies to fact and scope calls. The blind's REFUSE is its independently reconstructed literal interpretation of contradictory normative wording, not an observed actual author-model rejection. Keep the required contract/anchor-policy correction; do not advertise a nonexistent current-model bypass or overstate identity equality for genuinely distinct semantic location descriptors. Three inventory helper valid controls use the registry's `ladder`, NOT the empty per-rung extra-constraint object `rungs`; root's earlier helper wrong-rung and two failed extraction attempts are preserved and corrected in helper-rung-correction.json.\n\nAll other findings/ownership from the launch prompt stand. Correct the coherent public law and actual joins, rather than mechanically accepting a one-sentence remedy. S2 is not a bare missing-input-kit allegation: root inspected the actual helper/Run closure and confirms the authority/spelling must be published. ADV4 is currently unambiguous and explicitly refuses future same-document collisions; preserve that bounded versioned law unless a necessary existing requirement shows otherwise. No new flexibility needed merely to avoid the refusal.\n\nThe previously prepared v13 application is now INELIGIBLE and will not be assembled/applied. Root owns successor records/count correction/fixture integration and pins after source assessment, then fresh independent and NEW blind review. Current readiness is unchanged.\n''')
(author/'final-input-custody.json').write_text(json.dumps({'standing':'Completed actual blind evidence and root assessment added to separate coauthor after interim launch. No active blind contaminated.','review':ref(b/'output/blind-review.json'),'reviewSha256':expected,'codexAssessment':ref(p),'files':[{'path':str(q.relative_to(author)),'sha256':sha(q),'bytes':q.stat().st_size} for base in [final,author/'codex-original-recheck.v1'] for q in sorted(base.rglob('*')) if q.is_file()]},indent=2)+'\n')
print(json.dumps({'assessment':str(p),'coauthorFinalNote':str(note),'verdict':review['verdict'],'required':4,'advisories':4}))
