"""Derive M3-L item 13's provider-wire identity inventory mechanically from the pinned contract bytes.

Control L-C1 of M3-L r4. Nothing here is hand-listed except the frame -> payload selection (FRAMES), which
restates which payload NE section 9 (and section 0's supersessions) selects for each frame, with the line that
says so, and the record identities (SAME_RECORD), each quoting the sentence that makes two published records
one record. Every member, every nested record and every classification is read from the schemas.

Classification (closed). A member is identity-bearing iff one rule holds:
  R1 name      a scalar member whose name ends in Id, Ids, Key, Commitment, Sha256, Digest, Hash, MerkleRoot,
               Closure or Universe;
  R2 designate a member that a contract's machine-readable identity list names, on the payload that list
               governs (provider-handshake x-opensip-wire-law typescriptDescriptorBinding providerDescriptorFields
               and runtimeDescriptorFields on TypeScriptHelloAckV2; rustIdentityBinding identityFields on HelloAckV3
               and on HelloV3.expectedIdentity);
  R3 preimage  the universe descriptor `universe` on OpenUniverse and UniverseAccepted, whose hash is the
               universe coordinate (NE:3161-3163), listed whole and not descended into; and a member whose
               description says its value is a row of that descriptor ("exact rust-v1 row");
  R4 stated    a member whose published description names an identity type of its artifact, or names an
               R1-shaped member as its value or part of it (e.g. "exact providerBuildId", "exact C-2 stageId
               text", "<ordinal>-<planRow.outputDigest>.blob");
  R5 constant  a member whose description fixes exactly the constant that describes an R1 member of the same
               artifact (CoverageKeyV1.producer and StageRequestV1.providerId are both "exact text
               typescript-semantic");
  R6 pattern   a JSON Schema string whose pattern requires a 64-hex digest or a typed identity prefix
               (sha256:, snapshot2:, plan2:, closure2:, scope2:).
Containers are descended into; only leaves (and R3's descriptor) are classified. A description that begins
with a scalar type (SCALAR_START) describes a scalar even when it names a record it is computed over. Opaque
byte strings (chunk bytes, canonicalRelationPayload) are leaves and carry no member-level identity.

Usage:
    python3 evidence/wire_identities.py            # print the report
    python3 evidence/wire_identities.py --write    # write evidence/wire-identities.json and PROPOSAL.md's table
    python3 evidence/wire_identities.py --check    # re-derive and compare with both (the control)
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ARCH = HERE.parents[4]
LAW = HERE.parent / 'PROPOSAL.md'
REPORT = HERE / 'wire-identities.json'
BEGIN, END = '<!-- wire-identities:begin (generated by evidence/wire_identities.py; do not edit) -->', \
             '<!-- wire-identities:end -->'

SRC = {
    'NE': 'docs/v2/contracts/product-v1/native-evidence.md',
    'DLV': 'docs/coop/artifacts/delivery.v2.json',
    'RPP': 'docs/coop/artifacts/rust-provider-protocol.v2.json',
    'FP': 'docs/coop/artifacts/fact-plane.v1.json',
    'C2': 'docs/coop/artifacts/c2-plan-stage-schema.v3.json',
    'HS': 'docs/coop/design-corrections/native/provider-handshake.schemas.v1.json',
    'ST': 'docs/coop/design-corrections/native/provider-startup.schemas.v1.json',
    'REG': 'docs/coop/design-corrections/native/native-evidence.schemas.v2.json',
    'FB3': 'docs/coop/design-corrections/native/fact-batch.schema.v3.json',
    'OC': 'docs/coop/design-corrections/native/occupancy-companion.schema.v1.json',
    'FA2': 'docs/implementation/m3/native-successors-fa/fa-2/design/native/symbol-census.schemas.v1.json',
}

R1_SUFFIXES = ('Id', 'Ids', 'Key', 'Commitment', 'Sha256', 'Digest', 'Hash', 'MerkleRoot', 'Closure', 'Universe')
IDENTITY_TYPES = {
    'DLV': {'DigestHex', 'Sha256Text', 'ExecutionId', 'SnapshotId', 'PlanId', 'PlanIntentCommitment',
            'TypeScriptSemanticUniverseKey'},
    'RPP': {'IdentityText', 'DigestHex', 'Sha256Text', 'SnapshotId', 'PlanId'},
    'FP': set(), 'C2': set(),
}
IDENTITY_PATTERN = re.compile(r'\[0-9a-f\]\{64\}|\^(sha256|snapshot2|plan2|closure2|scope2):')

# Frame -> payload, per protocol. (frame, direction, payload locator, condition, the line that selects it.)
ALWAYS, TA, SC = 'always', 'under target-attribution-v2', 'under symbol-census-v1 (FA-2, proposed)'
FRAMES = {
    'typescript-semantic': [
        ('Hello', 'h→w', ('HS', 'TypeScriptHelloV2'), ALWAYS, 'NE:2955-2960'),
        ('HelloAck', 'w→h', ('HS', 'TypeScriptHelloAckV2'), ALWAYS, 'NE:2968-2981'),
        ('OpenUniverse', 'h→w', ('ST', 'TypeScriptOpenUniverseV2'), ALWAYS, 'NE:3166-3175'),
        ('UniverseAccepted', 'w→h', ('ST', 'TypeScriptUniverseAcceptedV2'), ALWAYS, 'NE:3176-3177'),
        ('SnapshotManifest', 'h→w', ('DLV', 'SnapshotManifestV1'), ALWAYS, 'NE:2994-2996 (normal order); NE:3160-3161'),
        ('SnapshotFileChunk', 'h→w', ('DLV', 'SnapshotFileChunkV1'), ALWAYS, 'NE:2994-2996'),
        ('SnapshotSeal', 'h→w', ('DLV', 'SnapshotSealV1'), ALWAYS, 'NE:2994-2996'),
        ('SnapshotAccepted', 'w→h', ('DLV', 'SnapshotAcceptedV1'), ALWAYS, 'NE:2994-2996'),
        ('NativeContextVerified', 'w→h', ('ST', 'NativeContextVerifiedV1'), ALWAYS, 'NE:2945-2950, NE:2881'),
        ('Unavailable (pre-Analyze)', 'w→h', ('ST', 'PreAnalyzeUnavailableV1'), ALWAYS, 'NE:3205-3207'),
        ('Analyze', 'h→w', ('DLV', 'AnalyzeV1'), ALWAYS, 'NE:2994-2996'),
        ('Analyze', 'h→w', ('FA2', 'TypeScriptAnalyzeV2', 'symbolCensus'), SC, 'FA-2 section 9.8'),
        ('FactBatch', 'w→h', ('DLV', 'FactBatchV1'), ALWAYS, 'NE:2986-2990'),
        ('FactBatch', 'w→h', ('FB3', '#'), TA, 'NE:2986, NE:3061-3069'),
        ('Coverage', 'w→h', ('ST', 'TypeScriptCoverageV2'), ALWAYS, 'NE:3272-3275'),
        ('Unavailable (post-Analyze)', 'w→h', ('ST', 'TypeScriptUnavailableV2'), ALWAYS, 'NE:3288-3292'),
        ('BudgetExhausted', 'w→h', ('ST', 'TypeScriptBudgetExhaustedV2'), ALWAYS, 'NE:3288-3292'),
        ('Complete', 'w→h', ('DLV', 'CompleteV1'), ALWAYS, 'NE:2994-2996; NE:3283-3287'),
        ('Complete', 'w→h', ('FA2', 'TypeScriptCompleteV2', 'symbolCensus'), SC, 'FA-2 section 9.8'),
        ('Cancel', 'h→w', ('DLV', 'CancelV1'), ALWAYS, 'NE:3296-3302'),
        ('Cancelled', 'w→h', ('DLV', 'CancelledV1'), ALWAYS, 'NE:3296-3302'),
    ],
    'rust-semantic': [
        ('Hello', 'h→w', ('HS', 'HelloV3'), ALWAYS, 'NE:2816-2829'),
        ('HelloAck', 'w→h', ('HS', 'HelloAckV3'), ALWAYS, 'NE:2830-2835'),
        ('OpenUniverse', 'h→w', ('ST', 'OpenUniverseV3'), ALWAYS, 'NE:3178-3187'),
        ('UniverseAccepted', 'w→h', ('ST', 'UniverseAcceptedV3'), ALWAYS, 'NE:3188-3189'),
        ('SnapshotManifest', 'h→w', ('RPP', 'SnapshotManifestV2'), ALWAYS, 'NE:2863-2866; NE:3160-3161'),
        ('SnapshotFileChunk', 'h→w', ('RPP', 'SnapshotFileChunkV2'), ALWAYS, 'NE:2863-2866'),
        ('SnapshotSeal', 'h→w', ('RPP', 'SnapshotSealV2'), ALWAYS, 'NE:2863-2866'),
        ('SnapshotAccepted', 'w→h', ('RPP', 'SnapshotAcceptedV2'), ALWAYS, 'NE:2863-2866'),
        ('DependencySourceManifest', 'h→w', ('NE', 'DependencySourceManifest'), ALWAYS, 'NE:2876'),
        ('DependencySourceChunk', 'h→w', ('NE', 'DependencySourceChunk'), ALWAYS, 'NE:2877'),
        ('DependencySourceSeal', 'h→w', ('NE', 'DependencySourceSeal'), ALWAYS, 'NE:2878'),
        ('DependencySourceAccepted', 'w→h', ('NE', 'DependencySourceAccepted'), ALWAYS, 'NE:2879'),
        ('PreparedOutputManifest', 'h→w', ('RPP', 'PreparedOutputManifestV2'), ALWAYS, 'NE:2880'),
        ('PreparedOutputChunk', 'h→w', ('RPP', 'PreparedOutputChunkV2'), ALWAYS, 'NE:2880'),
        ('PreparedOutputSeal', 'h→w', ('RPP', 'PreparedOutputSealV2'), ALWAYS, 'NE:2880'),
        ('PreparedOutputAccepted', 'w→h', ('RPP', 'PreparedOutputAcceptedV2'), ALWAYS, 'NE:2880'),
        ('NativeContextVerified', 'w→h', ('ST', 'NativeContextVerifiedV1'), ALWAYS, 'NE:2881'),
        ('Unavailable (pre-Analyze)', 'w→h', ('ST', 'PreAnalyzeUnavailableV1'), ALWAYS, 'NE:2882'),
        ('Analyze', 'h→w', ('RPP', 'AnalyzeV2'), ALWAYS, 'NE:2863-2866'),
        ('Analyze', 'h→w', ('FA2', 'AnalyzeV3', 'symbolCensus'), SC, 'FA-2 section 9.8'),
        ('FactBatch', 'w→h', ('RPP', 'FactBatchV2'), ALWAYS, 'NE:2883'),
        ('FactBatch', 'w→h', ('FB3', '#'), TA, 'NE:2883'),
        ('CoverageV3', 'w→h', ('ST', 'CoverageV3'), ALWAYS, 'NE:2884'),
        ('Unavailable (post-Analyze)', 'w→h', ('ST', 'UnavailableV3'), ALWAYS, 'NE:2882'),
        ('BudgetExhausted', 'w→h', ('ST', 'BudgetExhaustedV3'), ALWAYS, 'NE:3288-3292'),
        ('Complete', 'w→h', ('RPP', 'CompleteV2'), ALWAYS, 'NE:3283-3287'),
        ('Complete', 'w→h', ('FA2', 'CompleteV3', 'symbolCensus'), SC, 'FA-2 section 9.8'),
        ('ProviderFault', 'w→h', ('RPP', 'ProviderFaultV2'), ALWAYS, 'RPP:441-445'),
        ('Cancel', 'h→w', ('RPP', 'CancelV2'), ALWAYS, 'RPP:447-451'),
        ('Cancelled', 'w→h', ('RPP', 'CancelledV2'), ALWAYS, 'RPP:453-457'),
    ],
}

# Two published records that are one record. Descriptions are read from every member of the group.
SAME_RECORD = {
    'fact-candidate': [('DLV', 'FactCandidateV1'), ('FP', 'candidateSchema')],   # DLV hostJoin: "exactly opensip.fact-candidate.v1"
    'anchor-ref': [('DLV', 'AnchorRefV1'), ('FP', 'anchorSchema')],              # DLV AnchorRefV1.join: opensip.anchor-ref.v1
    'c2-coverage-key': [('DLV', 'CoverageKeyV1'), ('C2', 'coverageKey.key')],    # DLV CoverageKeyV1.join; RPP CoverageKeyV2.external
}
# A record whose members are another record's, read with that record's descriptions too. Routing never goes the other
# way: a DLV StageRequestV1 keeps its own members.
DESC_GROUP = {
    'c2-stage': [('C2', 'stage.fact-derivation'), ('DLV', 'StageRequestV1')],    # DLV ordering: "stageId/operator/providerId/relations are copied exactly"
}
# Nested members the inherited prose types by id, or with no array word: (target record, is an array).
CHILD = {
    ('DLV', 'FactCandidateV1', 'anchors'): ('anchor-ref', True),            # "array implementing opensip.anchor-ref.v1"
    ('FP', 'candidateSchema', 'anchors'): ('anchor-ref', True),             # "array of opensip.anchor-ref.v1"
    ('RPP', 'FactBatchV2', 'candidates'): ('fact-candidate', True),         # "recursively validated FactCandidateV1 array"
    ('RPP', 'CompleteV2', 'stageResults'): (('RPP', 'StageResultV2'), True),  # "exact one StageResultV2 per Analyze stage"
    ('RPP', 'StageRequestV2', 'planStage'): ('c2-stage', False),            # C2PlanStageV3 external
    ('RPP', 'StageRequestV2', 'analysisDomain'): (('RPP', 'StageAnalysisDomainV2'), False),
    ('RPP', 'StageAnalysisDomainV2', 'subjects'): (('RPP', 'SubjectV2'), True),          # subjectsAlgorithm, RPP:226-231
    ('RPP', 'StageAnalysisDomainV2', 'requestedCoverageDomain'): ('c2-coverage-key', True),  # coverageDomainAlgorithm, RPP:233-239
}
# A description that begins with a scalar type describes a scalar, even when it names a record it is computed over.
SCALAR_START = re.compile(r'^(uint64|Sha256Text|DigestHex|IdentityText|enum |exact text|text matching|non-empty NFC|'
                          r'boolean|non-empty byte string|exact byte string|one manifest file path)')
# R3 also covers a row copied from the universe descriptor (its value is part of the universe preimage).
UNIVERSE_ROW = re.compile(r'^(exact |complete external )?(rust-v1|typescript-v1|RustUniverseV1|TypeScriptSemanticUniverseV1)\b')
FB3_VECTOR_ONLY = {'canonicalRelationPayloadHex', 'decodedRelationPayload'}  # NE:3077-3082: not wire members


def load(key):
    raw = (ARCH / SRC[key]).read_bytes()
    return raw, raw.decode('utf-8')


def line_of(key, needle, start=1):
    text = load(key)[1].split('\n')
    for n in range(start - 1, len(text)):
        if needle in text[n]:
            return n + 1
    raise SystemExit(f'{key}: cannot find {needle!r}')


class Sources:
    def __init__(self):
        self.json = {k: json.loads(load(k)[1]) for k in SRC if k != 'NE'}
        dlv = self.json['DLV']['typescriptSemanticSubstrate']['providerProtocol']['wireSchema']
        records = lambda *ds: {k: v for d in ds for k, v in d.items() if isinstance(v, dict)}
        self.closed = {'DLV': records(dlv['definitions'], dlv['payloadSchemas']),
                       'RPP': records(self.json['RPP']['wireSchema']['definitions'],
                                      self.json['RPP']['wireSchema']['payloadSchemas'])}
        fp = self.json['FP']['factRecordContractV1']
        self.closed['FP'] = {'candidateSchema': fp['candidateSchema'], 'anchorSchema': fp['anchorSchema']}
        c2 = self.json['C2']
        self.closed['C2'] = {
            'coverageKey.key': {'required': [e['field'] for e in c2['coverageKey']['key']],
                                'fields': {e['field']: e.get('constraint', '') for e in c2['coverageKey']['key']}},
            'stage.fact-derivation': {
                'required': c2['stageSchemas']['common']['required'] + c2['stageSchemas']['kinds']['fact-derivation']['required'],
                'optional': c2['stageSchemas']['common']['optional'] + c2['stageSchemas']['kinds']['fact-derivation']['optional'],
                'fields': {}}}
        hs = self.json['HS']['x-opensip-wire-law']
        ts = hs['typescriptDescriptorBinding']
        self.designated = {
            ('HS', 'TypeScriptHelloAckV2'): set(ts['providerDescriptorFields']) | set(ts['runtimeDescriptorFields']),
            ('HS', 'HelloAckV3'): set(hs['rustIdentityBinding']['identityFields']),
            ('HS', 'ExpectedRustIdentityV3'): set(hs['rustIdentityBinding']['identityFields']),
        }
        self.ne = load('NE')[1].split('\n')

    # ---- closed (prose) records -------------------------------------------------------------------
    def closed_members(self, art, name):
        rec = self.closed[art][name]
        members = list(rec.get('required') or []) + list(rec.get('optional') or [])
        fields = rec.get('fields') or {}
        return [(m, [str(fields.get(m) or fields.get('all') or '')]) for m in members]

    def group_desc(self, group, member):
        out = []
        for art, name in {**SAME_RECORD, **DESC_GROUP}[group]:
            for m, d in self.closed_members(art, name):
                if m == member:
                    out += [(art, x) for x in d if x]
        return out

    def group_members(self, group):
        art, name = {**SAME_RECORD, **DESC_GROUP}[group][0]
        return [m for m, _ in self.closed_members(art, name)]

    def constants_of_r1(self, art):
        """Descriptions that describe an R1 member of the artifact, for R5."""
        out = set()
        for name in self.closed.get(art, {}):
            for m, d in self.closed_members(art, name):
                if is_r1(m) and d[0].startswith('exact text '):
                    out.add(d[0])
        return out


def is_r1(name):
    return name.endswith(R1_SUFFIXES)


def r4(art, desc):
    tokens = set(re.findall(r'[A-Za-z][A-Za-z0-9]*', desc))
    if tokens & IDENTITY_TYPES.get(art, set()):
        return True
    return any(is_r1(t) and t[0].islower() for t in tokens)


class Walker:
    def __init__(self, s: Sources):
        self.s = s
        self.r5 = {art: s.constants_of_r1(art) for art in ('DLV', 'RPP')}

    def classify_prose(self, member, descs, designated=False):
        if designated:
            return 'R2'
        if is_r1(member):
            return 'R1'
        for art, d in descs:
            if r4(art, d):
                return 'R4'
        for art, d in descs:
            if d in self.r5.get(art, set()):
                return 'R5'
        return None

    def child_of(self, art, rec, member, desc):
        """(target record, is_array) for a nested record member, else None."""
        key = (art, rec, member)
        if key in CHILD:
            return CHILD[key]
        if SCALAR_START.match(desc):
            return None
        for n in re.findall(r'[A-Za-z][A-Za-z0-9]*', desc):
            if n != rec and isinstance(self.s.closed.get(art, {}).get(n), dict) and self.s.closed[art][n].get('required'):
                target = next((g for g, recs in SAME_RECORD.items() if (art, n) in recs), (art, n))
                return target, 'array' in desc
        return None

    def classify_leaf(self, art, member, descs, designated):
        if any(UNIVERSE_ROW.match(d) for _, d in descs):
            return 'R3'
        return self.classify_prose(member, descs, designated)

    def walk_closed(self, art, rec, prefix, out, designated=frozenset(), seen=()):
        for member, d in self.s.closed_members(art, rec):
            path = prefix + member
            child = self.child_of(art, rec, member, d[0])
            if child is not None and child[0] not in seen:
                self.walk_child(child[0], path + ('[].' if child[1] else '.'), out, seen + (child[0],))
                continue
            out.append((path, self.classify_leaf(art, member, [(art, x) for x in d], member in designated)))

    def walk_child(self, child, prefix, out, seen):
        if isinstance(child, tuple):
            self.walk_closed(child[0], child[1], prefix, out, self.s.designated.get(child, frozenset()), seen)
            return
        for member in self.s.group_members(child):
            descs = self.s.group_desc(child, member)
            sub = next((CHILD[(a, n, member)] for a, n in {**SAME_RECORD, **DESC_GROUP}[child] if (a, n, member) in CHILD), None)
            if sub is not None and sub[0] not in seen:
                self.walk_child(sub[0], prefix + member + ('[].' if sub[1] else '.'), out, seen + (sub[0],))
                continue
            out.append((prefix + member, self.classify_leaf(None, member, descs, False)))

    # ---- JSON Schema records ------------------------------------------------------------------------
    def resolve(self, doc_key, schema):
        while '$ref' in schema:
            ref = schema['$ref']
            if ref.startswith('#/'):
                doc = self.s.json[doc_key]
            elif ref.startswith('urn:opensip:product-v1:native:evidence-schemas:v2#'):
                doc_key, doc, ref = 'REG', self.s.json['REG'], ref.split('#', 1)[1] and '#' + ref.split('#', 1)[1]
            elif ref == 'opensip.product.occupancy-companion.1':
                return 'OC', self.s.json['OC']
            else:
                raise SystemExit(f'unresolved $ref {ref}')
            node = doc
            for part in ref[2:].split('/'):
                node = node[part]
            schema = {**node, **{k: v for k, v in schema.items() if k != '$ref'}}
        return doc_key, schema

    def walk_json(self, doc_key, schema, prefix, out, payload_key, depth=0):
        doc_key, schema = self.resolve(doc_key, schema)
        if depth > 12:
            raise SystemExit('schema too deep')
        branches = schema.get('oneOf') or schema.get('anyOf')
        if branches:
            sub = []
            for b in branches:
                self.walk_json(doc_key, b, prefix, sub, payload_key, depth + 1)
            seen = set()
            for path, rule in sub:
                if path not in seen:
                    seen.add(path)
                    out.append((path, rule))
            return
        props = schema.get('properties')
        if props is not None:
            designated = self.s.designated.get(payload_key, set())
            for member, sub in props.items():
                if payload_key == ('FB3', '#') and member == 'candidates':
                    # NE:2883: "Candidates remain closed FactCandidateV1"
                    self.walk_child('fact-candidate', prefix + 'candidates[].', out, ('fact-candidate',))
                    continue
                if member in FB3_VECTOR_ONLY:
                    continue
                path = prefix + member
                if member == 'universe' and prefix == '' and payload_key[1] in (
                        'TypeScriptOpenUniverseV2', 'TypeScriptUniverseAcceptedV2', 'OpenUniverseV3', 'UniverseAcceptedV3'):
                    out.append((path, 'R3'))
                    continue
                sub_key = payload_key
                if member == 'expectedIdentity':
                    sub_key = ('HS', 'ExpectedRustIdentityV3')
                k2, s2 = self.resolve(doc_key, sub)
                if self.container(k2, s2):
                    self.walk_json(doc_key, sub, path + ('[].' if self.arrayish(k2, s2) else '.'), out, sub_key, depth + 1)
                    continue
                if member in designated:
                    out.append((path, 'R2'))
                elif is_r1(member):
                    out.append((path, 'R1'))
                elif self.patterned(k2, s2):
                    out.append((path, 'R6'))
                else:
                    out.append((path, None))
            return
        if schema.get('type') == 'array' and isinstance(schema.get('items'), dict):
            self.walk_json(doc_key, schema['items'], prefix, out, payload_key, depth + 1)
            return

    def container(self, doc_key, schema):
        doc_key, schema = self.resolve(doc_key, schema)
        if schema.get('properties') is not None:
            return True
        if schema.get('type') == 'array' and isinstance(schema.get('items'), dict):
            return self.container(doc_key, schema['items'])
        for b in schema.get('oneOf') or schema.get('anyOf') or []:
            if self.container(doc_key, b):
                return True
        return False

    def arrayish(self, doc_key, schema):
        doc_key, schema = self.resolve(doc_key, schema)
        if schema.get('type') == 'array':
            return True
        return any(self.arrayish(doc_key, b) for b in schema.get('oneOf') or schema.get('anyOf') or [])

    def patterned(self, doc_key, schema):
        doc_key, schema = self.resolve(doc_key, schema)
        if isinstance(schema.get('pattern'), str) and IDENTITY_PATTERN.search(schema['pattern']):
            return True
        return any(self.patterned(doc_key, b) for b in schema.get('oneOf') or schema.get('anyOf') or []
                   if isinstance(b, dict))

    # ---- NE section 9.2 table rows -------------------------------------------------------------------
    def walk_ne_row(self, frame, out):
        row = next(l for l in self.s.ne if l.startswith(f'| `{frame}` |'))
        cell = row.split('|')[3]
        if 'exact seal echo' in cell:
            row = next(l for l in self.s.ne if l.startswith('| `DependencySourceSeal` |'))
            cell = row.split('|')[3]
        body = re.search(r'\{(.*)\}', cell).group(1)
        depth, name, members = 0, '', []
        for ch in body + ',':
            if ch in '[{':
                depth += 1
            if ch in ']}':
                depth -= 1
            if ch == ',' and depth == 0:
                members.append(name.strip())
                name = ''
            else:
                name += ch
        for m in members:
            nested = re.match(r'(\w+)\[\{(.*)\}\]', m)
            if nested:
                for sub in nested.group(2).split(','):
                    sub = sub.strip()
                    out.append((f'{nested.group(1)}[].{sub}', 'R1' if is_r1(sub) else None))
            else:
                out.append((m, 'R1' if is_r1(m) else None))


def payload_line(locator):
    art, name = locator[0], locator[1]
    if art == 'NE':
        return 'NE:' + str(line_of('NE', f'| `{name}` |'))
    if art in ('DLV', 'RPP'):
        return f'{art}:' + str(line_of(art, f'"{name}": {{'))
    if art == 'FB3':
        return 'FB3:1'
    return f'{art}:' + str(line_of(art, f'"{name}": {{'))


def derive():
    s = Sources()
    w = Walker(s)
    report = {}
    for proto, frames in FRAMES.items():
        rows = []
        for frame, direction, loc, cond, selected_by in frames:
            out = []
            art, name = loc[0], loc[1]
            if art in ('DLV', 'RPP'):
                w.walk_closed(art, name, '', out, s.designated.get(loc[:2], frozenset()))
            elif art == 'NE':
                w.walk_ne_row(name, out)
            else:
                schema = s.json[art] if name == '#' else s.json[art]['$defs'][name]
                if len(loc) == 3:   # FA-2: only the member FA-2 adds
                    schema = {'properties': {loc[2]: schema['properties'][loc[2]]}}
                w.walk_json(art, schema, '', out, loc[:2])
            ident = [{'member': p, 'rule': r} for p, r in out if r]
            idset = {p for p, r in out if r}
            tops = []
            for p, r in out:
                top = re.split(r'[.\[]', p)[0]
                if top not in tops:
                    tops.append(top)
            other = [t for t in tops if not any(re.split(r'[.\[]', p)[0] == t for p in idset)]
            rows.append({'frame': frame, 'direction': direction, 'payload': name if name != '#' else 'FactBatchV3',
                         'source': payload_line(loc), 'condition': cond, 'selectedBy': selected_by,
                         'identityBearing': ident, 'otherTopLevelMembers': other})
        report[proto] = rows
    pins = {k: {'path': v, 'sha256': hashlib.sha256((ARCH / v).read_bytes()).hexdigest()} for k, v in SRC.items()}
    return {'standing': 'Generated by evidence/wire_identities.py (M3-L r4, control L-C1). Do not edit.',
            'rules': {'R1': 'name ends in ' + ', '.join(R1_SUFFIXES), 'R2': 'contract identity list',
                      'R3': 'universe descriptor (preimage of the universe coordinate)',
                      'R4': 'description names an identity type or an identity member as the value',
                      'R5': 'description fixes the constant of an R1 member', 'R6': 'identity pattern'},
            'sources': pins, 'protocols': report}


def render(report):
    lines = [BEGIN, '']
    names = {'typescript-semantic': 'TS2 (`typescript-semantic` major 2)', 'rust-semantic': 'Rust3 (`rust-semantic` major 3)'}
    for proto, rows in report['protocols'].items():
        lines += [f'**{names[proto]}**', '',
                  '| Frame | Payload (source line) | When | Identity-bearing members (rule) | Top-level members with no identity at any depth |',
                  '|---|---|---|---|---|']
        for r in rows:
            ids = '; '.join(f"`{m['member']}` ({m['rule']})" for m in r['identityBearing']) or '—'
            other = ', '.join(f'`{m}`' for m in r['otherTopLevelMembers']) or '—'
            lines.append(f"| {r['frame']} ({r['direction']}) | `{r['payload']}` ({r['source']}) | {r['condition']} | {ids} | {other} |")
        lines.append('')
    lines.append(END)
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true')
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    report = derive()
    raw = (json.dumps(report, indent=2, ensure_ascii=False) + '\n').encode('utf-8')
    table = render(report)
    law = LAW.read_text(encoding='utf-8')
    if args.write:
        REPORT.write_bytes(raw)
        if BEGIN in law:
            head, rest = law.split(BEGIN, 1)
            tail = rest.split(END, 1)[1]
            LAW.write_text(head + table + tail, encoding='utf-8')
        print('written')
    elif args.check:
        bad = []
        if REPORT.read_bytes() != raw:
            bad.append(str(REPORT))
        if BEGIN not in law or (BEGIN + law.split(BEGIN, 1)[1].split(END, 1)[0] + END) != table:
            bad.append(str(LAW) + ' (generated table)')
        if bad:
            raise SystemExit('L-C1 FAILED: differs from the schemas: ' + ', '.join(bad))
        print('L-C1 OK: item 13 equals the inventory derived from the pinned schemas')
    else:
        print(table)


if __name__ == '__main__':
    main()
