from pathlib import Path
import hashlib,json
B=Path('/tmp/opensip-design-corrections');L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews');O=B/'claude-independent-design.v35';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not O.exists();assert json.loads((B/'claude-independent-design.v34/process-completion.json').read_bytes())['exitCode']==0
mf=L/'candidate-subject.v35.json';m=json.loads(mf.read_bytes());c=json.loads((B/'root-final35-custody.v1/verification.json').read_bytes());assert c['manifestSha256']==sha(mf) and c['archiveEveryMemberVerified']
p=B/'claude-independent-design.v34/review.json';assert sha(p)=='c31f1c4779b8fa60385520009c73139d46572b29a7f22f251c5a0182a2a42bb3'
package=B/'claude-author-package-successor.v12';verification=B/'author-package-final35-verification.v1/verification.json';assert verification.is_file()
O.mkdir();(O/'root-delta34-to35.json').write_text(json.dumps({'standing':'Inventory only; independently verify','files':c['delta']},indent=2)+'\n')
obligations=(B/'root-source35-preparation.v1/independent35-review-obligations.md').read_text()
prompt=f"""Continue SAME independent reviewer ce3dec3b-0620-44ec-86e6-129b0e25cb1b, actual Claude, who has authored no source. Your COMPLETE34 verdict is CHANGES_REQUIRED; assess the exact newly frozen successor35. Never edit source, prior evidence or live repo. Write only THIS runtime. No other agents, product, activation, commit or push.

SUBJECT: {mf} SHA {sha(mf)}; archive {L/'candidate-source.v35.tar.gz'} SHA {sha(L/'candidate-source.v35.tar.gz')}; snapshot {m['snapshotRoot']}, {m['fileCount']} files/{m['totalBytes']} bytes. Parent34 manifest SHA {m['parentManifestSha256']}. Verify full source/archive/parent custody and independently derive delta. Root inventory is not an acceptance oracle.

BASELINE: complete claude-independent-design.v34/review.json SHA {sha(p)} and review.md SHA {sha(B/'claude-independent-design.v34/review.md')}. Preserve ALL107 individually reasoned rows and actual past read history; baseline is34 CHANGES_REQUIRED, not older33 acceptance. All current dispositions, corrected count91 inherited/11F reverified/5 cross-owner and all nine explicit legacy-read corrections must remain accurately scoped to the current bytes. Inherit unchanged reads only with exact current hash verification; report current changed owner arrays from actual manifests. Do not cosmetically rerun unchanged probes or rewrite historical reasoning, but assess whole-design cross-owner consequences of every substantive changed file.

REVIEW OBLIGATIONS (preparation wording below refers to previously future35; the exact frozen subject above is now current):
{obligations}

SUPPLEMENTAL EVIDENCE, nonblind authorship only: retained claude-incoming-binding-author.v1 complete public report/probes, root-incoming-binding-author-delta.v1, root-incoming-binding-prose-completion.v1, root-final35-pre-freeze.v1 and root-final35-custody.v1. Root bounded assessment is NOT whole-design assent. Root's own initial refusal-code and guard-shape assumptions failed before source writes/freeze and are preserved, not model defects. Final root bytes require your substantive review, including incoming-search.schema owner metadata not authored by the source author.

REFERENCE: root-final35-reference.v1 actual six-group receipt and16 child reports, codex-post-reset.v1/final-reference.v35 bound receipts, root-final35-planning-checks.v1. Independently execute meaningful affected checks and justified regressions; source-pinned helper PASS is no proof of reachable strong Run or qualified product behavior. Planning layer4 exact29 input bytes should be verified, not automatically version-bumped.

AUTHOR PACKAGE: {package}, artifact manifest SHA {sha(package/'artifact-manifest.json')}; root actual verification {verification} SHA {sha(verification)}. Verify all13 exact Run/control outcomes through BOTH open_run_closure and close_run, then7queries on current35. Construction mixed33TS/30normalized-Rust; no export remint in12, no relabelled historical execution. Preserve A9 repair boundary, A10 partial helper/operators/bindings, A11 and scoped A12 evidence; substantively reassess current consequences. Source author is not an eligible independent acceptor. No blind material is supplied or may be read.

OUTPUT: complete review.md and review.json, verifiedManifest/current SHA/verdict/newMustIssues/newShouldIssues/advisories and measured evidence; ALL107 rows in14F,30evaluationResidualDispositions,16arDispositions,15fwDispositions,27inheritedResidualDispositions,5scopedReviewOwnerDispositions. Include explicit MUST-34-01 and A12 closure or concrete remaining issue. Keep accurate scope and inherited source reading on every row. All28condition2,32productgates,54unexecutedrecoverycases,TCB13 joint consequence,D9DR007/DR011R08 remain. Every row grants no final application outcome: appliedByThisReview=false/finalApplicationOutcomeGranted=false. No readiness or product qualification. Finish substantive review, not progress-only handoff unless actual external blocker. Use /tmp/opensip-architecture-review-env/bin/python -I -B.
"""
(O/'prompt.md').write_text(prompt)
template=(B/'claude-independent-design.v34/launch.py').read_text();start=template.index('cmd=');end=template.index('\nstart=time.time()',start)
cmd=['/Users/sb/.local/bin/claude','--safe-mode','--strict-mcp-config','--model','opus','--resume','ce3dec3b-0620-44ec-86e6-129b0e25cb1b','--permission-mode','dontAsk','--tools','Read,Glob,Grep,Bash,Write,Edit','--allowedTools','Read','Glob','Grep','Write','Edit','Bash(python3 *)','Bash(/tmp/opensip-architecture-review-env/bin/python *)']
for d in [Path(m['snapshotRoot']),B/'claude-independent-design.v34',package,B/'author-package-final35-verification.v1',B/'root-final35-reference.v1',B/'root-final35-planning-checks.v1',L,Path('/tmp/opensip-architecture-review-env')]:cmd+=['--add-dir',str(d)]
cmd+=['--output-format','stream-json','--verbose','-p'];(O/'launch.py').write_text(template[:start]+'cmd='+repr(cmd)+template[end:]);(O/'dispatch.json').write_text(json.dumps({'standing':'Prepared only; process/init needed to prove launch. No acceptance.','sessionId':'ce3dec3b-0620-44ec-86e6-129b0e25cb1b','manifestSha256':sha(mf),'promptSha256':sha(O/'prompt.md'),'baselineReviewSha256':sha(p),'packageManifestSha256':sha(package/'artifact-manifest.json'),'actualPackageVerificationSha256':sha(verification)},indent=2)+'\n');print('Prepared independent35',sha(O/'prompt.md'))
