from pathlib import Path
import json,hashlib,shutil
B=Path('/tmp/opensip-design-corrections');L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews');old=B/'claude-author-package-successor.v11';out=B/'claude-author-package-successor.v12';mf=L/'candidate-subject.v35.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not out.exists();m=json.loads(mf.read_bytes());h=sha(mf);S=Path(m['snapshotRoot']);members={r['path']:r for r in m['files']}
pm=json.loads((old/'artifact-manifest.json').read_bytes())
for row in pm['files']:assert sha(old/row['path'])==row['sha256'] and (old/row['path']).stat().st_size==row['bytes']
assert sha(S/'docs/coop/design-corrections/native/native-evidence.schemas.v2.json')==json.loads((old/'source-rebuild.v1.json').read_bytes())['nativeSchemaSha256']
shutil.copytree(old,out,ignore=shutil.ignore_patterns('__pycache__'));H=out/'historical-source34-before-binding35';H.mkdir()
for n in ['source-manifest.json','artifact-manifest.json','README.md','verify-package.py','evaluation-residual-author-assessment.json']:shutil.copy2(out/n,H/n)
(out/'source-manifest.json').write_bytes(mf.read_bytes());p=out/'verify-package.py';s=p.read_text();assert s.count(sha(old/'source-manifest.json'))==1;p.write_text(s.replace(sha(old/'source-manifest.json'),h))
p=out/'evaluation-residual-author-assessment.json';j=json.loads(p.read_bytes());j['subjectManifestSha256']=h;j['standing']='Source35-bound author proposal only; all independent grades PENDING. No historical repair, application or qualification.'
for row in j['items']:
 assert row['independentGrade']=='PENDING'
 for r in row['evidence']:
  before=r['sha256'];r.update(previousSha256=before,sha256=members[r['path']]['sha256'],resolveAgainst='frozen candidate35',currentIndependentAssessment='PENDING',sourceBytesChanged=before!=members[r['path']]['sha256'])
j['sourceSha256']=members[j['source']]['sha256'];p.write_text(json.dumps(j,indent=2)+'\n')
(out/'source-binding.v35.json').write_text(json.dumps({'standing':'Current source35 binding only of exact package11 mixed-provenance exports. Actual source35 full replay and query verification remain required. No historical execution is relabelled.','sourceManifestSha256':h,'parentPackageManifestSha256':sha(old/'artifact-manifest.json'),'constructionAccounts':['source33-remint.v1.json','source-rebuild.v1.json'],'constructionSourceVersion':{'typescriptDerivedGroups':33,'normalizedAndRustGroups':30},'currentVerificationSourceVersion':35,'exportsChanged':False,'productQualification':False},indent=2)+'\n')
(out/'README.md').write_text("# Source35 author reference package (v12) — current verification pending\n\nExact package11 exports are rebound to source35. TypeScript-derived groups retain their source33 constructions; normalized/Rust groups retain source30 constructions. source-binding.v35.json distinguishes current binding from historical construction receipts. No remint occurred in this preparation.\n\nRun verify-package.py with the reference interpreter -I -B, --source <frozen-source35> and --out <new-external-output> for all13 structural/full semantic closures and7 query checks. An actual current replay is required; rebinding alone proves no conformance.\n\nOnly the TypeScript checkpoint compares a partial consumer helper with the owner; six positives are owner-derived/replayed self-consistency. Helper exercises exists/none; and/or/not are unexercised, count-at-most/all-covered unimplemented. Two-binding construction is incomplete with a single explicit binding. No compiler/provider/OS/process-isolation qualification. All30 independent residual grades remain PENDING. This author evidence must never be supplied to the blind consumer. Historical source34 README remains under historical-source34-before-binding35.\n")
for group in ['checkpoint3','normalized-examples6','rust-selection-examples1','semantic-controls1','binding-controls']:
 for p in (old/group).rglob('*'):
  if p.is_file():assert (out/p.relative_to(old)).read_bytes()==p.read_bytes()
rows=[{'path':p.relative_to(out).as_posix(),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(out.rglob('*')) if p.is_file() and p!=out/'artifact-manifest.json'];(out/'artifact-manifest.json').write_text(json.dumps({'standing':'Source35-bound author reference evidence; actual verification and independent review pending.','sourceManifestSha256':h,'files':rows},indent=2)+'\n');print(json.dumps({'files':len(rows),'artifactManifestSha256':sha(out/'artifact-manifest.json'),'sourceManifestSha256':h}))
