from pathlib import Path
import json,hashlib,re,shutil
r=Path.cwd();dc=r/'docs/coop/design-corrections';src=dc/'reviews/cycle-wording-author.v1';sha=lambda b:hashlib.sha256(b).hexdigest()
a=json.loads((src/'assessment.json').read_text());response=json.loads((src/'response.json').read_text());assert response['is_error'] is False and a['agrees'] is True and a['refinementProposed'] is True
p=r/a['placement']['file'];before=p.read_bytes();assert sha(before)==a['placement']['fileSha256']
info=a['placement']['exactReplacementBlocks']['refinedSentence'];old=b'\n'.join(before.split(b'\n')[581:586])+b'\n';assert len(old)==info['originalBytes'] and sha(old)==info['originalSha256']
blocks=re.findall(r'```\n(.*?)\n```',(src/'assessment.md').read_text(),re.S);matches=[(b+'\n').encode() for b in blocks if sha((b+'\n').encode())==info['replacementSha256']];assert len(matches)==1;new=matches[0];assert len(new)==info['replacementBytes']
sentence=a['refinement']['proposedAlternative'];assert len(sentence.encode())==a['refinement']['proposedAlternativeBytes'] and sha(sentence.encode())==a['refinement']['proposedAlternativeSha256']
# Formatting is explicit: Claude's exact assessed replacement rewraps one existing long line.
normal=lambda b:' '.join(b.decode().split())
assert normal(new).replace(sentence+' ','')==normal(old),'Unexpected semantic change beyond the assessed sentence'
assert before.count(old)==1;after=before.replace(old,new,1);assert len(after)-len(before)==82
out=dc/'reviews/codex-post-reset.v1/cycle-normative-clarification.v12';assert not out.exists();out.mkdir()
for name,data in [('before.md',before),('after.md',after),('original-block.md',old),('claude-assessed-replacement.md',new),('selected-sentence.md',(sentence+'\n').encode())]:(out/name).write_bytes(data)
record={'standing':'Codex adopts the exact alternative and replacement block proposed and assessed by actual Claude. This is mutual coauthor wording assessment, not independent acceptance.','actualCoauthorSession':response['session_id'],'assessment':{'path':str((src/'assessment.json').relative_to(r)),'sha256':sha((src/'assessment.json').read_bytes())},'path':str(p.relative_to(r)),'beforeSha256':sha(before),'afterSha256':sha(after),'selectedSentence':sentence,'sentenceSha256':sha(sentence.encode()),'replacementBlockSha256':sha(new),'byteDelta':82,'formattingDecision':'Explicitly accepts Claude-proposed local rewrap of the existing paragraph, including its pre-existing 105-character line. Whitespace-normalized original prose is unchanged after removal of the one added sentence.','codexAssessment':'I agree the refined sentence expresses termination despite a cycle, without suggesting that discovering a cycle stops the whole traversal. Existing per-occurrence coverage and visit-order rules still apply. Both chain guards and the seven bounded coauthor controls support this wording. No complexity bound, schema feature or new admission cause is introduced.','limitation':'The coauthor read the then-current v11 findings while that independent review finalized; it did not claim to read the completed independent verdict. Termination does not prove a work-complexity bound.','implementationAuthorized':False}
(out/'custody.json').write_text(json.dumps(record,indent=2)+'\n');shutil.copyfile(__file__,out/'apply.py');p.write_bytes(after);assert sha(p.read_bytes())==record['afterSha256'];print('Applied exact Claude-assessed491-byte replacement (+82bytes), preserving full before/after and original proposal history.')
