fsx,dx,fx=base_fs()
fsx[R+"/packages"]=dx(); fsx[R+"/packages/web"]=dx(); fsx[R+"/packages/web/package.json"]=fx()
fsx[R+"/packages/web/node_modules"]=dx(); fsx[R+"/packages/web/node_modules/dep"]=dx()
fsx[R+"/packages/web/node_modules/dep/package.json"]=fx()
fsx[R+"/vendorish"]=dx(); fsx[R+"/vendorish/.hg"]=dx()
ox=disc(fsx); inv=S.boundary_inventory(ox)
nd=N.discover_units(markers_of(fsx), None, inv)
adm=sorted((t["path"],t["reason"]) for t in inv["prunedTrees"])
car=sorted((t["path"],t["reason"]) for t in nd["prunedTrees"])
ok6 = nd["refused"] is None and car==adm and (("vendorish/.hg","vcs-tree") in car)
rec("C6 extra admitted anchor accepted and carried", adm, car, ok6, "vendorish/.hg holds no marker so native cannot derive it")
