"""Synthetic host builder for the Rust-universe Runs (phase 5: mixed package/target editions, body dialect, same file under
two selections, '#' marker directory, large edition map, version components, stable body identity on an ownership
change, partial enumeration with empty clones; candidate 16 asymmetry; Rust input controls).

Native evidence is authored as synthetic trusted observation over independently chosen bytes; every evaluator output is
computed by ref/execinputs.py + ref/evaluator.py. Usage: builders/rust_runs.py <variant>[~<mutation>] ...
"""
import hashlib
import json
import os
import sys

OUT = "/private/tmp/opensip-design-corrections/consumer-b.v24-source43.v1/output/preserved/pre-s42"
sys.path.insert(0, OUT + "/ref")
sys.path.insert(0, OUT + "/builders")

import canonical as K  # noqa: E402
import enumeration as EN  # noqa: E402
import evaluator as EV  # noqa: E402
import execinputs as XI  # noqa: E402
import membership as M  # noqa: E402
import native_ctx as NC  # noqa: E402
import native_facts as NF  # noqa: E402
import schemas  # noqa: E402
from store import Store  # noqa: E402
import source39 as S39  # noqa: E402
from syntax_runs import closure, ckey, sfx  # noqa: E402

KIT = schemas.kit()
ID = "foundation/identity-schemas.v3.json"
NE = "native/native-evidence.schemas.v2.json"
REL = "foundation/relation-payload-schemas.v2.json"
ENUM_DOC = "foundation/enumeration-plan.schema.v1.json"
EMIT_DOC = "foundation/evaluator-emission-plan.schema.v1.json"
CAP_MANIFEST_ID = "742a997a708fce51c354ab414e2f69fd7425ee4884eb4e19378431ead4506408"
TRIPLE = "x86_64-unknown-linux-gnu"

FILES = {
    "Cargo.toml": b"[workspace]\nmembers = [\"crates/a\", \"crates/#b\"]\nresolver = \"2\"\n",
    "Cargo.lock": b"# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"a\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"b\"\nversion = \"0.2.0-alpha.1+build.5\"\n",
    "crates/a/Cargo.toml": b"[package]\nname = \"a\"\nversion = \"0.1.0\"\nedition = \"2018\"\n\n[[bin]]\nname = \"tool\"\npath = \"src/bin/tool.rs\"\nedition = \"2021\"\n\n[[test]]\nname = \"it\"\npath = \"src/common.rs\"\nedition = \"2021\"\n",
    "crates/a/src/lib.rs": b"pub mod common;\npub fn shared() -> u32 {\n    7\n}\n",
    "crates/a/src/common.rs": b"pub fn helper() -> u8 {\n    1\n}\n",
    "crates/a/src/bin/tool.rs": b"fn main() {\n    println!(\"{}\", a::shared());\n}\n",
    "crates/#b/Cargo.toml": b"[package]\nname = \"b\"\nversion = \"0.2.0-alpha.1+build.5\"\nedition = \"2024\"\n",
    "crates/#b/src/lib.rs": b"pub fn shared() -> u32 {\n    7\n}\n",
}
FUNCS = [("crates/a/src/lib.rs", "shared"), ("crates/a/src/common.rs", "helper"), ("crates/a/src/bin/tool.rs", "main"), ("crates/#b/src/lib.rs", "shared")]
UNIT_DEFS = {  # key: (markerPath, crateName, targetKind, targetName, targetEdition, owned paths)
    "lib_a": ("crates/a/Cargo.toml", "a", "lib", "a", None, ["crates/a/src/lib.rs", "crates/a/src/common.rs"]),
    "bin_tool": ("crates/a/Cargo.toml", "a", "bin", "tool", 2021, ["crates/a/src/bin/tool.rs"]),
    "test_it": ("crates/a/Cargo.toml", "a", "test", "it", 2021, ["crates/a/src/common.rs"]),
    "lib_b": ("crates/#b/Cargo.toml", "b", "lib", "b", None, ["crates/#b/src/lib.rs"]),
    "bench_perf": ("crates/a/Cargo.toml", "a", "bench", "perf", None, ["crates/a/src/lib.rs"]),
}
VARIANTS = {
    "rust-mixed": {"units": ["lib_a", "bin_tool", "test_it", "lib_b"], "selected": ["lib_a", "bin_tool", "lib_b"], "enumeration": "complete", "clonesRequired": False},
    "rust-mixed-clones-required": {"units": ["lib_a", "bin_tool", "test_it", "lib_b"], "selected": ["lib_a", "bin_tool", "lib_b"], "enumeration": "complete", "clonesRequired": True},
    "rust-extra-unit": {"units": ["lib_a", "bin_tool", "test_it", "lib_b", "bench_perf"], "selected": ["lib_a", "bin_tool", "lib_b"], "enumeration": "complete", "clonesRequired": False},
    "rust-same-file-2021": {"units": ["lib_a", "bin_tool", "test_it", "lib_b"], "selected": ["test_it", "bin_tool", "lib_b"], "enumeration": "complete", "clonesRequired": False},
    "rust-ambiguous": {"units": ["lib_a", "bin_tool", "test_it", "lib_b"], "selected": ["lib_a", "bin_tool", "test_it", "lib_b"], "enumeration": "complete", "clonesRequired": False},
    "rust-partial": {"units": ["lib_a", "bin_tool", "test_it", "lib_b"], "selected": ["lib_a", "bin_tool", "lib_b"], "enumeration": "partial", "clonesRequired": False},
}
MUTATIONS = {"ambiguous-fact-present", "partial-fact-present", "unit-id-not-derived", "config-projection-mismatch",
             "compiler-version-not-from-manifest", "edition-crate-missing", "stdlib-component-not-in-llvm"}


def fn_span(data, name):
    i = data.index(b"fn " + name.encode())
    if data[max(0, i - 4):i] == b"pub ":
        i -= 4
    s = data.index(b"{", i)
    depth = 0
    for j in range(s, len(data)):
        if data[j:j + 1] == b"{":
            depth += 1
        elif data[j:j + 1] == b"}":
            depth -= 1
            if depth == 0:
                return i, s, j + 1
    raise ValueError(name)


def build(name):
    variant, _, mut = name.partition("~")
    assert not mut or mut in MUTATIONS, mut
    cfg = VARIANTS[variant]
    store = Store()
    for doc in (ID, NE, REL, ENUM_DOC, EMIT_DOC):
        store.put_bytes(KIT.raw[schemas.norm_rel(doc)], f"schema:{doc}")
    inv_rows = [{"path": p, "sha256": store.put_bytes(FILES[p], f"source:{p}"), "bytes": len(FILES[p])} for p in sorted(FILES, key=lambda p: p.encode())]
    inv = {r["path"]: r for r in inv_rows}
    # HC-16: the toolchain closure (normalizationClosure kind toolchain) carries the level specification and its map
    level_spec = b"cb24 L0-verbatim level specification (rust provider)\n"
    T, tdesc = closure(store, "toolchain", "cb24-rust-toolchain", {
        "bin/rustc": b"synthetic rustc\n", "bin/cargo": b"synthetic cargo\n", "bin/proc-macro-srv": b"synthetic proc macro server\n",
        "opensip-interface/normalization/levels/L0-verbatim.spec": level_spec,
        S39.NSL["closureTreePath"]: S39.normalization_map_bytes("cb24-rustc-normalizer", {"L0-verbatim": hashlib.sha256(level_spec).hexdigest()})},
        "1.82.0")
    L, ldesc = closure(store, "rust-dev-llvm", "cb24-rust-dev-llvm", {f"lib/rustlib/{TRIPLE}/lib/libstd.rlib": b"std rlib\n",
                                                                     f"lib/rustlib/{TRIPLE}/lib/libcore.rlib": b"core rlib\n"}, "1.82.0")
    stage_operation = "cb24.derive-rust-view"
    # HC-15: the producer closure registers its stage output schema at the interface tree path
    P, _ = closure(store, "provider", "cb24-rust-provider", {
        "bin/provider": b"synthetic rust provider\n",
        S39.stage_output_tree_path(stage_operation): S39.stage_output_schema_bytes(stage_operation, ["view"], "cb24 rust view stage output")})
    E, _ = closure(store, "evaluator", "cb24-evaluator3", {"bin/evaluator": b"synthetic evaluator3 identity\n"})
    D, _ = closure(store, "detector", "cb24-rust-pack", {"rules/pack.json": b"{\"pack\":\"cb24.rust-pack\"}\n"})
    tree = {r["path"]: r["sha256"] for r in tdesc["tree"]}
    comps = sorted([{"component": r["path"].split("/")[-1], "sha256": r["sha256"]} for r in ldesc["tree"]], key=lambda c: c["component"].encode())
    if mut == "stdlib-component-not-in-llvm":
        comps.append({"component": "liballoc.rlib", "sha256": hashlib.sha256(b"not in closure").hexdigest()})
    lock = {"path": "Cargo.lock", "contentSha256": inv["Cargo.lock"]["sha256"], "lockfileVersion": 3}
    dep = {"schemaVersion": 1, "language": "rust", "lockfileIdentity": lock, "packages": [], "completeness": {"state": "complete", "missing": []}}
    dep_id = "sha256:" + store.put_frame("native.dependency-source-set.v1", dep, "dependency-source-set")
    feats = {"schemaVersion": 1, "resolverVersion": 2, "targetTriple": TRIPLE,
             "activated": [{"packageKey": "a 0.1.0", "features": ["default"]}, {"packageKey": "b 0.2.0-alpha.1+build.5", "features": []}],
             "computedBy": {"producer": "opensip-cargo-adapter", "producerBuildId": "cb24-synthetic"}}
    feats_id = "sha256:" + store.put_frame("native.unified-features.rust.v1", feats, "unified-features")
    rustflags = {"honored": ["-Dwarnings"], "stripped": [{"flag": "-Clinker=/usr/bin/evil", "reason": "codegen-option-not-allowlisted"}], "executableSelected": False}
    projection = {"schemaVersion": 2, "honoredKeys": ["build.rustflags"], "strippedKeys": ["build.rustc-wrapper"], "replacedSnapshotConfigs": [],
                  "rustflags": rustflags, "ancestorCarrierVerified": True, "cargoHome": "private-empty", "environmentProjection": "none",
                  "claimsCargoSwitch": False, "projectionSha256": store.put_bytes(b"[build]\nrustflags = [\"-Dwarnings\"]\n", "cargo-config-projection-file")}
    ctx = {"schemaVersion": 2, "targetTriple": TRIPLE, "hostTriple": TRIPLE,
           "toolchain": {"rustCommitHash": "f6e511eec7342f59a25f7c0534f1dbea00d01b14",
                         "rustcVersion": "1.82.1" if mut == "compiler-version-not-from-manifest" else "1.82.0", "cargoVersion": "1.82.0",
                         "sysrootDigest": store.put_bytes(b"sysroot manifest synthetic\n", "sysroot-manifest"), "rustcDevLlvmDigest": sfx(L),
                         "standardLibraryComponentDigests": comps, "targetTriple": TRIPLE},
           "toolClosure": {"closureId": T, "rustc": tree["bin/rustc"], "cargo": tree["bin/cargo"], "procMacroServer": tree["bin/proc-macro-srv"],
                           "linker": None, "ar": None},
           "baseCfg": ["unix", "target_os=\"linux\""], "resolverVersion": 2, "dependencySourceSetId": dep_id, "unifiedFeaturesId": feats_id,
           "preparedOutputSetId": None, "configProjection": projection}
    ctx_hex = store.put_frame("native.context.rust.v2", ctx, "native-context:rust")
    proj_frame = store.put_frame("native.cargo-config-projection.v2", projection, "cargo-config-projection")
    if mut == "config-projection-mismatch":
        proj_frame = store.put_frame("native.cargo-config-projection.v2", dict(projection, strippedKeys=["build.rustc-wrapper", "build.target-dir"]), "cargo-config-projection-other")
    units, ids = [], {}
    for key in cfg["units"]:
        marker, crate, kind, tname, ted, _ = UNIT_DEFS[key]
        uid = NC.compilation_unit_id({"markerPath": marker, "targetKind": kind, "targetName": tname})
        if mut == "unit-id-not-derived" and key == "lib_b":
            uid = "sha256:" + "f" * 64
        ids[key] = uid
        units.append({"unitId": uid, "markerPath": marker, "crateName": crate, "targetKind": kind, "targetName": tname, "targetEdition": ted})
    rows = sorted({(p, ids[k]) for k in cfg["units"] for p in UNIT_DEFS[k][5]}, key=lambda t: (t[0].encode(), t[1].encode()))
    ownership = {"schemaVersion": 1, "enumeration": cfg["enumeration"], "units": sorted(units, key=lambda u: u["unitId"].encode()),
                 "selectedUnitIds": sorted((ids[k] for k in cfg["selected"]), key=lambda s: s.encode()),
                 "ownership": [{"path": p, "unitId": u} for p, u in rows]}
    own_id = "sha256:" + store.put_frame("native.source-unit-ownership.v1", ownership, "source-unit-ownership")
    edition = {f"dep_{i:03d}": [2015, 2018, 2021, 2024][i % 4] for i in range(300)}
    edition.update({"a": 2018, "b": 2024})
    if mut == "edition-crate-missing":
        del edition["b"]
    uni = {"schemaVersion": 2, "edition": edition, "lockfileIdentity": lock, "dependencySourceSetId": dep_id, "unifiedFeaturesId": feats_id,
           "nativeContextId": "sha256:" + ctx_hex, "cfgSets": [{"cfgSetId": "default", "cfg": ["unix", "target_os=\"linux\"", "feature=\"default\""]}],
           "rustflags": rustflags, "crateRootPaths": sorted(["crates/a/src/lib.rs", "crates/a/src/bin/tool.rs", "crates/a/src/common.rs", "crates/#b/src/lib.rs"], key=lambda p: p.encode()),
           "configProjectionSha256": proj_frame, "executionCapableResolution": False, "preparedOutputSetId": None, "preparedResolution": "none",
           "sourceUnitOwnershipId": own_id}
    U = store.put_frame("native.semantic-universe.rust.v2", uni, "native-universe:rust")
    adm = NC.admit_native_context(store, ctx_hex, inv_rows)
    bound = {U: NC.bind_universe(store, U, {ctx_hex: adm}, inv_rows)}
    inv_bytes = dict(FILES)
    discovery = M.discover_units(inv_bytes)
    membership = M.assign_membership(inv_bytes, discovery)
    # HC-19: zero-config discovery (Config2 discovery {}), so the retained DISCOVERED unit provenance agrees with the configuration
    scope = M.unit_scope_descriptor(discovery, [], None)
    budget = {"unit": "work-units", "limit": 1000000}
    requested = sorted({"calls": True, "clones-fact": cfg["clonesRequired"], "inventory": True, "syntax": True}.items(), key=lambda t: t[0].encode())
    config = {"analysis": {"profileId": "cb24-explicit", "capabilities": [c for c, _ in requested], "budget": budget},
              "components": {}, "discovery": {}, "policy": {}, "evidence": {}}
    vcs = {"schemaVersion": 2, "kind": "none", "commitId": None, "dirty": False, "sourceInventoryDigest": store.put_record(inv_rows, "source-inventory")}
    project_id = "prj1-" + hashlib.sha256(b"consumer-b.v24:rust").hexdigest()
    snapshot = {"schemaVersion": 2, "projectId": project_id, "sourceInventory": inv_rows,
                "resolvedConfigDigest": store.put_record(config, "configuration"), "scopeDigest": store.put_record(scope, "scope-descriptor"),
                "vcsDigest": store.put_record(vcs, "vcs-observation")}
    snapshot_id = store.put_object("snapshot", snapshot, "snapshot")
    fpaths = EN.file_extent(membership, scope, ".")
    sym_paths = EN.symbol_extent(bound[U], fpaths, membership)
    cells = []
    for cap, req in requested:
        kinds = sorted(EN.KIND_DERIVATION[cap], key=lambda k: k.encode())
        extents = []
        for k in kinds:
            if k == "file":
                paths = fpaths
            elif k == "package":
                named, failed = EN.named_manifests(inv_bytes, fpaths)
                paths = sorted({n["path"] for n in named} | set(failed), key=ckey)
            else:
                paths = sym_paths
            extents.append({"kind": k, "paths": paths})
        cells.append({"capabilityId": cap, "languageMode": "rust-cargo", "workspaceRoot": ".", "required": req, "kinds": kinds,
                      "programBindings": [{"ordinal": 0, "provenance": "default-unit", "enumerator": {"status": "selected", "closureId": P},
                                           "nativeContextDigest": ctx_hex, "universe": U, "programEntry": "Cargo.toml", "extents": extents}]})
    enum = {"schemaVersion": 1, "snapshotId": snapshot_id, "scopeDigest": K.raw_digest(scope),
            "membershipDigest": store.put_record(membership, "unit-membership"), "cells": cells}

    def ref(rid):
        return {"contributionId": "cb24.rust-pack", "ruleStableId": rid, "semanticsMajor": 1, "programDigest": hashlib.sha256(rid.encode()).hexdigest()}
    rules = sorted([
        {"ruleId": "cb24.rs.calls-into-b", "ruleProgramRef": ref("cb24.rs.calls-into-b"), "enabled": True, "severity": "error", "gate": True,
         "subjectEnumeration": {"universe": "rust", "subjectKind": "symbol"},
         "emitWhen": {"op": "exists", "relation": "calls", "minResolution": "resolved-callee", "filters": [{"field": "target", "cmp": "prefix", "value": "rs:crates/#b/"}]},
         "evidenceUse": []},
        {"ruleId": "cb24.rs.clone-body", "ruleProgramRef": ref("cb24.rs.clone-body"), "enabled": True, "severity": "warning", "gate": False,
         "subjectEnumeration": {"universe": "rust", "subjectKind": "file", "include": ["crates/**"]},
         "emitWhen": {"op": "exists", "relation": "clones", "minResolution": "normalized-body-hash", "filters": []}, "evidenceUse": []},
        {"ruleId": "cb24.rs.package-declared", "ruleProgramRef": ref("cb24.rs.package-declared"), "enabled": True, "severity": "warning", "gate": False,
         "subjectEnumeration": {"universe": "rust", "subjectKind": "package"},
         "emitWhen": {"op": "exists", "relation": "package", "minResolution": "manifest-declared", "filters": []}, "evidenceUse": []},
    ], key=lambda r: r["ruleId"].encode())
    policy = {"schemaFamily": "opensip.product.policy", "schemaMajor": 2, "gateSeverityAtLeast": "warning", "rules": rules}
    waivers = {"schemaFamily": "opensip.product.waivers", "schemaMajor": 1, "waivers": []}
    policy_digest = store.put_record(policy, "policy")
    emission = {"schemaVersion": 1, "policyDigest": policy_digest, "rules": [
        {"ruleId": r["ruleId"], "contributionId": "cb24.rust-pack", "ruleStableId": r["ruleId"], "semanticsMajor": 1, "detectorClosure": D,
         "stabilityClass": "path-stable", "emissionProfile": "declarative-subject-v1"} for r in rules]}
    spec = {"schemaVersion": 2,
            "requestedCapabilities": sorted([{"capabilityId": c, "languageMode": "rust-cargo", "workspaceRoot": ".", "required": r} for c, r in requested], key=ckey),
            "policyPackIds": [],
            "parameters": sorted([{"schemaDigest": KIT.digest(ENUM_DOC), "payloadDigest": store.put_record(enum, "enumeration-plan")},
                                  {"schemaDigest": KIT.digest(EMIT_DOC), "payloadDigest": store.put_record(emission, "emission-plan")}], key=ckey)}
    grant = {"schemaVersion": 2, "projectId": project_id, "principals": [{"kind": "first-party", "closureId": P, "ownerSourceDigest": None}],
             "analysisOperations": ["native-analysis", "read-source"], "scopeDigest": K.raw_digest(scope)}
    vec = json.load(open(OUT + "/vectors/capability-manifests.json"))
    cm = next(p for p in vec["positives"] if p.get("admission", {}).get("capabilityManifestId") == CAP_MANIFEST_ID)
    plan = {"schemaVersion": 2, "snapshotId": snapshot_id, "capabilityManifestId": CAP_MANIFEST_ID,
            "semanticClosures": sorted([P, E, D], key=ckey), "analysisSpecDigest": store.put_record(spec, "analysis-spec"),
            "resolvedConfigDigest": snapshot["resolvedConfigDigest"], "nativeContextDigests": [ctx_hex], "importIds": [],
            "policyDigest": policy_digest, "waiverDigest": store.put_record(waivers, "waivers"), "scopeDigest": snapshot["scopeDigest"],
            "budget": budget, "semanticGrantDigest": store.put_record(grant, "semantic-grant"),
            "capabilityManifestBytesDigest": store.put_bytes(bytes.fromhex(cm["admission"]["committedBytesHex"]), "capability-manifest-bytes")}
    plan_id = store.put_object("plan", plan, "plan")
    # HC-15b (own builder error in the first corrected build, logs/s39-hc-build.4.from_scratch.log): outputSchemaDigest is the raw
    # SHA-256 of the member the producer closure registers, not the native bundle digest
    registered = next(r["sha256"] for r in store.get_frame(sfx(P), {"closure"})[1]["tree"] if r["path"] == S39.stage_output_tree_path(stage_operation))
    ss = store.put_record({"schemaVersion": 2, "planId": plan_id, "producerClosure": P, "operation": stage_operation, "parameters": [],
                           "outputDomains": ["view"], "outputSchemaDigest": registered}, "stage-spec:0")
    exec_plan_id = store.put_object("execution-plan", {"schemaVersion": 2, "planId": plan_id,
                                                       "stages": [{"ordinal": 0, "stageSpecDigest": ss, "requires": [], "outputDomains": ["view"]}]}, "execution-plan")
    facts, payloads, body_ids = {}, {}, {}

    def fact(rel, rung, payload, anchors):
        desc = {"schemaVersion": 2, "snapshotId": snapshot_id, "relation": rel, "resolution": rung, "sourceUniverse": U, "targetUniverse": U,
                "producerClosure": P, "payloadSchemaDigest": KIT.digest(REL), "payloadDigest": store.put_record(payload, f"fact-payload:{rel}"),
                "anchors": sorted(anchors, key=ckey), "confidenceMillionths": 1000000}
        fid = store.put_object("fact", desc, f"fact:{rel}")
        facts[fid], payloads[fid] = desc, payload

    def anchor(path, s, e):
        return {"path": path, "blobDigest": inv[path]["sha256"], "startByte": s, "endByte": e}

    for r in inv_rows:
        fact("file", "enumerated", {"path": r["path"], "contentSha256": r["sha256"], "byteLength": r["bytes"]}, [])
    fact("package", "manifest-declared", {"packageName": "a", "packageVersion": "0.1.0", "manifestPath": "crates/a/Cargo.toml"}, [])
    fact("package", "manifest-declared", {"packageName": "b", "packageVersion": "0.2.0-alpha.1+build.5", "manifestPath": "crates/#b/Cargo.toml"}, [])
    lvl = store.put_bytes(b"cb24 L0-verbatim level specification (rust provider)\n", "level-spec:L0")
    sym_ids, dialects = [], {}
    clones_disclosure = {}
    for p, n in FUNCS:
        data = FILES[p]
        d, s0, e0 = fn_span(data, n)
        sid = f"rs:{p}#{n}"
        if p in sym_paths:
            sym_ids.append(sid)
            fact("declares", "syntactic", {"container": f"rs:{p}", "declared": sid, "declarationKind": "function"}, [anchor(p, d, e0)])
            lit = data.find(b"7", s0) if b"7" in data[s0:e0] else data.find(b"1", s0)
            if b"println" not in data[s0:e0]:
                fact("literal", "syntactic", {"owner": sid, "literalKind": "number", "valueText": data[lit:lit + 1].decode()}, [anchor(p, lit, lit + 1)])
        blv, lang, refusal = NC.body_language_version(bound[U], p)
        dialects[p] = blv["dialect"] if blv else refusal
        forced = (mut == "ambiguous-fact-present" and p == "crates/a/src/common.rs") or (mut == "partial-fact-present" and p == "crates/a/src/lib.rs")
        if refusal and forced:
            blv, lang = {"schemaVersion": 1, "languageId": "rust", "compilerName": "rustc", "compilerVersion": ctx["toolchain"]["rustcVersion"],
                         "compilerBuild": ctx["toolchain"]["rustCommitHash"], "dialect": {"edition": 2018}}, "rust"
            refusal = None
        if refusal:
            clones_disclosure[p] = refusal
            continue
        frame = NF.build_body_frame("L0-verbatim", lvl, lang, blv, NF.l0_payload(data[s0:e0]))
        bid = "sha256:" + store.put_bytes(frame, f"body-frame:{p}")
        body_ids[p] = bid
        fact("clones", "normalized-body-hash", {"bodyIdentity": bid, "normalisationLevel": "L0-verbatim", "normalisationVersion": lvl}, [anchor(p, s0, e0)])
    tool = FILES["crates/a/src/bin/tool.rs"]
    if "crates/a/src/bin/tool.rs" in sym_paths:
        i = tool.index(b"a::shared()")
        fact("calls", "resolved-callee", {"caller": "rs:crates/a/src/bin/tool.rs#main", "calleeText": "a::shared", "resolvedCallee": "rs:crates/a/src/lib.rs#shared"},
             [anchor("crates/a/src/bin/tool.rs", i, i + 11)])
    scopes, coverages = {}, {}
    closed = {"deadCodeRepairEligible": False, "dynamicDispatch": "resolved", "entryPointsRecognized": "all", "exportsClosed": "closed",
              "externalConsumers": "none-declared", "nonliteralLoading": "none", "reasons": []}

    def scope_cov(rel, rung, subjects, complete=True, deficiency=None, cause=None):
        sd = {"schemaVersion": 2, "snapshotId": snapshot_id, "sourceUniverse": U, "targetUniverse": U, "relation": rel, "resolution": rung,
              "enumeratorClosure": P, "subjects": sorted(set(subjects), key=ckey)}
        sid = store.put_object("subject-scope", sd, f"scope:{rel}")
        rc = ({"state": "complete", "attempted": True, "examinedExhaustive": True, "stageTerminal": "complete", "unresolvedEdgeCount": 0, "unresolvedEdgeClasses": []}
              if rung in NF.RESOLVED else {"state": "not-applicable", "attempted": False, "examinedExhaustive": complete,
                                           "stageTerminal": "complete" if complete else None, "unresolvedEdgeCount": 0, "unresolvedEdgeClasses": []})
        entry = {"relation": rel, "resolution": rung, "coverage": "complete" if complete else "unknown",
                 "examinedUniverse": {"subjectScopeCommitment": "sha256:" + sfx(sid), "subjectCount": len(sd["subjects"])},
                 "resolutionCompleteness": rc, "closedWorld": closed, "derivationKinds": [], "confidenceMillionths": 1000000,
                 "deficiency": deficiency, "nativeCause": cause}
        payload = {"schemaVersion": 3, "key": {"relation": rel, "resolution": rung, "sourceUniverse": U, "targetUniverse": U,
                                               "subjectScopeCommitment": "sha256:" + sfx(sid)}, "entry": entry}
        cd = {"schemaVersion": 2, "scopeId": sid, "payloadSchemaDigest": KIT.digest(NE), "payloadDigest": store.put_record(payload, f"coverage-payload:{rel}")}
        cid = store.put_object("coverage", cd, f"coverage:{rel}")
        scopes[sid], coverages[cid] = sd, (cd, payload)

    scope_cov("file", "enumerated", fpaths)
    scope_cov("package", "manifest-declared", ["a", "b"])
    for rel in ("declares", "literal", "control-flow"):
        scope_cov(rel, "syntactic", sym_ids)
    scope_cov("calls", "resolved-callee", sym_ids)
    # HC-14/HC-17: the clones account is owed only Rust's closed eligible suffix set; Cargo.toml / Cargo.lock stay inventoried
    body_paths = [p for p in fpaths if S39.body_eligible("native.semantic-universe.rust.v2", p)]
    if cfg["enumeration"] == "partial":
        scope_cov("clones", "normalized-body-hash", body_paths, False, "input-closure-incomplete", "body-language-owner-unenumerated")
    elif any(v == "BODY_LANGUAGE_OWNER_AMBIGUOUS" for v in clones_disclosure.values()):
        amb = [p for p, v in clones_disclosure.items() if v == "BODY_LANGUAGE_OWNER_AMBIGUOUS"]
        scope_cov("clones", "normalized-body-hash", [p for p in body_paths if p not in amb])
        scope_cov("clones", "normalized-body-hash", amb, False, "input-closure-incomplete", "body-language-owner-ambiguous")
    else:
        scope_cov("clones", "normalized-body-hash", body_paths)
    view = {"schemaVersion": 2, "planId": plan_id, "scopeIds": sorted(scopes, key=ckey), "facts": sorted(facts, key=ckey),
            "coverageIds": sorted(coverages, key=ckey), "producerClosure": P, "schemaDigests": sorted([KIT.digest(REL), KIT.digest(NE)], key=ckey)}
    view_id = store.put_object("view", view, "view")
    param_digest = K.raw_digest(enum)
    inventories = []
    for ci, cell in enumerate(cells):
        for k in cell["kinds"]:
            ext = next(e["paths"] for e in cell["programBindings"][0]["extents"] if e["kind"] == k)
            if k == "file":
                rws = [{"nativeSubjectId": p, "kind": "file", "path": p, "qualifiedName": p, "subjectLanguage": EN.subject_language(p),
                        "signatureTokens": [], "projections": []} for p in ext]
            elif k == "package":
                rws = [{"nativeSubjectId": nm, "kind": "package", "path": mp, "qualifiedName": nm, "subjectLanguage": "toml", "signatureTokens": [], "projections": []}
                       for nm, mp in (("a", "crates/a/Cargo.toml"), ("b", "crates/#b/Cargo.toml"))]
            else:
                rws = [{"nativeSubjectId": f"rs:{p}#{n}", "kind": "symbol", "path": p, "qualifiedName": n, "subjectLanguage": "rust", "exported": "exported",
                        "signatureTokens": ["fn", n], "projections": [{"closureId": D, "signatureTokens": ["fn", n, p]}]} for p, n in FUNCS if p in ext]
            record = {"schemaVersion": 1, "planId": plan_id, "parameterDigest": param_digest, "cellOrdinal": ci, "programOrdinal": 0, "kind": k,
                      "state": "complete", "deficiency": None, "nativeCause": None, "examinedPaths": ext,
                      "rows": sorted(rws, key=lambda r: (r["nativeSubjectId"].encode(), r["path"].encode()))}
            inventories.append((store.put_record(record, f"subject-inventory:{ci}:{k}"), record))
    closures_desc = {c: store.get_frame(sfx(c), {"closure"})[1] for c in plan["semanticClosures"]}
    efaults, index = EN.admit_enumeration(plan, plan_id, spec, scope, membership, enum, inventories, bound, closures_desc, inv_bytes)
    if index is None:
        raise SystemExit(f"enumeration refused {efaults}")
    receipts = [{"ordinal": 0, "stageSpecDigest": ss, "producerClosure": P, "outputDomains": ["view"],
                 "outputRefs": [{"domain": "view", "digest": sfx(view_id)}], "state": "complete", "unavailableReason": None}]
    # HC-42 (builder): the synthetic host capture observes each row's s3-attributed views, not the one view on every row
    attributed = XI.attribution_map(enum, receipts, {view_id: view}, scopes)
    observations = {(ci, 0): {"viewDigests": attributed[(ci, 0)], "stageOrdinal": 0, "candidateResultDigest": None} for ci in range(len(cells))}
    ctx_x = {"enum_index": index, "views": {view_id: view}, "scopes": scopes, "coverages": coverages, "candidates": {}, "vcs_kind": "none"}
    xi, derived, xfaults = XI.build_record(plan, plan_id, exec_plan_id, E, enum, receipts, observations, ctx_x)
    xi_digest = store.put_record(xi, "execution-inputs")
    inp = EV.Inputs(plan=plan, plan_id=plan_id, exec_plan_id=exec_plan_id, evaluator_closure=E, policy=policy, waivers=waivers, emission=emission,
                    enum_plan=enum, inventories=index["inventories"], views={view_id: view}, scopes=scopes, coverages=coverages, facts=facts,
                    fact_payloads=payloads, bound=bound, imports={}, import_payloads={}, import_observations={}, import_scopes={}, import_flags={},
                    exec_inputs=xi, exec_inputs_digest=xi_digest, required_rows=derived["requiredRows"], scope_document=None, project_id=project_id)
    out = EV.evaluate(inp)
    for d_, b in out["blobs"].items():
        assert store.put_bytes(b, "evaluator-output") == d_
    for ident, (dom, desc) in out["objects"].items():
        assert store.put_object(dom, desc, f"output:{dom}") == ident
    os.makedirs(OUT + "/runs", exist_ok=True)
    store_path = f"{OUT}/runs/{name}.store.json"
    with open(store_path, "w") as fh:
        json.dump(store.export({"runId": out["runId"], "variant": name}), fh, sort_keys=True)
    proof = out["proof"]
    summary = {"variant": name, "mutation": mut or None, "runId": out["runId"], "planId": plan_id, "universe": U, "verdict": proof["verdict"],
               "ruleOutcomes": {r["ruleId"]: r["outcome"] for r in proof["ruleResults"]},
               "findings": [(f["finding"]["ruleId"], f["subjectPath"]) for f in out["findings"]],
               "executionDeficiencies": [(d["cause"], d["nativeCause"]) for d in proof["executionDeficiencies"]],
               "cellOutcomes": [(o["capabilityId"], o["required"], o["state"], o["deficiency"], o["nativeCause"]) for o in xi["cellOutcomes"]],
               "bodyDialects": dialects, "bodyIdentities": body_ids, "editionMapSize": len(edition), "symbolExtent": sym_paths,
               "builderFaults": {"enumeration": efaults, "executionInputs": xfaults, "context": adm["refusals"], "universe": bound[U]["faults"]},
               "storeFile": store_path, "storeFileSha256": hashlib.sha256(open(store_path, "rb").read()).hexdigest()}
    with open(f"{OUT}/runs/{name}.build.json", "w") as fh:
        json.dump(summary, fh, indent=1, sort_keys=True)
    return summary


if __name__ == "__main__":
    for v in sys.argv[1:] or list(VARIANTS):
        s = build(v)
        print(json.dumps({k: s[k] for k in ("variant", "verdict", "ruleOutcomes", "executionDeficiencies", "bodyDialects", "builderFaults")}))
        print("  cells", s["cellOutcomes"])
