"""Scoped supersession rows (candidate 02). Old parent bytes stay unchanged; each row names exact selectors, scope,
disposition, wire effect, justification and the checker ids that test it."""

D2 = "$.typescriptSemanticSubstrate.providerProtocol.wireSchema."
R2 = "$.wireSchema."


def row(id_, scope, targets, disposition, statement, wire_change, justification, checks):
    return {"id": id_, "scope": scope, "targets": targets, "disposition": disposition, "statement": statement,
            "wireChange": wire_change, "justification": justification, "referenceChecks": checks}


def t(pin, *selectors):
    return {"pin": pin, "selectors": list(selectors)}


ROWS = [
    row("SUCC-PER-KEY-SCOPE2", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("delivery2", D2 + "definitions.RequestedCoverageDomainV1.workerRule (clause: every key.subjectScopeCommitment equals subjectScope.subjectScopeCommitment)",
           D2 + "coverageDomain.keyConstruction.subjectScopeCommitment"),
         t("rust2", "$.planAndDomainProjection.coverageDomainAlgorithm[3] (member subjectScopeCommitment)",
           "$.commitments.subjectScope (as the value placed in keys)")],
        "superseded-value",
        "Each request key's subjectScopeCommitment is the sha256: text form of the key's own scope2 (PER-KEY-SCOPE2). Retained unchanged: TS SubjectScopeV1 (shape, recipe, subjectCount) and its place inside domainCommitment; rust2 subjects/SubjectV2 and the analysis-domain recipe; rust2 commitments.subjectScope stays a named recipe with no wire carrier.",
        "none (member, type and pattern unchanged; values change)",
        "native-evidence §4.1a, identity §3 and startup coverageFrames.entries require per-key values; keys in one stage differ in relation/rung/target, so a single per-stage value cannot satisfy them.",
        ["scope2-ts2-admits", "scope2-rust3-admits", "scope2-per-stage-value-refused", "scope2-keys-differ", "vectors:PER-KEY-SCOPE2", "scope2-descriptor-members-match-owner"]),
    row("SUCC-FACT-REF-REFUSED", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("factPlane", "$.factRecordContractV1.anchorSchema.variants.fact-ref"),
         t("delivery2", D2 + "definitions.AnchorRefV1.variants.fact-ref")],
        "not-admitted-under-fact2",
        "kind=fact-ref is PROVIDER.PROTOCOL_VIOLATION at candidate admission. Vocabulary and AnchorRefV1 shape unchanged.",
        "none", "fact-identity-fact2 is mandatory in both token sets; identity-schemas.v3 #/$defs/fact/properties/anchors items are {path, blobDigest, startByte, endByte}; FACT-ID-V1 is never relabeled (native-evidence §9.1).",
        ["anchor-fact-ref-refused", "fact2-anchor-closed-shape", "vectors:ANCHOR-FACT-REF-REFUSED"]),
    row("SUCC-ANCHOR-RULES", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("factPlane", "$.factRecordContractV1.sourceSpanSchema.rule", "$.factRecordContractV1.anchorSchema.ordering"),
         t("delivery2", D2 + "definitions.AnchorRefV1.ordering", D2 + "definitions.AnchorRefV1.join ('field-for-field')"),
         t("identityModel3", "line 1892 ANCHOR_RANGE (unchanged, not narrowed)"),
         t("factBatch3", "#/properties/candidates/items/properties/anchors/maxItems (JSON-vector bound 4096)")],
        "clarified-types-and-separated-rules",
        "Wire anchor rule: non-empty in-bounds interval plus ANCHOR-WIRE-SPAN types. Shared fact2 rule: 0 <= startByte <= endByte <= blob length and UTF-8 boundaries, unchanged. Anchor order per language: TS2 deterministic-CBOR bytes (the more specific TS transport ordering wins over its 'field-for-field' fact-plane claim), Rust3 CVE1 bytes. The orders differ through map-key order, not through string encoding. Wire count 1..100000 from identity-schemas.v3; 4096 is the fact-batch.3 JSON-vector bound.",
        "none", "Types were unstated (TS2-G5/R3-G5); the empty-interval difference between the two owners is a scope difference once stated separately.",
        ["anchor-empty-interval-refused-on-wire", "fact2-anchor-range-permits-empty", "anchor-order-languages-differ", "anchor-order-path-only-same", "vectors:ANCHOR-WIRE-SPAN"]),
    row("SUCC-TS2-MANIFEST-DIGEST", ["typescript-semantic major 2"],
        [t("delivery2", D2 + "commitments.domains.snapshotManifest (as applied to SnapshotManifestV1/SnapshotSealV1/SnapshotAcceptedV1.manifestSha256)")],
        "not-applied",
        "manifestSha256 is DigestHex = lowercase hex SHA-256(deterministic-CBOR(entries)), no domain and no sha256: prefix.",
        "none", "Field text says DigestHex; DigestHex cannot hold a sha256: value; rust2 commitments.snapshotManifest states the same raw recipe. Citation correction: check-rust-provider-protocol.py is the v1 checker (line 27, recipe at line 1048); the v2 checker computes no manifest digest. Neither is an owner.",
        ["ts2-manifest-digest-raw", "ts2-manifest-domain-form-refused", "citation-v1-checker-is-v1", "vectors:TS2-MANIFEST-DIGEST"]),
    row("SUCC-DEPSRC-DIGEST", ["rust-semantic major 3"],
        [t("evidence", "#/$defs/DependencySourceManifestV3/properties/manifestSha256/x-opensip-digest",
           "#/$defs/DependencySourceSealV3/properties/manifestSha256/x-opensip-digest",
           "#/$defs/DependencySourceManifestV3/properties/entries/x-opensip-order")],
        "superseded-recipe-and-order-registered-bytes-kept",
        "manifestSha256 = lowercase hex SHA-256(deterministic-CBOR(entries)) (non-self-referential; rust2 commitments.snapshotManifest recipe, invoked by native-evidence §3.2 'same discipline as the snapshot'). entries order: UTF-8 byte tuple (name, version, sourceId, path) of the exactly joined package row, which equals DependencySourceSetV1.packages x-opensip-order {by:[name,version,sourceId]} then DependencyFileManifestV1 path order, as native_evidence_model.v2 dependency_source_set_admit sorts. The registered schema document is not edited.",
        "none (types/patterns unchanged; order and value recipe stated)",
        "The annotated preimage 'exact transport manifest frame bytes as sent' contains manifestSha256 itself. packageKey byte order is not the tuple order when a name holds a byte <= 0x20 (reviewer counterexample), so the tuple is normative.",
        ["depsrc-digest-non-self-referential", "depsrc-self-referential-unsatisfiable", "depsrc-file-manifest-join", "depsrc-empty-set", "vectors:DEPSRC-CUSTODY"]),
    row("SUCC-DEPSRC-SET-KEY", ["rust-semantic major 3"],
        [t("evidence", "#/$defs/DependencyPackageSourceV1/properties/name", "#/$defs/DependencyPackageSourceV1/properties/version",
           "#/$defs/DependencySourceManifestV3/properties/entries/items/properties/packageKey"),
         t("nativeMd", "§3.1 DependencySourceSetV1 (lines 1648-1703)")],
        "scoped-admission-constraint",
        "packageKey = name SP version SP sourceId, an exact echo join to one package row (PACKAGE-KEY-JOIN). Dependency-source set admission (before Plan binding) refuses a package whose name or version contains a scalar <= U+0020, or whose constructed key exceeds 4096 scalars (the registered packageKey maxLength), as request-rejected (2) REQUEST.PRECONDITION_FAILED detail native.dependency-source-package-key-invalid. sourceId keeps its owner domain: it may be empty (min key 4 scalars) and may contain spaces; a key is parsed only by the first two SP. Carrier minScalars is 4.",
        "none (no member/type change; a new typed refusal detail for an otherwise unrepresentable set)",
        "Owner row bounds (256 + 256 + 4096 + 2 = 4610) exceed the registered key bound 4096, and bytes <= 0x20 in name/version make keys ambiguous and break order. Cargo names and versions never contain such bytes, so no real lockfile is refused.",
        ["vectors:PACKAGE-KEY-JOIN", "vectors:DEPSRC-SET-KEY-CONSTRAINTS", "package-key-bounds-derived-from-owner"]),
    row("SUCC-DEPSRC-RECORDS", ["rust-semantic major 3"],
        [t("nativeMd", "§9.2 rows DependencySourceChunk (line 2877) and DependencySourceAccepted (line 2879)")],
        "field-level-publication",
        "Rust3DependencySourceChunkV3 and Rust3DependencySourceAcceptedV3 (alias of Native2DependencySourceSealV3) are private names; no wire tag or record name is added.",
        "none", "The frame rows gave members without types.", ["carrier-member-lists"]),
    row("SUCC-CANONICAL-PATH", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("rust2", R2 + "definitions.CanonicalPath.rule"),
         t("evidence", "#/$defs/CanonicalPath/pattern (supplementary; used by DependencySourceManifestV3 entries)"),
         t("identitySchemas3", "#/$defs/LogicalPath (declarative segment grammar)")],
        "normative-lexical-admission",
        "Rust3 paths admit by canonical-path-segments (split on /; segments non-empty, not . or ..; no U+0000 or backslash; no [A-Za-z]: first-segment prefix), including DependencySource manifest entries and chunks; snapshot paths <= 4096 UTF-8 bytes (c2 v3 canonicalRelativePath), dependency paths <= 4096 scalars (registered). TS2 project paths admit by logical-path-segments (identity LogicalPath). Newline is not forbidden by either owner. Patterns are informative/supplementary, declared ECMA-262 u-mode; lookaround patterns must be lowered to handwritten checks.",
        "none",
        "The prior lookaround pattern and the registered Native2 CanonicalPath pattern admit 'a\\n/../b', 'a\\n//b', 'x\\n/..', 'a\\n/.'; Native2 also admits 'a//b', 'a/', 'C:x'. The Rust regex crate has no lookaround.",
        ["vectors:CANONICAL-PATH-ADMISSION", "vectors:TS2-LOGICAL-PATH-ADMISSION", "native2-canonical-path-pattern-weaker", "pattern-lowering-required-declared"]),
    row("SUCC-PREPARED-V3", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.PreparedOutputManifestV2", R2 + "payloadSchemas.PreparedOutputChunkV2", R2 + "payloadSchemas.PreparedOutputSealV2",
           R2 + "payloadSchemas.PreparedOutputAcceptedV2", R2 + "definitions.PreparedOutputEntryV2", R2 + "definitions.PreparedOutputBlobV2",
           "$.commitments.preparedOutputBlob", "$.preparedOutputCustody.order", "$.preparedOutputCustody.manifestConstruction",
           "$.preparedOutputCustody.planCommitmentProof", "$.preparedOutputCustody.readAuthority", "$.requestProjection.preparedOutputs"),
         t("nativeMd", "§10 routes table row 'stale prepared/import row selected explicitly; non-inert prepared row' (line 3525): adds detail native.prepared-output-exceeds-wire-limit")],
        "superseded-value-members-kept",
        "Frame member names are unchanged. entries answer PreparedOutputSetV3.rows one-to-one (PREPARED-V3-ENTRY). maxPreparedOutputEntries = 256 is retained as the TOTAL entry bound (outputOrdinal 0..255); maxExpansionRows/maxGeneratedFileRows stay preparation-set limits. Before spawn the host refuses a selected set with more than 256 inert rows, blob bytes over maxPreparedOutputTotalBlobBytes, or an encoded manifest over maxFramePayloadBytes: request-rejected (2) REQUEST.PRECONDITION_FAILED detail native.prepared-output-exceeds-wire-limit, the same row family as non-inert/stale prepared refusals. Read authority: generated-file rows mount read-only at .opensip/out/v1/<ownerKey>/<generated.logicalPath>; expansion and directive rows are looked up by site/owner (§3.6 PO-4).",
        "none (member lists unchanged; value domains substituted)",
        "The V2 payloads join rust-v1 rows that native-evidence §0 line 130 supersedes. A Plan-bound set of up to 1,000,000 rows is reachable user input, so the refusal is a request precondition, not a host invariant.",
        ["prepared-v3-entries-from-set", "prepared-v3-generated-blob-equality", "prepared-v3-set-identity-join", "prepared-v3-v2-planrow-refused", "vectors:PREPARED-V3-WIRE-LIMIT", "limit-literals"]),
    row("SUCC-TRANSITION-PRECEDENCE", ["rust-semantic major 3"],
        [t("rust2", "$.orderingAndStateMachine.transitionAstV2.rules", "$.orderingAndStateMachine.eventRecord", "$.preparedOutputCustody.order"),
         t("p3", "$.rules[P3-25].guard", "$.initialState", "$.stateUpdates")],
        "precedence-and-guard-successor",
        "p3-guard-successor.v1.json (generated from TRANSITIONS.rust-semantic): P3 plus guard P3-25 outputSeen=false, outputSeen reset at Analyze and set by FactBatch/CoverageV3; framePrecheck and T016/T020 payload guards retained as pre-match admission; host never sends Cancel in START.",
        "none", "native-evidence §0 line 118 supersedes only phaseValues and P3 claims to state existing behaviour exactly, so rust2 T019's guard is retained law the P3 transcription dropped (equivalence: Coverage always sets outputSeen). START is host-controlled.",
        ["p3-unavailable-after-output-faults", "p3-unavailable-before-output-admits", "p3-cancel-in-start-no-row", "p3-overlay-differential", "ts2-order-unchanged", "vectors:P3-OVERLAY", "p3-guard-successor-file"]),
    row("SUCC-COMMIT-MAP", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("nativeMd", "§0 line 126 and line 129 ('recipes and domains unchanged'); §9.7 Coverage frames commitments")],
        "field-to-domain-map-stated",
        "COMMITMENT_MAP rows are the exact field-to-domain map for both languages, with value classes derived from owner recipe text.", "none",
        "Field texts named no domain for wrapper/terminal coverage commitments (TS2-G12, R3-G12).",
        ["commit-map-complete", "commit-map-value-classes-match-owner", "commit-ts2-fact-batch-matches-wire-model", "commit-empty-stream", "vectors:COMMIT-MAP"]),
    row("SUCC-ECHO-ENUMERATION", ["typescript-semantic major 2", "rust-semantic major 3"],
        [t("startup", "#/x-opensip-startup-law/identityMembers")],
        "enumeration-completed",
        "Transitive echoes also carry snapshot2/plan2 text: SnapshotFileChunk.snapshotId (both), AnchorRefV1 source-span snapshotId (both), PreparedOutputChunk/Seal.planId, and the snapshotId inside the rust2 SubjectV2.subjectId preimage.",
        "none", "Each is an exact echo of an enumerated member (R3-G16).", ["echo-rules-present"]),
    row("SUCC-RUST3-FAULT-CANCEL", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.ProviderFaultV2", R2 + "payloadSchemas.CancelV2", R2 + "payloadSchemas.CancelledV2")],
        "types-and-observation-semantics-stated",
        "Cancel/Cancelled per RUST3-CANCEL-TYPES (Cancelled.observedPhase = host send phase). ProviderFault per RUST3-PROVIDER-FAULT: worker-observed phase and null-or-echo triple, admitted against the host possible-phase set since the last admitted worker frame; the worker reads Hello before writing any frame.",
        "none", "Members had no types (R3-G14). A host-receipt phase is unsatisfiable when OpenUniverse, SnapshotManifest or Analyze is in flight (reviewer traces through protocol3_run).",
        ["rust3-cancel-types", "rust3-phase-vocabulary", "vectors:RUST3-PROVIDER-FAULT", "p3-race-traces-admitted-by-owner-table"]),
    row("SUCC-RUST3-OBSERVED", ["rust-semantic major 3"],
        [t("rust2", R2 + "payloadSchemas.BudgetExhaustedV2 (observed)")],
        "value-stated", "observed = limit + 1, as TS2 BudgetExhaustedV1 states and rust2 deterministicBudget checked increments imply.",
        "none", "R3-G14 residue.", ["rust3-observed-limit-plus-one", "vectors:RUST3-BUDGET-EXHAUSTED"]),
    row("SUCC-RUST3-SNAPSHOT-ENTRY", ["rust-semantic major 3"],
        [t("rust2", R2 + "definitions.SnapshotEntryV2.variants")],
        "types-stated", "contentSha256 DigestHex, executable bool, targetBytes non-empty byte string.",
        "none", "rust2 subjectsAlgorithm consumes contentSha256 as the manifest digest; requestProjection keeps symlink target BYTES in the manifest; schemaLanguage.bytes is the only byte type (R3-G15).",
        ["carrier-member-lists"]),
]

FALSE_GAPS = [
    {"gap": "R3-G13 StageResultV2 has no successor", "refutation": "native-evidence.md §9.7 names StageResultV2.coverageCommitment among recipes unchanged over CoverageResultV3 values; the §0 line 129 row supersedes its value domain, not its members."},
    {"gap": "R3-G15 chunk/seal integer types only derivable", "refutation": "rust2 schemaLanguage.integer plus canonicalCbor.closedDataModel make every integer member uint64; limitPolicy.arithmetic states the checked uint64 law."},
    {"gap": "TS2-G3 stageId bound", "refutation": "dispatch-binding expectedStageId maxLength 255 is defined as StageRequestV1.stageId / StageRequestV2.planStage.stageId and §9.6 requires a dispatch binding for each requested stage."},
    {"gap": "TS2-G6 / R3-G6 payload selection without tag", "refutation": "Handshake law factBatch.negotiated and startup preAnalyzeUnavailable.phase select the payload from host state; the carrier input publishes the two selectors and adds no wire tag."},
    {"gap": "TS2-G9 wireSchemaCommitment for major 2", "refutation": "No TS2 Hello member carries a contract digest (handshake frameAndMajor); the historical commitment stays recomputable over unchanged bytes and is not a wire field."},
    {"gap": "R3-G18 common-control owner", "refutation": "Closed by root: docs/implementation/m1/control-source-route.v1.json pins control-completion.schema.v3 through the reviewed freeze chain. Out of scope for provider carriers."},
    {"gap": "R3-G17(c) T016/T020/framePrecheck missing from P3", "refutation": "P3 ownedByProse assigns payload validation to prose/schemas; the retained rust2 guards are payload admission applied before matching, with the same FAULT outcome."},
    {"gap": "Envelope/DependencySourceChunk/Accepted names (R3-G3)", "refutation": "The wire carries no record names; private type names are implementation choices, not version changes."},
]

REVIEW_RESOLUTIONS = [
    {"id": "RF-1", "resolution": "Method inputs frozen under inputs/ (byte copies, pinned); the builder reads only inputs/; check.py reads only the subject, pinned architecture files and the reference environment; isolation-result.json runs check/selftest from a fresh copy of subject-files.json inputs.", "checks": ["subject-inputs-pinned", "field-coverage-matches-inputs", "isolation"]},
    {"id": "RF-2", "resolution": "ARCH_PINS is the observed complete closure (35 files incl. resolved-inputs.v2 for CVE1). check.py verifies every pin before importing any model, installs an open-audit hook, forces a private pycache prefix, and fails on any architecture read outside the pin set or any architecture .pyc read; reference-environment.json records and asserts package versions.", "checks": ["closure-architecture-reads-pinned", "closure-no-architecture-bytecode", "closure-no-hidden-tmp-reads", "reference-environment-matches", "cve1-tags-match-owner", "extern-namespaces-match-generator-options"]},
    {"id": "RF-3", "resolution": "Root decision applied: entries 0..256, outputOrdinal 0..255; PREPARED-V3-WIRE-LIMIT refuses before spawn as request-rejected REQUEST.PRECONDITION_FAILED native.prepared-output-exceeds-wire-limit.", "checks": ["limit-literals", "vectors:PREPARED-V3-WIRE-LIMIT"]},
    {"id": "RF-4", "resolution": "RUST3-PROVIDER-FAULT: worker-observed phase/null triple, host possible-phase set since the last admitted worker frame; reviewer race traces are vectors.", "checks": ["vectors:RUST3-PROVIDER-FAULT", "p3-race-traces-admitted-by-owner-table"]},
    {"id": "RF-5", "resolution": "Normative lexical rules canonical-path-segments / logical-path-segments applied to every path member including dependency sources; declared ECMA-262 u-mode dialect and mandatory lowering list; newline vectors.", "checks": ["vectors:CANONICAL-PATH-ADMISSION", "vectors:TS2-LOGICAL-PATH-ADMISSION", "pattern-lowering-required-declared", "native2-canonical-path-pattern-weaker"]},
    {"id": "RF-6", "resolution": "Tuple order (name, version, sourceId, path); exact key join; scoped set admission refusing name/version bytes <= 0x20 and key > 4096; minScalars 4; sourceId spaces and empty preserved.", "checks": ["vectors:DEPSRC-CUSTODY", "vectors:PACKAGE-KEY-JOIN", "vectors:DEPSRC-SET-KEY-CONSTRAINTS", "package-key-bounds-derived-from-owner"]},
]
