from pathlib import Path
import hashlib,json
B=Path('/tmp/opensip-design-corrections');L=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews');O=B/'claude-independent-design.v32';assert not O.exists();O.mkdir();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();mf=L/'candidate-subject.v32.json';m=json.loads(mf.read_bytes());p=json.loads((L/'candidate-subject.v31.json').read_bytes());before={r['path']:r for r in p['files']};after={r['path']:r for r in m['files']};delta=[{'path':x,'beforeSha256':before.get(x,{}).get('sha256'),'afterSha256':r['sha256'],'bytes':r['bytes']} for x,r in after.items() if before.get(x,{}).get('sha256')!=r['sha256']];(O/'root-delta31-to32.json').write_text(json.dumps({'standing':'Root inventory only; independently verify source ancestry and meaning.','files':delta,'removed':sorted(set(before)-set(after))},indent=2)+'\n')
prompt=f'''Continue the SAME independent reviewer origin ce3dec3b-0620-44ec-86e6-129b0e25cb1b, now reviewing exact frozen source32. You have authored no source in this lineage. Your31 ACCEPT and later bounded glob/repair review are historical, unchanged; neither automatically accepts these integrated bytes. Write only this NEW runtime; frozen source, all historical runtimes and live repository are read-only. No implementation, activation, commit or push.

VERIFY FIRST
Manifest {mf} SHA256 {sha(mf)}; archive {L/'candidate-source.v32.tar.gz'} SHA256 {sha(L/'candidate-source.v32.tar.gz')}; snapshot {m['snapshotRoot']}, {m['fileCount']} files, {m['totalBytes']} bytes. Verify all hashes/sizes and no extras, archive equality, and ancestry from your31. Derive your own delta; root-delta31-to32.json is an inventory, not approval. Source author origins eaa8276c-dc65-4d26-8ca2-703b345698f9,36a89be8-3442-4edb-90d8-a6fd959a437c,0aa529b3-0da1-44b1-b2b9-dbcd9f1bd206,329a5132-ee66-4303-97a9-b9ebd1b7ffc0,919c766d-f2d0-4cfa-abaa-9d7425d9395f remain forbidden independent acceptors. You are none of these.
Interpreter /tmp/opensip-architecture-review-env/bin/python -I -B; system python3 for stdlib orchestration only. Use disposable exact verified source copies for report writers. Preserve every failed invocation/probe honestly. Do not rerun completed passing tests without changed inputs, failures or unresolved issues justifying them.

CURRENT SOURCE CHANGES TO READ AND ASSESS
1. The repair closed-world selection owner at workflows/repair_closed_world_selection.v1.py is new since31. The full current module, workflow chapter6 law, both repair-schema annotations, native chapter link, workflows_model.v1/v3 selection seam, new checker controls and default-off evaluator_graph_fixture.v3 symbol_only_second_program extension require substantive assessment. Read complete changed regions and cross-owner consequences. Required retained EnumerationPlan extents plus candidateSourcePaths supplies selected program ownership; target ALL matched occurrences and extra source-path scope witnesses are unioned; selected unavailable overlapping bindings give typed unresolved ownership, unselected programs are not inferred. Every relevant sourceUniverse native Coverage participates, independent of recipe relation requirements; non-vacuous conjunction and deterministic display reduction/remedies are separately defined. Assess actual correctness, conservatism and completeness, not root/author agreement.
2. Your bounded review confirmed RRS-A1 and RRS-A2 against the older captured draft. Read completed author v2 reports, exact nine-file capture, and root-repair-scope-correction.v1/assessment.md under LIVE reviews. Author SID919c is coauthor, not independent. Root read entire source selector and prose/handoff but did not claim all174KB checker lines or whole structured authorJSON. Root integrated the final author bytes, then corrected evidence scope in the candidate checker; the original author reports remain unchanged.
3. IMPORTANT RRS-A3 evidence scope: fully admitted asymmetric Run896bef61... proves source-path scopes can omit a selected symbol owner. derive(targets=[]) isolates ownership; empty targets is NOT a legal repair descriptor (minItems1). The sole matched finding belongs to the dissenting symbol universe, so a valid target already selects it through the old target-occurrence join. Author claims “old law admits delete” and “discriminating through current preview” overstate this particular control. Root changed the projection control to real nonempty targets and labels its limits. _cw_preview still uses historical synthetic project/tree/snapshot/trust/requirements and inherited major-1 descriptor constructor, with a current selection hook. It proves integration of the gate with fully admitted native evidence; it does NOT prove a current schema-admitted descriptor, real Run snapshot/preimage join, or a lawful old-preview bypass. Assess whether the bounded design/reference evidence is sufficient and honestly scoped; do not misreport invalid adapter input as a product bypass, and do not demand product repair implementation as a design acceptance prerequisite. Identify a genuinely needed narrow reference correction if this boundary remains materially misleading.
4. New portable glob contract foundation/glob-pattern-contract.v1.md, two common schema annotations, atom-contract/checker and workflow-projection/main-chapter links. Your completed bounded review found no mismatch across finite differential checks; it was NOT a blind-prose-only origin (you had author/reference code). Actual matcher implementation is unchanged. Fullstring/case/scalar/emptysegments/whole-segment terminal **/literal brackets and owner-specific include/default laws need one coherent normative reading. Inspect the new main-chapter link as well as the five earlier files.
5. Planning inventory descriptions use EXISTING evaluator/policy.rs for shared portable glob and EXISTING host/repair.rs for retained program/Coverage selection. Two existing implementation-coverage verification methods changed accordingly. No new package or planned filename:198paths,20packages,320mappings,54planned unexecuted recovery cases. Current implementation-normative-inputs.v3 binds29inputs; layer2/original25/history are preserved. Assess exact layer3 and regenerated chapter14/build plan, report/module boundaries and M0–M6 sequencing. All five pin ledgers include the new normative glob owner and pin-only repair reference module. A reference .py is not a blind normative input.

CORRECT YOUR31 RECORD IN THIS SUCCESSOR
Read root-independent31-assessment.v1 from LIVE reviews and complete independent31-advisory8-evidence.v1 bundle. All16 DR011R01..16 rows had empty currentOwnerFiles despite the every-row actualpaths claim: supply real current owners/selectors. RES-EP13-13 checker changed27→28; distinguish unchanged normative law from changed FILE and fresh/inherited reading. A7 pointer stays unchanged while native-schema FILE changed; no cosmetic v2→v3 churn is required because referenced definitions are byte-identical. A8 exact original29 failed receipt/native cases and30 replacement bytes are now in the10-file bundle; assess actual one64hex replacement, preserving failure and distinguishing new custody from retroauthentication. Enumeration joins occur AFTER structural open_run_closure; correct the prior inverse explanation, while retaining join-only control scope. Finite hash controls never prove global injectivity. Your bounded remedy probe used pseudoIDs and unequal source/target on same-only file relation, so it did not demonstrate two lawfully admitted records. Root accepts the structural missing diagnostic coordinates finding, not that invalid-record claim.

AUTHOR PACKAGE8
{B/'claude-author-package-successor.v8'} artifact manifest SHA256 {sha(B/'claude-author-package-successor.v8/artifact-manifest.json')}. Current source binding32; exact exports originally constructed on30, preserved unchanged through31/32. Native schema unchanged; final source reference fixture extension is default-off. Verify package/member hashes and independently replay all13 exact Run/control outcomes through BOTH open_run_closure and close_run, then automatic7query checks. Assess semantics and scope. Seven positives/three false-result negatives/three binding controls; only TS checkpoint helper-v-owner, six owner-derived self-consistency. Exists/none only, and/or/not unexercised, count-at-most/all-covered unimplemented in partial helper; two-binding incomplete/singleexplicit. Property/mixed-universe probes remain separate. Reuse your actual31 construction evidence only with explicit exact-input equality and inherited standing; do not relabel historical commands as32. F06 stays a limit, F14 informational. All30 residual proposals remain author/PENDING, not grades.

FINAL OUTPUT AND ACCEPTANCE SCOPE
Write complete substantive review.md AND review.json with verifiedManifest/current source SHA, verdict, newMustIssues[], newShouldIssues[], advisories[], exact probe receipts, resolvedSinceV31/record corrections, and individually reasoned keyed maps14F,30evaluationResidualDispositions,16arDispositions,15fwDispositions,27inheritedResidualDispositions,5scopedReviewOwnerDispositions. Each row needs actual current owner paths/selectors, evidence and limits, and current status without stale contradictory inherited prose. Unchanged readings may be inherited ONLY after exact-byte verification and labelled as such; read every changed owner region. Root six suite results are evidence to assess, not authority. Independently run relevant changed checks/planning groups and remaining source-bound regressions as justified. Do not silently drop previously required families or scope the whole review to only two new changes.
TCB-SCOPE-01: assess once with13dependent rows and joint reopening consequence. All28condition2 obligations remain;32product qualification gates and54recoverycases unperformed, condition5NOTMET. D9published successor stays assigned implementation obligation on DR007/DR011R08. DESIGN review only: every mapped row appliedByThisReview=false/finalApplicationOutcomeGranted=false. No final application grade. Actual blind origin is a separate requirement: do NOT read any consumer runtime/output/reports, no blind acceptance claim. Final application review/activation are separate.
Complete rather than progress-only handoff unless an actual quota/tool blocker prevents it. No acceptance from author claims, root summaries or expected outputs. Disagree substantively where evidence warrants it.
'''
(O/'prompt.md').write_text(prompt)
s=(B/'claude-glob-repair-bounded-review.v1/launch.py').read_text();start=s.index('cmd=');end=s.index('\nstart=time.time()',start);cmd=['/Users/sb/.local/bin/claude','--safe-mode','--strict-mcp-config','--model','opus','--resume','ce3dec3b-0620-44ec-86e6-129b0e25cb1b','--permission-mode','dontAsk','--tools','Read,Glob,Grep,Bash,Write,Edit','--allowedTools','Read','Glob','Grep','Write','Edit','Bash(python3 *)']
for path in [m['snapshotRoot'],str(B/'claude-author-package-successor.v8'),str(B/'claude-independent-design.v31'),str(B/'claude-glob-repair-bounded-review.v1'),str(L),'/tmp/opensip-architecture-review-env']:cmd+=['--add-dir',path]
cmd+=['--output-format','stream-json','--verbose','-p'];s=s[:start]+'cmd='+repr(cmd)+s[end:];(O/'launch.py').write_text(s)
(O/'dispatch.json').write_text(json.dumps({'standing':'Prepared exact-source32 independent successor prompt; no execution, acceptance or activation inferred.','sessionId':'ce3dec3b-0620-44ec-86e6-129b0e25cb1b','subjectManifestSha256':sha(mf),'promptSha256':sha(O/'prompt.md'),'deltaFiles':len(delta)},indent=2)+'\n');print('Prepared independent32',len(delta),'delta files')
