#!/bin/zsh
# Dispatch the F1 recommendation review to Codex. Usage: dispatch-F1.sh <pane> [round]
set -e
cd /Users/sb/code/opensip-ai/opensip
PANE=${1:?pane}; R=${2:-1}
PK=DECISION-PACKETS/F-docs-rewrite.md
if [ "$R" = 1 ]; then CL=DECISION-PACKETS/F-docs-rewrite.claude-recommendation.md; OUT=DECISION-PACKETS/F-docs-rewrite.codex-recommendation.json
else CL=DECISION-PACKETS/F-docs-rewrite.claude-recommendation.r$R.md; OUT=DECISION-PACKETS/F-docs-rewrite.codex-recommendation.r$R.json; fi
PKS=$(shasum -a 256 $PK | cut -c1-64); CLS=$(shasum -a 256 $CL | cut -c1-64)
if [ "$R" = 1 ]; then
DP="Independent adversarial review of one orchestrator recommendation (DECISION-PACKETS/RECOMMENDATION-PROTOCOL.md). Refute, do not confirm.
Item F1 (documentation rewrite after sealing): read DECISIONS-NEEDED.md item F1 (L62-L70), the decision packet $PK (sha256 $PKS; ~108 KB — read all of it, in chunks) and Claude's recommendation $CL (sha256 $CLS).
The packet was built read-only by subagents from file 08, COORD and docs/coop/artifacts at HEAD 4abb961 and adversarially verified (its verifier's 15 findings are applied; see DECISION-PACKETS/.verify/F-docs-rewrite.md.findings.json). Re-check against the bytes every packet claim the recommendation relies on — at least: the page counts (26 contract pages / 31 or 32 artifacts per the packet's stated rule, 32 gate pages, 28 final occupancies, 43 named corpora, 49 ADR groups of 72 BINDING-DESIGN entries, 127 pages), 729 of 760 _dispatch.*.txt tracked (git ls-files docs/coop/artifacts | grep -c _dispatch vs ls), the five conditions and their state at 08:L414-L418, the D-010/C-D010 wording-amendment precedent (D-001 pin-note COORD L119-L121), the D-033 path+digest convention (COORD L1820), the sealing-entry form (D-000 / D-054 / D-132), the D-SEAL draft's negations, the claim that git mv leaves untracked files behind, and the A/B/C amendments' factual premises (DR-104 SATISFIED at D-236 with policy D-012 / integration contract v4 / negative-test corpus v1; DR-G21 remasured at D-292; the D-056 + D-133 pair as one ADR group).
Then form your own position on each of the ten owner options in packet §6 and on Claude's three amendments (pilot before the seal, tooling now, sizing as ceiling), and on the sequence (seal → git mv → derived tree). Say where Claude is wrong, where the packet is wrong, and what you would recommend instead. Do not decide anything for the owner; do not move or edit anything under docs/; do not commit.
Write ONLY $OUT, shape {\"item\":\"F1\",\"verdict\":\"AGREE|DISAGREE|AGREE-WITH-AMENDMENT\",\"recommendation\",\"rationale\",\"refutations\":[{\"claim\",\"evidence\",\"holds\":true|false}],\"amendments\":[],\"optionPositions\":{\"6.1\":\"…\",\"6.2\":\"…\",\"6.3\":\"…\",\"6.4\":\"…\",\"6.5\":\"…\",\"6.6\":\"…\",\"6.7\":\"…\",\"6.8\":\"…\",\"6.9\":\"…\",\"6.10\":\"…\"},\"confidence\"}. Final chat: \"F1: <verdict>\"."
elif [ "$R" = 3 ]; then
DP="Round 3 of the F1 recommendation exchange (DECISION-PACKETS/RECOMMENDATION-PROTOCOL.md; this is the last round — no round after 3). Read Claude's reply $CL (sha256 $CLS), which adopts your three round-2 amendments and six further repairs found by an independent re-verification (DECISION-PACKETS/.verify/F-docs-rewrite.md.reverify2.json). The packet $PK was corrected accordingly (new sha256 $PKS; its §0.3 table lists each repair): re-read the §2 legend, §2/§2.1/§5.1 (ARCHIVE.md as a fifth root page; 128 pages), §4.1-§4.5, §4.8, §6.5-§6.10, §7 and §0.3, and check that the four-state model (<P> measured, <R> measurement-record commit, <S> seal, <M> move), the push-per-decision steps, the <S>-anchored archive and mapping, the --ignored overlay guard, the ordered/qualified reversibility, and the §0.3 provenance (29d7a11c…) are faithful to the bytes and to your evidence, and that no defect you named survives anywhere. Write ONLY $OUT, same shape as your previous rounds, verdict AGREE | DISAGREE | AGREE-WITH-AMENDMENT (list only amendments that still stand; if none, AGREE). Do not edit anything under docs/; do not commit. Final chat: \"F1 r3: <verdict>\"."
else
DP="Round $R of the F1 recommendation exchange (DECISION-PACKETS/RECOMMENDATION-PROTOCOL.md; no round after 3). Read Claude's reply $CL (sha256 $CLS), which answers each refutation and amendment of your previous round. The packet $PK was CORRECTED per your refutations 7, 8, 10, 11, 12, 13, 14, 15 and 20 and amendments 1-5 (new sha256 $PKS; its new corrections table lists each repair): re-read its §0.2/§0.3, §4.1-§4.5, §4.8, §6.2, §6.5-§6.8, §6.10 and §7 and check that the repairs are faithful to the bytes and to your evidence, and that no defect you named survives elsewhere in the packet. Re-check every new factual claim in Claude's reply against the bytes. Write ONLY $OUT, same shape as your previous round, verdict AGREE | DISAGREE | AGREE-WITH-AMENDMENT with only the amendments that still stand. Do not edit anything under docs/; do not commit. Final chat: \"F1 r$R: <verdict>\"."
fi
herdr pane run "$PANE" "$DP" >/dev/null && sleep 4 && { herdr wait agent-status "$PANE" --status working --timeout 30000 >/dev/null 2>&1 || { herdr pane send-keys "$PANE" Enter; sleep 3; herdr wait agent-status "$PANE" --status working --timeout 30000 >/dev/null; }; } && echo "codex($PANE): working on F1 round $R (packet $PKS, claude $CLS)"
