from pathlib import Path
import json,hashlib,subprocess,datetime,sys
root=Path.cwd();version=sys.argv[1];consumer_version=sys.argv[2];source=root/f'docs/coop/design-corrections/reviews/candidate-subject.{version}.json';manifest=json.loads(source.read_text());sha=hashlib.sha256(source.read_bytes()).hexdigest()
review=Path(f'/tmp/opensip-design-corrections/post-reset-review.{version}/review.json');rd=json.loads(review.read_text());assert rd.get('verdict',rd.get('overallVerdict'))=='ACCEPT', 'Independent acceptance required before consumer B'
for key in ('newMustIssues','newShouldIssues'):
 assert type(rd.get(key)) is list and not rd[key], 'Missing, malformed or unresolved MUST/SHOULD findings prevent blind promotion even if headline says ACCEPT'
assert rd['subject']['manifestSha256']==sha, 'Independent review must bind exact parent manifest'
response=json.loads((review.parent/'response.json').read_text());assert response.get('is_error') is False, 'Actual successful independent CLI response required'
assent_path=root/f'docs/coop/design-corrections/reviews/codex-post-reset.v1/design-assent.{version}.json'
assent=json.loads(assent_path.read_text())
assert assent['designManifest']['sha256']==sha and assent['assent'].startswith('ACCEPT-DESIGN'), 'Actual Codex assent to the same frozen subject required before blind promotion'
assert assent['actualIndependentClaudeReview']['sha256']==hashlib.sha256(review.read_bytes()).hexdigest(), 'Codex assent must identify the actual independent review'
assert assent['actualIndependentClaudeReview']['sessionId']==response['session_id'], 'Codex assent must bind the successful actual independent session'

kit=Path(f'/tmp/opensip-design-corrections/consumer-b.{consumer_version}/subject');out=kit.parent/'output';kit.mkdir(parents=True,exist_ok=False);out.mkdir()
paths=[]
for row in manifest['files']:
 p=row['path']
 if p.startswith('docs/coop/design-corrections/reviews/'):continue  # never leak earlier blind kits, author-source copies or review material
 wanted=p.startswith('docs/v2/contracts/product-v1/') or (p.startswith('docs/coop/design-corrections/') and (('/schemas/' in p and p.endswith('.json')) or (p.startswith('docs/coop/design-corrections/foundation/') and 'schema' in p and p.endswith('.json'))))
 wanted=wanted or (p.startswith('docs/coop/design-corrections/') and '.schemas.' in p and p.endswith('.json'))
 wanted=wanted or p in ['docs/coop/design-corrections/workflows/command-inventory.v1.json','docs/coop/design-corrections/public-detail-registry.v1.json','docs/coop/design-corrections/native/native-capability-matrix.v2.json','docs/coop/design-corrections/native/capability-manifest-domains.v2.json','docs/coop/design-corrections/current-source-map.proposed.md','docs/coop/artifacts/resolved-inputs.v2.json','docs/coop/artifacts/fact-plane.v1.json','docs/coop/artifacts/fact-identity-policy.v2.json','docs/coop/artifacts/permission-truth-tables.v9.json','docs/coop/completion/security-completion.v8.md','docs/coop/completion/lifecycle-carrier.contract.v2.json','docs/coop/artifacts/delivery.v4.json','docs/coop/artifacts/c2-plan-stage-schema.v4.json','docs/coop/artifacts/d9-exit-contract.v1.14.json','docs/v2/architecture/13-evidence-workflows-and-product-contracts.md']
 wanted=wanted or (p.startswith('docs/coop/completion/security-schemas.v8/') and p.endswith('.schema.json'))
 if wanted:
  raw=(Path(manifest['snapshotRoot'])/p).read_bytes();assert hashlib.sha256(raw).hexdigest()==row['sha256'];dest=kit/p;dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(raw);paths.append(row)
(kit/'consumer-input-manifest.json').write_text(json.dumps({'standing':'Exact normative subset for blind implementer; no author models/cases/review outputs','parentSubjectSha256':sha,'files':paths},indent=2)+'\n')
prompt=f'''You are actual Claude in a completely fresh BLIND CONSUMER B session for OpenSIP DR-011-R10. You have authored none of this design, have no prior review context, and must independently reconstruct what an implementer needs. User specifically requires actual Claude and Codex design alignment, with this separate blind litmus before implementation. Do not spawn agents. This is only a disposable design reference exercise, not product implementation.

Your ONLY design inputs are in {kit}. Begin with consumer-input-manifest.json; verify all hashes. It is a subset of the exact accepted parent subject SHA256 {sha}. Read the five contracts via docs/v2/contracts/product-v1/README.md and their normative schemas/registries in this kit. The current-source map is provided for scope. Read the index’s explicit distinction between normative selector tables and governance standing: readiness/review records are intentionally excluded, never needed to invent a semantic recipe. The complete retained resolved-inputs.v2 canonicalValueEncoding supplies all eight CVE1 types for constructing capability manifests. Do NOT access the original repository, author Python/TypeScript reference models, fixtures/cases/goldens/reports, prior reviews, or other /tmp/opensip-design-corrections directories. The kit includes the explicitly retained normative DELIVERY v4 capability-manifest recipe, C2 operational identity grammar, D9 contract and architecture13 evidence restrictions. Retained fact-plane relation payload schemas, fact normalization policy, permission truth tables and security metadata/canonicalization/lifecycle definitions are included as normative dependencies. Apply the five successor contracts where they explicitly replace an inherited selector. Historical review narratives inside inherited normative documents are provenance only and grant no current acceptance; do not follow links to reviews, models or fixtures. Historical/review links are provenance only; do not follow them. Embedded normative examples are illustrations, not an oracle: independently choose and compute your vectors. If an essential normative dependency is missing from the kit, identify the exact path/selector as an input-custody problem rather than assuming the repository design omitted it. No author oracle or expected results are supplied. You may read the installed Python standard library/jsonschema and use /tmp/opensip-architecture-review-env/bin/python -I -B. Write your own disposable reference code and outputs ONLY under {out}. Do not edit the input kit.

Independently reconstruct, with exact owning contract/schema citations:
1. Zero-config repository discovery -> typed config/source -> invocation/step/attempt lifecycle -> analysis Plan -> native facts/Coverage/view -> proof verification -> Evidence/EvaluationSeal/Run -> durable receipt and current availability. Distinguish semantic identities from operational authority and mutation/analysis steps.
2. Build your OWN canonicalization and H identity helper directly from prose, then independently authored minimal descriptor vectors. Exercise exact integer/duplicate/string admission; semantic-field changes vs operational timestamp/request-id changes; source/Plan/View/Proof/Evidence/Seal/Run acyclic construction and joins. Build complete minimal positive Run descriptor graphs for BOTH TypeScript and Rust using your own synthetic trusted observations, with nonempty selected native contexts and actual language-specific universe/fact/Coverage paths. A Rust context merely present in a TypeScript graph does not exercise the Rust universe path. Include an ordinary TypeScript project that reads node_modules and resolves bare specifiers, with its retained configuration graph and dependency layout; also exercise synthesized configuration, an explicitly selected custom-named project config inheriting from multiple ordered bases (including repeated bases whose precedence must be retained), and JavaScript config inheriting a shared base with another filename. Use actual registered relation, native Coverage and imported payload records. Also construct a JavaScript clone body through the TypeScript analyzer universe, distinguishing actual body language from provider identity. Build at least one complete file-fact Run with inventoried path/hash/length checks and independently reconstructed clone body identities at L0 and a normalized level from the retained body grammar, with level-specification/source/language-version custody and actual negative vectors. Include a mixed-edition Rust workspace, including a target-specific edition differing from its package default, with body-specific dialect selection, the same physical file under distinct explicitly selected target editions, ambiguity/partial-enumeration handling including an empty clone view that must not claim complete Coverage from partial ownership, a valid # marker directory, stable body identity when only ownership selection changes without changing effective dialect, and a representative large edition map, deriving the bounded version component from the exact admitted compiler context and body provenance. Enumeration completeness is distinct from resolution completeness; do not invent a resolved rung for file facts. Reconstruct generic mutation replay scope and the distinct repair-apply key, and a complete pinned-purge refusal. Exercise at least one refused hidden/mismatched input per language, and reconstruct native dependency/configuration H preimages from the normative recipes. Schema validation may use the kit. Do not copy author code or choose expected outputs by observing author implementation.
3. Work through current-baseline audit and missing/evidence-changed/empty-result comparison, explicit test/preparation and repair authorization, purge/replay and required output failure. Write independent public termination examples validated from schemas, and explain which subsystem owns every decision.
4. Independently identify any missing recipe, conflicting type/field vocabulary, circular authority ordering, ambiguous default or required implementation choice that would force you to INVENT design. Distinguish algorithm freedom explicitly left to implementation from a missing public/semantic contract. If you cannot build a promised vector from these normative inputs, report exact blocker rather than adjusting expected meaning or importing author code. Real OS/compiler/crypto/SQLite measurements are future qualification; do not demand product already exists. Synthetic TCB observations are assumptions, never native enforcement proof.

Deliver blind-review.md AND blind-review.json in output directory: ACCEPT-RECONSTRUCTABLE or CHANGES_REQUIRED (or actual BLOCKED), input manifest/hash verification, reconstruction, every independent vector and result, specific MUST/SHOULD/advisory issues with exact selectors, what required invention, and limitations. Retain source and machine-readable vector outputs. Give a substantive verdict, not a checklist count. Any remaining MUST/SHOULD design gap requires CHANGES_REQUIRED. Include top-level newMustIssues and newShouldIssues arrays, both empty only when no unresolved required finding remains; report nonblocking advisories separately. No claim of full product qualification or implementation authorization. Work thoroughly now.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Bash','Write','--strict-mcp-config','--output-format','json']
proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=kit,start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close();(out/'process.json').write_text(json.dumps({'pid':proc.pid,'parentSubjectSha256':sha,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(proc.pid,len(paths))
