from pathlib import Path
import json,hashlib
r=Path.cwd();dc=r/'docs/coop/design-corrections';rp=dc/'reviews/post-reset-review.v10/review.json';review=json.loads(rp.read_text());resp=json.loads(rp.with_name('response.json').read_text());assert resp['is_error'] is False;assert review['verdict']=='CHANGES_REQUIRED' and not review['newMustIssues'] and [x['id'] for x in review['newShouldIssues']]==['v10-S1'];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
ref={'path':str(rp.relative_to(r)),'sha256':sha(rp),'sessionId':resp['session_id'],'verdict':review['verdict'],'newMustIds':[],'newShouldIds':['v10-S1']}
f=review['newShouldIssues'][0]
d={'standing':'PROPOSED v11 correction in progress; actual independent v10 finding retained. Coauthor disposable delta not yet released/applied.','predecessorManifestSha256':'82c1be11d3b61908b2a45ebb6e59e71bb5cb31d8450a96a61857ced430e786fd','actualPredecessorReview':ref,'priorCorrections':{'path':'docs/coop/design-corrections/post-reset-dispositions.v10.proposed.json','sha256':sha(dc/'post-reset-dispositions.v10.proposed.json'),'standing':'Completed v10 independently resolves v9-S1 and prior effective-annotation cases but finds remaining same-path merge order dependence.'},'items':[{'id':f['id'],'severity':f['severity'],'status':'AUTHOR-CORRECTION-IN-PROGRESS-DISPOSABLE-COPY','owner':'actual Claude coauthor v9 + Codex integration','finding':f['title'],'reviewEvidence':dict(ref,selector='/newShouldIssues/0'),'intendedCorrection':'Preserve missing annotation as an explicit monotonic fact across every same-path merge. Both captured orders must refuse at RELATION_DIGEST_UNANNOTATED, all-lawful controls must admit, and new regressions must actually reach the merge and discriminate pre/post source.','limitation':f['scope']}],'advisoryCorrections':[{'id':'v10-A1','status':'PROPOSED-NORMATIVE-TEXT-AWAITING-COAUTHOR-ASSESSMENT','intent':'Name conflict and unaddressable claimed-join refusal in the existing normative relation law section.'},{'id':'v10-A2','status':'PROPOSED-NORMATIVE-TEXT-AWAITING-COAUTHOR-ASSESSMENT','intent':'Make supported effective annotation inheritance/terminal exclusion/order independence explicit in the normative identity contract included in the blind kit; registered schema document bytes remain unchanged.'},{'id':'v10-A3','status':'AUTHOR-REGRESSION-PENDING-FINAL-SOURCE-RECHECK','intent':'Use actual before/after source evidence and cases reaching same-path collisions, including a later annotated sighting after missingness. Counts alone are not coverage proof.'}],'advisoryAccount':{'path':'reviews/codex-post-reset.v1/advisory-application-account.v11.proposed.json','standing':'28 carried actual advisories, prospective dispositions; no independent v11 acceptance or assent.'},'implementationAuthorized':False,'readinessChanged':False,'productQualification':False,'remaining':['released correction and agreed normative wording applied with exact custody','five root final-source rechecks, fixture provenance, pins and six commands','new frozen successor at zero unresolved MUST/SHOULD independent review','new fresh blind on accepted normative bytes','complete independently reviewed application/readiness reconciliation']}
p=dc/'post-reset-dispositions.v11.proposed.json';assert not p.exists();p.write_text(json.dumps(d,indent=2)+'\n')
a=json.loads((dc/'reviews/codex-post-reset.v1/advisory-application-account.v10.proposed.json').read_text());a['standing']='Prepared 28 carried v5-v10 advisory dispositions; no v11 acceptance/assent. Normative A1/A2 wording and merge-regression evidence remain pending final integration and new independent review.'
text={'v10-A1':'Proposed correction now: explicitly name conflicting effective annotations and unaddressable claimed joins as refusals in the normative identity contract, without changing schema payload types or raw registered schema bytes. Actual coauthor wording assessment and fresh independent acceptance remain required. Historical advisory severity unchanged.','v10-A2':'Proposed correction now: specify effective annotation inheritance, intermediate aliases, terminal-type exclusion, per-occurrence coverage and visit-order independence in the normative identity contract supplied to the next blind kit. The blind implementer must not need author Python to discover this rule. Actual wording still requires coauthor assessment and independent acceptance.','v10-A3':'The successor must add cases that actually reach same-path aggregation, prove refusal in both orders and preserve all-lawful controls, with before/after source measurements and root rechecks. Existing counts are not asserted as code-path coverage; historical zero-collision instrumentation remains unchanged.'}
for i,x in enumerate(review['newAdvisories']):a['items'].append({'id':x['id'],'reviewEvidence':dict(ref,selector='/newAdvisories/'+str(i)),'disposition':text[x['id']]})
assert len(a['items'])==28;p=dc/'reviews/codex-post-reset.v1/advisory-application-account.v11.proposed.json';assert not p.exists();p.write_text(json.dumps(a,indent=2)+'\n')
print('Prepared v11 actual-finding and28-advisory accounts; no candidate source edited or acceptance asserted.')
