import hashlib
S='/private/tmp/opensip-design-corrections/claude-root-binding-correction.v1/scratch'
NL=chr(10)
def sha(fp): return hashlib.sha256(open(fp,'rb').read()).hexdigest()
p1=S+'/src25/docs/v2/contracts/product-v1/native-evidence.md'
s1=open(p1,encoding='utf-8').read(); b1=sha(p1)
anchor1='- **U-1 (one unit per directory and language family)** A directory holding'
assert s1.count(anchor1)==1, s1.count(anchor1)
U0='- **U-0 (internal root representation, normative)** `rootPath` and every\n  `memberPackageRoots[]` entry are the **internal** relative directory form and nothing\n  else. `rootPath` is the empty string `` for the project root, or a canonical relative\n  directory (`#/$defs/InternalUnitRootV1`); a member package root is always a NON-EMPTY\n  canonical relative directory (`#/$defs/CanonicalRelativeDirV1`), because a member is\n  always strictly inside its workspace root. A canonical relative directory is one or more\n  `/`-joined non-empty segments with no leading or trailing `/`, no empty segment, no `.`\n  or `..` segment, no NUL and no backslash. `CanonicalPath` is deliberately NOT this\n  grammar: it admits a trailing `/` and an interior empty segment (`a//b`), neither of\n  which is canonical for a directory used as a membership prefix.\n  `.` is the **external** sentinel only, on both edges: Config2 `discovery.workspaceRoots`\n  and CLI `--workspace-root` inbound (`normalize_explicit_root`, `.` -> ``), and the\n  outward `workspaceRoot` of the shared scope record and of enumeration cells\n  (`spell_root`, `` -> `.`). A retained `WorkspaceUnitV2` is **never** normalized after\n  retention, because `rootPath` is consumed as an exact string prefix by U-3 membership, by\n  relative-path slicing and by the deepest-unit `len(rootPath)` ranking.\n  A unit whose root is not in internal form is refused **before** membership, slicing or\n  enumeration binding reads it (`admit_unit_roots`; internal decision key\n  `NATIVE_UNIT_ROOT_REPRESENTATION`, and `ENUMERATION_MEMBERSHIP_UNIT_ROOT` when the same\n  decision is reached through enumeration admission). This is an INTERNAL host-invariant\n  decision and adds no public detail code; a malformed EXTERNAL root keeps its existing\n  typed public refusal `native.explicit-root-grammar` (CONFIG.INVALID). Deciding it first\n  is the whole point: `.` makes every U-3 prefix test false, so the unit would silently own\n  no file and the result would be an empty but schema-valid analysis, and the enumeration\n  join would otherwise surface the same wrong root as `ENUMERATION_BINDING_PROGRAM_ENTRY`,\n  attributing it to a different field.\n'
s1=s1.replace(anchor1, U0+anchor1, 1)
open(p1,'w',encoding='utf-8').write(s1)
print('native-evidence.md before',b1,'after',sha(p1))
p2=S+'/src25/docs/coop/design-corrections/foundation/execution-inputs-contract.v1.md'
s2=open(p2,encoding='utf-8').read(); b2=sha(p2)
anchor2='## 6. Candidate-only'
assert s2.count(anchor2)==1, s2.count(anchor2)
Q2="\n**Per-universe attribution of a cell-bound view (this section owns it; section 3 owns the\nscope and receipt half).** A selected `(cellOrdinal, programOrdinal)` binding carries exactly\nONE universe U (`AvailableProgramBindingV1.universe`). When this section derives that\nbinding's native Coverage accounts it resolves the Coverage entries of the views THAT\ncell/program returned, restricted to the binding's own enumerator/provider closure. Inside\nthat resolution exactly two things are decided, and they are the only two: every resolved\nCoverage envelope's subject-scope `sourceUniverse` and every resolved Coverage payload\n`key.sourceUniverse` MUST equal U -- a foreign-universe Coverage reached this way is\n`EXECUTION_INPUTS_COVERAGE_DERIVE`, not a silently skipped row -- and the account's declared\n`coverageIds` MUST equal the complete matching returned partition set for\n`(cell, program, relation, resolution, U, producer)`. Section 3 separately requires each\nNAMED scope's `sourceUniverse` to equal the binding U and binds view `planId`, enumerator\nclosure, stage `producerClosure` and receipt `outputDomains`.\n\nThis clause is deliberately narrow. It does NOT constrain `targetUniverse`: a Coverage or a\nfact may name a target in another universe, and cross-universe relationships and incoming\ntargets stay lawful. It does NOT ban a multi-universe Run: a Run carrying one per-universe\nview per selected binding admits. It does NOT ban a view that carries more than one universe\nin general; it constrains only views REACHED THROUGH a selected cell/program binding's\naccount derivation, so a retained fact view that no selected binding resolves is not\nrestricted here. It forbids exactly one thing: making a SINGLE view carry two universes'\nCoverage and then attributing that view to a cell/program binding fixed at one of them.\nSplitting the selected evidence into one view per universe is the lawful construction. No\nnew refusal code and no new semantic scope are introduced: both conditions above are what\nthe derivation already decides today.\n\n"
s2=s2.replace(anchor2, Q2+anchor2, 1)
open(p2,'w',encoding='utf-8').write(s2)
print('execution-inputs-contract.v1.md before',b2,'after',sha(p2))
