"""Prepared assessment/integration; execute only after root has read final handoff and assented."""
from pathlib import Path
import json,hashlib,shutil,datetime
root=Path.cwd();dc=root/'docs/coop/design-corrections';ev=dc/'reviews/codex-post-reset.v1';author=dc/'reviews/bv4-corrections-author.v3';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text())
h=read(author/'handoff.json');response=read(author/'response.json');assert response['is_error'] is False and response['session_id']=='77758b10-d7ba-4868-9d42-ae0b13e84cb6'
assert set(response['modelUsage'])=={'claude-opus-5'}
checkpoints=list(author.glob('review-ready*.json'));latest=max(checkpoints,key=lambda p:int(p.stem.split('.v')[-1]) if '.v' in p.stem else 1);feedback=latest.with_name(latest.name.replace('review-ready','root-review'));fd=read(feedback);assert fd['technicalAssent'] is True and fd['checkpointSha256']==sha(latest)
rows=h['delta']['aggregateVsFrozenV13']['changedFiles'];assert not h['delta']['aggregateVsFrozenV13']['additions'] and not h['delta']['aggregateVsFrozenV13']['deletions']
for row in rows:assert sha(author/'work'/row['path'])==row['afterSha256'] and sha(root/row['path'])==row['beforeSha256'],row['path']
accounts=read(author/'source-copy-accounts.json');released=accounts['work'];finalroot=h['finalChecksOnCompletedSource']['disposableRoot'] if 'finalChecksOnCompletedSource' in h else None
# Inspect actual handoff shape and supply a separate root read-account before execution.
read_account=read(ev/'bv4-v3-final-handoff-read.json');assert read_account['handoffSha256']==sha(author/'handoff.json') and read_account['allRequiredResolved'] is True
assert read_account['latestCheckpointSha256']==sha(latest)
probe=ev/'bv4-v3-checkpoint5'/'bv4-v3-checkpoint5-unicode.v2'/'report.json';assert probe.exists();unicode=read(probe);assert unicode['checkpointSha256']==sha(latest) and len(unicode['cases'])==24 and all(r['fullFailureEnvelope']=='ADMIT' and r['exactIndependentProjection'] for r in unicode['cases'])
for row in h['delta']['thisTurnVsV2']['changedFiles']:assert sha(author/'before-images'/row['path'])==row['v2Sha256'],row['path']
def ref(p):return {'path':str(p.relative_to(root)),'sha256':sha(p)}
a={'standing':'Actual Codex final coauthor-source assessment. Assent to integrate and advance to fresh independent review only.','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'finalSourceAssent':True,'independentAcceptance':False,'implementationAuthorized':False,'readinessChanged':False,'productQualification':False,'verdict':'ASSENT-TO-CORRECTED-SOURCE','unresolvedMustIssues':[],'unresolvedShouldIssues':[],
'actualCoauthor':{'sessionId':response['session_id'],'model':'claude-opus-5','role':'COAUTHOR follow-up, not independent reviewer','response':ref(author/'response.json'),'handoff':ref(author/'handoff.json'),'custody':ref(author/'custody.json')},'sourceDelta':rows,'finalHandoffReadAccount':ref(ev/'bv4-v3-final-handoff-read.json'),'finalCheckpoint':ref(latest),'substantiveRootCheckpoint':ref(feedback),
'substantiveAssessment':[
'Bv4 anchor/inventory, body-language, deficiency-carrier, totality and derivation corrections remain supported by the prior complete v1/v2 source assessments and exact final-source Run controls. V3 publication work does not regrade unchanged source merely by carrying it. Original Bv4 two MUST, two SHOULD and four advisory severities remain unchanged.',
'The fixed matrix-derived product default is distinct from installed declaration availability. Missing candidates do not fabricate facts, Coverage or candidates. The original invocation now carries bounded typed capability/mode/workspace absences per step, with exact counts and explicit no-selection versus empty-selection behavior. Root composed two1023request selections (2046 notices) through the actual synthetic invocation reference and admitted the complete invocation envelope. These operational inputs are trusted and IDs synthetic, not a content-derived Run or real host.',
'All five analysis commands, including repair-verify, declare capability-availability. Complete supplied fields survive each advertised pure renderer projection. Missing inherited required-coverage and new availability now refuse, preserving the selected required-delivery fault law. The earlier if-filter regression and root incorrect assertion that repair-verify advertises HTML are retained with additive corrections. HTML is not an advertised repair-verify format.',
'Public error composition follows actual colon-suffixed guard output through longest registered key normalization, explicit known origin, selected D9 classification and nonempty schema-admitted failure errors. Three origins remain distinct. Actual preview declaration guard now emits a registered key. Four precise DomainDetail codes join the existing registry, and host-invariant adds exactly one cause mapping to existing SYSTEM.OUTCOME.ILLEGAL_STATE; historical D9 v1.14 bytes and its ten existing mappings are unchanged. Totality is not confused with surjectivity.',
'Diagnostic projection is bounded in Unicode scalar/code-point units while SHA256 hashes the complete raw UTF8 bytes. Root exact final-source probe exercises supplementary-plane and accented characters at raw scalar lengths1023/1024/1025/4149 across all three origins:24 full failure envelopes admit and every projected subject equals an independently computed result. No Unicode normalization, raw diagnostic store or impossible collision guarantee is invented.',
'Checkpoint feedback and source snapshots preserve each intermediate defect and correction. Actual Claude read stable numbered root feedback before revising; root technical assent names exact frozen checkpoint bytes. Coauthor development repins remain separate from the six final pinned commands and independent reproduction.'],
'priorEvidence':[ref(ev/'coauthor-assessment-bv4-v1.json'),ref(ev/'coauthor-assessment-bv4-v2.json'),ref(ev/'bv4-final-source-recheck.v2/summary.json')],
'publicationEvidence':[ref(ev/'bv4-v3-checkpoint4/bv4-v3-checkpoint4-probes.v1/report.json'),ref(probe)],
'limits':['No compiler/parser/OS/storage/crypto qualification. Synthetic trusted observations and pure projection/schema controls are design-reference evidence.','Schema admission alone does not enforce every association/count/order invariant; the owning native/workflow laws and reference composition specify them.','All32 product qualification gates remain false. Fresh independent review, NEW blind consumer and full independently reviewed application/readiness reconciliation remain required.'],
'rootOwnedAssemblyCorrectionsStillRequired':{'proposal':h['rootOwnedEditorialProposal'],'standing':'Claude substantively agrees all three exact replacements. Root must apply them before final pins and independent review; the omitted fifth command is a residual current-prose inconsistency, not merely optional shorthand. This coauthor-byte assent does not accept later bytes.'},
'remaining':['apply three mutually assessed publication wording corrections','six final source-pinned reference commands and sealed successor','fresh independent review with zero unresolved MUST/SHOULD','NEW blind consumer on accepted normative bytes','full application review and readiness reconciliation']}
p=ev/'coauthor-assessment-bv4-v3.json';assert not p.exists();p.write_text(json.dumps(a,indent=2)+'\n')
before=ev/'integration-before-v14';before.mkdir(exist_ok=False)
for row in rows:
 p=root/row['path'];q=before/row['path'];q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,q)
for rel in ['integration-fixtures.py','foundation/source-pins.v1.json','security/source-pins.v1.json','native/source-pins.v2.json','workflows/source-pins.v1.json','validation-summary.v1.json']:
 p=dc/rel;q=before/'root-owned'/rel;q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,q)
for row in rows:
 p=root/row['path'];assert sha(p)==row['beforeSha256'];shutil.copy2(author/'work'/row['path'],p);assert sha(p)==row['afterSha256']
(ev/'integration-receipt-bv4-v3.json').write_text(json.dumps({'standing':'Integrated exact assessed coauthor source preserving every live before-image; no implementation or readiness change.','files':rows,'assessment':ref(ev/'coauthor-assessment-bv4-v3.json')},indent=2)+'\n')
print(json.dumps({'integratedFiles':len(rows),'finalSourceAssent':True,'independentAcceptance':False}))
