from pathlib import Path
import json,hashlib,shutil,datetime
B=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v3');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();root=Path.cwd();R=root/'docs/coop/design-corrections/reviews/codex-post-reset.v1/bv4-v3-checkpoint5'
ready=json.loads((B/'review-ready.v5.json').read_text());checkpoint=sha(B/'review-ready.v5.json');assert checkpoint=='33c25a5b6a7401a39eafeef90b01fac56a1ab4981d0a0b4cbafb1cbcf63abb86'
for row in ready['delta']['aggregateVsFrozenV13']['changedFiles']:assert sha(B/'work'/row['path'])==row['afterSha256'],row['path']
probe=Path('/tmp/opensip-design-corrections/bv4-v3-checkpoint5-unicode.v2');r=json.loads((probe/'report.json').read_text());assert r['checkpointSha256']==checkpoint and len(r['cases'])==24
assert all(v['exactIndependentProjection'] and v['fullFailureEnvelope']=='ADMIT' for v in r['cases'])
proposal=Path('/tmp/opensip-design-corrections/codex-post-reset.v1/reconcile-publication-shorthand-v14.py');q=B/'root-publication-shorthand-proposal.py';assert not q.exists();shutil.copy2(proposal,q)
d={'artifact':'codex-coauthor-review-bv4-v3-checkpoint5','at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checkpointSha256':checkpoint,'verdict':'ASSENT-TO-SUBMITTED-SOURCE','technicalAssent':True,'finalSourceAssent':True,'verifiedChangedSourceFiles':19,'standing':'Root coauthor checkpoint assent to these exact bytes. Final handoff custody/aggregate integration assessment still required; not independent/blind/application acceptance, readiness or qualification.',
'substantiveAssessment':['Read complete checkpoint5 structured disposition and delta, verified all19source hashes; exactly4files differ from checkpoint4. Read full four diffs: native normative Unicode recipe, matching schema annotation, two docstrings and additional reference controls. Native executable algorithm unchanged; prior measured behavioral joins remain applicable.','Root executed24 actualguard cases using supplementary-plane crab and accented e, raw composed scalar lengths1023/1024/1025/4149, all3origins. All complete failure envelopes admit; fitting subjects unchanged and elided subjects exactly match independently computed Unicode-sliced prefix/ASCII marker/full-raw UTF8 SHA256. Units and published-only guarantee now agree across affected sources.','Read actual suite-final-v6 summary: foundation231,identity1282passingcalls0failed,quality24,configuration28,array65,workflow1598,native347/347/66cells/open0, all exit0. These are development temporary-repin results, not six final pinned commands. All20declared disposable roots need final custody.','Prior checkpoint4 closes per-step cardinality, exact workspace attribution, all5analysis projections and required-field refusal, registered preview and full failure envelopes, exact selectedD9causeextension. No unresolved required coauthor finding on submitted source.'],
'rootProbeCorrection':{'evidence':'bv4-v3-checkpoint5-unicode.v1/failed-attempt.json','cause':'My first independent expectation hardcoded950 prefix characters. The ASCII marker is11characters, so the normative formula is949. Initial root AssertionError was a harness error, not a source finding. Initial script/failure retained; corrected formula gives24admittedexact controls.'},
'requiredFollowup':[],
'rootOwnedEditorialProposal':{'path':str(q),'sha256':sha(q),'purpose':'Three shorthand references can be reconciled during root assembly without changing selected behavior: native1.4 explicitly identify release_absence_notices leaf before adding stepId; list all5analysis commands as already required by workflow8/inventory; native schema unsupportedTyped prose name typed notice in CommandEnvelope.availability rather than generic DomainDetail. Exact replacements are in the attached PREPARED ONLY script. Read it and state substantive agreement/disagreement in final handoff; do not edit source after this assent. Root will own these changes before final pins and fresh independent review, with before-images and no claim this assent accepts later bytes.'},
'next':'Prepare final handoff JSON+Markdown now, retaining all exact checkpoint bytes, this-turn before-images, aggregate19/turn12 account, ALL20disposable roots, initial failed suites/probes and precise development limits. Include substantive position on root-owned editorial proposal. Source stays unchanged after this assent. Finish CLI response. Root then retains complete custody, records final integration assessment, performs records/pins/sixchecks/freeze, fresh independent, NEWblind and full application review. No implementation/commit/push/history rewrite.'}
assert not (B/'root-review.v5.json').exists();R.mkdir(exist_ok=False);shutil.copy2(B/'review-ready.v5.json',R/'review-ready.v5.json');shutil.copytree(probe,R/probe.name);p=probe.with_name('bv4-v3-checkpoint5-unicode.v1');shutil.copytree(p,R/p.name);shutil.copy2(q,R/q.name)
raw=(json.dumps(d,indent=2)+'\n').encode();(R/'root-review.v5.json').write_bytes(raw);(B/'root-review.v5.json').write_bytes(raw)
N=R.parents[1]/'NEXT-REVIEW.md';shutil.copy2(N,R/'NEXT-REVIEW.before.md')
with N.open('a') as f:f.write('\n\n## v3 checkpoint5 SOURCE ASSENT actually returned (15:01UTC); final handoff pending\n\nExact ready5SHA '+checkpoint+'; all19source hashes verified. root-review.v5.json SHA '+sha(B/'root-review.v5.json')+' technicalAssentTRUE to exact submitted coauthor source. Retained checkpoint/source24actualUnicodeguardsuccesses and initial root harness error (950 vs correct949 prefix; original preserved), substantive feedback and precise PREPARED root-owned3shorthand editorial proposal in codex-post-reset.v1/bv4-v3-checkpoint5. Claude must fullread proposal and give substantive position in finalhandoff; NO further sourceediting. All20disposable roots +releasedwork need final retention. Actualsuite-final-v6:231/1282/24/28/65/1598/native347/66/open0; all0. Await finalhandoff+successfulresponse SAMEPID28882/session777...; do not relaunch/endturn. Finalaggregate custody/assessment/integration/sixchecks/freeze/newindependent/newblind/fullapplication remain REQUIRED.\n')
print(json.dumps({'feedback':str(B/'root-review.v5.json'),'sha256':sha(B/'root-review.v5.json'),'technicalAssent':True}))
