from pathlib import Path
import json,hashlib,shutil,datetime
B=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v3');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
R=Path('/Users/sb/code/opensip-ai/opensip_arch/docs/coop/design-corrections/reviews/codex-post-reset.v1/bv4-v3-checkpoint4')
ready=json.loads((B/'review-ready.v4.json').read_text());checkpoint=sha(B/'review-ready.v4.json');assert checkpoint=='1e04688c986f3df750e75aad4173f85c5114e2b0c15bb6f057cfc85c90f2e0f7'
for row in ready['delta']['aggregateVsFrozenV13']['changedFiles']:assert sha(B/'work'/row['path'])==row['afterSha256'],row['path']
probe=Path('/tmp/opensip-design-corrections/bv4-v3-checkpoint4-probes.v1');report=json.loads((probe/'report.json').read_text());assert report['checkpointSha256']==checkpoint
D={'artifact':'codex-coauthor-review-bv4-v3-checkpoint4','at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checkpointSha256':checkpoint,'verifiedChangedSourceFiles':19,'verdict':'CHANGES_REQUIRED','technicalAssent':False,'finalSourceAssent':False,'standing':'Coauthor technical checkpoint, not independent, blind or application acceptance; no readiness or qualification.',
'supported':['All prior behavioral corrections pass root exact-source probe: per-step2046 notices, synthetic two-analysis invocation and single-step envelopes, empty/no-selection distinction, notice code const, all12 ASCII actual-guard boundary failure envelopes, registered preview failure, exact D9 inherited10 plus host-invariant.','Required-field regression corrected: missing required-coverage and capability-availability now refuse in all5formats. All5analysis commands preserve supplied availability in every advertised format. Pure projection/schema evidence, trusted scripted operational results and fake IDs; no real host/renderer or content-derived Run closure.','Current carrier/projection prose now coherent; native prose correctly confines diagnostic guarantee to bounded published subject/digest and ordinary SHA256 collision resistance.'],
'rootCorrection':{'priorFile':'root-review.v3.json','incorrectClaim':'repair-verify advertises SARIF/HTML','correctedClaim':'repair-verify advertises human/json/sarif/agent; it does NOT advertise HTML. The omission finding was valid for its actual formats. Preserve prior feedback bytes; this is an additive correction.'},
'requiredFollowup':[{'id':'CX-BV4-PUBLICATION/exact-string-units-and-mirrors','finding':'The native10 encoding recipe calls raw UTF-8 then applies len/slicing, but the code uses Unicode string length/slicing and only hashes UTF8 bytes. A non-ASCII mode makes these different interoperable interpretations. Also native schema subjectBoundLaw and bounded_subject/_detail docstrings still promise a retained raw diagnostic and impossible collisions, contradicting the corrected current prose.', 'required':'Clarify raw is the admitted Unicode scalar string <registered key>[:<value>]; len and slicing count Unicode code points (BoundedText/JSON Schema), not UTF8 bytes or UTF16 units. SHA256 input is exactly raw.encode(UTF8), without additional normalization; lowercase64hex, ASCII marker ...#sha256:, prefix length1024-len(marker)-64. Align native schema subjectBoundLaw and both current docstrings to the published-only guarantee and ordinary collision-resistance assumption. No new store/feature required. Add a focused non-ASCII actual-guard control (e.g. supplementary-plane character mode at composed raw scalar lengths1024 and1025, with UTF8 byte lengths greater than1024) and full failure-envelope admission, unchanged fitting text and independent full-raw UTF8digest check. This completes the same publication contract, not a scope expansion.'}],
'probeRoot':str(probe),'probeReportSha256':sha(probe/'report.json'),'developmentChecks':ready['finalChecksOnCompletedSource'],'next':'Make the narrow wording/mirror/control correction, then submit review-ready.v5.json and stop for root-review.v5.json. All prior corrected behavior is supported. Full final-byte development suite before handoff remains required; no final source assent yet.'}
assert not (B/'root-review.v4.json').exists();R.mkdir(exist_ok=False);shutil.copy2(B/'review-ready.v4.json',R/'review-ready.v4.json');shutil.copytree(probe,R/probe.name)
for row in ready['delta']['aggregateVsFrozenV13']['changedFiles']:
 q=R/'submitted-source'/row['path'];q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(B/'work'/row['path'],q)
raw=(json.dumps(D,indent=2)+'\n').encode();(R/'root-review.v4.json').write_bytes(raw);(B/'root-review.v4.json').write_bytes(raw)
N=R.parents[1]/'NEXT-REVIEW.md';shutil.copy2(N,R/'NEXT-REVIEW.before.md')
with N.open('a') as f:f.write('\n\n## v3 checkpoint4 reviewed/returned (14:52UTC), still ACTIVE\n\nExact checkpointSHA '+checkpoint+'; all19source hashes verified, retained checkpoint/source/root actual probes/feedback in codex-post-reset.v1/bv4-v3-checkpoint4. root-review.v4.json CHANGES_REQUIRED SHA '+sha(B/'root-review.v4.json')+'. All prior behavioral joins now pass exact probes, including strict missing-field refusal and all5analysis projection parity. One narrow remaining correction: native10 Unicode scalar len/slicing vs UTF8 digest units, plus native schema subjectBoundLaw and two docstrings still incorrectly promise raw retention/impossible collisions. Add non-ASCII actualguard boundary control. Root additively corrects prior feedback3: repair-verify has human/json/sarif/agent, NO HTML. Original feedback retained. Await review-ready.v5.json and MUST return root-review.v5.json, same PID/session. No final source assent/integration/freeze. All remaining independent/blind/application steps required.\n')
print(json.dumps({'feedback':str(B/'root-review.v4.json'),'sha256':sha(B/'root-review.v4.json'),'retained':str(R)}))
