from pathlib import Path
import json,hashlib,shutil,datetime,ast
b=Path('/tmp/opensip-design-corrections/bv4-corrections-author.v4');snap=Path('/tmp/opensip-design-corrections/candidate-subject.v14');out=Path('/tmp/opensip-design-corrections/bv4-v4-checkpoint3');out.mkdir(exist_ok=False);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();r=json.loads((b/'review-ready-3.json').read_text());rows=r['delta']['againstFrozenV14']['changedFiles']
for row in rows:
 p=row['path'];assert sha(snap/p)==row['beforeSha256'] and sha(b/'work'/p)==row['afterSha256'];q=out/'source'/p;q.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(b/'work'/p,q)
probe=Path('/tmp/opensip-design-corrections/bv4-v4-checkpoint3-preflight.v1');pr=json.loads((probe/'report.json').read_text());assert pr['checkpointSha256']==sha(b/'review-ready-3.json') and len(pr['cases'])==17 and pr['allHold'] is True
suite=r['completedSourceSuite'];assert suite['allExitZero'] is True
for rec in suite['results']:assert rec['exitCode']==0 and sha(Path(suite['disposableRoot'])/rec['reportActuallyWritten'])==rec['reportSha256']
# Reconstruct the exact prior probe from the retained public replacement strings, not guessed text.
log=Path(json.loads((b/'session-discovery.json').read_text())['logPath']);blocks=[]
for line in log.read_text().split('\n'):
 if not line:continue
 d=json.loads(line)
 if d.get('timestamp')!='2026-09-07T16:05:09.581Z':continue
 for x in d.get('message',{}).get('content',[]):
  if isinstance(x,dict) and x.get('type')=='tool_use' and x.get('name')=='Bash':blocks.append(x)
assert len(blocks)==1;cmd=blocks[0]['input']['command'];script=cmd.split("<<'PY'\n",1)[1].split('\nPY',1)[0];values={}
for node in ast.parse(script).body:
 if isinstance(node,ast.Assign) and len(node.targets)==1 and isinstance(node.targets[0],ast.Name) and node.targets[0].id in ('old','new'):values[node.targets[0].id]=ast.literal_eval(node.value)
current=(b/'probes/p4_preplan_order.py').read_text();assert current.count(values['new'])==1;old=current.replace(values['new'],values['old']);assert hashlib.sha256(old.encode()).hexdigest()=='e21b4c9c54bc0417ee7311547b99a3239260e8892e705b087133131464d6a827'
history=out/'probe-history';history.mkdir();(history/'p4_preplan_order.checkpoint2.py').write_text(old);(history/'public-replacement.json').write_text(json.dumps(blocks[0],indent=2)+'\n');(history/'account.json').write_text(json.dumps({'standing':'Exact historical checkpoint2 probe reconstructed by reversing the documented public comment-only replacement, then verified against checkpoint2 SHA. No source or recorded measurement changed.','beforeSha256':sha(history/'p4_preplan_order.checkpoint2.py'),'afterSha256':sha(b/'probes/p4_preplan_order.py'),'publicReplacementSha256':sha(history/'public-replacement.json')},indent=2)+'\n')
f={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checkpointSha256':sha(b/'review-ready-3.json'),'technicalAssent':True,'verdict':'ASSENT-TO-EXACT-COAUTHOR-SOURCE','standing':'Root substantive technical source assent only, not independent acceptance, blind reconstruction, application, readiness or product qualification.','sourceDelta':rows,'requiredFollowup':[],
'substantiveAssessment':['The three current contract/annotation/helper availability descriptions now agree on CommandEnvelope.availability and typed original-invocation ownership; compatibility details remain explicitly limited.','The published pre-Plan boundary admits complete default and explicit selections, conditionally checks only actual arrays, then validates the full schema and native vocabulary. PROJECT.SCOPE_LIMIT reuse states all four fields/two record families. Bounds/defaults/explicit narrowing remain unchanged.','Root reran its unchanged17case probe against this exact halted checkpoint: all17hold. Five previously failed malformed-field cases now reach schema ValidationError; valid0/1/1024 explicit and1/93TS defaults admit;1025explicit/94TS defaults produce typed refusal plus schema-admitted full failure envelopes.','Pre-Plan absence of Plan/Run is scoped to the refused step, retaining request/invocation attribution and earlier committed outcomes. Retained schema validation remains separate and unchanged; the earlier unreachable reclassification claim is explicitly withdrawn.','Development reports and their actual paths/hashes were verified. Source changed since the earlier run, justifying the completed rerun. Development pins are not the later repository final seal or independent acceptance.'],
'rootProbe':{'root':str(probe),'reportSha256':sha(probe/'report.json'),'probeSha256':sha(probe/'probe.py'),'cases':17,'allHold':True,'limits':pr['standing']},
'additiveClarifications':['Final checkpoint limits says six malformed shapes were broken; root actually measured FIVE failing cases among17 (one missing field, three non-length scalar types, one oversized string). Keep the original checkpoint unchanged and use the exact five-case count in the final handoff. This requires no source edit or repeated suite.','The amended p4 probe comment is now accurate. Root reconstructed and retained the exact prior e21b4c9c... bytes from the public replacement operation, independently SHA-matching checkpoint2, in '+str(history)+'. Please cite this historical account in the final handoff; no rerun or source edit is needed.'],
'next':'Keep these source bytes unchanged and write final handoff.json/md with delta.againstFrozenV14, exact checkpoint/root assent and all full/partial copy roots, genuine failed-attempt history and limits. Finish the coauthor session. Root will retain and integrate exact assessed bytes, then process the separate ongoing v14 review and freeze/review the corrected successor. This assent does not imply the unseen independent verdict or final readiness.', 'implementationAuthorized':False}
shutil.copy2(b/'review-ready-3.json',out/'review-ready-3.json');shutil.copytree(probe,out/'preflight');(out/'root-review-3.json').write_text(json.dumps(f,indent=2)+'\n');shutil.copy2(out/'root-review-3.json',b/'root-review-3.json');d=Path.cwd()/'docs/coop/design-corrections/reviews/codex-post-reset.v1/bv4-v4-checkpoint3';shutil.copytree(out,d);shutil.copy2(__file__,d/'review.py');print(json.dumps({'feedbackSha256':sha(b/'root-review-3.json'),'checkpointSha256':f['checkpointSha256'],'technicalAssent':True,'rootCases':17},indent=2))
