from pathlib import Path
import json,hashlib,shutil,subprocess
A=Path('/Users/sb/code/opensip-ai/opensip_arch');M=A/'docs/implementation/m2';U=M/'initial-root-binding-owner-selection-v1';T=Path('/tmp/opensip-implementation');G=T/'initial-diagnostics-generation404';P=G/'product';L=A.parent/'opensip'
def dig(b):return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def pin(p):return {'path':str(p.relative_to(A)),**dig(p.read_bytes())}
def save(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2)+'\n')
def copy(src,dst):dst.parent.mkdir(parents=True,exist_ok=True);dst.write_bytes(src.read_bytes())
assert json.loads((G/'admission-r2-checks.json').read_text())[-1]['exitCode']==0
for name in ['admission-tests.stdout','admission-tests.stderr','admission-checks.json','admission-r2.stdout','admission-r2.stderr','workspace-r2.stdout','workspace-r2.stderr','admission-r2-checks.json','typescript.stdout','typescript.stderr','typescript-result.json','typescript-emit.stdout','typescript-emit.stderr','typescript-runtime.stdout','typescript-runtime.stderr']:
 copy(G/name,U/'evidence'/name)
for name in ['prepare_generation404.py','complete_generation404.py','run_generation404.py','run_generation404_r2.py','compile_generation404.py','correct_admission406.py','check_generated406.py']:
 copy(T/name,U/'evidence'/name)
copy(T/'doctor-reference406-result.json',U/'evidence/doctor-reference-first-result.json');copy(T/'doctor-reference406-r2-result.json',U/'evidence/doctor-reference-result.json')
copy(G/'typescript-runtime406/probe.mjs',U/'evidence/typescript-runtime-probe.mjs')
# Preserve the exact newer historically reviewed checker/vector bytes, without treating
# their old paths as available accepted parents (application pins take precedence).
lock=json.loads((L/'design-lock.json').read_text());manifests={k:json.loads((A/lock['approvals'][k]['path']).read_text())for k in ('sourceManifest','applicationManifest')};provenance=[]
for name in ['check_workflows.v1.py','workflow-cases.v1.json','check-workflow-projection.v3.py']:
 p=A/'docs/coop/design-corrections/workflows'/name;r={k:next((x for x in v['files']if x['path']==str(p.relative_to(A))),None)for k,v in manifests.items()};assert r['sourceManifest']and pin(p)==r['sourceManifest']
 q=U/'reference/historical-source'/name;copy(p,q);provenance.append({'originalPath':str(p.relative_to(A)),'sourceManifestPin':r['sourceManifest'],'applicationManifestPin':r['applicationManifest'],'effectiveAcceptedParentPin':r['applicationManifest']or r['sourceManifest'],'retainedCopy':pin(q),'currentDoctorReplacement':'reference/check_doctor.py and reference/doctor-cases.json','oldFullCheckerExecutedOrRequalified':False})
save(U/'reference/reconciliation.json',{'standing':'Current doctor replacement and exact historical evidence provenance. Historical-source copies are read-only provenance, not executable current entrypoints or wholesale adoption of old behavior. No frozen original path is edited.','selectedBehaviorBaseline':pin(M/'import-totality-reference-selection-v1/reference/workflows_model.v1.py'),'modelDelta':['doctor excludes exact informational detail from count and termination selection','terminate false doctor-report branch emits pre-existing DOCTOR.REPORT_NOT_PRODUCIBLE golden detail'],'allOtherTopLevelStatementsUnchanged':116,'oldCheckerAndVectorReconciliation':provenance,'replacementChecks':'reference/check_doctor.py','replacementCases':'reference/doctor-cases.json','existingChecksPreserved':'Two-defect no-note report, schema validation, exit0, DOCTOR.DEFECTS_FOUND; false report exit4/HOST.IO_FAILURE now also verifies promised detail. Existing generic render method preserved and invoked with actual declared parity fields.','projectionCheckerGoldenJoin':'The original check-workflow-projection.v3.py doctor golden mapping is tested by the replacement against command-inventory.v3 doctor-report-not-producible; it is not silently omitted.','activation':'Only this scoped doctor reconciliation replaces those sections. Full historical checker remains tied to its historical fixture/model/schema graph; no claim it is directly runnable against new sources.'})
# Refresh materialization map after the two required native-pin/test changes.
base=json.loads((G/'baseline.json').read_text());mapping=[];unchanged=[]
for row in base['files']:
 assert dig((L/row['path']).read_bytes())=={k:row[k]for k in ('bytes','sha256')}
 raw=(P/row['path']).read_bytes()
 if dig(raw)!={k:row[k]for k in ('bytes','sha256')}:
  assert row['path']!='design-lock.json';target=U/'product'/row['path'];copy(P/row['path'],target);mapping.append({'productPath':row['path'],'candidatePath':str(target.relative_to(A)),'before':{k:row[k]for k in ('bytes','sha256')},'after':dig(raw)})
 elif row['path']!='design-lock.json':unchanged.append(row)
assert len(mapping)==12 and len(unchanged)==579
save(U/'materialization-map.json',{'schemaVersion':1,'standing':'Exact prospective development materialization; formal independent review/root assent and fresh private/live checks required before selection.','baseProductHead':base['productHead'],'files':mapping,'unchanged':unchanged})
save(U/'diagnostic-routes.json',{'standing':'Proposed exact D9 composition; trusted reference outcomes only, no native command routing implemented.','routes':[{'boundary':'noncreator authoritative-root positive absence after earlier request prerequisites','class':'request-rejected','errorCode':'REQUEST.PRECONDITION_FAILED','detail':'INSTALLATION.NOT_INITIALIZED','exit':2,'effects':0},{'boundary':'first creator BACKED_UP storage without invocation acknowledgement','class':'request-rejected','errorCode':'REQUEST.PRECONDITION_FAILED','detail':'storage.backup-choice-required','exit':2,'effects':0},{'boundary':'complete-I doctor report produced with zero actual defects','class':'success','detailChannel':'doctor.defects','detail':'INSTALLATION.DURABILITY_NOT_CHECKED','defectsFound':0,'terminationDomainDetail':None,'exit':0,'effects':0},{'boundary':'complete-I doctor report produced with positive actual defects','class':'success','detailChannel':'doctor.defects','informationalDetail':'INSTALLATION.DURABILITY_NOT_CHECKED','terminationDomainDetail':'DOCTOR.DEFECTS_FOUND','count':'actual defects only, excluding exactly reserved informational code','exit':0,'effects':0},{'boundary':'doctor report cannot be produced, including bounded complete-root overflow','class':'operational-failed','errorCode':'HOST.IO_FAILURE','faultCause':'host-io','detail':'DOCTOR.REPORT_NOT_PRODUCIBLE','exit':4,'reportSessionFailed':True,'effects':0}],'noticesAbsent':['trust doctor','store status'],'authorityLimits':'A schema-valid refusal or boolean reference observation never admits a native creator, original root, trust context or write.'})
copy(Path(__file__),U/'evidence/complete406.py')
print('Completed406 draft:12mapped579unchanged; focused reference and historical consumer provenance retained')
