"""Regenerate the CURRENT in-tree native report (native/native-evidence-report.v2.json) with the maintained checker.

check_native_evidence.v2.py main() is run unchanged except for its pin GATE: this runtime changes pinned files on
purpose and the pin ledger is root's integration step. The report main() writes is then given its TRUE pin state
(`verified: false` with every real fault and a standing note) instead of the stub's empty list. Nothing else in the
report is edited. Prints a summary; exits nonzero unless the report result is PASS.
Usage: native_report_regenerate.py ROOT
"""
import importlib.util
import json
import sys
from pathlib import Path

native = Path(sys.argv[1]) / "docs/coop/design-corrections/native"
spec = importlib.util.spec_from_file_location("c24_native_report_checker", native / "check_native_evidence.v2.py")
K = importlib.util.module_from_spec(spec)
sys.modules["c24_native_report_checker"] = K
spec.loader.exec_module(K)
real_faults = K.verify_pins()
K.verify_pins = lambda: []
code = K.main([])
path = K.REPORT_PATH
report = json.loads(path.read_text(encoding="utf-8"))
report["pins"] = {"verified": not real_faults, "faults": real_faults,
                  "standing": ("Regenerated by consumer24 native author v2 with the checker's own main(); the pin GATE was "
                               "bypassed because source-pins.v2.json is regenerated by root after integration. These faults "
                               "are the checker's real verify_pins() result at regeneration time.")}
path.write_text(json.dumps(report, indent=1) + "\n", encoding="utf-8")
print(json.dumps({"exit": code, "report": str(path), "result": report["result"], "pinFaults": len(real_faults),
                  "cases": {k: report["cases"][k] for k in ("total", "passed", "failed")}}, indent=1))
raise SystemExit(0 if report["result"] == "PASS" else 1)
