[workspace]
[package]
name = "unicode-nfc-probe"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "unicode-nfc-probe"
path = "src/main.rs"

[dependencies]
unicode-normalization = { version = "=0.1.24", default-features = false }
