"""Record root's substantive rejection of released coauthor v1 after full handoff/source reading."""
from pathlib import Path
import hashlib,json,shutil,datetime
root=Path.cwd();ev=root/'docs/coop/design-corrections/reviews';src=ev/'bv5-corrections-author.v1';dest=ev/'codex-post-reset.v1';helpers=Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
h=json.loads((src/'handoff.json').read_text());response=json.loads((src/'response.json').read_text());assert response.get('is_error') is False
assert (src/'handoff.md').is_file() and (src/'source-copy-accounts.json').is_file()
accounts=json.loads((src/'source-copy-accounts.json').read_text());actual=accounts['work']
assert not actual['addedFiles'] and not actual['deletedFiles']
declared={r['path']:r for r in h['changedSource']};assert set(declared)=={r['path'] for r in actual['changedFiles']}
for row in actual['changedFiles']:
 r=declared[row['path']];assert row['sha256']==r['afterSha256'] and row['beforeSha256']==r['beforeSha256']
 assert sha(src/'work'/row['path'])==row['sha256']
out=dest/'bv5-root-source-review.v1';assert not out.exists();out.mkdir()
names=['bv5-draft-root-feedback.v1.md','probe-bv5-draft-rc1.py','probe-bv5-draft-rc1.first-attempt.py','bv5-draft-rc1-result.v1.json','bv5-draft-rc1-result.v2.json','probe-bv5-draft-cross-rung.py','bv5-draft-cross-rung-result.v1.json','probe-bv5-rc1-full-run.py','bv5-rc1-full-run-result.v1.json','launch-bv5-corrections-author-v2.py','assess-bv5-author-v1.py']
for name in names:shutil.copyfile(helpers/name,out/name)
shutil.copytree(helpers/'bv5-author-v1-outside-logs',out/'outside-logs')
issues=[
 ('CX-BV5-01','SHOULD','Full default lowercase is not Unicode simple lowercase','The new normative simple code-point mapping conflicts with Python str.lower(), demonstrated by U+0130 expansion and context-sensitive Greek final sigma. Publish deterministic version-bound intended full conversion, not a locale/casefold/ASCII substitution.'),
 ('CX-BV5-02','SHOULD','Schema-stage and origin routing are overstated','New prose and admit_analysis_spec docstring omit missing/wrong-shape arrays from schema-reaching inputs and flatten host-invariant exit4 into external request exit2. Preserve cardinality-first and actual origin law.'),
 ('CX-BV5-03','SHOULD','Repair guard and projected evidence wording need precision','Existing UNSAFE_ACTIONS guards every delete/replace. The new exported-only replacement wording narrows it. The inline comment says dynamicDispatch already consumed although helper reads eligibility/reasons; preserve full native evidence and target-relative requirements without a global dynamic-dispatch veto.'),
 ('CX-BV5-04','MUST','Contradictory not-applicable coverage closes a full Run','Root full reference Run controls show attempted=true or nonempty registered unresolvedEdgeClasses accepted on unresolved-edge@observed despite new normative minting law. Valid observed control also closes. Reconcile producer and retained admission; stageTerminal/examined coverage remain independent.'),
 ('CX-BV5-05','SHOULD','Fingerprint path enforcement description invents a join','Only anchors join snapshot inventory. Fingerprint logicalPath has imperative recursive checking; per-segment255 is not uniformly enforced there. Describe exact current schema and imperative obligations without changing accepted sets by accident.'),
 ('CX-BV5-06','advisory','Windows source citation is wrong','New inherited-platform explanation repeats admission section5 item1 for Windows selection. Actual owning selection is security S8/native matrix.'),
 ('CX-BV5-07','advisory','Identical-observation wording exceeds evidence','Root agrees the RC1 prose gap; the blind alternatives differ in state/attempted/stage/coverage. Different changed payloads are not a digest collision or proof of divergence on identical complete observations.'),
 ('CX-BV5-08','MUST','Cross-relation scope and coverage close a full Run','Root full reference Run accepts unresolved-edge@enumerated, with its own re-keyed scope, payload and proper requested capability. A fact admission or later sufficiency lookup does not prevent a fact-free invalid coverage pair from closing. Correct relation-specific membership at producer and retained boundaries.')]
findings=[{'id':i,'severity':s,'title':t,'evidenceAndRequiredCorrection':e,'status':'REQUIRES-CORRECTION'} for i,s,t,e in issues]
ref=lambda p:{'path':str(p.relative_to(root)),'sha256':sha(p)}
record={'standing':'Root coauthor/integration review of actual released v1 bytes; NOT source assent or independent acceptance. Continue actual Claude follow-up.','at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sessionId':response['session_id'],'handoffReadInFull':True,'sourceDiffsReadInFull':True,'finalSourceAssent':False,'independentAcceptance':False,'implementationReady':False,'actualHandoff':ref(src/'handoff.json'),'actualMarkdown':ref(src/'handoff.md'),'actualReportedAssent':h['technicalAssent'],'sourceDelta':h['changedSource'],'requiredFindings':findings,
 'originalBlindDispositions':[{'id':r['id'],'originalSeverity':r['severity'],'actualCoauthorDisposition':r['disposition'],'rootDisposition':'Proposed correction assessed; exact successor still requires the associated root corrections and fresh review.'} for r in h['requiredFindingDispositions']],
 'originalAdvisories':[{'id':r['id'],'originalSeverity':r['retainedSeverity'],'actualCoauthorDisposition':r['disposition'],'rootDisposition':'Retained; root corrections apply where stated, no retrospective acceptance.'} for r in h['advisoryDispositions']],
 'coauthorNewFindings':[{'id':'BV5A-NEW-1','originalSeverity':'advisory','rootDisposition':'Required correction under CX-BV5-08 based on full retained Run counterexample. Original advisory and scope explanation preserved verbatim; user authorization includes reference corrections.'},{'id':'BV5A-NEW-2','originalSeverity':'advisory','rootDisposition':'Address now proportionately: align current six-member synthetic fixture with the full native record and clearly state the admitted-input assumption; assess any real missing validation separately, rather than infer product enforcement from a pure workflow helper.'},{'id':'BV5A-NEW-3','originalSeverity':'corroboration, not a new defect','rootDisposition':'Agreed: existing DOM/ES2022 fixture substantiates mapping, but does not verify Unicode simple-vs-full conversion.'}],
 'referenceEvidence':ref(out/'bv5-rc1-full-run-result.v1.json'),
 'limits':['Root full-Run probe uses current shared synthetic graph builder with explicit root mutations and exact re-keying; it is full reference closure, not a product compiler/host/OS test.','Root initial producer probe used an unregistered dynamic-dispatch class, which correctly schema-refused; rerun uses registered computed-member-access. Both original attempt and corrected probe retained.','Coauthor five probe outputs are mixed reference entry-point, schema and direct byte/description assertions. Their counts do not mean that every assertion is a full graph or production host refusal.','Coauthor left two new findings open on a narrower self-imposed scope. That is not a user authorization limitation; required reference correction is authorized.','Coauthor final writeCustody/Markdown disclose transient /tmp logs and /tmp/v15-extract, copied back and deleted. That disclosure qualifies the still-unchanged all-writes-under-output sentence. Root also preserved current logs additively before cleanup; earlier overwritten usage-error bodies persist in public tool outputs. No live product source edit inferred.','Coauthor no-filesystem-executed limit means no PRODUCT filesystem qualification; actual Python/shell IO occurred.','Coauthor says two schema files changed, but changedSource contains three schema bundles (identity, native, repair), plus registry/prose/model comments. Exact source inventory owns the count.','Response summary reports 95 checks: 17 pair rows plus 16+18+23+21 check rows. It is not a count of every admission or control: each pair has two attempts and RC1 output has 8 controls, despite handoff saying 6. Preserve actual reported count with its aggregation limit; do not inflate a replacement exhaustive-coverage claim.','No source integrated, pins refreshed, successor frozen, readiness changed, or implementation/commit/push performed.'],
 'artifacts':[ref(p) for p in sorted(out.rglob('*')) if p.is_file()]}
p=dest/'coauthor-assessment-bv5-v1.json';assert not p.exists();p.write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps({'assessment':str(p),'finalSourceAssent':False,'sourceFiles':len(declared),'rootFindings':len(findings)},indent=2))
