"""Record root's full reading and scoped assessment of actual completed blind v5."""
from pathlib import Path
import datetime, hashlib, json
root=Path('/Users/sb/code/opensip-ai/opensip_arch');reviews=root/'docs/coop/design-corrections/reviews';b=reviews/'consumer-b.v5';out=reviews/'codex-post-reset.v1/blind-assessment.v5.json'
assert not out.exists();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text())
r=load(b/'output/blind-review.json');response=load(b/'output/response.json');custody=load(b/'custody.json')
assert response['is_error'] is False and response['session_id']=='04af6558-0b64-4a99-9fa4-0ca5ad653a27'
assert r['verdict']=='CHANGES_REQUIRED' and [len(r[x]) for x in ('newMustIssues','newShouldIssues','nonblockingAdvisories')]==[2,2,4]
assert r['inputVerification']['allVerified'] and r['inputVerification']['verifiedOk']==45
assert custody['parentSubjectSha256']=='5ec7928426c7a91e323240337dc382c4de32bd4e5f2626eba92c8991067b365f'
for kind in ('referenceSources','vectorOutputs'):
 for row in r['retainedOutputs'][kind]:assert sha(b/'output'/row['path'])==row['sha256'],row['path']
summary=load(b/'output/vectors/_summary.json');assert summary['scenarioCount']==29 and summary['errors']=={}
assert load(b/'output/vectors/rust-mixed-edition.json')['editionMapCanonicalBytes']==650
ref=lambda p:{'path':str(p.relative_to(root)),'sha256':sha(p)}
record={'standing':'Actual completed blind review CHANGES_REQUIRED; four required corrections prevent readiness/application. Root accepts the need to correct all four, with evidence precision qualifications below. No source integration or new acceptance is granted.',
 'recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'fullRead':{'reviewJson':True,'reviewMarkdown':True,'successfulCliResponse':True,'finalMarkdownCorrectionRead':'21-crate map final value650 bytes; earlier738 wording was corrected by reviewer before completion.'},
 'review':ref(b/'output/blind-review.json'),'markdown':ref(b/'output/blind-review.md'),'custody':ref(b/'custody.json'),'actualSessionId':response['session_id'],'actualModels':list(response['modelUsage']),'turns':response['num_turns'],'permissionDenials':len(response['permission_denials']),'spawnedSubagents':response['subagent_stats']['spawned'],
 'independentInputScope':'Fresh45-file normative kit only; no author reference model or prior review supplied. Exact97file retention and240publictoolblocks preserve independently written sources/outputs, failed intermediate attempts and final input verification.',
 'requiredDispositions':[
 {'id':'CB5-MUST-1','disposition':'CORRECT','basis':'The effective CVE1-admission sentence names delivery.v4, while the existing ADM-DOMAIN successor claims selectors that are absent. Explicitly select its scoped value-domain/ladder successor and retain inherited identity/codec/other admission laws.'},
 {'id':'CB5-MUST-2','disposition':'CORRECT','basis':'Current native model explicitly maps effective lib names to lib.<lowercase-name>.d.ts and validates the complete retained declaration inventory. Publish that mapping at the owning prose and schema descriptions without changing the representation or ignoring configuration agreement.'},
 {'id':'CB5-SHOULD-1','disposition':'CORRECT','basis':'Specify resolution-state applicability for all registered pairs, including unresolved-edge@observed. Existing model uses the five resolved-rung set and its complement; the seven-relation prose list is incomplete. A one-rung heuristic alone is insufficient because reachability has one resolved rung. Unknown pairs remain invalid.','evidenceLimit':'The two exhibited entries differ in attempted, coverage and stage fields; their differing payload hashes do not demonstrate a hash collision or identity divergence on identical committed observations. The missing explicit normative mapping remains a valid clarity problem.'},
 {'id':'CB5-SHOULD-2','disposition':'CORRECT','basis':'repair_preview already projects exactly five fields from full native ClosedWorldV2. Publish the projection and preserve the original full evidence/eligibility requirement, including dynamicDispatch/reasons before projection; never promote copied output fields into repair authority.'}],
 'advisoryDispositions':[{'id':x['id'],'originalSeverity':'ADVISORY','disposition':'Address through narrow current-source clarification in the already-required successor; preserve original source/review history and no silent scope expansion.','finding':x['title']} for x in r['nonblockingAdvisories']],
 'additionalAcceptedAdvisory':'V15-ADV-1 will be clarified at its original nonblocking severity while the required successor is prepared; cardinality-first semantics unchanged.',
 'clearedFinding':r['checkedAndCleared'],
 'reconstructionScope':{'reportedScenarioGroups':29,'reportedClosedRunGraphs':8,'closedGraphBreakdown':'5 TypeScript,1Rust,2syntax-only; independently authored synthetic inputs and reconstructed admission, not product enforcement.','reportedNegativeProbeCount':58,'countMeaning':'Reviewer aggregation recursively counts mapping entries under negatives/admissionRefusals/pinnedPurgeNegatives. This is not a count of58 demonstrated refusals: it includes bool/string schemaVersion cases that CVE1 encodes with prose ADM-TYPE obligations, schema-valid forward dependencies and schema-valid pin subsets. It also omits the separately named flat ts-negatives18 and rust-negatives14 maps. Preserve the reported58 as a labelled aggregation only; no replacement inflated total or qualification claim.','runIds':'Review correctly limits closed graphs to8; the intermediate string scan found11 unique runId values because public-envelope examples contain3 synthetic placeholders, which are not additional closed graphs.','rustEditionIllustration':'Final current blind example650bytes for21crates is independent of historical prior723/222/400/946examples; no crate-count threshold.'},
 'otherPrecisionLimits':['The blanket wording that no filesystem or cryptographic primitive executed is read as no product filesystem/TCB/signature/crypto qualification; actual reference code read/wrote files and executed hashlib SHA-256. Do not repeat that blanket wording literally as execution evidence.','Public output examples validate envelopes and reconstructed route mappings; they do not execute real host commit/delivery or renderer behavior.','The first inline smoke command was rejected by CLI tool-input validation for control characters before execution; later file-based smoke ran. This is distinct from the successful CLI receipt reporting zero permission denials.','S2 report says projection is determinate by elimination yet requiredInvention true; root corrects the misleading copy contract without claiming the existing projection algorithm itself was unknowable.','ADV4 mis-cites admission§5 item1 for Windows; actual product platform selection is securityS8/native matrix. Advisory scope boundary still warrants explicit accounting.'],
 'next':'Actual fresh correction coauthor bv5-corrections-author.v1 and root assess exact proposed source; preserve old acceptance, refresh pins only after final records, run six checks, freeze successor and obtain fresh independent plus NEW blind and full application review.','implementationAuthorized':False,'readinessChanged':False,'applicationEligible':False}
out.write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'rootAssessment':str(out),'requiredCorrections':4,'advisories':4,'applicationEligible':False}))
