"""Fresh actual independent review only after exact v16 source seal."""
from pathlib import Path
import datetime,hashlib,json,subprocess
root=Path.cwd();dc=root/'docs/coop/design-corrections';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_text())
mp=dc/'reviews/candidate-subject.v16.json';m=load(mp);digest=sha(mp)
a=load(dc/'reviews/codex-post-reset.v1/successor-source-assessment.v16.json');assert a['finalSourceAssent'] is True and a['independentAcceptance'] is False
for rel in ['reviews/bv5-corrections-author.v2/custody.json','reviews/codex-post-reset.v1/technical-review.v16.md','post-reset-dispositions.v16.proposed.json']:assert (dc/rel).is_file()
for row in m['files']:
 p=Path(m['snapshotRoot'])/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes']
out=Path('/tmp/opensip-design-corrections/post-reset-review.v16');out.mkdir(exist_ok=False)
prompt=f'''You are ACTUAL CLAUDE in a FRESH INDEPENDENT OpenSIP architecture/design/reference review. You authored NONE of these bytes and are not coauthor f6955666-0878-461a-a4e1-2ca2c4f5e824, blind04af6558-0b64-4a99-9fa4-0ca5ad653a27, or earlier independent7954d0b3-0895-4506-ad06-08f320d35fe8. User requires actual Claude and Codex alignment before implementation. No agents, product implementation, fixes, commits, pushes or subject edits. Write ONLY {out}, including disposable source copies/probes. Python /tmp/opensip-architecture-review-env/bin/python -I -B. Never execute report-writing commands in the immutable snapshot or original repo.

Frozen subject {m['snapshotRoot']}; manifest {mp}; SHA256 {digest}. Verify ALL file hashes/lengths and undeclared inventory before and after review. Read all five product contracts/index, exact v15->v16 source delta, successor-source-assessment.v16.json, technical-review.v16.md, v16 dispositions/advisory account, actual bv5-corrections-author.v2 handoff/source/probes/custody, preserved v1 handoff and root coauthor-assessment-bv5-v1.json feedback/limits. Individually assess all nine CX-BV5-01..09 and BV5A-NEW-1/2, not merely the original blind findings. Root supplied actual full retained Run counterexamples for cross-relation coverage and contradictory not-applicable attempted/classes fields; a valid observed control closed as well. FULLY read the actual completed post-reset-review.v15 review JSON/MD and consumer-b.v5/output/blind-review JSON/MD. Earlier v15 ACCEPT did not survive the separate blind litmus: CB5 has2MUST2SHOULD4ADV. Every unresolved MUST OR SHOULD requires CHANGES_REQUIRED, regardless of headline acceptance or test counts.

Independently assess EACH actual CB5-MUST-1/2,CB5-SHOULD-1/2,CB5-ADV-1..4 and accepted V15-ADV-1 against exact final bytes:
- Effective capability-manifest ADM-DOMAIN selection: actual committed CVE1 gate follows explicitly selected scoped successor with all13relations and correct relation-specific ladders, while inherited codec/identity/typed/closed/order obligations stay intact. Wrong relation/rung still refuses. Schema/registry selection must be normative, not only a file's self-asserted standing.
- TypeScript lib-name to retained declaration-component mapping: exact spelling/case/order/configuration agreement, complete inventory and unique basenames, retained closure/tree digests. Both valid library selections and malformed/missing/ambiguous context inputs need honest controls; no implicit alternate representation, simple-versus-full/context-sensitive lowercase mismatch, locale dependency or unbound Unicode-version choice. Assess the exact selected version and reference portability limits with discriminating controls.
- RC-1 applicability over ALL registered relation/rung pairs: observed, annotated and syntactic rungs; reachability's single rung is nevertheless resolved. Unknown pairs cannot become not-applicable by fallback. Independently reproduce producer AND full retained Run refusal for unresolved-edge@enumerated and observed attempted=true/nonempty registered classes, preserving the valid observed control and independent examined/stage fields. Also check CX-BV5-09: a resolved complete record with zero unresolved facts/count cannot retain a nonempty class set; verify the actual state-specific law and preserved not-attempted/partial cases. Preserve RC-2 attempted/exhaustive/stage/edge laws and observed coverage versus resolution distinction. The earlier blind probe's alternatives also changed attempted/coverage/stage fields; do not claim a collision on identical inputs, but independently assess the actual missing contract mapping.
- RepairPlanDescriptor closedWorld projection must name exact fields and remain a summary of the original full native evidence. Original eligibility and reasons remain grounded in full native evidence; dynamic-edge effects are target-relative and do not globally veto unrelated targets. Every delete/replace action keeps the existing repair guard; a copied boolean, dropped field or detached descriptor cannot authorize destructive repair. Verify valid projection and denial from full evidence where it is decidable. Distinguish pure reference admission from real host enforcement.
- Four concrete digest representations versus by-domain selector, accurate LogicalPath direct versus joined grammar, explicit inherited L0 inner+outer length framing without historical rewrite, and inherited platform vocabulary versus four selected product platforms. All original advisory severities and source history retained. V15 cardinality-first ordering unchanged: schema failures at second step only for inputs reaching it; retained Run payload corruption remains a distinct boundary.

Assess all actual additional source changes and any new issues; do not restrict review to the named findings. Source prose or schema descriptions may change document digests used by identity preimages; truthful source-bound digest changes must not be described as identical exact semantic inputs. Confirm no unintended grammar/authority/admission widening. Preserve prior corrected capability/default/availability composition, body language/compiler dialect ownership, anchor cardinality/file-totality, digest annotations, typed canonical equality, relation/rung scope, imported observation/ScopeDocument binding, runtime evidence boundary, cache admission, repair replay, purge disclosure and required-output failure after a committed Run.

Reproduce ALL SIX recorded final-reference.v16/reference-checks.json commands in a disposable FULL exact subject copy. Verify all transitive source pins BEFORE execution, exits and deterministic reports against frozen results; never repin to manufacture success. Native checker writes its actual in-tree report (ignores --help/--report), so only run in a disposable copy. Preserve every failed attempt and full source-copy deltas, name each copy. Shared fixture is construction data, not independent verdict oracle; avoid rerunning full check-identity suite on every probe import. Independently author expected outcomes and bind exact sources. Exercise complete positive Run admission where changes can affect it and retain negative controls; a positive schema fragment is not a complete Run. Counts are passing calls/distinct IDs, security sweeps/native cases with actual scope, never product qualification.

Read root blind-assessment.v5.json: reported58 negative-labelled rows are not58 demonstrated refusals and omit some flat maps; original8closedgraphs differ from3public-envelope placeholderRunIds. Blanket no-filesystem/no-crypto wording refers to no product/TCB qualification; actual Python file IO/hashlib executed. Preserve original reports plus these explicit qualifications. Fresh blind reconstruction is separate and still required after your actual acceptance; this review cannot supply it.

One complete intended product implemented in stages. Native TS/JS/Rust plus bounded bundled grammar modes, four selected macOS/Linux machine IDs. All16AR/all15FW,27inherited residuals,30evaluation subresiduals,fiveDR201..205 and32unperformed qualification gates remain in view. Preserve literal prior scope: CARRIED-UNCHANGED and routing-only are not new grades or final application outcomes. Source/design acceptance can coexist with pending independently reviewed application; do not invent grade authority. D372 unapplied,condition5 NOT MET,no implementation authorization. No implicit repository execution/untrusted ecosystem/full Map app/model dependency or platform/compiler/storage/cryptographic qualification.

Deliver substantive review.md AND review.json, top-level verdict or overallVerdict ACCEPT/CHANGES_REQUIRED/actualBLOCKED, subjectManifestSha256='{digest}', required newMustIssues and newShouldIssues arrays (empty ONLY if no unresolved required finding), separate newAdvisories. priorFindingDispositions must individually account all4CB5required/4CB5advisories/V15ADV1 plus nineCX-BV5rootpoints and BV5A-NEW1/2; preserve each original reported severity and root-required correction scope explicitly. Individually keyed arDispositions/fwDispositions/inheritedResidualDispositions/scopedReviewOwnerDispositions must provide actual basis/scope/authority; unchanged routing/preservation scope is not final application acceptance. Retain probes/source, positive controls, actual refusal expectations, failed attempts and complete-copy custody. Finish with a substantive verdict bound to the exact frozen bytes. No blind/application/readiness/product qualification inferred.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Bash','Write','--strict-mcp-config','--output-format','json']
proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=root,start_new_session=True);proc.stdin.write(prompt.encode());proc.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':proc.pid,'manifestSha256':digest,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args},indent=2)+'\n');print(proc.pid,digest)
