"""Fresh actual-Claude correction coauthor after completed blind v5, never independent acceptance."""
from pathlib import Path
import datetime, hashlib, json, shutil, subprocess
root=Path('/Users/sb/code/opensip-ai/opensip_arch');dc=root/'docs/coop/design-corrections';reviews=dc/'reviews'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
manifest=reviews/'candidate-subject.v15.json';expected='5ec7928426c7a91e323240337dc382c4de32bd4e5f2626eba92c8991067b365f'
assert sha(manifest)==expected
blind=reviews/'consumer-b.v5/output/blind-review.json';result=json.loads(blind.read_text());response=json.loads(blind.with_name('response.json').read_text())
assert response.get('is_error') is False and result['verdict']=='CHANGES_REQUIRED'
assert len(result['newMustIssues'])==2 and len(result['newShouldIssues'])==2
out=Path('/tmp/opensip-design-corrections/bv5-corrections-author.v1');assert not out.exists();out.mkdir()
m=json.loads(manifest.read_text());snapshot=Path(m['snapshotRoot']);work=out/'work';shutil.copytree(snapshot,work)
for row in m['files']:
 p=work/row['path'];assert sha(p)==row['sha256'] and p.stat().st_size==row['bytes']
prompt=f'''You are ACTUAL CLAUDE, a fresh CORRECTION COAUTHOR, not an independent accepting reviewer. The user authorized Codex and actual Claude to address every architecture/design/reference gap before implementation. No agents, product implementation, commit, push or publication. Write ONLY under {out}. Never edit the repository, frozen subjects or blind review. Your editable complete source copy is {work}, verified against accepted historical v15 manifest {manifest}, SHA256 {expected}. Its original source archive/evidence is immutable. Python /tmp/opensip-architecture-review-env/bin/python -I -B is available.

FIRST fully read the completed actual fresh blind v5 review {blind} and {blind.with_name('blind-review.md')}, including all required findings, four advisories, explicit non-issue and limitations. This blind reviewed normative inputs only and returned CHANGES_REQUIRED despite earlier design ACCEPT. Review hash {sha(blind)}. This is the correction pass; it is NOT a new blind review. Inspect its independently authored source/vectors in its retained directory as needed. Do not assume its counts or probe prose exceed their actual evidence.

Address ALL four required findings (MUST-1, MUST-2, SHOULD-1, SHOULD-2) and individually dispose all four advisories. Root preliminary reasoning for you to independently assess:
- MUST-1: the effective committed-CVE1 admission currently cites delivery.v4 while capability-manifest-domains.v2 claims selection that the prose doesn't actually make. Select the existing scoped ADM-DOMAIN/ladder successor explicitly, preserve inherited codec/identity/typed/closed/order obligations and historical bytes; name its actual source in native §11. Do not silently expand unrelated domains or claim missing selection was already present.
- MUST-2: current native model admit_native_context uses `lib.<lib.lower()>.d.ts`, full declaration inventory and unique basenames; the prose/schema descriptions omit the mapping. Publish exact deterministic mapping/equality/case/order and custody meaning consistent with the admitted representation, without changing selected names into file names or dropping config agreement. Inspect the actual model, schema and closed configuration contract; avoid introducing a new case algorithm or accepting extra inputs by accident.
- SHOULD-1: RC-1 omits unresolved-edge@observed. Existing completeness_from_stage/coverage_bijection uses membership in the five resolved rungs and makes other registered pairs not-applicable. Explicitly state complete applicability over registered relation/rung pairs, including observed and syntactic/annotated rungs. Do not use a generic one-rung count as the only rule: reachability has one rung but it IS resolved and must never be not-applicable. Unknown relation/rung still refuses; do not create a fallback for unknown records. Preserve RC-2 state and examined-versus-resolution distinction. The blind probe's two alternatives also differ in attempted/coverage fields; its 'same observation' phrase is stronger than the exhibited evidence. Account that limitation without dismissing the contract clarity gap.
- SHOULD-2: current repair_preview consumes the original native ClosedWorldV2 and projects exactly five fields into RepairPlanDescriptor, preserving its evidenceRunId; full native evidence includes dynamicDispatch/reasons and determines eligibility before projection. Publish the exact projection and the full-evidence authority prerequisite, so deleting fields from a display/descriptor cannot bypass a destructive repair gate. Independently check code, schema and workflow prose rather than inventing an acceptance from a copied boolean.
- Advisories: clarify four concrete digest representations versus by-domain selector; correct LogicalPath description without silently widening or narrowing accepted paths; explicitly state inherited L0 inner/outer length framing in current owning prose with a byte example, preserving historical fact-identity-policy.v2 bytes; clarify broader inherited platform vocabulary versus the four selected product platforms without claiming or enabling unsupported platforms. Each retains its actual severity. Prefer narrow current-source clarifications; no historical artifact rewrite.
- Also close the already accepted nonblocking V15-ADV-1 wording while these bytes already need a successor: the cardinality-first ordering is exact; schema errors refuse at schema stage only for requests reaching that stage. No change to bounded array limit/order/retained corruption handling.

Scope is minimal consistent contract/schema-description/reference corrections. Do NOT rewrite generated reports, review history, crosswalks, readiness or source-pin manifests in the source proposal. If you need runnable checks in a disposable copy, name that separate copy and preserve all deltas. Source pins will be refreshed by Codex only AFTER all final source/records, followed by six final checks and fresh independent review. A stale pin refusal during changed-source work is not a product failure and cannot be called a PASS.

Independently exercise meaningful reference controls for the actual corrected meaning: committed capability manifest containing unresolved-edge versus unknown/cross-relation values; TS retained lib name mapping positive/case/order/missing/ambiguous components; ALL registered relation/rung pairs plus unknown and resolved negative controls; valid repair projection with the original full closed-world guard and unsafe repair refused when that evidence denies eligibility. Include admitted positive graphs where needed; schema-only or pure-helper checks do not demonstrate host enforcement. Preserve actual original failures/attempts and distinguish fixture errors from design findings. No gratuitous test count inflation or tests that only check their own implementation. Existing six whole-subject checks will be run by root later; you need not duplicate all of them on unsealed pins.

Deliver handoff.md AND handoff.json with substantive technicalAssent true/false to the EXACT source bytes you propose, each required/advisory disposition, any new findings, exact relative changed-source paths and before/after SHA256, executed commands/evidence, preserved behavior, and limitations. Original v15 independent and blind reviews remain literal historical evidence; this coauthor assent grants no independence/readiness. Explain disagreement rather than manufacturing alignment. Finish the bounded correction and report final exact bytes; no whole-tree acceptance claim.'''
(out/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Bash','Write','--strict-mcp-config','--output-format','json']
proc=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(out/'response.json').open('wb'),stderr=(out/'stderr.log').open('wb'),cwd=work,start_new_session=True)
proc.stdin.write(prompt.encode());proc.stdin.close()
(out/'process.json').write_text(json.dumps({'pid':proc.pid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'parentSubjectSha256':expected,'blindReviewSha256':sha(blind),'sourceCopyFiles':len(m['files'])},indent=2)+'\n')
print(json.dumps({'pid':proc.pid,'out':str(out),'sourceCopyFiles':len(m['files']),'standing':'Actual correction coauthor launched; no acceptance or source integration.'}))
