from pathlib import Path
import json,subprocess,datetime,hashlib
B=Path('/tmp/opensip-design-corrections');P=B/'v21-evaluator-contract-assessment.v2';assert not P.exists();P.mkdir();R=Path('/Users/sb/code/opensip-ai/opensip_arch');S=B/'candidate-subject.v21';prev=B/'v21-evaluator-contract-assessment.v1'
assert not json.loads((prev/'response.json').read_text())['is_error']
prompt=f'''Continue as actual Claude DESIGN COAUTHOR with Codex, same source21 READ ONLY. Your prior assessment is preserved verbatim at {prev} and in repo reviews; no source edits or product implementation occurred. Blind9 is still independent and ACTIVE; DO NOT read/contact its output or any other active review. Write only under {P}, no outside memory, agents, commits, push. This is a bounded correction-PROPOSAL refinement, not source acceptance or application. Return revised-assessment.json/md and an exact coherent normative proposal (separate proposal.md/JSON as useful); no large replacement implementation yet.

Codex has FULLY READ your assessment JSON/MD/receipt and the directly relevant normative schemas/prose. We agree that G1-G4 expose a real missing retained-evidence selection contract; G5's import witness address and G7's per-subject Coverage selection also need an explicit rule. We do NOT assent to your complete C1-C9 proposal yet. Address these concrete defects and settle the remaining design choices on evidence and product intent:

1. C6 is factually wrong: toggling enabled changes PolicyDocumentV1 digest; RuleProgramV1 includes policyDigest, so ruleProgramDigest DOES change even though rules array retains disabled entries. Correct every no-identity-change claim. Law/schema/registry revisions can change exact document hashes and transitive identities too; distinguish unchanged H algorithms/shapes from unchanged values. Your own C8 typed addition also contradicts 'C5 only identity-breaking item'. Specify exact affected schema/identity majors and migration standing. This is preimplementation design, historical frozen subjects remain immutable; there are no produced current product Runs to silently migrate.
2. G3's 100-file example does not show differing verdicts as stated: complete file@enumerated has the explicit totality law, so missing inventoried file facts are rejected; if all100 facts exist both choices produce100true findings. Use two admitted subjects with partial Coverage / a relation without that totality, one match, and show the actual differing per-subject values (and arrange gating/waivers if you claim verdict difference). Do not call hypothetical pseudodata schema-admitted unless actually validated. Likewise G1 U_ts versus U_syn are different DOMAIN classes, so a single-domain selector does not itself give a same-domain multi-universe discriminator. Use two distinct TypeScript universe contexts and account predicate tuple uniqueness.
3. C5's claim none/count-at-most/all-covered could never be true solely because imported runtime evidence cannot prove universal STATIC absence is too broad. Count-at-most is certainly false after >N known distinct observations; bounded observation presence/absence is different from universal static non-use. Preserve intended runtime/history functionality rather than removing three operators on this inference. Read the owning observation/window/population/optional-required laws and define finite imported evaluation/witness addressing, absence semantics and no-static-negative boundary coherently. Don't mint native fact2 for imports. Clarify whether occurrence identity is import wrapper+member address, how duplicate observations across imports count, and how source mapping/observability enter per-subject selection.
4. C2/C4 withdraw export and targetKind and refuse all symbol/package globs without considering the promised target/export/closed-world subject semantics. Do not silently narrow product intent to save schema work. Determine whether retained subject metadata (also needed by G8) can represent export status, kind, path, language and stable key while leaving actual native extraction as qualification. Target kind can sometimes be a registry-derived role, sometimes unknown; 'nothing supports it' must not become 'all targetKind filters inherently impossible'. Define actual supported/missing cases and refuse unknown claims. Metadata need not fabricate symbol-to-path truth: it may explicitly be a trusted native observation, distinguish retained join validation from semantic extraction correctness. Explain any unavoidable narrowing or added typed metadata and prefer the smallest COMPLETE design, not the fewest edited lines.
5. C7 'every rung >=k has some complete scope in some universe' is not yet sound: it overconstrains lower-rung analysis to unavailable higher capabilities, may let complete scope from one universe substitute for another, and must handle resolution state not-applicable for inventory/syntax correctly. Stronger evidence may satisfy a weaker request. Derive explicit selected scope/view/rung/subject sets, quantification across selected universes/producer views, missing Coverage, exact matchingFactIds count, positive versus universal-negative closed-world applicability, and required/optional evidence. Do not use existential 'some U' to discharge another U's absence. Do not infer the atom's view/scope from its own claimed witness; independently select from Plan/policy/evaluation inputs.
6. G8: ProofInputRef already admits blob, so 'no member can name any adapter output' is too absolute. A typed authenticated/producer-bound subject projection may still be missing. Read exact retention/subject discriminator/selected detector token-projection clauses and decide current contract vs future qualification ownership, not leave this required choice open. Actual compiler token extraction is future qualification; a COMPLETE current retained-input/replay law cannot be deferred there. Cover subject/finding/related keys, language/dialect, message default, parameters, detector closure/rule reference binding and waiver-by-fingerprint/path. Avoid a circular subject descriptor -> scope -> descriptor identity dependency. No expected-result flag or producer-supplied fingerprint may substitute for host recomputation.
7. C4 says targetFieldByRung is mechanically the field in rungs.required and 'invents nothing'; this is an actual semantic selection, and several rows have no such required table. Mark new design choices as choices and make a complete table, including unknown/absent/textual targets and operator typing. Existing FieldFilter allOf ALREADY restricts gte/lte to numeric confidence and eq/neq/prefix/glob to strings/in to stringarray; preserve that actual answer.
8. C9 and E1: verify any existing surface projection/blueprint law before claiming global absence. Define threshold/gate/waived finding preservation/disabled rules, exact omission/deficiency carriers and normalized complete replay comparison. Do not change sealed three-value precedence or operational D9 precedence. Correct the policy-versus-compiled-program explanation without weakening exact compilation projection.

Read missing owning sections necessary to settle these, including native closed-world/requirements and imports, current-source-map/blueprint/freeze if those actually own a selector. Do not open review history as normative authority. Return explicit disposition of EVERY G1-G9/E1 and C1-C9 concern, what was wrong in v1, which concrete semantics you recommend and WHY, typed shape/registry changes, honest compatibility, and minimal discriminating reference examples for a later correction author. Settling normative laws is authorized design work; actual implementation and compiler/OS qualification are not. No final proposal assent unless the selection algorithm is total over admitted shapes; explicitly identify any remaining decision you cannot settle. Aim3000words plus exact tables/records. Work now.'''
(P/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--resume','006a1d7b-0dff-4d8b-98ce-a5ba8abf6e1b','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json']
p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(P/'response.json').open('wb'),stderr=(P/'stderr.log').open('wb'),cwd=prev,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(P/'process.json').write_text(json.dumps({'pid':p.pid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'standing':'Actual coauthor refinement of v1, not independent or blind acceptance.','priorReviewJsonSha256':hashlib.sha256((prev/'assessment.json').read_bytes()).hexdigest(),'priorReviewMdSha256':hashlib.sha256((prev/'assessment.md').read_bytes()).hexdigest()},indent=2)+'\n');print(p.pid)
