from pathlib import Path
import json,subprocess,datetime,hashlib
B=Path('/tmp/opensip-design-corrections');P=B/'v21-evaluator-contract-assessment.v1';assert not P.exists();P.mkdir()
R=Path('/Users/sb/code/opensip-ai/opensip_arch');S=B/'candidate-subject.v21'
mp=R/'docs/coop/design-corrections/reviews/candidate-subject.v21.json'
assert hashlib.sha256(mp.read_bytes()).hexdigest()=='360c2758c0409ebc307966c7a385c385c2d7f580b4623dd760b7ba0e26bf18c1'
prompt=f'''You are actual Claude, a bounded DESIGN COAUTHOR ASSESSOR working with Codex. User explicitly authorizes correcting architecture/design/reference gaps with actual Claude before product implementation. You are NOT the separate blind consumer currently running; do not contact it, inspect its output, or use any other active review. No agents, product implementation, commit, push, publication. Frozen source is READ ONLY. Write ONLY under {P}. No memory writes outside this directory.

Assess one concrete question: does the published deterministic evaluator contract fully define the join from policy DSL subject enumeration and filters to retained native fact/scope/Coverage/import records, so an independent implementer can reconstruct the same subjects, matching facts, completeness, findings and verdict WITHOUT inventing public semantics? Source21 at {S}, manifest {mp} SHA360c2758c0409ebc307966c7a385c385c2d7f580b4623dd760b7ba0e26bf18c1 has passed a separate architecture review but that is not an oracle for your judgment. It is still awaiting blind review and application. Do not read prior reviews or author models first, nor search reviews recursively. Start with docs/v2/contracts/product-v1/identity-and-evidence.md sections3/4, workflows-and-surfaces.md section5, their policy-document.schema.json and policy-test.schema.json, identity-schemas.v2.json, relation-payload-schemas.v2.json, imported-evidence schemas/registry, native context/universe/coverage definitions and relevant normative selector dependencies. You may inspect author reference models ONLY after deriving the normative answer, explicitly separate any implementation evidence from normative authority. Do not mistake the flattened bounded policy-test fixture API for a published projection from retained facts.

Root observed questions, not conclusions you must accept:
- Rule.subjectEnumeration.universe is CanonicalIdentifier, native facts/scopes carry 64-hex universe H digests. Is there an exact published binding/selection recipe? If yes cite its full selector; if not identify ambiguity with two concrete plausible choices.
- SubjectEnumeration.subjectKind file/symbol/export/package differs from relation registry source-path/symbol/package-name; symbols are opaque, symbol-to-file attribution explicitly not derivable. How are all required subjects selected, including absent facts and multiple universes? How does each atom bind the CURRENT subject, and which scopes/views belong to it?
- FieldFilter fields subject/target/resolution/universe/confidenceMillionths/subjectKind/targetKind/observability confront heterogeneous relation payload fields caller/callee/importer/resolvedTarget/path/container/declared etc. Is exact projection and missing-field/type/cmp behavior already defined? Imported evidence has its own target/observability semantics. Avoid inventing data no retained field supports.
- Identity section4 already explicitly requires examination AND resolution/closed-world completeness, exact named input views, exact witnesses, complete finding fingerprints/outcomes/verdict replay. Preserve those obligations; a deficient independent implementation is not itself proof of a normative gap.

Read enough adjacent contract to assess the entire affected join, including disabled rules, required/optional imports, finding identity emission, waiver targets and per-relation ladders. Distinguish an implementation freedom from missing public behavior. Do not demand real compiler/OS/production code: this is a contract question. Do not claim replay from schema/hash checks.

Deliver assessment.json and assessment.md with substantive verdict, exact read scope/selector citations, each actual MUST/SHOULD/advisory (or none), minimal discriminating examples, existing-answer vs genuinely missing-design distinctions, and a concrete coherent correction proposal if required. A proposal should define stable deterministic laws using already retained data wherever possible, identify any unavoidable typed schema changes, preserve zero-config/common-language applicability, and explain compatibility/test consequences. It must be complete enough for a bounded correction author to apply without more public-semantic invention, but do NOT edit source and do NOT produce a large replacement implementation here. About1500-2500words plus small JSON examples if useful. If the gap is broader than these questions, identify adjacent obligations explicitly rather than silently claiming the narrow mapping makes full replay complete. State limits and unresolved design choices candidly. Work now.'''
(P/'prompt.txt').write_text(prompt)
args=['/Users/sb/.local/bin/claude','-p','--model','opus','--effort','high','--permission-mode','dontAsk','--tools','Read,Grep,Glob,Write,Bash','--allowedTools','Read','Grep','Glob','Write','Bash','--strict-mcp-config','--output-format','json']
p=subprocess.Popen(args,stdin=subprocess.PIPE,stdout=(P/'response.json').open('wb'),stderr=(P/'stderr.log').open('wb'),cwd=P,start_new_session=True);p.stdin.write(prompt.encode());p.stdin.close();(P/'process.json').write_text(json.dumps({'pid':p.pid,'startedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'command':args,'parentSubjectSha256':hashlib.sha256(mp.read_bytes()).hexdigest(),'standing':'Bounded coauthor assessment; not independent design acceptance, blind consumer or application review.'},indent=2)+'\n');print(p.pid)
