"""Prepare fresh actual Claude application review with public-only event retention.
Uses reviewed build_prompt API; no changes to design/application tools. Does not launch.
Retain through run_retain(..., claude_log_text=PUBLIC_EVENTS_TEXT) to avoid private fallback.
"""
from pathlib import Path
import argparse,json,hashlib,importlib.util,sys
B=Path('/tmp/opensip-design-corrections');T=B/'application-successor-root.v2'
def main():
 p=argparse.ArgumentParser();p.add_argument('--stage',type=Path,required=True);p.add_argument('--root',type=Path,required=True);p.add_argument('--version',required=True);p.add_argument('--bound-receipt',type=Path,required=True);a=p.parse_args();bound=json.loads(a.bound_receipt.read_text());assert bound['readyForAssembly'] is True and bound['applicationVersion']==a.version and bound['vendor']=='claude';stage=a.stage.resolve();repo=a.root.resolve();mp=stage/('application-subject.'+a.version+'.json');digest=hashlib.sha256(mp.read_bytes()).hexdigest();app=json.loads((stage/'files/docs/coop/design-corrections/application.v1.json').read_text());R=stage.parent/('application-review.'+a.version);R.mkdir(exist_ok=False)
 sys.path.insert(0,str(T));spec=importlib.util.spec_from_file_location('app_prompt_owner',T/'launch-application-review.successor.v1.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);prompt=m.build_prompt(bound['reviewerPublicLabel'],'claude',R,stage,mp,digest,repo,app['designSnapshotRoot'],app['independentDesignReview'],app['freshBlindConsumerReview']);prompt+='\nOperational: all review/probe writes only in this runtime. Public tool activity is captured directly; do not inspect private session logs. Use direct Python for filesystem orchestration; reference interpreter /tmp/opensip-architecture-review-env/bin/python -I -B is allowed. No product implementation. This is a FRESH session: no design, blind or source-author session resumed.\n';(R/'prompt.md').write_text(prompt);(R/'prompt.txt').write_text(prompt)
 template=(B/'claude-independent-design.v32/launch.py').read_text();start=template.index('cmd=');end=template.index('\nstart=time.time()',start);cmd=['/Users/sb/.local/bin/claude','--safe-mode','--strict-mcp-config','--model','opus','--permission-mode','dontAsk','--tools','Read,Glob,Grep,Bash,Write,Edit','--allowedTools','Read','Glob','Grep','Write','Edit','Bash(python3 *)','Bash(/tmp/opensip-architecture-review-env/bin/python *)','--add-dir',str(stage),'--add-dir',str(repo),'--add-dir',app['designSnapshotRoot'],'--add-dir','/tmp/opensip-architecture-review-env','--output-format','stream-json','--verbose','-p'];script=template[:start]+'cmd='+repr(cmd)+template[end:];stdout_name=bound.get('launch',{}).get('stdoutName','response.json');assert Path(stdout_name).name==stdout_name
 # Append expected public-envelope filename AFTER successful process completion; never raw stdout.
 script += "\nif (root/'result.json').is_file():\n (root/"+repr(stdout_name)+").write_bytes((root/'result.json').read_bytes())\n"
 assert '--resume' not in cmd;(R/'launch-public.py').write_text(script);compile(script,str(R/'launch-public.py'),'exec');(R/'dispatch.json').write_text(json.dumps({'standing':'Prepared fresh independent application review, not executed or accepted','subjectManifestSha256':digest,'boundReceiptSha256':hashlib.sha256(a.bound_receipt.read_bytes()).hexdigest(),'priorSessionsExcluded':[bound['independentDesignReview']['sessionId'],bound['freshBlindConsumerReview']['sessionId']],'publicEventsPath':str(R/'public-events.jsonl'),'retentionInstruction':'Pass claude_log_text explicitly to run_retain; no private fallback.','stdoutName':stdout_name},indent=2)+'\n');print(R/'launch-public.py')
if __name__=='__main__':main()
